# DO NOT EDIT. This file was auto generated by ../scripts/generate-pkg.sh
{ pkgs ? import <nixpkgs> { } }:

pkgs.stdenv.mkDerivation {
  name = "languagetool-code-comments";
  src = pkgs.fetchurl {
    url = "https://github.com/dustinblackman/languagetool-code-comments/releases/download/v0.6.1/languagetool-code-comments_0.6.1_linux_amd64.tar.gz";
    sha256 = "1wk8r1ricgxishq2sa9pis5czcqq3dfrv7lvlcxrj4za6vrg0dkx";
  };
  phases = [ "installPhase" ];
  installPhase = ''
    mkdir -p $out/bin
    tar -zxf $src -C $out/bin/ languagetool-code-comments
  '';
}

