# DO NOT EDIT. This file was auto generated by ../scripts/generate-pkg.sh
{ pkgs ? import <nixpkgs> { } }:

pkgs.stdenv.mkDerivation {
  name = "oatmeal";
  src = pkgs.fetchurl {
    url = "https://github.com/dustinblackman/oatmeal/releases/download/v0.8.2/oatmeal_0.8.2_linux_amd64.tar.gz";
    sha256 = "17fsb1mhdkskxsf880lgc6s0k43y5jzwi34il5lwy0gs6bfwplc6";
  };
  phases = [ "installPhase" ];
  installPhase = ''
    mkdir -p $out/bin
    tar -zxf $src -C $out/bin/ oatmeal
  '';
}

