name: GitHub Agentic Workflows Compile
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths:
      - .github/workflows/**/*.md
      - .github/workflows/*.md
permissions:
  contents: write
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    environment: gh-aw
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install GH AW CLI
        uses: github/gh-aw-actions/setup-cli@9b1d730701c16b15673633e5696d01677fad9844 # v0.79.2
      - name: Compile
        run: gh aw compile
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "gh-aw: Compile"
          commit_options: --no-verify
          push_options: --force
          file_pattern: .github/
