# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0dyhsxb1cz3d95b45ryi2gyim592knikh86advgqvar6h369m497";
    x86_64-linux = "16skacpljnfcfi9v0rdmsg8dg4vds4saqah5z5q9bhf02vfxnbq1";
    armv7l-linux = "02qk8cck402armqgx60wbwx7zklqrxnns4kbrwzk2f3p70zgw543";
    aarch64-linux = "08s04zsaaz3qjlvga9igk6wwipvwiy3cbp8kvwraywymwv1684ds";
    x86_64-darwin = "0prqbqynjiq15vrlr7x42i4sijmixs5px144zvibwmgjyz1ip83v";
    aarch64-darwin = "1vmbkaxxvdjdkc82hj1k8m1lsv4i0r8r8zidjmn3m9yxjsnyndk9";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/freeze/releases/download/v0.2.2/freeze_0.2.2_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/freeze/releases/download/v0.2.2/freeze_0.2.2_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/freeze/releases/download/v0.2.2/freeze_0.2.2_Linux_arm.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/freeze/releases/download/v0.2.2/freeze_0.2.2_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/freeze/releases/download/v0.2.2/freeze_0.2.2_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/freeze/releases/download/v0.2.2/freeze_0.2.2_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "freeze_0.2.2_Linux_i386";
    x86_64-linux = "freeze_0.2.2_Linux_x86_64";
    armv7l-linux = "freeze_0.2.2_Linux_arm";
    aarch64-linux = "freeze_0.2.2_Linux_arm64";
    x86_64-darwin = "freeze_0.2.2_Darwin_x86_64";
    aarch64-darwin = "freeze_0.2.2_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "freeze";
  version = "0.2.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./freeze $out/bin/freeze
  '';

  system = system;

  meta = {
    description = "Generate images of code and terminal output.";
    homepage = "https://charm.sh/";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
