# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  bling = {
    pname = "bling";
    version = "affc165bda9dd8a88de8c7d9b22d5ccb466f2742";
    src = fetchFromGitHub {
      owner = "blingcorp";
      repo = "bling";
      rev = "affc165bda9dd8a88de8c7d9b22d5ccb466f2742";
      fetchSubmodules = false;
      sha256 = "sha256-khHAM26TGwhfXO8RppGia/ViIhxi7wDdLw7P2lg161U=";
    };
    date = "2023-02-09";
  };
  cardinal = {
    pname = "cardinal";
    version = "68c94903e392417fa88887fe4d84fd60850b137f";
    src = fetchFromGitHub {
      owner = "DISTRHO";
      repo = "Cardinal";
      rev = "68c94903e392417fa88887fe4d84fd60850b137f";
      fetchSubmodules = true;
      sha256 = "sha256-nRYoCdx7tw3G8Taa7dngsAxv9z1Dxamp7zvIXBWyO2E=";
    };
    date = "2023-02-09";
  };
  carla = {
    pname = "carla";
    version = "4151e160f1e9e03412c112fec54b5f1cde4c45de";
    src = fetchFromGitHub {
      owner = "falkTX";
      repo = "Carla";
      rev = "4151e160f1e9e03412c112fec54b5f1cde4c45de";
      fetchSubmodules = false;
      sha256 = "sha256-93gpzeMoMW3i0Fwam8eJ2Se4x7KFBrfLRrvMVjuEgOI=";
    };
    date = "2023-01-29";
  };
  dmenu-flexipatch = {
    pname = "dmenu-flexipatch";
    version = "05f5efc5e544fdb8e7744eb79a6a5d6f882b4d4c";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dmenu-flexipatch";
      rev = "05f5efc5e544fdb8e7744eb79a6a5d6f882b4d4c";
      fetchSubmodules = false;
      sha256 = "sha256-6hGunum5+IBSpxJPvEOAgNmCkDNbm3R++RSTg8TL8Vo=";
    };
    date = "2022-10-26";
  };
  dwm-flexipatch = {
    pname = "dwm-flexipatch";
    version = "e206d65f1e9c85005f290c9c2cddacf9079827b9";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dwm-flexipatch";
      rev = "e206d65f1e9c85005f290c9c2cddacf9079827b9";
      fetchSubmodules = false;
      sha256 = "sha256-IqGKTAbdCNCs4HBi5r0oeyB4VhdD+Z55ZZAuhWsk6Zo=";
    };
    date = "2023-02-03";
  };
  keepmenu = {
    pname = "keepmenu";
    version = "1.3.1";
    src = fetchFromGitHub {
      owner = "firecat53";
      repo = "keepmenu";
      rev = "1.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-1s+vl5j0oPERUvJCKFTvLubCF8Nhx7OtkPjpWmpEG/o=";
    };
  };
  kiwmi = {
    pname = "kiwmi";
    version = "17814972abe6a8811a586fa87c99a2b16a86075f";
    src = fetchFromGitHub {
      owner = "buffet";
      repo = "kiwmi";
      rev = "17814972abe6a8811a586fa87c99a2b16a86075f";
      fetchSubmodules = false;
      sha256 = "sha256-n9PA6cyEjSlnDcRrqIkO83UaCE/hovbi/oZon1B+nuw=";
    };
    date = "2022-07-30";
  };
  lua-dbus = {
    pname = "lua-dbus";
    version = "cdef26d09aa61d7f1f175675040383f6ae0becbb";
    src = fetchFromGitHub {
      owner = "dodo";
      repo = "lua-dbus";
      rev = "cdef26d09aa61d7f1f175675040383f6ae0becbb";
      fetchSubmodules = false;
      sha256 = "sha256-S+W6QTqv4kdyR86GCyDLnkml10dO4ZVNXEd3/7vDFGE=";
    };
    date = "2015-04-22";
  };
  lua-dbus_proxy = {
    pname = "lua-dbus_proxy";
    version = "v0.10.3";
    src = fetchFromGitHub {
      owner = "stefano-m";
      repo = "lua-dbus_proxy";
      rev = "v0.10.3";
      fetchSubmodules = false;
      sha256 = "sha256-Yd8TN/vKiqX7NOZyy8OwOnreWS5gdyVMTAjFqoAuces=";
    };
  };
  luakit = {
    pname = "luakit";
    version = "858dc946b01487e6ba2475cb7a9bede34c17d134";
    src = fetchFromGitHub {
      owner = "luakit";
      repo = "luakit";
      rev = "858dc946b01487e6ba2475cb7a9bede34c17d134";
      fetchSubmodules = false;
      sha256 = "sha256-TKQvnavoofGtBo2aBJtZVZjrmm5Ln7vOgW9bAXjcpRM=";
    };
    date = "2023-01-29";
  };
  lv2vst = {
    pname = "lv2vst";
    version = "30a669a021812da05258519cef9d4202f5ce26c3";
    src = fetchFromGitHub {
      owner = "x42";
      repo = "lv2vst";
      rev = "30a669a021812da05258519cef9d4202f5ce26c3";
      fetchSubmodules = false;
      sha256 = "sha256-WFVscNivFrsADl7w5pSYx9g+UzK2XUBF7x0Iqg8WKiQ=";
    };
    date = "2020-06-07";
  };
  raze = {
    pname = "raze";
    version = "1.6.2";
    src = fetchFromGitHub {
      owner = "ZDoom";
      repo = "Raze";
      rev = "1.6.2";
      fetchSubmodules = false;
      sha256 = "sha256-5EXU7mXhg9gvNvz13OCvzJHMb4VArYQj/6rTmzDK6uY=";
    };
  };
  slock-flexipatch = {
    pname = "slock-flexipatch";
    version = "780a7887a3b976a48786f991d55fc8a474e76a25";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "slock-flexipatch";
      rev = "780a7887a3b976a48786f991d55fc8a474e76a25";
      fetchSubmodules = false;
      sha256 = "sha256-3jzEXIaH6qZkbvumlYqPSW1kDjg8obDMVoj6y3Vhe4I=";
    };
    date = "2022-10-06";
  };
  st-flexipatch = {
    pname = "st-flexipatch";
    version = "a8e2af0d923e7b6f7b19e8fa516bcd0670dfae84";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "st-flexipatch";
      rev = "a8e2af0d923e7b6f7b19e8fa516bcd0670dfae84";
      fetchSubmodules = false;
      sha256 = "sha256-cYaHI19ctmfPSNr4UgT7p1GSEVMKZUlHJ4Gn33A0KR8=";
    };
    date = "2023-01-09";
  };
  taffybar = {
    pname = "taffybar";
    version = "253c10fc2af08d3d9eab9ca2362f4dce05c58554";
    src = fetchFromGitHub {
      owner = "taffybar";
      repo = "taffybar";
      rev = "253c10fc2af08d3d9eab9ca2362f4dce05c58554";
      fetchSubmodules = false;
      sha256 = "sha256-52epXu0VDlNA6yZ3JTsgbbD/1YCPX2s3Lpaz3Lk7lsA=";
    };
    date = "2022-12-25";
  };
  tailwindcss-intellisense = {
    pname = "tailwindcss-intellisense";
    version = "4b215ba92eb2b0ac0043328468adb10a5b118bfd";
    src = fetchFromGitHub {
      owner = "tailwindlabs";
      repo = "tailwindcss-intellisense";
      rev = "4b215ba92eb2b0ac0043328468adb10a5b118bfd";
      fetchSubmodules = false;
      sha256 = "sha256-cwIPAEfmCja/C+SXtjV972LkbVXCZoFmoNVrupPI5og=";
    };
    date = "2023-01-31";
  };
  xmonad-entryhelper = {
    pname = "xmonad-entryhelper";
    version = "ee2d0c14f9258503d7bd62907aa731dd64fa34d0";
    src = fetchFromGitHub {
      owner = "Javran";
      repo = "xmonad-entryhelper";
      rev = "ee2d0c14f9258503d7bd62907aa731dd64fa34d0";
      fetchSubmodules = false;
      sha256 = "sha256-CGaibR0Yejng9IQInm92Zx0pEZS29tJjWvPgaiWgUNQ=";
    };
    date = "2022-05-18";
  };
  zix = {
    pname = "zix";
    version = "18e62483cb7173c6604f7dd2097299e47c2a4c0c";
    src = fetchFromGitHub {
      owner = "drobilla";
      repo = "zix";
      rev = "18e62483cb7173c6604f7dd2097299e47c2a4c0c";
      fetchSubmodules = false;
      sha256 = "sha256-IQIMbguqdTuYThzSD3Fx1qOFk3C4QmWPqdIZDlwRcyI=";
    };
    date = "2023-02-05";
  };
  zmusic = {
    pname = "zmusic";
    version = "1.1.3";
    src = fetchFromGitHub {
      owner = "ZDoom";
      repo = "ZMusic";
      rev = "1.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-wrNWfTIbNU/S2qFObUSkb6qyaceh+Y7Loxqudl86+W4=";
    };
  };
  zrythm = {
    pname = "zrythm";
    version = "dc30931820a951dc48dd75365bcc5b60249cb02d";
    src = fetchgit {
      url = "https://git.sr.ht/~alextee/zrythm";
      rev = "dc30931820a951dc48dd75365bcc5b60249cb02d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oWomklmf+GYkWeeSlhtXHpWqCDlSAuFsMkxarHF8tUA=";
    };
    date = "2023-02-09";
  };
}
