name: Package checks

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: checks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    if: (github.event.pull_request.head.repo.full_name || github.repository) == 'DaVinci42/nur-packages'
    runs-on: self-hosted
    timeout-minutes: 120
    env:
      PYTHONDONTWRITEBYTECODE: '1'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Build and validate packages
        run: nix-shell --run 'just check-all'
