name: "Update source and create PR"
on:
  schedule:
    - cron:  '0 19 * * *'
  workflow_dispatch:
jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
    - name: Generate GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        token: ${{ steps.app-token.outputs.token }}
        persist-credentials: false
    - name: Install nix
      uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31.10.1
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Update sources
      run: nix run nixpkgs#nvfetcher
    - name: Update firefox addons
      run: nix run git+https://git.sr.ht/~rycee/mozilla-addons-to-nix pkgs/firefox-addons/{addons.json,default.nix}
    - name: Update readme
      run: nix develop -c update-readme
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      with:
        token: ${{ steps.app-token.outputs.token }}
        commit-message: "update source"
        title: "update source"
        branch: update-nvfetcher
        sign-commits: true
    - name: Enable auto-merge
      if: steps.cpr.outputs.pull-request-number
      run: |
        gh pr merge --auto --merge "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
