# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  misstrhortion = {
    pname = "misstrhortion";
    version = "c3d110fc48b5a867393c435e3722ff1ee4ecd6f4";
    src = fetchgit {
      url = "https://github.com/bandithedoge/misstrhortion";
      rev = "c3d110fc48b5a867393c435e3722ff1ee4ecd6f4";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-ub9cSNj5JlIjPqcPY5StCrqypYqZly2n4663Hd8Ry2g=";
    };
    date = "2024-12-14";
  };
}
