# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  ep_subscript_and_superscript = nodeEnv.buildNodePackage {
    name = "ep_subscript_and_superscript";
    packageName = "ep_subscript_and_superscript";
    version = "0.0.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/ep_subscript_and_superscript/-/ep_subscript_and_superscript-0.0.3.tgz";
      sha1 = "47f74a242fe8be5911391943f718eab81c390620";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Add support for Subscript and Superscript";
    };
    production = true;
    bypassCache = false;
  };
}