name: Build packages
on:
  workflow_dispatch:
  push:
    branches:
      - staging
  workflow_run:
    workflows:
      - Update sources
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cacheable: [true, false]
    name: ${{ format('Build {0} packages', matrix.cacheable && 'cacheable' || 'uncacheable') }}
    steps:
      - name: ci-hoover
        uses: xd009642/ci-hoover@0.1.1

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: staging
          fetch-depth: 0

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@latest
        with:
          extra_nix_config: |
            keep-env-derivations = true
            keep-outputs = true
            accept-flake-config = true

      - name: Restore cache
        if: ${{ !matrix.cacheable }}
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: build-${{ runner.os }}
          gc-max-store-size: 8G
          purge: true

      - name: Build cacheable packages
        if: ${{ matrix.cacheable }}
        run: |
          nix develop .#build -c nix-fast-build \
            -f .#legacyPackages.x86_64-linux._CACHEABLE \
            --no-nom \
            --skip-cached \
            --result-file result.xml \
            --result-format junit \
            -j 1 \
            --cachix-cache bandithedoge
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build uncacheable packages
        if: ${{ !matrix.cacheable }}
        run: |
          nix develop .#build -c nix-fast-build \
            -f .#legacyPackages.x86_64-linux._UNCACHEABLE \
            --no-nom \
            --skip-cached \
            --result-file result.xml \
            --result-format junit

      - name: Install uncacheable packages
        if: ${{ !matrix.cacheable }}
        shell: nix run nixpkgs#nushell -- {0}
        run: |
          nix profile list --json
            | from json
            | get elements
            | items {|key, _| nix profile remove $key}

          nix eval .#_UNCACHEABLE --apply builtins.attrNames --json
            | from json
            | each {|attr| nix profile install $".#_UNCACHEABLE.($attr)" }

      - name: Build summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: "result.xml"

  merge:
    needs: build
    runs-on: ubuntu-latest
    name: Merge into master
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: staging
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Merge into master
        uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ secrets.BRANCH_MERGE_PAT }}
          source_ref: staging
          target_branch: master
          commit_message_template: "Merge updates"

      - name: Trigger NUR update
        run: curl -XPOST "https://nur-update.nix-community.org/update?repo=bandithedoge"
