# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  bassline-101 = {
    pname = "bassline-101";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-BassLine-101_64_linux.zip";
      sha256 = "sha256-EiGW1ICp3uROxQp4u6BMwA7vVgSioVlioQII4kQCz2M=";
    };
  };
  chorus-lx = {
    pname = "chorus-lx";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/Tal-Chorus-LX_64_linux.zip";
      sha256 = "sha256-F2OWyDo/Q9PsCuCxSDwu97lICVJpnMmZ85OZP7p4ag4=";
    };
  };
  dac = {
    pname = "dac";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-DAC_64_linux.zip";
      sha256 = "sha256-/7JDVxEfOQRqiCGPkejmPkbtnk3HqS/QgTskKz7Zfpc=";
    };
  };
  drum = {
    pname = "drum";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Drum_64_linux.zip";
      sha256 = "sha256-2KEMtmjtvzb5IoLRL7TWEm54vKDMMhI5ynPioiFUjys=";
    };
  };
  dub-x = {
    pname = "dub-x";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Dub-X_64_linux.zip";
      sha256 = "sha256-HkeSYuFS8ApVqUFZwuA2HUJgi1rQP7y0qeXldDpZ7tw=";
    };
  };
  filter-2 = {
    pname = "filter-2";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Filter-2_64_linux.zip";
      sha256 = "sha256-ymwvK21o3+FgqKcjVJ5R0qdFBbPPjEYlgL9QAfOEe+k=";
    };
  };
  j-8 = {
    pname = "j-8";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-J-8_64_linux.zip";
      sha256 = "sha256-0xQc1FBY4lcQn4nWHJv9GeTSo0UkE1yRwOzCzRy+L3w=";
    };
  };
  mod = {
    pname = "mod";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Mod_64_linux.zip";
      sha256 = "sha256-RkCNzjRTcxMMkAIC/aiHXOwOU5Ssxxc9MwvHV08I6KI=";
    };
  };
  noisemaker = {
    pname = "noisemaker";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-NoiseMaker_64_linux.zip";
      sha256 = "sha256-MoVl5kb5jxTdkxoz+kOKTJ7dxFHnWbktEAX0M2+j/SA=";
    };
  };
  pha = {
    pname = "pha";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Pha_64_linux.zip";
      sha256 = "sha256-u+yikSkKHrvXustpKEM7HEMCTxn4zcsNjqENaZ2u1Qk=";
    };
  };
  reverb-4 = {
    pname = "reverb-4";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Reverb-4_64_linux.zip";
      sha256 = "sha256-sI2r0JHXUzUBHJqODINud7Ovj8C4iE1LzRYm/LUVW7o=";
    };
  };
  sampler = {
    pname = "sampler";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Sampler_64_linux.zip";
      sha256 = "sha256-golt5Zmq8X4FoH+A7TNvjG9s0y1AsZ6X+GYduYuXHaI=";
    };
  };
  u-no-lx = {
    pname = "u-no-lx";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-U-NO-LX-V2_64_linux.zip";
      sha256 = "sha256-UOYa/uL6AQ70qqiuip2/5NVcfYe5EUQIlRGWbr/dsAM=";
    };
  };
  vocoder = {
    pname = "vocoder";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Vocoder-2_64_linux.zip";
      sha256 = "sha256-vOSpQqN8DEK4f5vISeQnZBpxhW3AaW1+/0ImajeoPsY=";
    };
  };
}
