#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i ysh ../../../../integrations/nix-shell --arg f 'ps: [ ps.common-updater-scripts ps.coreutils ps.curl ps.oils-for-unix ]'

source $LIB_YSH/args.ysh

proc usage {
  echo "USAGE: addon-version-lister [--max-versions N] [-v] [-v] --old-version SEMVER URL"
  echo ""
  echo "--max-versions N  (default: 10)"
  echo "  only show up to this many of the most recent valid versions."
  echo "  the lower this value, the faster this script will complete."
  echo "  many use cases can set this to '1'."
  echo ""
  echo "-v --verbose: more logging"
  echo ""
  echo "-v -v: even more logging"
  echo ""
  echo "--old-version SEMVER"
  echo "  version which yielded the provided url, used to recognize how the URL needs to be updated per version."
  echo ""
  echo "URL"
  echo "  URL at which to expect a .xpi file."
  echo "  combined with '--old-version', this is treated as a template for discovering newer versions."
}

var CliArgs = Object(null, {
  help: false,
  max_versions: 10,
  old_version: null,
  url: null,
  verbosity: 0,
})

# internal function for use by `parseArgs`.
# transforms argv into `CliArgs` object. should be side-effect free.
# @arg(cur, next, ...): each one is str; unpacked only for internal use
# @arg(p): intermediate CliArgs object; meant for internal use
# @return: CliArgs instance
func _parseArgs(p,cur=null, next=null, ...rest) {
  if (cur === null) {
    # end
    return (p)
  } else {
    case (cur) {
      -h | --help {
        setvar p.help = true;
        return (_parseArgs (p, next, ...rest))
      }
      --max-versions {
        setvar p.max_versions = int(next)
        return (_parseArgs (p, ...rest))
      }
      --old-version {
        setvar p.old_version = next
        return (_parseArgs (p, ...rest))
      }
      -v | --verbose {
        setvar p.verbosity = p.verbosity + 1
        return (_parseArgs (p, next, ...rest))
      }
      (else) {
        setvar p.url = cur
        return (_parseArgs (p, next, ...rest))
      }
    }
  }
}

func parseArgs(...args) {
  var p=Object(CliArgs, {})
  return (_parseArgs(p, ...args))
}


func numeric_version (tag) {
  # TODO: consider `b<n>` or `rc<n>` suffixes?
  return ($(echo "$tag" | egrep --only-matching "[0-9.]+" | head -n1))
}

func sort_versions (versions) {
  var numerics = []
  for v in (versions) {
    var row = [numeric_version(v), v] => join(" ")
    call numerics->append (row)
  }
  var lines = numerics => join (b'\n')
  var sorted = $(echo "$lines" | sort --version-sort --reverse | cut -d " " -f 2)
  return (sorted => split (b'\n'))
}

proc log (; ...stmts; level, context) {
  for s in (stmts) {
    var prefix = " $context:" if context else ""
    var formatted = "$(pp value (s))"
    echo "[$level]$prefix $formatted" >&2
  }
}

proc info (context=""; ...stmts) {
  log (level="INFO", context=context, ...stmts)
}

proc debug (context=""; ...stmts) {
  if (VERBOSE) {
    log (level="DEBUG", context=context, ...stmts)
  }
}

var CURL_FLAGS = []

try {
  var args = parseArgs(...ARGV)
}
if failed {
  usage
  exit 1
}

var MAX_VERSIONS = args.max_versions
var OLD_VERSION = args.old_version
var URL = args.url
var VERBOSE = args.verbosity >= 1

if (args.verbosity >= 2) {
  call CURL_FLAGS->append("--verbose")
}

debug "invoked" (ARGV)

if (args.help) {
  usage
  exit 0
}

# we need the bare git URL.
# strip `https://github.com/OWNER/NAME/releases/download/...` -> `https://github.com/OWNER/NAME`
var repo_url = URL.replace(/ '/releases/' .* $ /, "")
debug "extracted" (repo_url)

var all_tags = $(list-git-tags --url="$repo_url") => split(b'\n')
debug "extracted tags" (all_tags)
setvar all_tags = sort_versions (all_tags)
debug "sorted tags" (all_tags)

# # filter to the versions for which we can actually download an artifact.
# # some packages (uBlock) publish releases even before all artifacts are available.
var online_versions = []

# OLD_VERSION is a semver, like 8.9.2, whereas tags may be more rich, e.g. v8.9.2.
# try to locate the tag tied to the current version, and thereby determine a template
# mapping between tag and version.

var version_prefix = null;
for tag in (all_tags) {
  if (tag.endsWith(OLD_VERSION)) {
    var new_prefix = tag.trimEnd(OLD_VERSION)
    if (version_prefix === null) {
      setvar version_prefix = new_prefix
      debug "discovered version_prefix" (version_prefix)
    } elif (new_prefix !== version_prefix) {
      # no common prefix exists
      debug "conflicting version_prefix -> clearing" ([version_prefix, new_prefix])
      setvar version_prefix = ""
    }
  }
}

if (version_prefix === null) {
  setvar version_prefix = ""
}

for tag in (all_tags) {
  var v = tag.trimStart(version_prefix)
  var url_to_test = URL => replace (OLD_VERSION, v);
  debug "testing url" (url_to_test)
  if curl @CURL_FLAGS --fail "$url_to_test" {
    info "found online tag/version" ([tag, v])
    call online_versions -> append (v)
    if (len(online_versions) >= MAX_VERSIONS) {
      break
    }
  }
}

var pretty_versions = online_versions => join(" ")
echo "$pretty_versions"
