name: "Build"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # rebuild everyday at 1:10
    # TIP: Choose a random time here so not all repositories are build at once:
    # https://www.random.org/clock-times/?num=1&earliest=01%3A00&latest=08%3A00&interval=5&format=html&rnd=new
    - cron:  '10 1 * * *'

jobs:
  build:
    strategy:
      matrix:
        nixpkgs:
          - nixpkgs-unstable
          - nixos-unstable
          - nixos-26.05
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v35
      with:
        nix_conf: |
          experimental-features = nix-command flakes ca-derivations
          extra-experimental-features = nix-command flakes ca-derivations
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          keep-going = true
          log-lines = 25
          substituters = https://nix-community.cachix.org https://cache.nixos.org/
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
          trusted-substituters = https://nix-community.cachix.org https://cache.nixos.org/
    - name: Setup cachix
      uses: cachix/cachix-action@v15
      with:
        name: shadowrz
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Show nixpkgs version
      env:
        NIXPKGS_VERSION: ${{ matrix.nixpkgs }}
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version' -I "nixpkgs=https://channels.nixos.org/${NIXPKGS_VERSION}/nixexprs.tar.zst"
    - name: Build
      env:
        NIXPKGS_VERSION: ${{ matrix.nixpkgs }}
      run: nix run github:Mic92/nix-fast-build -- --file . --skip-cached -I "nixpkgs=https://channels.nixos.org/${NIXPKGS_VERSION}/nixexprs.tar.zst"
