# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  "WeidiDeng/caddy-cloudflare-ip" = {
    pname = "WeidiDeng/caddy-cloudflare-ip";
    version = "f53b62aa13cb7ad79c8b47aacc3f2f03989b67e5";
    src = fetchFromGitHub {
      owner = "WeidiDeng";
      repo = "caddy-cloudflare-ip";
      rev = "f53b62aa13cb7ad79c8b47aacc3f2f03989b67e5";
      fetchSubmodules = false;
      sha256 = "sha256-b2JPVdXBgbI91zRzXGut7QKYT/pe15Gcr3JvIKxvTH4=";
    };
    moduleName = "github.com/WeidiDeng/caddy-cloudflare-ip";
    date = "20231130082422+0800";
  };
  "caddy-dns/cloudflare" = {
    pname = "caddy-dns/cloudflare";
    version = "35fb8474f57d7476329f75d63eebafb95a93022f";
    src = fetchFromGitHub {
      owner = "caddy-dns";
      repo = "cloudflare";
      rev = "35fb8474f57d7476329f75d63eebafb95a93022f";
      fetchSubmodules = false;
      sha256 = "sha256-6Od+Ho2Tpn8dsm6fH5SxrGBND9Hfly2uZkTltgXzPE8=";
    };
    moduleName = "github.com/caddy-dns/cloudflare";
    date = "20250506093119-0600";
  };
  catppuccin-kitty = {
    pname = "catppuccin-kitty";
    version = "b14e8385c827f2d41660b71c7fec1e92bdcf2676";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "kitty";
      rev = "b14e8385c827f2d41660b71c7fec1e92bdcf2676";
      fetchSubmodules = false;
      sha256 = "sha256-59ON7CzVgfZUo7F81qQZQ1r6kpcjR3OPvTl99gzDP8E=";
    };
    date = "2024-11-10";
  };
  catppuccin-zsh-fsh = {
    pname = "catppuccin-zsh-fsh";
    version = "a9bdf479f8982c4b83b5c5005c8231c6b3352e2a";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "zsh-fsh";
      rev = "a9bdf479f8982c4b83b5c5005c8231c6b3352e2a";
      fetchSubmodules = false;
      sha256 = "sha256-WeqvsKXTO3Iham+2dI1QsNZWA8Yv9BHn1BgdlvR8zaw=";
    };
    date = "2024-07-20";
  };
  "mholt/caddy-l4" = {
    pname = "mholt/caddy-l4";
    version = "4d3c80e89c5f80438a3e048a410d5543ff5fb9f4";
    src = fetchFromGitHub {
      owner = "mholt";
      repo = "caddy-l4";
      rev = "4d3c80e89c5f80438a3e048a410d5543ff5fb9f4";
      fetchSubmodules = false;
      sha256 = "sha256-JhxoJYatDgOfYO3TJXQdg16RNWualZ1IsIiNEYEjwbA=";
    };
    moduleName = "github.com/mholt/caddy-l4";
    date = "20250530094005-0600";
  };
  "mholt/caddy-webdav" = {
    pname = "mholt/caddy-webdav";
    version = "33ba3cd2088c2219e2eeef1edf949bdd90bf47ab";
    src = fetchFromGitHub {
      owner = "mholt";
      repo = "caddy-webdav";
      rev = "33ba3cd2088c2219e2eeef1edf949bdd90bf47ab";
      fetchSubmodules = false;
      sha256 = "sha256-IpTeH9dK010X2LP00QAOGPjg5LrGVRy2kbAPfDfTu6g=";
    };
    moduleName = "github.com/mholt/caddy-webdav";
    date = "20250609101527-0600";
  };
  rime-ice = {
    pname = "rime-ice";
    version = "2025.04.06";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "2025.04.06";
      fetchSubmodules = false;
      sha256 = "sha256-s3r8cdEliiPnKWs64Wgi0rC9Ngl1mkIrLnr2tIcyXWw=";
    };
  };
  rime-ice-unstable = {
    pname = "rime-ice-unstable";
    version = "7acdee60d09602383b6299d1bdaaba03f0a57869";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "7acdee60d09602383b6299d1bdaaba03f0a57869";
      fetchSubmodules = false;
      sha256 = "sha256-yCVcTc8qitar5JJfVTH4xNJMTPgx/NsRMoTxVm5PVrY=";
    };
    date = "2025-07-06";
  };
  rime-moegirl = {
    pname = "rime-moegirl";
    version = "20250711";
    src = fetchurl {
      url = "https://github.com/outloudvi/mw2fcitx/releases/download/20250711/moegirl.dict.yaml";
      sha256 = "sha256-gs/JhdSeLFkBKvBdVRxk3RhqlkOhly18w4Pz63GG814=";
    };
  };
  yazi-rs-plugins = {
    pname = "yazi-rs-plugins";
    version = "b8860253fc44e500edeb7a09db648a829084facd";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "b8860253fc44e500edeb7a09db648a829084facd";
      fetchSubmodules = false;
      sha256 = "sha256-29K8PmBoqAMcQhDIfOVnbJt2FU4BR6k23Es9CqyEloo=";
    };
    date = "2025-07-06";
  };
}
