name: nix flake check
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: [native-x86_64-linux, bigger-parallel]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - run: nix fmt -L --accept-flake-config -- --ci
      - run: nix flake check --accept-flake-config
