# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0p03wgjffs3k8vcc53zfklwmqrz65rgzhwzy1qgaa9ss4acvfc46";
    x86_64-linux = "1w5shkbzmmx7kgj2pm6ha7n9xihykir46ach3qb9dgzf8nidk1lv";
    armv7l-linux = "19vzfsp498szkncj6yj0567x6xfin7bz9cq2440naas6bwn9yqij";
    aarch64-linux = "02mjbk5pr416b4499vbqzz25ppjj170jik167pvppf4hps8nfazz";
    x86_64-darwin = "0blsn4zzdmvpmfagnyl2rc2ilc5bmxl7iqccxrihhfq5zhdx4rsm";
    aarch64-darwin = "0gcrfnb3m23x1xaa2qp55bhsxzqhpc1lpwchxcaw0z6crxjl95w2";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/crush/releases/download/v0.7.9/crush_0.7.9_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/crush/releases/download/v0.7.9/crush_0.7.9_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/crush/releases/download/v0.7.9/crush_0.7.9_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/crush/releases/download/v0.7.9/crush_0.7.9_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/crush/releases/download/v0.7.9/crush_0.7.9_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/crush/releases/download/v0.7.9/crush_0.7.9_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "crush_0.7.9_Linux_i386";
    x86_64-linux = "crush_0.7.9_Linux_x86_64";
    armv7l-linux = "crush_0.7.9_Linux_armv7";
    aarch64-linux = "crush_0.7.9_Linux_arm64";
    x86_64-darwin = "crush_0.7.9_Darwin_x86_64";
    aarch64-darwin = "crush_0.7.9_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "crush";
  version = "0.7.9";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./crush $out/bin/crush
    installManPage ./manpages/crush.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal.";
    homepage = "https://charm.sh/crush";
    license = lib.licenses.fsl11Mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
