# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0rzmp46a3bfynn0hiaphs7ls26jdx631i7fg2wmi8p34j7xxwqzi";
    x86_64-linux = "17l52pa9lqk4p0xmazmz9gq8nbxk574fzbw7ig1501hamsdw5mly";
    armv7l-linux = "13b4gwp78pfzmbyhvhai3xgnw0sa0dmkcldf26zfm93l0b8g3rrd";
    aarch64-linux = "0zxgf5np7qp37506a8xlmi0f0pyk70zska35k2k1l1v3hd9c3jyd";
    x86_64-darwin = "1c7jk7z4njzlfm8niwrd5i5miyrchcnmbgdqn5cavrfnrygrq6sa";
    aarch64-darwin = "1riga3bl0pnh2jx4y68j65qnprq6i8ipy5xs45vphpn31iqw0dfd";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/crush/releases/download/v0.19.0/crush_0.19.0_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/crush/releases/download/v0.19.0/crush_0.19.0_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/crush/releases/download/v0.19.0/crush_0.19.0_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/crush/releases/download/v0.19.0/crush_0.19.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/crush/releases/download/v0.19.0/crush_0.19.0_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/crush/releases/download/v0.19.0/crush_0.19.0_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "crush_0.19.0_Linux_i386";
    x86_64-linux = "crush_0.19.0_Linux_x86_64";
    armv7l-linux = "crush_0.19.0_Linux_armv7";
    aarch64-linux = "crush_0.19.0_Linux_arm64";
    x86_64-darwin = "crush_0.19.0_Darwin_x86_64";
    aarch64-darwin = "crush_0.19.0_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "crush";
  version = "0.19.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./crush $out/bin/crush
    installManPage ./manpages/crush.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal.";
    homepage = "https://charm.sh/crush";
    license = lib.licenses.fsl11Mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
