# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0pjvmf5f5h0qgbnnncayyp3h1ak5fhpjvbzggs62a53fffyjprjs";
    x86_64-linux = "0zbnzpp0in0yy2arljjxjykxqagx4k6asywq8mxn3p0d6fvccwgj";
    armv7l-linux = "0wjapcvjxlfa3p3w3xwiablvmpfbgyhpg3zvhhzjkyy4qxib5898";
    aarch64-linux = "1c3n6glvxcvvjvj51raziynbdyydfz7d2i5sv82lbw6086mhdlj0";
    x86_64-darwin = "1xjv94y4qfh4nvpmxwc14a7jhmmi1czqfs5fz8q23x0jasm6dzzi";
    aarch64-darwin = "180z0zzj1jvm4w8qj8a4pp3v22ndnz3n9gmpvglpbhgkgj0s9z2x";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/crush/releases/download/v0.7.5/crush_0.7.5_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/crush/releases/download/v0.7.5/crush_0.7.5_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/crush/releases/download/v0.7.5/crush_0.7.5_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/crush/releases/download/v0.7.5/crush_0.7.5_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/crush/releases/download/v0.7.5/crush_0.7.5_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/crush/releases/download/v0.7.5/crush_0.7.5_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "crush_0.7.5_Linux_i386";
    x86_64-linux = "crush_0.7.5_Linux_x86_64";
    armv7l-linux = "crush_0.7.5_Linux_armv7";
    aarch64-linux = "crush_0.7.5_Linux_arm64";
    x86_64-darwin = "crush_0.7.5_Darwin_x86_64";
    aarch64-darwin = "crush_0.7.5_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "crush";
  version = "0.7.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./crush $out/bin/crush
    installManPage ./manpages/crush.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal.";
    homepage = "https://charm.sh/crush";
    license = lib.licenses.fsl11Mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
