# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "013cmbfm0ah209zlmjgk9w13xs95fxs2c51zn247dz88qnf51v1g";
    aarch64-linux = "1q2mp4f2sza9ifpykmxlazl2h3jd4bv639irir33fcy3iscb7kr2";
    x86_64-darwin = "1wq363flxzc500adrwiq4gcj5wlkgkhswahiqmpj953fsvcm9j22";
    aarch64-darwin = "08rih7brg7q475hi2062lc79y1mcnxpxk6gsf70mrh9k4vjwk37s";
  };

  urlMap = {
    x86_64-linux = "https://github.com/goreleaser/nfpm/releases/download/v2.41.0/nfpm_2.41.0_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/goreleaser/nfpm/releases/download/v2.41.0/nfpm_2.41.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/goreleaser/nfpm/releases/download/v2.41.0/nfpm_2.41.0_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/goreleaser/nfpm/releases/download/v2.41.0/nfpm_2.41.0_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "nfpm";
  version = "2.41.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./nfpm $out/bin/nfpm
    installManPage ./manpages/nfpm.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "nFPM is a simple, 0-dependencies, deb, rpm and apk packager.";
    homepage = "https://nfpm.goreleaser.com";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
