#!/usr/bin/env bash

echo "Check evaluation"
nix flake show
echo "Build nix packages"
nix run nixpkgs#nix-fast-build -- --skip-cached --flake ".#checks.$(nix eval --raw --impure --expr builtins.currentSystem)" -j 1 --eval-workers 1
echo "Check evaluation"
nix-env -f . -qa \* --meta --xml \
  --allowed-uris https://static.rust-lang.org \
  --option allow-import-from-derivation true \
  --drv-path --show-trace \
  -I $PWD
echo "Build nix packages"
nix shell -f '<nixpkgs>' nix-build-uncached -c nix-build-uncached ci.nix -A cacheOutputs
