name: "Setup NIX"
description: "Install NIX and Cachix"
inputs:
  channel:
    description: 'Nixpkgs channel'
    required: true
    default: 'nixos-unstable'
  cachix_token:
    description: 'cachix auth token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Reclaim space
      uses: wimpysworld/nothing-but-nix@v6
      with:
        hatchet-protocol: rampage

    - shell: bash
      run: |
        sudo mkdir -m0770 -p /nix/var/cache/ccache

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v20
      with:
        extra-conf: |
          extra-sandbox-paths = /nix/var/cache/ccache

    - uses: cachix/cachix-action@v15
      with:
        name: slaier
        authToken: ${{ inputs.cachix_token }}
        extraPullNames: nix-community

    - shell: bash
      run: |
        sudo chown --reference=/nix/store /nix/var/cache/ccache
