name: "Setup NIX"
description: "Install NIX and Cachix"
inputs:
  channel:
    description: 'Nixpkgs channel'
    required: true
    default: 'nixos-unstable'
  cachix_token:
    description: 'cachix auth token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Reclaim space
      uses: wimpysworld/nothing-but-nix@v10
      with:
        hatchet-protocol: rampage
        nix-permission-edict: true

    - shell: bash
      run: |
        sudo mkdir -m0770 -p /nix/var/cache/ccache

    - name: Install Nix
      uses: cachix/install-nix-action@v31.10.6
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          build-dir = /nix/build
          extra-sandbox-paths = /nix/var/cache/ccache

    - uses: cachix/cachix-action@v15
      with:
        name: slaier
        authToken: ${{ inputs.cachix_token }}
        extraPullNames: nix-community

    - shell: bash
      run: |
        sudo chown --reference=/nix/store /nix/var/cache/ccache
