# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0cb50wgzcfsfj6g9h8yhpnd1cmplir6zldbl72k0d30fni6c5zxz";
    x86_64-linux = "02a7crwflxpv3574nhvbj8h1vvzvqz1qsdrhf3wwdx171yfi8mqd";
    armv7l-linux = "1yaawxfsc1hyiqf73a08gs2b74vbngq6jipvc8gjpbirnl61cpja";
    aarch64-linux = "0s679rsl9rgni0fm5jj96pdlsqhna1jlis5zcmrhbn10habyd6yy";
    x86_64-darwin = "13jwqip6jbxmqv59v3h69iv69wvi7fl4bs90bpnmxvgym7ihgz62";
    aarch64-darwin = "1fnsv5iya9d9y6irhj9y63ykmdc2bjnczy4wjav5z0ig9kgmwrn8";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/markscribe/releases/download/v0.8.0/markscribe_0.8.0_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/markscribe/releases/download/v0.8.0/markscribe_0.8.0_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/markscribe/releases/download/v0.8.0/markscribe_0.8.0_Linux_arm.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/markscribe/releases/download/v0.8.0/markscribe_0.8.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/markscribe/releases/download/v0.8.0/markscribe_0.8.0_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/markscribe/releases/download/v0.8.0/markscribe_0.8.0_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "markscribe_0.8.0_Linux_i386";
    x86_64-linux = "markscribe_0.8.0_Linux_x86_64";
    armv7l-linux = "markscribe_0.8.0_Linux_arm";
    aarch64-linux = "markscribe_0.8.0_Linux_arm64";
    x86_64-darwin = "markscribe_0.8.0_Darwin_x86_64";
    aarch64-darwin = "markscribe_0.8.0_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "markscribe";
  version = "0.8.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./markscribe $out/bin/markscribe
  '';

  system = system;

  meta = {
    description = "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers";
    homepage = "https://charm.sh/";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
