# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  gitpane = {
    pname = "gitpane";
    version = "v0.7.14";
    src = fetchFromGitHub {
      owner = "affromero";
      repo = "gitpane";
      rev = "v0.7.14";
      fetchSubmodules = false;
      sha256 = "sha256-aT0kFoqF7w0MAVf9Ou/TknpB96FZN2ON185AGl5Q4qM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-aT0kFoqF7w0MAVf9Ou_TknpB96FZN2ON185AGl5Q4qM=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  hammerspoon = {
    pname = "hammerspoon";
    version = "1.1.1";
    src = fetchurl {
      url = "https://github.com/Hammerspoon/hammerspoon/releases/download/1.1.1/Hammerspoon-1.1.1.zip";
      sha256 = "sha256-EbsckPr1Qn83x71P5+q5d0rkPh1csCDFswiNrDKEnvo=";
    };
  };
  mermaid-rs-renderer = {
    pname = "mermaid-rs-renderer";
    version = "v0.2.2";
    src = fetchFromGitHub {
      owner = "1jehuang";
      repo = "mermaid-rs-renderer";
      rev = "v0.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-iV9kiAaGMVDfWu2BGbalw5NmzmTEsbZWWCh6oQ9BroY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-iV9kiAaGMVDfWu2BGbalw5NmzmTEsbZWWCh6oQ9BroY=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  omniwm = {
    pname = "omniwm";
    version = "v0.4.9.8";
    src = fetchurl {
      url = "https://github.com/BarutSRB/OmniWM/releases/download/v0.4.9.8/OmniWM-v0.4.9.8.zip";
      sha256 = "sha256-PTvpSwTJnj9BKZ+Hx5lC1t7npaQ7hNQ3N02T6m8Bx1I=";
    };
  };
  paperwm-spoon = {
    pname = "paperwm-spoon";
    version = "3a6d076c5169d693e6271d5af5038036bd591bbd";
    src = fetchFromGitHub {
      owner = "mogenson";
      repo = "PaperWM.spoon";
      rev = "3a6d076c5169d693e6271d5af5038036bd591bbd";
      fetchSubmodules = false;
      sha256 = "sha256-H9A7nwt0NkyPqN+iOZ9BU24dkAvvfZxucVSPhNx9WPA=";
    };
    date = "2026-05-29";
  };
  powershell-beautifier = {
    pname = "powershell-beautifier";
    version = "V1.2.5";
    src = fetchFromGitHub {
      owner = "DTW-DanWard";
      repo = "PowerShell-Beautifier";
      rev = "V1.2.5";
      fetchSubmodules = false;
      sha256 = "sha256-N/Wz2TDgQFEW//QR5SwzFFJAiRx8+RoMS842m27mYjM=";
    };
  };
}
