# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  gitpane = {
    pname = "gitpane";
    version = "v0.6.2";
    src = fetchFromGitHub {
      owner = "affromero";
      repo = "gitpane";
      rev = "v0.6.2";
      fetchSubmodules = false;
      sha256 = "sha256-+tyG6bzWEicVMvjFlw6ItEcYfOssB/K2JS9qkG89oaY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-+tyG6bzWEicVMvjFlw6ItEcYfOssB_K2JS9qkG89oaY=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  hammerspoon = {
    pname = "hammerspoon";
    version = "1.1.1";
    src = fetchurl {
      url = "https://github.com/Hammerspoon/hammerspoon/releases/download/1.1.1/Hammerspoon-1.1.1.zip";
      sha256 = "sha256-EbsckPr1Qn83x71P5+q5d0rkPh1csCDFswiNrDKEnvo=";
    };
  };
  mermaid-rs-renderer = {
    pname = "mermaid-rs-renderer";
    version = "v0.2.2";
    src = fetchFromGitHub {
      owner = "1jehuang";
      repo = "mermaid-rs-renderer";
      rev = "v0.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-iV9kiAaGMVDfWu2BGbalw5NmzmTEsbZWWCh6oQ9BroY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-iV9kiAaGMVDfWu2BGbalw5NmzmTEsbZWWCh6oQ9BroY=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  omniwm = {
    pname = "omniwm";
    version = "v0.4.8.1";
    src = fetchurl {
      url = "https://github.com/BarutSRB/OmniWM/releases/download/v0.4.8.1/OmniWM-v0.4.8.1.zip";
      sha256 = "sha256-f2ByexWwgc9qzUC0wbXf0nDIMl4w1xtuUfXpmzA/CFc=";
    };
  };
  paperwm-spoon = {
    pname = "paperwm-spoon";
    version = "97c88cb16fc9330f9e1f71cd8defc17fd865afe4";
    src = fetchFromGitHub {
      owner = "mogenson";
      repo = "PaperWM.spoon";
      rev = "97c88cb16fc9330f9e1f71cd8defc17fd865afe4";
      fetchSubmodules = false;
      sha256 = "sha256-EmPIcF2e19fs6Pv3eCC94DdwlB79qWTk3yPXUfZbCio=";
    };
    date = "2026-05-01";
  };
  powershell-beautifier = {
    pname = "powershell-beautifier";
    version = "V1.2.5";
    src = fetchFromGitHub {
      owner = "DTW-DanWard";
      repo = "PowerShell-Beautifier";
      rev = "V1.2.5";
      fetchSubmodules = false;
      sha256 = "sha256-N/Wz2TDgQFEW//QR5SwzFFJAiRx8+RoMS842m27mYjM=";
    };
  };
}
