# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  gitpane = {
    pname = "gitpane";
    version = "v0.7.3";
    src = fetchFromGitHub {
      owner = "affromero";
      repo = "gitpane";
      rev = "v0.7.3";
      fetchSubmodules = false;
      sha256 = "sha256-4lJ+aLuHC0bdSfTX0jsiYzzHwVddbMfQiFBKQoawld4=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-4lJ+aLuHC0bdSfTX0jsiYzzHwVddbMfQiFBKQoawld4=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  hammerspoon = {
    pname = "hammerspoon";
    version = "1.1.1";
    src = fetchurl {
      url = "https://github.com/Hammerspoon/hammerspoon/releases/download/1.1.1/Hammerspoon-1.1.1.zip";
      sha256 = "sha256-EbsckPr1Qn83x71P5+q5d0rkPh1csCDFswiNrDKEnvo=";
    };
  };
  mermaid-rs-renderer = {
    pname = "mermaid-rs-renderer";
    version = "v0.2.2";
    src = fetchFromGitHub {
      owner = "1jehuang";
      repo = "mermaid-rs-renderer";
      rev = "v0.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-iV9kiAaGMVDfWu2BGbalw5NmzmTEsbZWWCh6oQ9BroY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-iV9kiAaGMVDfWu2BGbalw5NmzmTEsbZWWCh6oQ9BroY=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  omniwm = {
    pname = "omniwm";
    version = "v0.4.9.5";
    src = fetchurl {
      url = "https://github.com/BarutSRB/OmniWM/releases/download/v0.4.9.5/OmniWM-v0.4.9.5.zip";
      sha256 = "sha256-h4ax/9LeRZwoT+TIptJIk078+66tynnc+ULmU57WZRA=";
    };
  };
  paperwm-spoon = {
    pname = "paperwm-spoon";
    version = "c6ee4c18ef9234a9dce1cd3c88d1d0e705481e80";
    src = fetchFromGitHub {
      owner = "mogenson";
      repo = "PaperWM.spoon";
      rev = "c6ee4c18ef9234a9dce1cd3c88d1d0e705481e80";
      fetchSubmodules = false;
      sha256 = "sha256-BwDrW8ItjZot0unyRXtFXnHqXq7/gojn+vTB5sY2G8A=";
    };
    date = "2026-05-10";
  };
  powershell-beautifier = {
    pname = "powershell-beautifier";
    version = "V1.2.5";
    src = fetchFromGitHub {
      owner = "DTW-DanWard";
      repo = "PowerShell-Beautifier";
      rev = "V1.2.5";
      fetchSubmodules = false;
      sha256 = "sha256-N/Wz2TDgQFEW//QR5SwzFFJAiRx8+RoMS842m27mYjM=";
    };
  };
}
