#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i bash ../../../../integrations/nix-shell --arg f 'ps: [ ps.bash ps.curl ps.gitMinimal ps.nix ps.patchutils ]'

set -eu

usage() {
  echo "USAGE: vendor-patch-updater [--revert] [revert-]PR_NUMBER_OR_COMMIT"
  echo "creates or updates the patch file indicated by the PR/commit"
  echo ""
  echo "FLAGS"
  echo "  --revert    fetch the patch, and then revert it before vendoring."
  echo "              if the patch identifier starts with 'revert-', this is implied"
  echo "              and if --revert is specified then 'revert-' is implicitly prepended to the vendored patch name"
}

# ident: PR number or commit hash
ident=
# revert: "" or "revert-" to signify that `ident` should be reverted before saving to the patches/ dir
revert=
parseArgs() {
  while [ "$#" -ne 0 ]; do
    local arg=$1
    shift
    case $arg in
      (--help)
        usage
        exit 0
        ;;
      (--revert)
        revert=revert-
        ;;
      (*)
        if [ -z "$ident" ]; then
          ident=$arg
        else
          usage
          exit 1
        fi
        ;;
    esac
  done

  if [[ "$ident" == revert-* ]]; then
    revert=revert-
    ident=${ident/revert-/}
  fi

  ident=$(parseIdent $ident)

  if [ -z "$ident" ]; then
    usage
    exit 1
  fi
}

parseIdent() {
  local ident=$1
  # best effort to map various URIs back to their PR or commit number.
  # this function serves the manual invocations to vendor-patch-updater, as updateScripts always pass in the parsed ident.
  ident=${ident/https:\/\/github.com\/NixOS\/nixpkgs\/pull\//}
  ident=${ident/.patch/}
  ident=${ident/.diff/}
  echo "$ident"
}

tryPatchesDir() {
  echo "tryPatchesDir: have='${PATCHES_DIR:-}' .. considering='$1'"
  if [ -z "${PATCHES_DIR:-}" ] && [ -d "$1" ]; then
    export PATCHES_DIR=$1
  fi
}

getPatchesDir() {
  # invoked from update script
  if [ -n "${UPDATE_NIX_ATTR_PATH:-}" ]; then
    local attrPos=$(nix-instantiate --raw --eval -A "$UPDATE_NIX_ATTR_PATH.meta.position")
    if [ -n "$attrPos" ]; then
      tryPatchesDir "$(dirname $(dirname $attrPos))/patches"
    fi
  fi
  # invoked from update script, but the attr path fails to eval (it's a quoting issue, for patches which aren't valid identifiers).
  # or invoked from root
  local gitTop=$(git rev-parse --show-toplevel || true)
  if [ -n "$gitTop" ]; then
    tryPatchesDir "$gitTop/pkgs/by-name/nixpkgs-bootstrap/patches"
  fi
  # fail if unable to locate
  test -n "${PATCHES_DIR:-}"
}

tryUri() {
  local output=$1
  local uri=$2
  local scratch=$(mktemp)
  curl --follow --fail "$uri" -o "$scratch" && test -s "$scratch" && mv "$scratch" "$output"
}

main() {
  local ident=$1
  local scratch=$(mktemp)
  local output=$PATCHES_DIR/$revert$ident.patch
  # N.B.: github's commit endpoint replies to short hashes; a PR number may also be a value short hash,
  # so try the GH commit endpoint *last*. Gitea does not have this problem.
  tryUri "$scratch" "https://git.uninsane.org/colin/nixpkgs/commit/$ident.patch?full_index=1" || \
    tryUri "$scratch" "https://github.com/NixOS/nixpkgs/pull/$ident.patch?full_index=1" || \
    tryUri "$scratch" "https://github.com/uninsane/nixpkgs/commit/$ident.patch?full_index=1"

  if [ -n "$revert" ]; then
    interdiff "$scratch" /dev/null > "$output"
  else
    mv "$scratch" "$output"
  fi
}

parseArgs "$@"
set -x
getPatchesDir
main "$ident"
