[bitburner]
pr = "https://github.com/NixOS/nixpkgs/pull/542677"

[eez-studio]
pr = "https://github.com/NixOS/nixpkgs/pull/493671"

[fmodstudio]
pr = "https://github.com/NixOS/nixpkgs/pull/491823"

[icu56]
pr = "https://github.com/NixOS/nixpkgs/pull/491823"

[keyguard]
pr = "https://github.com/NixOS/nixpkgs/pull/495316"

[pokeclicker]

[pokeclicker-desktop]
pr = "https://github.com/NixOS/nixpkgs/pull/545651"

[wl-find-cursor]
pr = "https://github.com/NixOS/nixpkgs/pull/504085"
merged = true
removeAfter = 2605

[zellij-autolock]
pr = "https://github.com/NixOS/nixpkgs/pull/548437"
merged = true
removeAfter = 2605
replacementMessage = "Please replace `${pkgs.nur.repos.ilkecan.zellij-autolock}/share/zellij/plugins/zellij-autolock.wasm` with `${pkgs.zellijPlugins.autolock}`."

[zellij-workspace]
pr = "https://github.com/NixOS/nixpkgs/pull/548444"
merged = true
removeAfter = 2605
replacementMessage = "Please replace `${pkgs.nur.repos.ilkecan.zellij-workspace}/share/zellij/plugins/zellij-workspace.wasm` with `${pkgs.zellijPlugins.workspace}`."
