#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i bash ../../../../integrations/nix-shell --arg f 'ps: [ ps.bash ps.nettools ps.systemd ]'

set -eu

usage() {
  echo "sane-shutdown HOST"
  echo "  shutdown the current machine, so long as its hostname equals HOST"
}

target=
parseArgs() {
  while [ "$#" -ne 0 ]; do
    local arg=$1
    shift
    case $arg in
      (--help)
        usage
        exit 0
        ;;
      (*)
        if [ -z "$target" ]; then
          target=$arg
        else
          usage
          exit 1
        fi
        ;;
    esac
  done
}

main() {
  local target="$1"
  local host="$(hostname)"
  if [ "$host" = "$target" ]
  then
    shutdown now "$@"
  else
    echo "WRONG MACHINE. you're on $host."
    exit 1
  fi
}

parseArgs "$@"
main "$target"
