#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i bash ../../../../integrations/nix-shell --arg f 'ps: [ ps.bash ps.coreutils-full ps.findutils ps.sops ]'

usage() {
  echo "sane-secrets-update-keys DIRECTORY..."
  echo
  echo "after modifying .sops.yaml, run this to re-encode all secrets to the new keys"
  echo "pass the base directory (under which *everything* is a secret) as argument(s)"
}

paths=()
parseArgs() {
  while [ "$#" -ne 0 ]; do
    local arg=$1
    shift
    case $arg in
      (--help)
        usage
        exit 0
        ;;
      (*)
        paths+=("$arg")
        ;;
    esac
  done
}

main() {
  for base in "${paths[@]}"; do
    for i in $(find "$base" -print)
    do
      yes | sops updatekeys "$i"
    done
  done
}

parseArgs "$@"
main
