#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i python3 ../../../../integrations/nix-shell --arg f 'ps: [ ps.inetutils ps.miniupnpc ps.python3 ps.sane-scripts.lib.ssdp ]'
# vim: set filetype=python :

USAGE = '''
USAGE: sane-ip-port-forward [options] [proto:port[:desc]]*

options:
  -v:  verbose (show info messages)
  -vv: more verbose (show debug messages)
  -h:  show this help messages
  -d <int>: lease for the given duration in seconds (default: {DEFAULT_LEASE_SEC})

proto:port[:desc]:
  proto is `udp` or `tcp` (case insensitive)
  port is any integer 1-65535 inclusive
  desc is some public description of the port forward (for humans trying to understand a network config)
'''

DEFAULT_LEASE_SEC = 86400

import logging
import subprocess
import sys

from dataclasses import dataclass
from typing import List, Optional, Tuple

from sane_ssdp import get_any_wan, forward_port

logger = logging.getLogger(__name__)

class Usage(Exception):
    def __init__(self, msg: str = None):
        helpstr = USAGE.format(DEFAULT_LEASE_SEC=DEFAULT_LEASE_SEC).strip()
        if msg:
            super().__init__(f"{msg}\n\n{helpstr}")
            self.exit_ = 1
        else:
            super().__init__(helpstr)
            self.exit_ = 0

@dataclass
class PortForward:
    proto: str  # udp or tcp
    port: int
    external_port: int  # usually same as `port`
    description: str

def try_parse_port(s: str) -> Optional[PortForward]:
    """
    `udp:53` -> ["udp", 53, 53, ""]
    `tcp:65535:my description` -> ["tcp", 65535, 65535, "my description"]
    `tcp:65535:1234:my description` -> ["tcp", 65535, 1234, "my description"]

    try to be tolerant of the description field including colons.
    """
    s = s.strip()

    def split_at_colon(s_: str) -> Tuple[str, str]:
        next_colon = s_.find(":")
        return s_[:next_colon], s_[next_colon+1:]

    if ":" not in s: return  # invalid format
    proto, rest = split_at_colon(s)

    if ":" in rest:
        portstr, rest = split_at_colon(rest)
    else:
        portstr = rest
        rest = ""

    if ":" in rest and all(c in "0123456789" for c in rest[:rest.find(":")]):
        external_portstr, rest = split_at_colon(rest)
    else:
        external_portstr = ""

    desc = rest

    try:
        proto, port, external_port = proto.lower(), int(portstr), int(external_portstr or portstr)
        assert proto in ["tcp", "udp"]
        assert 0 < port < 65536
        return PortForward(proto=proto, port=port, external_port=external_port, description=desc)
    except Exception:
        pass

def parse_args(argv: List[str]) -> List[PortForward]:
    """
    returns (list of forwards, lease duration)
    where:
    - list of forwards is [('udp'|'tcp', port: int, description: str)]
    - lease duration is seconds: int
    """
    forwards = []
    duration = DEFAULT_LEASE_SEC
    unparsed = sys.argv[1:][::-1]
    while unparsed:
        arg = unparsed.pop()
        if arg in ["-h", "--help"]:
            raise Usage()
        if arg == "-v":
            logging.getLogger().setLevel(logging.INFO)
        elif arg == "-vv":
            logging.getLogger().setLevel(logging.DEBUG)
        elif arg == "-d" and unparsed:
            d = unparsed.pop()
            try:
                duration = int(d)
            except Exception:
                raise Usage(f"invalid CLI argument: -d {d!r}")
        elif try_parse_port(arg):
            forwards.append(try_parse_port(arg))
        else:
            raise Usage(f"invalid CLI argument: {arg!r}")
    return forwards, duration

if __name__ == '__main__':
    logging.basicConfig()

    try:
        forwards, duration = parse_args(sys.argv)
    except Usage as e:
        print(e)
        sys.exit(e.exit_)

    logger.debug("ports to forward: %r", forwards)

    root_device, lan, _wan = get_any_wan(cached=True)
    for f in forwards:
        forward_port(root_device, f.proto, f.port, f.external_port, lan_ip=lan, reason=f.description, duration=duration)
