#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i bash ../../../../integrations/nix-shell --arg f 'ps: [ ps.bash ps.rsync ]'
# rsync, with sane defaults
# + verbosity
# + default to cwd as destination if none is provided
dest=
if (( $# <= 1 )); then
        # rsync to the current directory by default
        dest='.'
fi
rsync -arv --progress --append-verify "$@" $dest
