#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i bash ../../../../integrations/nix-shell --arg f 'ps: [ ps.bash ps.nix ]'

# script to reclaim some hard drive space
# some of this is documented here:
# - <https://nixos.wiki/wiki/Storage_optimization>

set -eu

usage() {
  echo "sane-reclaim-disk-space"
  echo "  equivalent to:"
  echo '  $ nix-env --profile /nix/var/nix/profiles/system --delete-generations 14d'
  echo '  $ nix-collect-garbage --delete-older-than 14d'
  echo ""
  echo 'flags:'
  echo '--keep-days NUM_DAYS   [default: 14]'
  echo '--max-freed NUM_BYTES  [default: 500000000000]'
}

keepDays=14
maxFreed=500000000000  # 500 GB
parseArgs() {
  while [ "$#" -ne 0 ]; do
    local arg=$1
    shift
    case $arg in
      (--help)
        usage
        exit 0
        ;;
      (--keep-days)
        keepDays=$1
        shift
        ;;
      (--max-freed)
        maxFreed=$1
        shift
        ;;
      (*)
        usage
        exit 1
        ;;
    esac
  done
}

main() {
  if [ "$(id -u)" -ne 0 ]; then
    echo 'must be run as root!'
  fi

  # scan the store and hard-link identical files
  # nix-store --optimise
  (
    set -x;
    nix-env --profile /nix/var/nix/profiles/system --delete-generations "$keepDays"d;
    nix-collect-garbage --delete-older-than "$keepDays"d --max-freed "$maxFreed";
  )

  echo 'to free more space (e.g. boot space), manually manage the profiles'
  echo '- nix-env --profile /nix/var/nix/profiles/system --list-generations'
  echo '- nix-env --profile /nix/var/nix/profiles/system --delete-generations {first..last}'
  echo '- sudo sane-reclaim-boot-space'
}

parseArgs "$@"
main
