wireplumber.settings = {
  device.restore-profile = false
  # persist device volume/mute/codec switches
  device.restore-routes = true
  # persist system default source/sink: true/false
  node.restore-default-targets = false
  # persist app volume/mute settings: true/false
  node.stream.restore-props = false
  # persist app input/output links: true/false
  node.stream.restore-target = false
}

# log spec is "[<topic>:]level,...,"
# where `level` is
# - `0` or `F`: fatal errors
# - `1` or `E`: critical warnings
# - `2` or `W` or `N`: warnings and notices
# - `3` or `I`: informational messages
# - `4` or `D`: debug messages
# - `5` or `T`: trace messages
# context.properties = {
#   log.level = "D"
# }
