wireplumber.components = [
  {
    name = "autolink-mic-effects.lua", type = script/lua
    provides = custom.autolink-mic-effects
  }
]

wireplumber.profiles = {
  main = {
    custom.autolink-mic-effects = required
  }
}
