#!/usr/bin/env python3
"""Generator for the four corpora the CI performance gate was missing.

`benches/compile.rs` protects only the shapes that happen to be in
`bench/corpus/generated/`, and three planned improvements measure *zero* there
(`docs/PERF_PLAN_2026-09-16.md`, B4). This script emits the shapes where they
are visible, so that landing them and later regressing them are distinguishable
in CI:

  gate/legacy_deprecations.scss  legacy colour functions called from one mixin,
                                 so ~13 spans repeat ~1200 times: the
                                 deprecation bookkeeping path, and the most
                                 sensitive early warning for the whole
                                 diagnostics area.
  gate/extend_heavy.scss         placeholder and class `@extend` in chains and
                                 inside nested/at-rule contexts, the shape that
                                 real frameworks hit and `large.scss` does not
                                 contain at all.
  gate/use_graph/**              a multi-file `@use` graph, plus a second entry
                                 that reaches every module through two paths
                                 (the redundant-`@use` case).
  gate/selector_lists.scss       multi-line comma selector lists, which is the
                                 ONLY way to reach `eval_style_rule`'s
                                 `share_current == false` branch -- the one
                                 every other corpus, `large.scss` included,
                                 leaves at zero.

Deterministic by construction -- no PRNG, no clock, no environment -- so
re-running rewrites byte-identical files. The output is checked into git, like
`bench/corpus/generated/large.scss`, because `benches/compile.rs` reads it with
`include_str!` and the benchmark must not depend on a generator having been run.

Usage:
    python3 bench/scripts/gen_gate_corpora.py           # rewrite in place
    python3 bench/scripts/gen_gate_corpora.py --check    # verify, write nothing

`--check` exits non-zero if any file on disk differs from what this script
would emit, which is what makes MANIFEST.json worth having: it says which
generator version produced the corpus, so a hand-edit is visible.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

GENERATOR_VERSION = 2
REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = REPO_ROOT / "bench" / "corpus" / "gate"

# The marker rule every benchmark can assert on, so a corpus that silently
# stopped compiling cannot masquerade as a fast one.
MARKER = ".sasso-gate-corpus"

HEADER = (
    "// GENERATED by bench/scripts/gen_gate_corpora.py -- do not edit by hand.\n"
    "// Regenerate with `python3 bench/scripts/gen_gate_corpora.py`.\n"
)

# ----------------------------------------------------------------- corpus 1

# 150 x 8 = 1200 mixin includes over 13 deprecated call sites. The call sites
# live INSIDE the mixin on purpose: every include reports the same ~13 spans,
# which is what makes this a saturated test of the deprecation dedup and memo
# rather than a test of how fast 15600 distinct warnings can be constructed.
DEPRECATION_REPEATS = 150
PALETTE = [
    "#3498db",
    "#e74c3c",
    "#2ecc71",
    "#f1c40f",
    "#9b59b6",
    "#1abc9c",
    "#e67e22",
    "#34495e",
]


def legacy_deprecations() -> str:
    """A legacy-deprecation-dense sheet: the A1 lever's best case.

    Every function named here is deprecated in dart-sass 1.103 -- either a
    global built-in with a module equivalent, or one of the legacy colour
    functions -- so each `@include` walks the whole diagnostics path: the
    `deprecates()` name check, the dedup key, and (for the colour functions)
    the replacement suggestion.
    """
    out = [HEADER]
    out.append("$palette: (%s);\n" % ", ".join(PALETTE))
    out.append(
        """@mixin legacy($c) {
  color: darken($c, 20%);
  border-color: lighten($c, 10%);
  background: saturate($c, 15%);
  outline-color: desaturate($c, 5%);
  box-shadow: 0 0 2px transparentize($c, 0.3);
  fill: opacify($c, 0.2);
  stroke: adjust-hue($c, 30deg);
  --r: #{red($c)};
  --g: #{green($c)};
  --h: #{hue($c)};
  --s: #{saturation($c)};
  --l: #{lightness($c)};
}
"""
    )
    out.append(
        """@for $i from 1 through %d {
  @each $c in $palette {
    .legacy-#{$i}-#{index($palette, $c)} { @include legacy($c); }
  }
}
"""
        % DEPRECATION_REPEATS
    )
    out.append("%s { --generated: true; }\n" % MARKER)
    return "".join(out)


# ----------------------------------------------------------------- corpus 2

# `@extend` cost grows super-linearly (measured exponent ~1.8 before the A2
# lever, ~1.4-1.6 after), so these counts are chosen for a compile in the same
# order of magnitude as `large.scss` rather than for the largest possible delta.
# 6 roots x 4 bases x 3 concretes, plus 4 combo placeholders, 6 class variants
# and 4 media blocks, measured 7.6 ms/compile and showed the A2 prototype at
# -49.7% (macOS/arm64, 2026-09-16).
EXTEND_ROOTS = 6
EXTEND_BASES_PER_ROOT = 4
EXTEND_CONCRETES_PER_BASE = 3
EXTEND_MEDIA_QUERIES = 4
EXTEND_NESTED_EVERY = 3


def extend_heavy() -> str:
    """An `@extend`-heavy sheet: the A2 lever's corpus.

    Three properties matter, and all three come from real frameworks rather
    than from what is convenient to generate:

    * **Chains.** A placeholder extends a placeholder, and a concrete selector
      extends that, so `extend_to_fixpoint` actually iterates instead of
      settling in one pass.
    * **Class extends, not only placeholders.** Extending a `.class` leaves the
      extended rule in the output and multiplies its selector list, which is
      the case the extend store indexes.
    * **Nested and at-rule contexts.** `@extend` inside a nested rule and
      inside `@media` is where the extender's own selector has to be resolved
      against its parent before it can be registered.
    """
    out = [HEADER]

    for r in range(1, EXTEND_ROOTS + 1):
        out.append(
            """%%root-%d {
  box-sizing: border-box;
  display: inline-flex;
  font: inherit 1rem/%s sans-serif;
  transition: color %dms ease-in-out;
}
"""
            % (r, "1.%d" % (r % 7 + 2), 80 + r * 5)
        )

    for r in range(1, EXTEND_ROOTS + 1):
        for b in range(1, EXTEND_BASES_PER_ROOT + 1):
            out.append(
                """%%base-%d-%d {
  @extend %%root-%d;
  border: %dpx solid rgba(0, 0, 0, 0.%d);
  padding: %dpx %dpx;
  &:focus-visible { outline: 2px solid #3498db; }
}
"""
                % (r, b, r, b % 3 + 1, (r + b) % 9 + 1, b * 2, b * 3)
            )

    # A second layer of placeholders, each extending two bases from different
    # roots: the transitive closure is what the fixpoint loop is for.
    for b in range(1, EXTEND_BASES_PER_ROOT + 1):
        left = (b - 1) % EXTEND_ROOTS + 1
        right = b % EXTEND_ROOTS + 1
        out.append(
            """%%combo-%d {
  @extend %%base-%d-%d;
  @extend %%base-%d-%d;
  gap: %dpx;
}
"""
            % (b, left, b, right, b, b + 1)
        )

    n = 0
    for r in range(1, EXTEND_ROOTS + 1):
        for b in range(1, EXTEND_BASES_PER_ROOT + 1):
            for c in range(1, EXTEND_CONCRETES_PER_BASE + 1):
                n += 1
                # Only every EXTEND_NESTED_EVERY'th concrete extends from a
                # nested context. Every one of them doing so is a fine
                # microbenchmark and a poor CI corpus: the first shape tried
                # here (12 roots x 8 bases x 4 concretes, all of them nested)
                # measured 442 ms/compile against this one's 7.6 ms, buying a
                # bigger delta with ~58x the runner time.
                nested = (
                    "\n  .inside & { @extend %%combo-%d; }"
                    % ((b + c - 1) % EXTEND_BASES_PER_ROOT + 1)
                    if n % EXTEND_NESTED_EVERY == 0
                    else ""
                )
                out.append(
                    """.c-%d-%d-%d {
  @extend %%base-%d-%d;
  color: #%02x%02x%02x;%s
}
"""
                    % (r, b, c, r, b, r * 17 % 256, b * 29 % 256, c * 53 % 256, nested)
                )

    # Extending a class rather than a placeholder: `.btn` survives into the
    # output and grows a selector list, which placeholders never do.
    out.append(
        """.btn {
  appearance: none;
  cursor: pointer;
}
"""
    )
    for r in range(1, EXTEND_ROOTS + 1):
        out.append(
            """.btn-variant-%d {
  @extend .btn;
  background: hsl(%d, 60%%, 50%%);
}
"""
            % (r, r * 29 % 360)
        )

    # `@extend` inside `@media` -- with the extended selector inside the same
    # query, because dart-sass rejects extending across one ("You may not
    # @extend selectors across media queries"), which is itself a reason this
    # corpus has to be compiled rather than assumed correct.
    for q in range(1, EXTEND_MEDIA_QUERIES + 1):
        out.append(
            """@media (min-width: %dpx) {
  %%mq-%d {
    display: grid;
    grid-template-columns: repeat(%d, minmax(0, 1fr));
  }
  .responsive-%d { @extend %%mq-%d; }
  .responsive-%d .nested { @extend %%mq-%d; }
  .responsive-%d:not(.plain) { @extend %%mq-%d; }
}
"""
            % (320 * q, q, q + 1, q, q, q, q, q, q)
        )

    out.append("%s { --generated: true; }\n" % MARKER)
    return "".join(out)


# ----------------------------------------------------------------- corpus 3

# 6 sections x 5 components + 2 token files + 3 vendor files + 2 entries = 43
# files in the corpus, of which either entry loads 42 -- close to the 36-file
# real-world shape the modular corpus mirrors.
USE_SECTIONS = 6
USE_COMPONENTS_PER_SECTION = 5


SELECTOR_LIST_GROUPS = 120
SELECTOR_LIST_WIDTH = 4


def selector_lists() -> str:
    """Multi-line comma selector lists, and a few selectors dart-sass drops.

    This corpus exists because of a gap, not because of a lever. `share_current`
    in `eval_style_rule` is the fast path that skips the per-complex rebuild,
    and it is false whenever the rule carries per-complex line-break flags --
    which is to say whenever the author wrote a comma selector list across
    lines, the normal shape of hand-written CSS. Every other corpus here, and
    `large.scss`, has exactly ZERO of those, so the slow branch was never
    benchmarked: work added to it was not merely unmeasured but unmeasurable.

    Three properties, each for a reason:

    * **The lists span lines.** A single-line `a, b {` does not set the flags;
      the newline is what does.
    * **The lists are nested.** `current_linebreaks` is handed to every
      descendant rule, so a nested body inherits the branch from its parent --
      the poisoning chain, and the reason one list at the top of a file is
      enough to move a whole sheet onto it.
    * **A few of them are bogus.** A repeated combinator run (`> +`) is dropped
      from the output with a `bogus-combinators` warning, which is the only
      shape that reaches the span-mapping added for #119/#120. Kept rare, the
      way it is in real sheets, so the corpus measures the common branch and
      merely visits the rare one.
    """
    out = [HEADER]

    for g in range(1, SELECTOR_LIST_GROUPS + 1):
        names = ",\n".join(
            "  .grp-%d-%d .item" % (g, k) for k in range(1, SELECTOR_LIST_WIDTH + 1)
        )
        out.append(
            """%s {
  color: #%02x%02x%02x;
  margin-block: %dpx;

  .nested-a,
  .nested-b {
    padding-inline: %dpx;
    &:hover { opacity: 0.%d; }
  }
}
"""
            % (
                names.lstrip(),
                (g * 7) % 256,
                (g * 13) % 256,
                (g * 29) % 256,
                g % 12,
                g % 9,
                g % 9 + 1,
            )
        )

    # The dropped shape, at roughly the density a real sheet carries it.
    for g in range(1, SELECTOR_LIST_GROUPS // 20 + 1):
        out.append(
            """.bogus-%d >  + .tail,
.bogus-%d >  + .tail .inner {
  border-width: %dpx;
}
"""
            % (g, g, g % 4 + 1)
        )

    # `corpora_still_compile` asserts on this: a corpus that silently stopped
    # compiling would otherwise be timed as a fast failure.
    out.append("%s { --generated: true; }\n" % MARKER)
    return "".join(out)


def use_graph() -> dict[str, str]:
    """A multi-file `@use` graph, and the same graph reached twice over.

    Returns a `{relative path: contents}` map rooted at `gate/use_graph/`.

    `entry.scss` loads each section once; `redundant.scss` loads the sections
    *and* every component and token file directly, so ~40 modules are reached
    through two paths instead of one. Both must produce identical CSS: `@use`
    is idempotent, and that is precisely why probing the module cache before
    calling the importer is safe -- and why a corpus that only ever loads a
    module once cannot show it.

    The vendored `lib` package resolves through a load path
    (`gate/use_graph/vendor`), not relatively, so the benchmark also exercises
    the load-path arm of `FsImporter::canonicalize` -- the arm that records
    dependencies for `--quiet-deps`.
    """
    files: dict[str, str] = {}

    files["_tokens.scss"] = HEADER + """$space: 4px;
$radius: 3px;
$brand: #3498db;
$accent: #e67e22;
$muted: #7f8c8d;
$sizes: (sm: 4px, md: 8px, lg: 16px, xl: 32px);
$weights: (light: 300, normal: 400, bold: 700);
"""

    files["_mixins.scss"] = HEADER + """@use "sass:color";
@use "tokens" as t;

@mixin surface($tint) {
  background: color.mix($tint, white, 12%);
  border: 1px solid color.mix($tint, black, 88%);
  border-radius: t.$radius;
}

@mixin stack($gap: t.$space) {
  display: flex;
  flex-direction: column;
  gap: $gap;
}

// Emitted once by the entry so a benchmark can assert the graph compiled.
@mixin gate-marker {
  """ + MARKER + """ { --generated: true; }
}
"""

    for s in range(1, USE_SECTIONS + 1):
        for c in range(1, USE_COMPONENTS_PER_SECTION + 1):
            tint = ["t.$brand", "t.$accent", "t.$muted"][(s + c) % 3]
            files["components/_c%d_%d.scss" % (s, c)] = HEADER + """@use "sass:color";
@use "sass:math";
@use "../tokens" as t;
@use "../mixins" as m;

.c%d-%d {
  @include m.surface(%s);
  @include m.stack(t.$space * %d);
  color: color.adjust(%s, $lightness: -%d%%);

  @each $name, $size in t.$sizes {
    &--#{$name} {
      padding: $size math.div($size, 2);
      font-size: math.div($size, 2) + 8px;
    }
  }

  .icon {
    width: t.$space * %d;
    &:hover { color: color.adjust(%s, $saturation: %d%%); }
  }
}
""" % (s, c, tint, c % 4 + 1, tint, c * 3, c + 2, tint, c * 5)

    for s in range(1, USE_SECTIONS + 1):
        body = ['@use "../tokens" as t;', '@use "../mixins" as m;']
        for c in range(1, USE_COMPONENTS_PER_SECTION + 1):
            body.append('@use "../components/c%d_%d";' % (s, c))
        body.append("")
        body.append(".section-%d { @include m.stack(t.$space * 2); }" % s)
        files["sections/_s%d.scss" % s] = HEADER + "\n".join(body) + "\n"

    files["vendor/lib/_index.scss"] = HEADER + """@forward "reset";
@forward "grid";
"""
    files["vendor/lib/_reset.scss"] = HEADER + """*, *::before, *::after { box-sizing: border-box; }
body { margin: 0; font-family: system-ui, sans-serif; }
"""
    files["vendor/lib/_grid.scss"] = HEADER + """@use "sass:math";

$columns: 12;

@for $i from 1 through $columns {
  .col-#{$i} { width: math.percentage(math.div($i, $columns)); }
}
"""

    entry = [
        HEADER.rstrip("\n"),
        '@use "lib"; // vendored: resolves through the `vendor` load path',
        '@use "mixins" as m;',
    ]
    for s in range(1, USE_SECTIONS + 1):
        entry.append('@use "sections/s%d";' % s)
    entry += ["", "@include m.gate-marker;", ""]
    files["entry.scss"] = "\n".join(entry)

    # The same graph, every module also loaded directly by the entry. `@use` is
    # idempotent, so this compiles to the same CSS as `entry.scss` while asking
    # the importer about ~40 modules that are already in the module cache.
    redundant = [
        HEADER.rstrip("\n"),
        "// The redundant-`@use` case: identical output to `entry.scss`, reached",
        "// through roughly twice as many load requests.",
        '@use "lib";',
        '@use "tokens";',
        '@use "mixins" as m;',
    ]
    for s in range(1, USE_SECTIONS + 1):
        redundant.append('@use "sections/s%d";' % s)
    for s in range(1, USE_SECTIONS + 1):
        for c in range(1, USE_COMPONENTS_PER_SECTION + 1):
            redundant.append('@use "components/c%d_%d";' % (s, c))
    redundant += ["", "@include m.gate-marker;", ""]
    files["redundant.scss"] = "\n".join(redundant)

    return files


# --------------------------------------------------------------------- main


def build() -> dict[str, str]:
    """Every file this generator owns, as `{path relative to OUT_DIR: text}`."""
    files = {
        "legacy_deprecations.scss": legacy_deprecations(),
        "extend_heavy.scss": extend_heavy(),
        "selector_lists.scss": selector_lists(),
    }
    for rel, text in use_graph().items():
        files["use_graph/" + rel] = text
    return files


def manifest(files: dict[str, str]) -> str:
    entries = {
        rel: {
            "bytes": len(text.encode()),
            "sha256": hashlib.sha256(text.encode()).hexdigest()[:16],
        }
        for rel, text in sorted(files.items())
    }
    return (
        json.dumps(
            {
                "generatorVersion": GENERATOR_VERSION,
                "generator": "bench/scripts/gen_gate_corpora.py",
                "expectedMarker": MARKER,
                "files": entries,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify, write nothing")
    args = ap.parse_args()

    files = build()
    files["MANIFEST.json"] = manifest(files)

    if args.check:
        drift = []
        for rel, want in sorted(files.items()):
            path = OUT_DIR / rel
            got = path.read_text() if path.exists() else None
            if got != want:
                drift.append(rel if got is not None else rel + " (missing)")
        for rel in drift:
            print("DRIFT %s" % rel, file=sys.stderr)
        print(
            "%d files checked, %d differ" % (len(files), len(drift)),
            file=sys.stderr,
        )
        return 1 if drift else 0

    for rel, text in sorted(files.items()):
        path = OUT_DIR / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    total = sum(len(t.encode()) for t in files.values())
    print(
        "wrote %d files, %d bytes to %s"
        % (len(files), total, OUT_DIR.relative_to(REPO_ROOT)),
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
