[workspace]
members = [
    ".",
    "mods/testbed", "mods/urban_chaos",
]

[package]
name = "hanga"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.7.0"
bevy = "0.19.0"
bevy_voxel_world = "0.17.0"
wasmtime = "47.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossbeam-channel = "0.5.11"

[dev-dependencies]
kani = "0.0.1"
