# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0n8m2cym4qr8w16gbmlj66lhpac7nrmlxssmvbxpd2z9816w9frc";
    armv7l-linux = "08bhip2avmfxz37izn7vglhcy0l4xl0hlrnnsiwf61l1mvd1lmk1";
    aarch64-linux = "0ijjl4w0nz1sn1hjz3k43100g9lb75qfbq0r7mxkrcz6y2mc5300";
    x86_64-darwin = "1azfqldi9zqv6vah1a3s55742syqiqqvz67sg7hgjsn266bfkhpz";
    aarch64-darwin = "1hmzm14hmwgv12snyjg9cm5wrqbil93b2ac4jqdc6nzzwj7q464a";
  };

  urlMap = {
    x86_64-linux = "https://dl.dagger.io/dagger/releases/0.18.12/dagger_v0.18.12_linux_amd64.tar.gz";
    armv7l-linux = "https://dl.dagger.io/dagger/releases/0.18.12/dagger_v0.18.12_linux_armv7.tar.gz";
    aarch64-linux = "https://dl.dagger.io/dagger/releases/0.18.12/dagger_v0.18.12_linux_arm64.tar.gz";
    x86_64-darwin = "https://dl.dagger.io/dagger/releases/0.18.12/dagger_v0.18.12_darwin_amd64.tar.gz";
    aarch64-darwin = "https://dl.dagger.io/dagger/releases/0.18.12/dagger_v0.18.12_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dagger";
  version = "0.18.12";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ././dagger $out/bin/./dagger
  '';
  postInstall = ''
    installShellCompletion --cmd dagger \
    --bash <($out/bin/dagger completion bash) \
    --fish <($out/bin/dagger completion fish) \
    --zsh <($out/bin/dagger completion zsh)
  '';

  system = system;

  meta = {
    description = "Dagger is an integrated platform to orchestrate the delivery of applications";
    homepage = "https://dagger.io";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
