# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0i9g3r1f039lp4pzf7v6a2mc8c1aaxvyzay08rmywm393a2cpz1v";
    armv7l-linux = "1mr5fj6l1cp08zhd5h8spwvv5aysyz4fjrkwmsfjx7r4hx2f7cms";
    aarch64-linux = "128rslq9v0zgzkz242yg47z8ab5q3n22p4180ijy7jmyn6qf460h";
    x86_64-darwin = "0qr2r6av9ffsichax3c3xk7xq98yw9caqz5zsn6p4v1017qw2x0j";
    aarch64-darwin = "19mvy7dyvddfhp7p2z6v55z490pvk330hppl8giwvw29knzxfcbd";
  };

  urlMap = {
    x86_64-linux = "https://dl.dagger.io/dagger/releases/0.20.6/dagger_v0.20.6_linux_amd64.tar.gz";
    armv7l-linux = "https://dl.dagger.io/dagger/releases/0.20.6/dagger_v0.20.6_linux_armv7.tar.gz";
    aarch64-linux = "https://dl.dagger.io/dagger/releases/0.20.6/dagger_v0.20.6_linux_arm64.tar.gz";
    x86_64-darwin = "https://dl.dagger.io/dagger/releases/0.20.6/dagger_v0.20.6_darwin_amd64.tar.gz";
    aarch64-darwin = "https://dl.dagger.io/dagger/releases/0.20.6/dagger_v0.20.6_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dagger";
  version = "0.20.6";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ././dagger $out/bin/./dagger
  '';
  postInstall = ''
    installShellCompletion --cmd dagger \
    --bash <($out/bin/dagger completion bash) \
    --fish <($out/bin/dagger completion fish) \
    --zsh <($out/bin/dagger completion zsh)
  '';

  system = system;

  meta = {
    description = "Dagger is an integrated platform to orchestrate the delivery of applications";
    homepage = "https://dagger.io";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
