# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "assert-plus-0.1.5" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.1.5.tgz";
        sha1 = "ee74009413002d84cec7219c6ac811812e723160";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "async-stacktrace-0.0.2" = {
      name = "async-stacktrace";
      packageName = "async-stacktrace";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-stacktrace/-/async-stacktrace-0.0.2.tgz";
        sha1 = "8bbb9787e3b38c836c729a7e9d7c08630db5d1ef";
      };
    };
    "backoff-2.5.0" = {
      name = "backoff";
      packageName = "backoff";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/backoff/-/backoff-2.5.0.tgz";
        sha1 = "f616eda9d3e4b66b8ca7fca79f695722c5f8e26f";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "bunyan-1.8.12" = {
      name = "bunyan";
      packageName = "bunyan";
      version = "1.8.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/bunyan/-/bunyan-1.8.12.tgz";
        sha1 = "f150f0f6748abdd72aeae84f04403be2ef113797";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "dtrace-provider-0.7.1" = {
      name = "dtrace-provider";
      packageName = "dtrace-provider";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dtrace-provider/-/dtrace-provider-0.7.1.tgz";
        sha1 = "c06b308f2f10d5d5838aec9c571e5d588dc71d04";
      };
    };
    "dtrace-provider-0.8.7" = {
      name = "dtrace-provider";
      packageName = "dtrace-provider";
      version = "0.8.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/dtrace-provider/-/dtrace-provider-0.8.7.tgz";
        sha1 = "dc939b4d3e0620cfe0c1cd803d0d2d7ed04ffd04";
      };
    };
    "extsprintf-1.2.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.2.0.tgz";
        sha1 = "5ad946c22f5b32ba7f8cd7426711c6e8a3fc2529";
      };
    };
    "glob-6.0.4" = {
      name = "glob";
      packageName = "glob";
      version = "6.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-6.0.4.tgz";
        sha1 = "0f08860f6a155127b2fadd4f9ce24b1aab6e4d22";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "ldap-filter-0.2.2" = {
      name = "ldap-filter";
      packageName = "ldap-filter";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ldap-filter/-/ldap-filter-0.2.2.tgz";
        sha1 = "f2b842be0b86da3352798505b31ebcae590d77d0";
      };
    };
    "ldapjs-1.0.1" = {
      name = "ldapjs";
      packageName = "ldapjs";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ldapjs/-/ldapjs-1.0.1.tgz";
        sha1 = "352b812ae74b0a8e96549a4b896060eee1b9a546";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "moment-2.24.0" = {
      name = "moment";
      packageName = "moment";
      version = "2.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.24.0.tgz";
        sha512 = "bV7f+6l2QigeBBZSM/6yTNq4P2fNpSWj/0e7jQcy87A8e7o2nAfP/34/2ky5Vw4B9S446EtIhodAzkFCcR4dQg==";
      };
    };
    "mv-2.1.1" = {
      name = "mv";
      packageName = "mv";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mv/-/mv-2.1.1.tgz";
        sha1 = "ae6ce0d6f6d5e0a4f7d893798d03c1ea9559b6a2";
      };
    };
    "nan-2.13.2" = {
      name = "nan";
      packageName = "nan";
      version = "2.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.13.2.tgz";
        sha512 = "TghvYc72wlMGMVMluVo9WRJc0mB8KxxF/gZ4YYFy7V2ZQX9l7rgbPg7vjS9mt6U5HXODVFVI2bOduCzwOMv/lw==";
      };
    };
    "ncp-2.0.0" = {
      name = "ncp";
      packageName = "ncp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ncp/-/ncp-2.0.0.tgz";
        sha1 = "195a21d6c46e361d2fb1281ba38b91e9df7bdbb3";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "precond-0.2.3" = {
      name = "precond";
      packageName = "precond";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/precond/-/precond-0.2.3.tgz";
        sha1 = "aa9591bcaa24923f1e0f4849d240f47efc1075ac";
      };
    };
    "rimraf-2.4.5" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.4.5.tgz";
        sha1 = "ee710ce5d93a8fdb856fb5ea8ff0e2d75934b2da";
      };
    };
    "safe-json-stringify-1.2.0" = {
      name = "safe-json-stringify";
      packageName = "safe-json-stringify";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-json-stringify/-/safe-json-stringify-1.2.0.tgz";
        sha512 = "gH8eh2nZudPQO6TytOvbxnuhYBOvDBBLW52tz5q6X58lJcd/tkmqFR+5Z9adS8aJtURSXWThWy/xJtJwixErvg==";
      };
    };
    "vasync-1.6.4" = {
      name = "vasync";
      packageName = "vasync";
      version = "1.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vasync/-/vasync-1.6.4.tgz";
        sha1 = "dfe93616ad0e7ae801b332a9d88bfc5cdc8e1d1f";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "verror-1.6.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.6.0.tgz";
        sha1 = "7d13b27b1facc2e2da90405eb5ea6e5bdd252ea5";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
  };
in
{
  ep_ldapauth = nodeEnv.buildNodePackage {
    name = "ep_ldapauth";
    packageName = "ep_ldapauth";
    version = "0.3.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/ep_ldapauth/-/ep_ldapauth-0.3.0.tgz";
      sha1 = "8b34ea34b20ae97d53d753cc7d1f6f191800e3b0";
    };
    dependencies = [
      sources."asn1-0.2.3"
      sources."assert-plus-1.0.0"
      sources."async-stacktrace-0.0.2"
      sources."backoff-2.5.0"
      sources."balanced-match-1.0.0"
      sources."brace-expansion-1.1.11"
      (sources."bunyan-1.8.12" // {
        dependencies = [
          sources."dtrace-provider-0.8.7"
        ];
      })
      sources."concat-map-0.0.1"
      sources."core-util-is-1.0.2"
      sources."dashdash-1.14.1"
      sources."dtrace-provider-0.7.1"
      sources."extsprintf-1.2.0"
      sources."glob-6.0.4"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      (sources."ldap-filter-0.2.2" // {
        dependencies = [
          sources."assert-plus-0.1.5"
        ];
      })
      sources."ldapjs-1.0.1"
      sources."minimatch-3.0.4"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."moment-2.24.0"
      sources."mv-2.1.1"
      sources."nan-2.13.2"
      sources."ncp-2.0.0"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."precond-0.2.3"
      sources."rimraf-2.4.5"
      sources."safe-json-stringify-1.2.0"
      (sources."vasync-1.6.4" // {
        dependencies = [
          sources."verror-1.6.0"
        ];
      })
      sources."verror-1.10.0"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Hooks into etherpad lite auth to provide LDAP authentication.";
      homepage = "https://github.com/tykeal/ep_ldapauth#readme";
      license = "GPL-2.0";
    };
    production = true;
    bypassCache = true;
  };
}
