//! CodSpeed benchmarks for the `sasso` SCSS -> CSS pipeline.
//!
//! Each benchmark drives the public [`sasso::compile`] entry point, which runs
//! the full pipeline (scan -> parse -> evaluate -> emit) over a representative
//! input. Inputs range from a large generated stylesheet to focused snippets
//! that stress nesting, control flow and the color functions.
//!
//! **These benchmarks must measure the program that ships.** Two ways of
//! getting that wrong were measured on 2026-09-16 and are fixed below; see
//! `docs/PERF_PLAN_2026-09-16.md` (B0) for the numbers.
//!
//! 1. The `ScopedAlloc` bump arena is installed here, exactly as `src/main.rs`
//!    and `wasm/src/lib.rs` install it. Without it every recorded number
//!    measures sasso against the system malloc: -41% on macOS, -22% on Linux,
//!    and it *inverts* the cross-machine ranking rather than shifting it by a
//!    constant.
//! 2. At least one workload supplies a display URL. `compile` enables
//!    diagnostics only when `options.url` is `Some`, so without one the whole
//!    deprecation path -- ~16% of a compile, and where the 2026-09-15
//!    regression landed -- never executes.

use divan::{black_box, Bencher};
use sasso::{compile, compile_with_source_map, Options, OutputStyle};

/// The allocator the CLI and the wasm package ship with (`src/main.rs:40`,
/// `wasm/src/lib.rs:40`). Benchmarking without it measures a different program.
#[global_allocator]
static GLOBAL: sasso::ScopedAlloc = sasso::ScopedAlloc;

fn main() {
    corpora_still_compile();
    divan::main();
}

/// ~400-component generated stylesheet (`bench/corpus/generated/large.scss`).
/// Self-contained: only pulls in the built-in `sass:math` module.
const LARGE: &str = include_str!("../bench/corpus/generated/large.scss");

/// Legacy-deprecation-dense sheet: 1200 `@include`s of one mixin whose 13 call
/// sites are all deprecated names, so the same 13 spans repeat throughout.
/// Generated by `bench/scripts/gen_gate_corpora.py`.
const LEGACY_DEPRECATIONS: &str = include_str!("../bench/corpus/gate/legacy_deprecations.scss");

/// `@extend`-heavy sheet: placeholder chains, class extends, and `@extend`
/// inside nested and `@media` contexts. Generated by the same script.
const EXTEND_HEAVY: &str = include_str!("../bench/corpus/gate/extend_heavy.scss");

/// Multi-line comma selector lists: the only shape that puts `eval_style_rule`
/// on its `share_current == false` branch, where the per-complex list is
/// rebuilt instead of shared. Every other corpus here, and `large.scss`, has
/// zero of them, so that branch was unmeasurable before this file existed.
/// Carries a few dropped `> +` selectors too, at the density a real sheet has.
const SELECTOR_LISTS: &str = include_str!("../bench/corpus/gate/selector_lists.scss");

/// Multi-file `@use` graph: 43 files behind one entry.
const USE_GRAPH_ENTRY: &str = include_str!("../bench/corpus/gate/use_graph/entry.scss");

/// The same graph, with every module also loaded directly by the entry, so
/// ~40 modules are reached through two paths instead of one. Compiles to
/// byte-identical CSS -- `@use` is idempotent.
const USE_GRAPH_REDUNDANT: &str = include_str!("../bench/corpus/gate/use_graph/redundant.scss");

/// The `@use` graph is the one corpus that is not just a string: its imports
/// have to resolve on disk, so the benchmark needs real paths. They are baked
/// in at compile time, which is also when the `include_str!`s above read the
/// entries, so the source and the URL cannot disagree about which checkout
/// they came from.
///
/// The URL is what `@use "sections/s1"` resolves against -- dart-sass tries the
/// containing file's directory before any load path -- so it has to be the
/// entry's own path, not a bare name.
const USE_GRAPH_ENTRY_URL: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/bench/corpus/gate/use_graph/entry.scss"
);

/// As [`USE_GRAPH_ENTRY_URL`], for the redundant-`@use` entry.
const USE_GRAPH_REDUNDANT_URL: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/bench/corpus/gate/use_graph/redundant.scss"
);

/// The load path the corpus's vendored `lib` package resolves through, so the
/// benchmark exercises the load-path arm of `FsImporter::canonicalize` -- the
/// arm that records dependencies -- and not only relative resolution.
const USE_GRAPH_VENDOR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/bench/corpus/gate/use_graph/vendor");

/// The marker rule `bench/scripts/gen_gate_corpora.py` emits into every gate
/// corpus (`MANIFEST.json` records it as `expectedMarker`).
const GATE_MARKER: &str = ".sasso-gate-corpus";

/// Deeply nested rules exercising the `&` parent selector and selector emission.
const NESTING: &str = r#"
.card {
  color: #333;
  .header {
    font-weight: bold;
    &:hover { color: #0066cc; }
    .title { a { color: red; &:visited { color: purple; } } }
  }
  .body {
    p { margin: 0; line-height: 1.5; }
    .footer { small { opacity: 0.6; &::after { content: ""; } } }
  }
}
"#;

/// Control-flow heavy input: `@for` / `@each` loops with interpolation.
const CONTROL_FLOW: &str = r#"
@use "sass:math";
@for $i from 1 through 100 {
  .col-#{$i} { width: math.div($i, 100) * 100%; }
}
@each $name, $size in (sm: 4px, md: 8px, lg: 16px, xl: 32px) {
  .pad-#{$name} { padding: $size; }
  .gap-#{$name} { gap: $size; }
}
"#;

/// Color-function heavy input: builds a shade scale from a base color.
const COLORS: &str = r#"
@use "sass:color";
$base: #3498db;
@for $i from 1 through 40 {
  .shade-#{$i} {
    background: color.adjust($base, $lightness: $i * 1%);
    border-color: rgba($base, 0.5);
    box-shadow: 0 0 ($i * 1px) mix($base, white, 50%);
  }
}
"#;

/// `Options` in the shape a real invocation has: a display URL, which is the
/// only thing that turns diagnostics on (`compile` sets the diagnostic source
/// only when `options.url` is `Some`, `src/lib.rs:560`), plus a handler that
/// throws the warnings away.
///
/// Every benchmark added for a lever in `docs/PERF_PLAN_2026-09-16.md` goes
/// through here, because the alternative is easy to write and measures half a
/// program: a corpus wired up with a bare `Options::default()` leaves
/// `diag_enabled()` false, and a deprecation-dense sheet then protects only the
/// construction half of the path it was added for.
///
/// The handler is a no-op on purpose. A benchmark has no business writing to
/// stderr, and staying quiet costs nothing measurable: printing measured
/// 9.478 ms against the silent 9.408 ms on `large_expanded_with_url_silent`,
/// i.e. the same within noise, so the surcharge is bookkeeping rather than I/O.
fn diagnostics_live(url: &str) -> Options<'_> {
    // `WarnHandler` is an `Rc`, which is not `Sync`, so divan cannot hoist it
    // out of a benched closure -- it has to be built inside. One `Rc::new` per
    // iteration is noise against a multi-millisecond compile.
    let sink: sasso::WarnHandler = std::rc::Rc::new(|_ev: &sasso::WarnEvent<'_>| {});
    Options::default().with_url(url).with_warn_handler(sink)
}

/// The importer the `@use`-graph benchmarks pass, built fresh per compile as a
/// CLI invocation would: [`sasso::FsImporter`] carries the per-compilation
/// dependency record, so sharing one across iterations would accumulate state
/// no real run has.
fn use_graph_importer() -> sasso::FsImporter {
    sasso::FsImporter::new(vec![std::path::PathBuf::from(USE_GRAPH_VENDOR)])
}

/// Compile each gate corpus once, before divan takes over, and check the marker
/// rule is in the output.
///
/// A benchmark that silently stopped compiling what it claims to would still
/// report a number, and a faster one. `compile(...).unwrap()` catches an error,
/// but not the subtler failure this guards: three earlier `@use`-graph
/// measurements in `bench/perf_audit_2026-09-15.md` were void because the
/// vendor load path was missing, so they timed a *failed* compile. In the
/// `@use` graph the marker comes from a mixin defined in a loaded module, so it
/// can only appear if the graph actually resolved.
fn corpora_still_compile() {
    for (name, source) in [
        ("legacy_deprecations.scss", LEGACY_DEPRECATIONS),
        ("extend_heavy.scss", EXTEND_HEAVY),
        ("selector_lists.scss", SELECTOR_LISTS),
    ] {
        let css = compile(source, &diagnostics_live(name))
            .unwrap_or_else(|e| panic!("bench corpus {name} failed to compile: {e}"));
        assert!(
            css.contains(GATE_MARKER),
            "bench corpus {name} lost its marker rule"
        );
    }

    for (url, source) in [
        (USE_GRAPH_ENTRY_URL, USE_GRAPH_ENTRY),
        (USE_GRAPH_REDUNDANT_URL, USE_GRAPH_REDUNDANT),
    ] {
        let importer = use_graph_importer();
        let opts = diagnostics_live(url).with_importer(&importer);
        let css =
            compile(source, &opts).unwrap_or_else(|e| panic!("bench corpus {url} failed to compile: {e}"));
        assert!(
            css.contains(GATE_MARKER),
            "bench corpus {url} lost its marker rule"
        );
    }
}

#[divan::bench]
fn large_expanded(bencher: Bencher<'_, '_>) {
    bencher.bench(|| compile(black_box(LARGE), &Options::default()).unwrap());
}

/// `large_expanded` with diagnostics live: a display URL turns on the
/// deprecation bookkeeping that the URL-less benchmarks skip entirely.
///
/// Read this **against** `large_expanded`. The ratio of the two is the
/// diagnostics surcharge, and it is that ratio, not either number alone, that
/// would have flagged the two deprecation merges of 2026-09-15. Measured at
/// +15.7% (macOS/arm64) and +9.6% (Linux/x86_64) on 2026-09-16 against the
/// printing arm, and +12.5% fastest / +10.8% median here against the silent
/// one; treat the spread as the reason CI wants instruction counts rather than
/// wall time.
#[divan::bench]
fn large_expanded_with_url_silent(bencher: Bencher<'_, '_>) {
    bencher.bench(|| compile(black_box(LARGE), &diagnostics_live("large.scss")).unwrap());
}

/// A legacy-deprecation-dense sheet, with diagnostics live: the corpus for A1
/// in `docs/PERF_PLAN_2026-09-16.md`, and the suite's early-warning signal for
/// the whole diagnostics area.
///
/// Every one of the mixin's 13 call sites is a deprecated name, and 1200
/// `@include`s repeat those same 13 spans, so this measures the gates, the
/// dedup and the memo rather than how fast 15600 distinct warnings can be
/// built. A1 measured **-48.3%** here against **-17.4%** on `large.scss`
/// (macOS/arm64, 2026-09-16, `b1acfe6` vs `7346b5a`, byte-identical output), so
/// a regression in that path shows up here about three times as loudly.
#[divan::bench]
fn legacy_deprecations_with_url_silent(bencher: Bencher<'_, '_>) {
    bencher.bench(|| {
        compile(
            black_box(LEGACY_DEPRECATIONS),
            &diagnostics_live("legacy_deprecations.scss"),
        )
        .unwrap()
    });
}

/// An `@extend`-heavy sheet: the corpus for A2, which measures **0.00% on
/// `large.scss`** because `large.scss` contains no `@extend` at all.
///
/// Without this benchmark, landing A2 and then regressing it are
/// indistinguishable in CI. The A2 prototype measured **-49.7%** here with
/// byte-identical output, against -0.2% on `large.scss` (macOS/arm64,
/// 2026-09-16, `ad11c61` vs the salvaged prototype).
///
/// It is deliberately not the largest `@extend` shape that could be generated.
/// `@extend` grows super-linearly: the first shape tried -- five times the
/// extending selectors, every one of them extending from a nested context --
/// measured 442 ms/compile against this one's 7.6 ms. That is a bigger delta
/// bought with ~58x the runner time.
#[divan::bench]
fn extend_heavy_with_url_silent(bencher: Bencher<'_, '_>) {
    bencher.bench(|| compile(black_box(EXTEND_HEAVY), &diagnostics_live("extend_heavy.scss")).unwrap());
}

/// Multi-line comma selector lists, with the diagnostics live because the
/// dropped-selector warnings are part of the shape.
///
/// This is a coverage corpus before it is a lever: `share_current == false` is
/// the branch a hand-written sheet takes and no other corpus reaches, so work
/// added there — the span mapping behind `bogus-combinators`, for one — could
/// not be measured at all. A corpus that makes a regression visible is worth
/// having even when nothing here is trying to make it faster.
#[divan::bench]
fn selector_lists_with_url_silent(bencher: Bencher<'_, '_>) {
    bencher.bench(|| {
        compile(
            black_box(SELECTOR_LISTS),
            &diagnostics_live("selector_lists.scss"),
        )
        .unwrap()
    });
}

/// A multi-file `@use` graph, 43 files behind one entry: the corpus for A3,
/// which measures **0.00% single-file**.
///
/// Unlike the other benchmarks this one touches the filesystem, because the
/// thing being measured is import resolution. The importer is built per
/// iteration, as a CLI invocation would build it. The A3 prototype measured
/// **-39.5%** here (macOS/arm64, 2026-09-16, `ad11c61` vs the salvaged
/// prototype), with byte-identical output.
#[divan::bench]
fn use_graph_with_url_silent(bencher: Bencher<'_, '_>) {
    bencher.bench(|| {
        let importer = use_graph_importer();
        let opts = diagnostics_live(USE_GRAPH_ENTRY_URL).with_importer(&importer);
        compile(black_box(USE_GRAPH_ENTRY), &opts).unwrap()
    });
}

/// The same graph reached twice over -- the entry loads every section *and*
/// every component and token file directly -- so ~40 modules arrive at the
/// importer already in the module cache.
///
/// This is the redundant-`@use` case B4 asks for, and it is the shape that
/// separates "probe the cache before calling the importer" from "resolve
/// everything twice": the CSS is byte-identical to `use_graph_with_url_silent`
/// (`@use` is idempotent) while the base cost is ~30% higher. The A3 prototype
/// measured **-42.2%** here.
#[divan::bench]
fn use_graph_redundant_with_url_silent(bencher: Bencher<'_, '_>) {
    bencher.bench(|| {
        let importer = use_graph_importer();
        let opts = diagnostics_live(USE_GRAPH_REDUNDANT_URL).with_importer(&importer);
        compile(black_box(USE_GRAPH_REDUNDANT), &opts).unwrap()
    });
}

/// `large_expanded_with_url_silent` with a source map generated alongside the
/// CSS: the corpus for the source-map row of `docs/PERF_PLAN_2026-09-16.md`
/// (A5), which no other benchmark here touches at all.
///
/// Read this **against** `large_expanded_with_url_silent`, exactly as that one
/// is read against `large_expanded`: the ratio is the map surcharge, measured at
/// +25% (CLI) to +37% (in-process) on 2026-09-16. Only the difference is
/// meaningful — the map path is the only thing the two benchmarks disagree
/// about, and the map's JSON is deliberately *not* serialized here, because
/// `SourceMap::to_json` is string escaping rather than mapping arithmetic.
///
/// The CLI cannot stand in for this. `--loop` refuses to run with
/// `--source-map` (`src/main.rs`), so before this benchmark existed the map path
/// could only be measured one process at a time, with process startup inside
/// every reading.
#[divan::bench]
fn large_expanded_with_map_silent(bencher: Bencher<'_, '_>) {
    bencher.bench(|| compile_with_source_map(black_box(LARGE), &diagnostics_live("large.scss")).unwrap());
}

#[divan::bench]
fn large_compressed(bencher: Bencher<'_, '_>) {
    bencher.bench(|| {
        let mut opts = Options::default();
        opts.style = OutputStyle::Compressed;
        compile(black_box(LARGE), &opts).unwrap()
    });
}

#[divan::bench]
fn nesting(bencher: Bencher<'_, '_>) {
    bencher.bench(|| compile(black_box(NESTING), &Options::default()).unwrap());
}

#[divan::bench]
fn control_flow(bencher: Bencher<'_, '_>) {
    bencher.bench(|| compile(black_box(CONTROL_FLOW), &Options::default()).unwrap());
}

#[divan::bench]
fn colors(bencher: Bencher<'_, '_>) {
    bencher.bench(|| compile(black_box(COLORS), &Options::default()).unwrap());
}
