#!/usr/bin/env bash

for f in /nix/var/nix/gcroots/auto/*; do
    f="$(readlink $f)"
    if [[ "$f" =~ ^/home ]]; then
        rm "$f" || true
    fi
    if [[ "$f" =~ ^/tmp ]]; then
        rm "$f" || true
    fi
done
