# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  uhhyou = {
    pname = "uhhyou";
    version = "UhhyouPlugins0.65.0";
    src = fetchFromGitHub {
      owner = "ryukau";
      repo = "VSTPlugins";
      rev = "UhhyouPlugins0.65.0";
      fetchSubmodules = true;
      sha256 = "sha256-IoWSxefuWisqFFcKrhmwMvNnuZzyVb0Y6uZHP6mT1Qk=";
    };
  };
}
