#!/usr/bin/env bash

_load_envrc() {
    local dir="${PWD}"

    while [ "${dir}" != "/" ]; do
        if [ -f "${dir}/.envrc" ]; then
            source "${dir}/.envrc"
            echo -e "\033[0;32m[*] Sourced .envrc from ${dir}\033[0m"
            return
        fi
        dir=$(dirname "${dir}")
    done
}

source ${HOME}/.hadk.env
 
# Minimalistic direnv hook (load_envrc is sourced from ~/.hw.profile)
_load_envrc
 
export PROMPT_COMMAND='PS1_CMD1=$(echo $DEVICE); PS1_CMD2=$(git branch --show-current 2>/dev/null)'
export PS1='\[\e[38;5;33;1m\][$?]\[\e[0;38;5;161m\][${PS1_CMD1}]\[\e[0m\] \[\e[38;5;40m\]\w\[\e[0m\] \[\e[38;5;220m\]<${PS1_CMD2}>\[\e[0m\] \[\e[1m\]\$\[\e[0m\] '
