name: "Build and populate cache"
on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    # rebuild everyday at 2:51
    # TIP: Choose a random time here so not all repositories are build at once:
    # https://www.random.org/clock-times/?num=1&earliest=01%3A00&latest=08%3A00&interval=5&format=html&rnd=new
    - cron: "43 3 * * *"
  workflow_dispatch:
jobs:
  channel-build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: &runs-on [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
        nixChannel:
          - nixpkgs-unstable
          - nixos-unstable
        # Set this to notify the global nur package registry that changes are
        # available.
        #
        # The repo name as used in
        # https://github.com/nix-community/NUR/blob/master/repos.json
        nurRepo:
          - xyenon
        # Set this to cache your build results in cachix for faster builds
        # in CI and for everyone who uses your cache.
        #
        # Format: Your cachix cache host name without the ".cachix.org" suffix.
        # Example: mycache (for mycache.cachix.org)
        #
        # For this to work, you also need to set the CACHIX_SIGNING_KEY or
        # CACHIX_AUTH_TOKEN secret in your repository secrets settings in
        # Github found at
        # https://github.com/<your_githubname>/nur-packages/settings/secrets
        cachixName: &cachixName
          - nur-xyenon
    runs-on: ${{ matrix.runs-on }}
    env:
      NIX_PATH: nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/${{ matrix.nixChannel }}.tar.gz
    steps:
      - &checkoutRepository
        name: Checkout repository
        uses: actions/checkout@v6
      - &installNix
        name: Install nix
        uses: DeterminateSystems/nix-installer-action@v21
      - name: Show nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - &setupCachix
        name: Setup cachix
        uses: cachix/cachix-action@v17
        # Don't replace <YOUR_CACHIX_NAME> here!
        if: ${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}
        with:
          name: ${{ matrix.cachixName }}
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check evaluation
        run: |
          nix-env -f . -qa \* --meta --xml \
            --allowed-uris https://static.rust-lang.org \
            --option restrict-eval true \
            --option allow-import-from-derivation true \
            --drv-path --show-trace \
            -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
            -I $PWD
      - name: Build nix packages
        # https://github.com/NixOS/nixpkgs/pull/501027
        run: nix run github:Mic92/nix-fast-build -- --no-nom --skip-cached --file ci.nix -A cacheOutputAttrs
      - name: Trigger NUR update
        # Don't replace <YOUR_REPO_NAME> here!
        if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
        run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"
  flake-build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: *runs-on
        cachixName: *cachixName
    runs-on: ${{ matrix.runs-on }}
    steps:
      - *checkoutRepository
      - *installNix
      - *setupCachix
      - name: Build nix packages
        # https://github.com/NixOS/nixpkgs/pull/501027
        run: nix run github:Mic92/nix-fast-build -- --no-nom --skip-cached --flake ".#cacheOutputAttrs.$(nix eval --raw --impure --expr builtins.currentSystem)"
