// 2> /dev/null; exit 1

main (args) {
    const system = $ nix eval --raw --impure --expr builtins.currentSystem $?
    let packages = [Text]
    let default_packages = [
        "amber-lsp",
        "code996",
        "dnspick",
        "ghost-downloader-3",
        "ipgw",
        "quien",
        "uipro-cli",
    ]
    const system_binary_package_names = [
        "meatshell",
        "nyaterm",
    ]

    for package_name in system_binary_package_names {
        const package = "{package_name}-{system}-bin"
        $ test -f "pkgs/{package_name}/{system}-bin.nix" $ succeeded {
            default_packages += [package]
        }
    }

    if len(args) == 1 {
        echo("Usage: nur-packages-update <package>...")
        echo("       nur-packages-update --all")
        echo("       nur-packages-update --list")
        echo("")
        echo("Available packages:")
        for package in default_packages {
            echo("  {package}")
        }
        exit(0)
    }

    if len(args) == 2 {
        if args[1] == "--help" or args[1] == "-h" {
            echo("Usage: nur-packages-update <package>...")
            echo("       nur-packages-update --all")
            echo("       nur-packages-update --list")
            exit(0)
        }

        if args[1] == "--list" {
            for package in default_packages {
                echo(package)
            }
            exit(0)
        }

        if args[1] == "--all" {
            packages = default_packages
        } else {
            packages += [args[1]]
        }
    } else {
        for index, arg in args {
            if index > 0 {
                packages += [arg]
            }
        }
    }

    for package in packages {
        echo("==> Updating {package}")
        $ nix-update {package} --flake --build --format --use-github-releases $?
    }
}
