{ ... }:
{
  imports = [
    ../os
    ./containers/authentik.nix
    ./containers/home-assistant.nix
    ./containers/immich.nix
    ./containers/jellyfin.nix
    ./containers/minecraft.nix
    ./containers/monitoring.nix
    ./containers/nextcloud.nix
    ./containers/open-webui.nix
    ./containers/starr.nix
    ./containers/terraria.nix
    ./containers/vintagestory.nix
    ./boot.nix
    ./kanata.nix
    ./networking.nix
    ./nix-ld.nix
    ./system.nix
    ./ids.nix
    ./filesystems.nix
    ./gaming.nix
    ./mcsmanager.nix
    ./monitoring/default.nix
    ./monitoring/grafana.nix
    ./monitoring/internet.nix
    ./monitoring/loki.nix
    ./monitoring/prometheus.nix
    ./monitoring/tempo.nix
    ./podman.nix
    ./services/desktopManager/cosmic.nix
    ./services/desktopManager/gnome.nix
    ./services/desktopManager/plasma.nix
    ./services/desktopManager/xfce.nix
    ./services/minecraft.nix
    ./services/ollama.nix
    ./services/protonmail-bridge.nix
    ./services/hermes-dashboard.nix
    ./services/hermes-webui.nix
    ./services/signal-cli.nix
    ./syncthing.nix
    ./tmpfiles.nix
    ./vintagestory.nix
  ];
}
