# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  sheepshaver-bin = {
    pname = "sheepshaver-bin";
    version = "2024-05-11";
    src = fetchurl {
      url = "https://github.com/Korkman/macemu-appimage-builder/releases/download/2024-05-11/SheepShaver-x86_64.AppImage";
      sha256 = "sha256-2dsR144L9K3/WLDAn5A9DCQDnoFiGiIzp5EmiR0HCU0=";
    };
  };
}
