# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  luakit = {
    pname = "luakit";
    version = "0bc0e39459cd8b4a758318b3f805ce98ae2e12e8";
    src = fetchFromGitHub {
      owner = "luakit";
      repo = "luakit";
      rev = "0bc0e39459cd8b4a758318b3f805ce98ae2e12e8";
      fetchSubmodules = false;
      sha256 = "sha256-i0CNk51q6zj6vPOObO69QYCAOivW8c6Z1UtC2dVjw74=";
    };
    date = "2024-02-03";
  };
}
