#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i bash ../../../../integrations/nix-shell --arg f 'ps: [ ps.bash ps.brightnessctl ]'
dev="$1"
if [ -z "$dev" ]; then
  dev="white:flash"
fi

if [ "$(brightnessctl -d "$dev" get)" -gt 0 ]; then
  brightnessctl -q -d "$dev" set "0%"
else
  brightnessctl -q -d "$dev" set "100%"
fi
