#!/usr/bin/env bash
# after modifying .sops.yaml, run this to re-encode all secrets to the new keys
# pass the base directory (under which *everything* is a secret) as argument
for i in $(find "$1" -print)
do
	yes | sops updatekeys "$i"
done
