Dir.glob(File.expand_path('~/.pake/*.rake')).each { |r| load r}

task :default => [:help]

task :help do
  sh "rake -T"
end

desc "gnome40setbinding"
task :gnome40setbinding do

  #remove app key bindings
  sh "dconf write /org/gnome/shell/extensions/dash-to-panel/hot-keys false"
  sh "dconf write /org/gnome/shell/extensions/dash-to-panel/hotkey-prefix-text \"''\""
  for a in 1..9 do
    sh "gsettings set org.gnome.shell.keybindings switch-to-application-#{a} []"
    sh "dconf write /org/gnome/shell/extensions/dash-to-panel/app-hotkey-#{a} \"['']\""
  end

end

desc "bitbar_gitlab_lingewoud stel bitbar_gitlab in voor gitlab.lingewoud.net"
task :bitbar_gitlab_lingewoud do
  sh "rm -f ~/.bitbar_gitlab_cnf.yml && ln -s  ~/.bitbar_gitlab_cnf.lingewoud.yml ~/.bitbar_gitlab_cnf.yml"
  sh "ls -al ~/.bitbar_gitlab_cnf.yml"
end

desc "bitbar_gitlab_gitlabcom stel bitbar_gitlab in voor gitlab.com"
task :bitbar_gitlab_gitlabcom do
  sh "rm -f ~/.bitbar_gitlab_cnf.yml && ln -s  ~/.bitbar_gitlab_cnf.gitlabcom.yml ~/.bitbar_gitlab_cnf.yml"
  sh "ls -al ~/.bitbar_gitlab_cnf.yml"
end

desc "aws_lingewoud stel aws cli in voor lingewoud"
task :aws_lingewoud do
  sh "rm -f ~/.aws/credentials && cd ~/.aws && ln -s credentials.lingewoud credentials"
  sh "ls -al ~/.aws"
end

desc "aws_kaftmeister stel aws cli in voor Kaftmeister"
task :aws_kaftmeister do
  sh "rm -f ~/.aws/credentials && cd ~/.aws && ln -s credentials.kaftmeister credentials"
  sh "ls -al ~/.aws"
end

desc "aws_poppygo stel aws cli in voor PoppyGo"
task :aws_poppygo do
  sh "rm -f ~/.aws/credentials && cd ~/.aws && ln -s credentials.poppygo credentials"
  sh "ls -al ~/.aws"
end

desc "trash_adobe"
task :trash_adobe do
  sh "~/.pim-macos-housekeeping/remove_adobe_junk.sh"
end

desc "toon_homestead_domeinen"
task "toon_homestead_domeinen" do
  sh 'grep "^[[:blank:]]*-\ map:\ [[:alnum:]]" ~/Sys/homestead/Homestead.yaml'
end

desc "letsencrypttest"
task "letsencrypttest" do
  sh 'cd ~/cOperations/monitor-domains-ssl && nix-shell --command "./checkssl.rb domains_from_markdown ~/secondbrain/wikiContent/letsencrypt_domains.md"'
end

desc "letsencryptproblems"
task "letsencryptproblems" do
  sh 'cd ~/cOperations/monitor-domains-ssl && nix-shell --command "./checkssl.rb domains_from_markdown ~/secondbrain/wikiContent/letsencrypt_domains.md|grep -v \"😀\|#\|monitor-domains-ssl\" |sed \"/^$/d\""'
end

desc "letsencryptalmost"
task "letsencryptalmost" do
  sh 'cd ~/cOperations/monitor-domains-ssl && nix-shell --command "./checkssl.rb domains_from_markdown ~/secondbrain/wikiContent/letsencrypt_domains.md|grep days|sort -k 9,9 | head -n 5"'
end

desc "macshowhidden"
task "macshowhidden" do
  sh 'defaults write com.apple.finder AppleShowAllFiles TRUE'
  sh 'killall Finder'
end

desc "machidehidden"
task "machidehidden" do
  sh 'defaults write com.apple.finder AppleShowAllFiles FALSE'
  sh 'killall Finder'
end

desc "sourcezsh"
task "sourcezsh" do
  sh 'source ~/.zshrc'
end

desc "enable_nvm"
task "enable_nvm" do
  sh 'source ~/.zsh.d/manual_load/70-nvm.zsh'
  p 'source ~/.zsh.d/manual_load/70-nvm.zsh'
end


special_hosts= {
  "larox" => "ssh pim@213.206.241.11",
  "bach" => "ssh pim@blatter.node.lingewoud.net -p 32768",
  "bowie" => "ssh pim@brepi.eu",
  "oj" => "ssh pim@gruyter.lingewoud.net",
  "kaftmeister_mgmt_node" => 'ssh ubuntu@52.210.3.14 -i ~\/\.ssh\/kaftmeister_admin_rsa',
  "ccv1" => "ssh lingewoud@31.7.4.76",
  "buwadock" => "ssh dockeruser@kantoor.buwa.nl -p 10022",
  "pogosite" => "ssh ubuntu@pogosite.com"
}

hosts =  [
  "pogosite",
  "larox",
  "x-chromosoom",
  "xaviaar2",
  "xl2",
  "ohmy",
  "rackstation1",
  "xavier3",
  "schurk",
  "valencia",
  "blatter",
  "volkert",
  "droste",
  "bach",
  "bowie",
  "ccv1",
  "buwadock",
]

hosts.each do |host|
  desc "ssh#{host}"
  task "ssh#{host}" do
    sessname = "ssh-#{host}"

    if special_hosts.has_key? host
      cmd = "tmux send-keys -t 'ssh-#{host}' '#{special_hosts[host]}' C-m"
    else
      cmd = "tmux send-keys -t 'ssh-#{host}' 'ssh pim@#{host}.node.lingewoud.net' C-m"
    end

    tmux_create_or_switch sessname, [cmd]
  end
end


desc "hostscheck check hosts in dns"
task "hostscheck" do
  hosts.each do |host|
    #sh "dig #{host}.node.lingewoud.net| grep #{host}"
    sh "dig +noall +answer #{host}.node.lingewoud.net"
  end
end

desc "light set iterm solarized light"
task "light" do
  sh '~/.iterm2/it2setcolor preset "Solarized Light"'
end

desc "dark set iterm solarized dark"
task "dark" do
  sh '~/.iterm2/it2setcolor preset "Solarized Dark"'
end

desc "zshgitstatus_off"
task "zshgitstatus_off" do
  p "git config oh-my-zsh.hide-status 1"
end

desc "make desktop"
task "make_desktop" do
  sh "touch ~/.i-am-desktop-machine"
end


desc "pitadd voegt standaard materiaal toe aan git commit"
task "pitadd" do
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .vim"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .zsh.d"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/awesome"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/browser-home"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/nvim"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/alacritty.yml"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/gtk*"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/compton.conf"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/git"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/htop"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/inkscape"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/picom.conf"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/rofi"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .config/ranger"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .Xmodmap"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .Xresources"
#  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .fzf*"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .gitconfig"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add Rakefile"
  sh "git --git-dir=$HOME/.dotfiles-pim/ --work-tree=$HOME add .gitignore"
end

desc "voiddisableevolutionalarm"
task "voiddisableevolutionalarm" do
  sh "sudo echo \"#\\!/bin/sh\" > /usr/libexec/evolution-data-server/evolution-alarm-notify"
end
