#!/usr/bin/env bash
# See https://discourse.nixos.org/t/25274
set -Eeuo pipefail

root="$(readlink --canonicalize "${0%/*}/..")"; readonly root
readonly attr="${1:-}"

# Mock nixpkgs
trap 'rm --force "$root/default.nix" "$root/shell.nix"' EXIT
echo '{}: import <nixpkgs> { overlays = [ (import ./packages.nix) ]; }' > "$root/default.nix"
echo '{ pkgs ? import <nixpkgs> { } }: pkgs.mkShell { }' > "$root/shell.nix"

# Run package update scripts
path="$(nix-instantiate --eval --expr '<nixpkgs/maintainers/scripts/update.nix>')"
args=(
  --show-trace \
  --arg include-overlays "(import $root { }).overlays" \
  --arg keep-going 'true' \
  --argstr max-workers '8' \
  --argstr order 'topological' \
  --argstr skip-prompt 'true'
)
if [[ -n "$attr" ]]; then
  args+=(--argstr package "$attr")
else
  args+=(--arg predicate '_: p: p.meta ? position && builtins.substring 0 5 p.meta.position != "/nix/"')
fi
NIXPKGS_ALLOW_UNFREE='1' nix-shell "$path" "${args[@]}"

# Discard unused artifacts
if [[ -f "$root/update-git-commits.txt" ]]; then
  cat "$root/update-git-commits.txt" && rm "$root/update-git-commits.txt"
fi
