# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  plugalyzer = {
    pname = "plugalyzer";
    version = "v0.5.0";
    src = fetchFromGitHub {
      owner = "CrushedPixel";
      repo = "Plugalyzer";
      rev = "v0.5.0";
      fetchSubmodules = true;
      sha256 = "sha256-UmeSQi77OQnSjCBD1BgW8Iu/c+IoxipGlVfw5X7nWQo=";
    };
  };
}
