#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale /home/riro/Pictures/Wallpapers/秋の旅.jpg
picom --experimental-backend -b
fcitx5 -r &
polybar bar &
bspc monitor -d 1 2 3 4 5 
bspc config top_padding	        0
bspc config border_width        3
bspc config window_gap          4

bspc config border_radius      10

bspc config split_ratio          0.52
bspc config focus_follows_pointer true
bspc config focused_border_color "#5e81ac"
bspc config normal_border_color "#b6a49b"
bspc config active_border_color "#5e81ac"
bspc config presel_feedback_color "#867979"
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
