# Examples
# https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# https://github.com/getsops/sops#213using-sopsyaml-conf-to-select-kms-pgp-and-age-for-new-files
keys:
  - &alpha age135jhww6q6e46h30k4vjt2f6vrtduqxccu9rw25tcv46cku9q95nsgh6yzk
  - &archimedes age1pq1yha8ydtgr6vs2a5lk269qxjw6xnxc7ct0gqznjwv8sch9svqnz6rxksy3ex9wu4pgsgqyr96ghvzpjfm0054vu9ly9wzp250sfs4lph5h2wmx2agzape2q2wdn3yslwy285y02kf0gmtuzsx729tn504gt34xqsmqq4e3gj57f5gq6th22lpswc3g8zq9xaf2sq4f44ppl9ncpw3qhr0jddsvkvjqnzhgtlkj8slwz22aatl3c3f7v05ff7a2rpsdx5pnk4tswreflmqrvtczu4dhf2kq29wy85nq49jxc3yt25n2s5r3t9vs0eh8agkzcka4z3w22mzqd2aqufv0v7z0lszw4fl2uezqxpphx5982hvna0ez0t0yq4k4j95qcqgzluzts6wqa6mjpxjmga5d4vk4u78p3jrs5rew3h80pk0jh6evx9s3y5kvp8grqne4xrk84gsk93kfn7wsvlhrxl594zcnj78vg0ms2hdkfl57s44lzu67dn2e5uek8huwqntvvhsycvfusrhkysp0z4de26d9gduf7nhjl25gglzvshxgt46cwaz0f5eg8j5r7jpjdztrvx4c5cw54twrpuzfu9zr4y42p3q23uhh3gzdg9eg6s8dyvajh04e2lvzjeq5y6gse3vx7urvgl87k4qncu84ga8lfspynpyey3ffyvxsfel27kf86v4827hx9jv2pkeyadpfq9c97yyghz3dfk9qyxjcjs0crtkjv0kg7s0qp67qu688k260y992n2ucm2s4vtaqa4klv5afcm3q9wzs0gm57e9kkr623k2crqs4ekync5rkt73x60x7f36xxshwgq3d92lyahl90r4nvz2qjvh6vtuk68qf9v709g92jamskx85gw6tezqnsy5kamhakavel2f9awnzf8y8jhdd9g38vnaq4gcf7cxh4dxzklp60x8uf4n695hheahfpmuqq6nqymm2sgd25pscha3rs0pegtky5g28rye2mgn0m5ez679j5ynd94ekvvrxyyfz8fu2p9yrpd57559d8rsqu5facrcnflrq9756qs5vv605d69jxck59cpnwkmw72gs658264fy5jnvshmv2m8srzzv9gynajjj5l8vj7nw2svqpq8zsfvs9s3c9dg8rj6cvrgpsyuzxf0ygdp5r2seg6tzkpv0zg3276wwrukpux82lm42tmcxvcsts4m7pyvjn3efwrp8nzv60xkvfsy4y682gj8v0k9np389xws8gce08u2gpupc4kgdrl6rwqxz9y2kvqcv69h8zxjwr4eka6q8avanyvfw3wgy70aztxejkpjuegythnsvzl9gw78fv89pp3c8x79tq4grrzegqd90t7zvypvfwq3x8qpj0ns3qzkxjpazgllk7356uj80ndcrxv72e9nu20nhyyqu228f8u60rfv4skkxpaz4aaf2umc3evmdsxgyp3dary5ml9qa838apu5066f2dkqqmp3jpgg2zasaxkftf7sst7u30xtnxpqfefj7gt8gk23z7kzjy4vkwjgy8xxxpl2r2cl49m4zf65sf4rdy346vhfkfs28snlvgjpu32ukm9jy34nj9t638fqsjctkqmljrvmd9mst9tk2724kpuzkffwx37txu344wyg895w5xrac3nnm6s3049xn3w9ccs70ylm95xr8424hdhuve6rgnuztsch0fa90y9ucygmeeeg29ec7tyn8e54df2es5se0q6fv77y7ae3awgzt3j5ydlsr293y9c9ayhagsffa2t27lkncuqq68fntwp4esp8h2wxms2c8tfckw4h6vazhgva4q6vqk6d2zewjgm5ucamyh2v8wlj6h4mk896l8zy2jddrnysftu5dapa8c9gkkz5dphtlcvd8nw9mv3ny4h3fgwp689l8rclr5xj7e2f
  - &daedalus age1yex4qwcqx33ghuxcxew9zl3kmdn44ashsafdgmmly6arra48wcmsy0re2a
  - &goliath age1s2e5f6ayf33quexchwa75w5w6ss6jyxju38pjkwrwspefd2v8ezsh3c7l8
creation_rules:
  # path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
  - path_regex: secrets/daedalus/.*
    key_groups:
      - age:
        - *daedalus
  - path_regex: secrets/[^/]+
    key_groups:
      - age:
        - *alpha
        - *archimedes
        - *goliath
        - *daedalus

