# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cockpit-podman = {
    pname = "cockpit-podman";
    version = "120";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-podman/releases/download/120/cockpit-podman-120.tar.xz";
      sha256 = "sha256-iiEonz1uyRDfR5FehrB0vPxYQlS+99mrfwAZLe9X9AA=";
    };
  };
}
