# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cockpit-podman = {
    pname = "cockpit-podman";
    version = "121";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-podman/releases/download/121/cockpit-podman-121.tar.xz";
      sha256 = "sha256-58+R0uGDllwACZVdX0NI2mg0MO0noTkXvDhxIOGmPho=";
    };
  };
}
