#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i python3 ../../../integrations/nix-shell --arg f 'ps: [ ps.go2tv ps.python3 ps.sblast ]'
# vim: set filetype=python :
"""
cast media (local video or audio files) to a device on the same network
with some awareness of device-specific quirks
and a menu to select a device if there's more than one online
"""

from dataclasses import dataclass
from enum import Enum
from typing import NoReturn, Optional

import argparse
import logging
import os
import socket
import subprocess
import sys
import tempfile

logger = logging.getLogger(__name__)

class Compat(Enum):
    Default = "default"
    # RenameToMp4: ensure the name of the file sent ends in ".mp4".
    # this does not *transcode*. it doesn't modify the contents of the file at all. it just changes the name.
    # some devices are just so dumb that they'll only render a mkv file if it ends in .mp4.
    RenameToMp4 = "RenameToMp4"

@dataclass
class Device:
    # "model", or device name. e.g. "Theater TV".
    model: str
    compat: Optional[Compat] = None
    # URL: endpoint at which the device can be controlled. e.g. http://1.2.3.4:567/MediaRenderer.xml
    url: Optional[str] = None

    def augmented(self, other: "Device") -> "Device":
        return Device(
            model = self.model or other.model,
            compat = self.compat or other.compat,
            url = self.url or other.url,
        )

    def matches(self, filter: str) -> bool:
        """ return True if the filter string occurs inside the identifier for this device """
        clean = lambda s: "".join(c for c in s.lower() if c in "abcdefghijklmnopqrstuvwxyz0123456789")
        return clean(filter) in clean(self.model)

# ranked in order of preference
KNOWN_DEVICES = [
    Device("Theater TV", Compat.RenameToMp4),
    Device("Cuddlevision", Compat.Default),
]

class MorselParser:
    def __init__(self, morsel: str) -> None:
        self.morsel = morsel
        self.unparsed = morsel

    def sanitize(self) -> None:
        MARKUP = [
            # observed pre-2026-04-23:
            "\x1b[0m",
            "\x1b[1m",
            # observed 2026-04-23:
            "\x1b[?25l",
            "\x1b[?2004h",
            "\x1b[2A",
            "\x1b[J",
            "\x1b[3A",
            "\x1b[2K",
            "\x1b[?2004l",
            "\x1b[?25h",
            "\x1b[?1002l",
            "\x1b[?1003l",
            "\x1b[?1006l",
        ]
        for m in MARKUP:
            self.unparsed = self.unparsed.replace(m, "")
        self.unparsed = self.unparsed.strip()

    def take(self, token: str) -> Optional[str]:
        advanced = self.unparsed.removeprefix(token)
        if advanced != self.unparsed:
            self.unparsed = advanced
            return token

    def chomp(self) -> Optional[str]:
        if self.unparsed == '':
            return None
        char = self.unparsed[0]
        self.unparsed = self.unparsed[1:]
        return char

    def expect_chomp(self) -> str:
        char = self.chomp()
        assert char is not None, f'unexpected EOF when parsing morsel {self.morsel!r}'
        return char

    def eof(self) -> bool:
        return self.unparsed == ""

    def expect_eof(self) -> None:
        assert self.eof(), f'trailing tokens when parsing morsel {self.morsel!r}: {self.unparsed!r}'

class Go2TvParser:
    def __init__(self) -> None:
        self.parsed_devices = []

    def into_devices(self) -> list[Device]:
        return self.parsed_devices[:]

    def feed_line(self, line: str) -> None:
        mparser = MorselParser(line)
        mparser.sanitize()
        logger.debug(repr(mparser.unparsed))

        if mparser.take('Scanning devices... (q to quit)'):
            pass
        elif mparser.take('• '):
            # examples:
            # `• Cuddlevision [http://10.78.78.27:1328/]`
            # `• Theater TV [http://10.78.78.10:52323/MediaRenderer.xml]`
            partial_model = ''
            partial_url = ''
            while not mparser.take(' ['):
                partial_model += mparser.expect_chomp()
            while not mparser.take(']'):
                partial_url += mparser.expect_chomp()

            self.parsed_devices.append(Device(
                model=partial_model,
                url=partial_url,
            ))

        mparser.expect_eof()

class Executor:
    def __init__(self, dry_run: bool) -> None:
        self.dry_run = dry_run

    def exec(self, argv: list[str]) -> NoReturn:
        cmdstr = " ".join(argv)
        if self.dry_run:
            logger.info(f"# exec {cmdstr}")
            logger.info("dry-run: exiting 0")
            sys.exit(0)
        else:
            logger.info(f"exec {cmdstr}")
            os.execvp(argv[0], argv)

class Go2TvDriver:
    def __init__(self, executor: Executor, timeout: int) -> None:
        self.executor = executor
        self.timeout = timeout

    def scan_devices(self) -> list[Device]:
        args = [
            # XXX(2026-04-23): go2tv -l now *always* hangs until it receives `q` input (on flowy);
            # solve by forcibly killing it after `self.timeout` seconds...
            "timeout",
            "--foreground",
            "--preserve-status",
            str(self.timeout),
            "go2tv",
            "-l"
        ]
        logger.debug(" ".join(args))
        go2tv = subprocess.Popen(args, stdout=subprocess.PIPE)

        parser = Go2TvParser()
        assert go2tv.stdout is not None  # else type check for `go2tv.stdout.readline` fails
        for line in iter(go2tv.stdout.readline, b''):
            parser.feed_line(line.decode("utf-8"))

        return parser.into_devices()

    def cast_to(self, dev: Device, media: str) -> NoReturn:
        logger.info(f"casting to {dev.model} at {dev.url} with compat {dev.compat}")

        if dev.compat == Compat.RenameToMp4:
            if not media.endswith(".mp4"):
                if media.startswith("http://") or media.startswith("https://"):
                    logger.info(f"ignoring compat requirement {dev.compat} for {media}")
                else:
                    media = os.path.abspath(media)
                    # TODO: make sure this directory gets cleaned up!
                    dir_ = tempfile.mkdtemp(prefix="sane-cast-")
                    new_name = os.path.join(dir_, os.path.basename(media) + ".mp4")
                    os.symlink(media, new_name)
                    media = new_name

        if media.startswith("http://") or media.startswith("https://"):
            media_args = [ "-u", media ]
        else:
            media_args = [ "-v", media ]

        self.executor.exec([ "go2tv", "-t", dev.url ] + media_args)

class BlastDriver:
    def __init__(self, executor: Executor) -> None:
        self.executor = executor

    def cast_to(self, dev: Device) -> NoReturn:
        logger.info(f"casting audio to {dev.model} at {dev.url} with compat {dev.compat}")

        cli_args = [
            "sblast",
            # "blast.monitor" source will create a new output, or we can do that in pipewire config for better predictability.
            "-source", "effect_input.virtual_sink.monitor",
            "-device", dev.model,
            "-ip", get_ranked_ip_addrs()[0],
        ]
        if dev.compat != Compat.RenameToMp4:
            cli_args += [ "-usewav" ];

        self.executor.exec(cli_args)

def get_ranked_ip_addrs():
    """
    return the IP addresses most likely to be LAN addresses
    based on: <https://stackoverflow.com/a/1267524>
    """
    __unused_name__, __unused_aliases__, static_addrs = socket.gethostbyname_ex(socket.gethostname())
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("1", 53))
    con_addr, __unused_port__ = s.getsockname()
    return sorted(set(static_addrs + [ con_addr ]), key=lambda a: (a.startswith("127"), a))

def filter_devices(devices: list[Device], filter: str) -> list[Device]:
    return [d for d in devices if d.matches(filter)]


def rank_devices(devices: list[Device]) -> list[Device]:
    ranked = []
    for known in KNOWN_DEVICES:
        for vis in devices:
            if vis.model == known.model:
                ranked.append(known.augmented(vis))

    for vis in devices:
        if not any(vis.model == r.model for r in ranked):
            ranked.append(vis)

    return ranked


def ask_device(devices: list[Device]) -> Optional[Device]:
    dev = None
    while dev is None:
        # TODO: use a GUI menu like zenity?
        print("choose a device:")
        for i, d in enumerate(devices):
            print(f"[{i + 1}] {d.model}")
        print("[q] quit")
        print("")
        print("> ", end="")

        choice = input()
        if choice.strip() == "q":
            return
        try:
            dev = devices[int(choice.strip()) - 1]
        except:
            print(f"invalid choice {choice!r}")

    return dev

def get_default_device(devices: list[Device]) -> Optional[Device]:
    if not devices:
        logger.info("no devices found!")

    if len(devices) == 1:
        return devices[0]

def main():
    logging.basicConfig()
    logging.getLogger().setLevel(logging.INFO)

    parser = argparse.ArgumentParser(description="cast media to a DLNA receiver in range")
    parser.add_argument("--verbose", action="store_true", help="more logging")
    parser.add_argument("--always-ask", action="store_true", help="always ask which device to cast to, regardless how many are available")
    parser.add_argument("--device", help="filter devices based on if this string is contained in their name (case-insensitive)")
    parser.add_argument("--dry-run", action="store_true", help="always ask which device to cast to, regardless how many are available")
    parser.add_argument("--scan-timeout", type=int, default=10, help="how many seconds to spend scanning for devices")
    parser.add_argument("media", nargs="?", help="file or URL to send to the DLNA device. empty to cast just an audio stream")

    args = parser.parse_args()

    if args.verbose:
        logger.setLevel(logging.DEBUG)

    executor = Executor(dry_run=args.dry_run)

    blast = BlastDriver(executor)
    go2tv = Go2TvDriver(executor, timeout=args.scan_timeout)
    devices = go2tv.scan_devices()

    if args.device:
        devices = filter_devices(devices, args.device)
    devices = rank_devices(devices)

    dev = get_default_device(devices)
    if dev is None or args.always_ask:
        dev = ask_device(devices)
    if dev:
        if args.media:
            go2tv.cast_to(dev, args.media)
        else:
            blast.cast_to(dev)

if __name__ == "__main__":
    main()
