;; WASI preview1 stubs for kklib + wasi-libc (no preview2).
(module
  (func $i (param i32) (result i32) i32.const 0)
  (func $ii (param i32 i32) (result i32) i32.const 0)
  (func $iii (param i32 i32 i32) (result i32) i32.const 0)
  (func $iiii (param i32 i32 i32 i32) (result i32) i32.const 0)
  (func $iiiii (param i32 i32 i32 i32 i32) (result i32) i32.const 0)
  (func $i64i (param i32 i64 i32) (result i32) i32.const 0)
  (func $i64ii (param i32 i64 i32 i32) (result i32) i32.const 0)
  (func $i64i64i (param i32 i64 i64 i32) (result i32) i32.const 0)
  (func $i9 (param i32 i32 i32 i32 i32 i64 i64 i32 i32) (result i32) i32.const 0)
  (func $iii64i (param i32 i32 i32 i64 i32) (result i32) i32.const 0)
  (func $empty (result i32) i32.const 0)

  (export "args_get" (func $ii))
  (export "args_sizes_get" (func $ii))
  (export "environ_get" (func $ii))
  (export "environ_sizes_get" (func $ii))
  (export "clock_res_get" (func $ii))
  (export "clock_time_get" (func $i64i))
  (export "fd_advise" (func $i64ii))
  (export "fd_allocate" (func $i64ii))
  (export "fd_close" (func $i))
  (export "fd_datasync" (func $i))
  (export "fd_fdstat_get" (func $ii))
  (export "fd_fdstat_set_flags" (func $ii))
  (export "fd_filestat_get" (func $ii))
  (export "fd_filestat_set_size" (func $i64i))
  (export "fd_filestat_set_times" (func $i64i64i))
  (export "path_filestat_set_times" (func $i64i64i))
  (export "path_open" (func $i9))
  (export "fd_pread" (func $iiii))
  (export "fd_prestat_get" (func $ii))
  (export "fd_prestat_dir_name" (func $iii))
  (export "fd_pwrite" (func $iiii))
  (export "fd_read" (func $iiii))
  (export "fd_readdir" (func $iii64i))
  (export "fd_renumber" (func $ii))
  (export "fd_seek" (func $i64ii))
  (export "fd_sync" (func $i))
  (export "fd_tell" (func $ii))
  (export "fd_write" (func $iiii))
  (export "path_create_directory" (func $iii))
  (export "path_filestat_get" (func $iiiii))
  (export "path_link" (func $iiiii))
  (export "path_readlink" (func $iiiii))
  (export "path_remove_directory" (func $iii))
  (export "path_rename" (func $iiiii))
  (export "path_symlink" (func $iiii))
  (export "path_unlink_file" (func $iii))
  (export "poll_oneoff" (func $iiii))
  (export "proc_raise" (func $i))
  (export "random_get" (func $ii))
  (export "sched_yield" (func $empty))
  (export "sock_accept" (func $iii))
  (export "sock_recv" (func $iiiii))
  (export "sock_send" (func $iiii))
  (export "sock_shutdown" (func $ii))
  (func (export "proc_exit") (param i32)
    unreachable)
)
