#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i bash ../../../integrations/nix-shell --arg f 'ps: [ ps.bash ps.git ]'

set -euo pipefail

usage() {
  echo "git-work DIRECTORY: create a worktree in DIRECTORY and cd into it"
}

dir=
parseArgs() {
  while [ "$#" -ne 0 ]; do
    local arg=$1
    shift
    case $arg in
      (-h|--help)
        usage
        exit 0
        ;;
      (*)
        if [ -n "$dir" ]; then
          usage
          exit 1
        fi;
        dir="$arg"
        ;;
    esac
  done
}

parseArgs "$@"

git worktree add "$dir" 2>&1
echo "$PWD/$dir"
