# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
  git,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "047024z6xhpkgvp4ywfs8j78qyhzs29lb7mrzkba5lscg16xmnn8";
    aarch64-linux = "1a31pq4f9bs8kydlk2xh64q0y3hvng92wfyfrfxr1v5pq0s1b8c8";
    x86_64-darwin = "1f8r2pf2psfmbv0p8lcyfvzbwggr0vjlr6jw120vv2cnlcbjrx95";
    aarch64-darwin = "1lq4nxz2gxwzvqsgy6pri2am7wnis1hnaxg1ji3ghky1zv8b1gci";
  };

  urlMap = {
    x86_64-linux = "https://github.com/aymanbagabas/drift/releases/download/v0.0.8/drift_0.0.8_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/aymanbagabas/drift/releases/download/v0.0.8/drift_0.0.8_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/aymanbagabas/drift/releases/download/v0.0.8/drift_0.0.8_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/aymanbagabas/drift/releases/download/v0.0.8/drift_0.0.8_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "drift";
  version = "0.0.8";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./drift $out/bin/drift
    wrapProgram $out/bin/drift --prefix PATH : ${lib.makeBinPath ([ git ])}
  '';

  meta = {
    description = "A standalone git diff pager for the terminal.";
    homepage = "https://github.com/aymanbagabas/drift";
    license = lib.licenses.mit;
    mainProgram = "drift";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
