Syntax 4

SectionUseCase."HiFi" {
	File "/Xiaomi/beryllium/HiFi.conf"
	Comment "HiFi quality Music."
}

SectionUseCase."Voice Call" {
	File "/Xiaomi/beryllium/VoiceCall.conf"
	Comment "Make a phone call"
}

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"

BootSequence [
	# Headphones Playback Default Volume
	cset "name='HP Mix Digital Volume' 100,100"

	# Headphones Mic Default Volume
	cset "name='ADC2 Volume' 16"
	cset "name='DEC0 Volume' 80"

	# Phone Bottom Mic Default Volume
	cset "name='ADC3 Volume' 16"
	cset "name='DEC7 Volume' 80"
]
