# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0cyvaj0dmj7ky5iv7shqyyv1bwmp8r9kj4jxj0si70d8x75ak48q";
    x86_64-linux = "0yb9i7d4dm6gzgj1s7895ikqjwq37gfxi924h2gz4636i6cy5cwf";
    armv7l-linux = "0z2cs30ps60180c8fmc3dlq6sgkr8cn0wcps01alf1smlicnprsn";
    aarch64-linux = "113idcgckc2mx1gycjxc7gyyp6vq940bfx3hgvh20ji49rjf6if0";
    x86_64-darwin = "1a7gs3002lpn4ndsf10vz917pb9y92h43p7ycnf3jysdn1la599r";
    aarch64-darwin = "0nwnrm2mxjkfkqsqm72avp0ds28k2vxc6m977bvbgp883npa3y6c";
  };

  urlMap = {
    i686-linux = "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.5/shcopy_0.1.5_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.5/shcopy_0.1.5_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.5/shcopy_0.1.5_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.5/shcopy_0.1.5_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.5/shcopy_0.1.5_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.5/shcopy_0.1.5_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "shcopy";
  version = "0.1.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./shcopy $out/bin/shcopy
  '';

  system = system;

  meta = {
    description = "Copy text to clipboard from anywhere using ANSI OSC 52 sequence";
    homepage = "https://github.com/aymanbagabas/shcopy";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
