# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  osirus-clap = {
    pname = "osirus-clap";
    version = "1.2.30";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/master/DSP56300Emu-1.2.30-Linux_x86_64-Osirus-CLAP.deb";
      sha256 = "sha256-33M/yPFeFfYtXcKY/IIzM4q0d44+kLBFuXeLgWC0oRg=";
    };
  };
  osirus-test-console = {
    pname = "osirus-test-console";
    version = "1.2.30";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/master/DSP56300Emu-1.2.30-Linux_x86_64-OsirusTestConsole.deb";
      sha256 = "sha256-2QanjIdfHrr5vkreEgdSkEQxqb/X2FDcZ0B3GyQVnsc=";
    };
  };
  osirus-vst2 = {
    pname = "osirus-vst2";
    version = "1.2.30";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/master/DSP56300Emu-1.2.30-Linux_x86_64-Osirus-VST2.deb";
      sha256 = "sha256-nvEqjj4Dm4SiE+kX5xdbqX9lMFJl9BVlWEpt1zbBGmI=";
    };
  };
  osirus-vst3 = {
    pname = "osirus-vst3";
    version = "1.2.30";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/master/DSP56300Emu-1.2.30-Linux_x86_64-Osirus-VST3.deb";
      sha256 = "sha256-ZcsjaBJkK7XmTipalIS90P+7M2ErALSmfOwbehX5qsA=";
    };
  };
  osirusfx-clap = {
    pname = "osirusfx-clap";
    version = "1.2.30";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/master/DSP56300Emu-1.2.30-Linux_x86_64-OsirusFX-CLAP.deb";
      sha256 = "sha256-84Th0f0QAyII0SHNmr2/OmlDgBWsvCaR3BMU1vCHbZ0=";
    };
  };
  osirusfx-vst2 = {
    pname = "osirusfx-vst2";
    version = "1.2.30";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/master/DSP56300Emu-1.2.30-Linux_x86_64-OsirusFX-VST2.deb";
      sha256 = "sha256-6CT/RVOq396ZhgmJ6fuA3OUHzOaqp4o67xcj8tolOJQ=";
    };
  };
  osirusfx-vst3 = {
    pname = "osirusfx-vst3";
    version = "1.2.30";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/master/DSP56300Emu-1.2.30-Linux_x86_64-OsirusFX-VST3.deb";
      sha256 = "sha256-+Vn3dQP0iQ7YZH1J0Hs01SubNWI5Y6wQ02u6M595l7k=";
    };
  };
}
