#! /usr/bin/env bash
set -euo pipefail

update_repo(){
  echo -e "\nUpdate local repository\n"
  git pull
}

update_flake(){ 
  echo -e "\nUpdate repo flake\n"
  nix flake update --flake .
}

check_rev_change(){
  if [[ -n "$(git status --porcelain)" ]]; then
    ### Initialize variable to get version and hash commit
    NIXPKGS_VERSION=$(nix eval --raw "github:NixOS/nixpkgs/$(jq -r '.nodes.nixpkgs.locked.rev' flake.lock)#lib.version")
    echo -e "New revision\n"
    git add flake.lock
    git commit -m "[nixpkgs/${NIXPKGS_VERSION}] flake.lock: update to the new rev"

    ### Push changes
    git push

    echo -e "\nChange commited to the repo"
  else
    echo "No changes detected"
  fi
}

main(){
  update_repo
  update_flake
  check_rev_change
}

### Execute the main function
main
