diff --git a/src/Makefile b/src/Makefile
index 29af9de..805868f 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -9,7 +13,7 @@ KNOWN_SYSTEM= no
 LIB= $(MCFOST_INSTALL)/lib
 
 ifndef SYSTEM
-    SYSTEM= ifort
+    SYSTEM=gfortran
 endif
 
 ifeq ($(gfortran), yes)
@@ -93,15 +97,15 @@ ifeq ($(SYSTEM), xeonphi)
 endif
 
 ifeq ($(SYSTEM), gfortran)
-    FC= gfortran
+#    FC= gfortran
     FFLAGS+= -m64 -cpp -O3 -funroll-loops -ffinite-math-only \
              -fno-trapping-math -ffree-line-length-none -fbacktrace  -static-libgcc -static-libstdc++
     DBLFLAG= -fdefault-real-8 -fdefault-double-8
     DEBUGFLAG= -g -fbounds-check -Wunused-variable -Wunused-function -Wuninitialized -fbacktrace
     KNOWN_SYSTEM= yes
     FOMPFLAGS= -fopenmp
-    CC= gcc
-    CXX= g++
+#    CC= gcc
+#    CXX= g++
     CCFLAGS= -Wall -pedantic -m64 -O3 -funroll-loops -ffinite-math-only -fno-trapping-math
     COMPFLAGS= -fopenmp
     LIBCXX= -lstdc++
@@ -139,7 +143,7 @@ endif
 
 #------------------------------------------------------------------------------#
 # Library flags
-INCLUDE+= -I$(MCFOST_INSTALL)/include -I$(MCFOST_INSTALL)/include/voro++ -I$(MCFOST_INSTALL)/include/hdf5 -I$(MCFOST_INSTALL)/include/$(SYSTEM)
+#INCLUDE+= -I$(MCFOST_INSTALL)/include -I$(MCFOST_INSTALL)/include/voro++ -I$(MCFOST_INSTALL)/include/hdf5 -I$(MCFOST_INSTALL)/include/$(SYSTEM)
 LDFLAGS+= -L$(LIBS) $(LIBCXX) -lcfitsio -lvoro++ -lsprng -lxgboost -ldmlc -lrabit -lhdf5_fortran -lhdf5 -lz -ldl
 
 #------------------------------------------------------------------------------#
