# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
}:
let
  shaMap = {
    i686-linux = "1ci6pj9id6h0l19pk5lipih07c8q14h42fsylp4cyl4lby3najng";
    x86_64-linux = "0y5cxw1dbp68d2wzlxh03da5082ax4kdyi70afzqz3vgfxr9d86d";
    armv7l-linux = "1rm3yhdaffxi5f4rsg38pwm50g93b15icgywd8frnmm82sgcarhw";
    aarch64-linux = "1x6r30kcdxs8v3m8kcvhfpbv2m1j7ygalgkv7lsqrb81sq2mrq22";
    x86_64-darwin = "018dm3s1pzksvyaxbj2jnxifvazh0spx93zxlpy420zynbwhyn7v";
    aarch64-darwin = "0fkmnfg0565m62xl18k9xicp7g3nybvl9a682y2y6rp4wgw4n5l6";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/mods/releases/download/v1.2.1/mods_1.2.1_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/mods/releases/download/v1.2.1/mods_1.2.1_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/mods/releases/download/v1.2.1/mods_1.2.1_Linux_arm.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/mods/releases/download/v1.2.1/mods_1.2.1_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/mods/releases/download/v1.2.1/mods_1.2.1_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/mods/releases/download/v1.2.1/mods_1.2.1_Darwin_arm64.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "mods";
  version = "1.2.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./mods $out/bin/mods
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "AI on the command line";
    homepage = "https://charm.sh/";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
