--- a/GNUmakefile
+++ b/GNUmakefile
@@ -39,9 +39,6 @@
 gallant.bdf: gallant.hex hextobdf
 	./hextobdf < $< > $@
 
-gallant.hex: gallant.src srctohex
-	./srctohex < $< > $@
-
 gallant.fnt: gallant.hex
 	vtfontcvt -v -o $@ $^
 
@@ -51,9 +48,6 @@
 gallant.pcf.gz: gallant.pcf
 	gzip -cnv9 $^ > $@
 
-gallant.src: hextosrc
-	./hextosrc < gallant.hex > $@
-
 gallant.ttf gallant.woff gallant.woff2: gallant.src srctottf.py
 	python srctottf.py
 
