--- a/GNUmakefile
+++ b/GNUmakefile
@@ -39,7 +39,4 @@
 gallant.bdf: gallant.hex hextobdf
 	./hextobdf < $< > $@.tmp && mv $@.tmp $@
 
-gallant.hex: gallant.src srctohex
-	./srctohex < $< > $@.tmp && mv $@.tmp $@
-
 gallant.fnt: gallant.hex
@@ -54,7 +51,4 @@
 gallant.pcf.gz: gallant.pcf
 	gzip -cnv9 $^ > $@
 
-gallant.src: hextosrc
-	./hextosrc < gallant.hex > $@.tmp && mv $@.tmp $@
-
 gallant.ttf gallant.woff gallant.woff2 &: gallant.src srctottf.py
