systems = ["x86_64-linux"]
exclude = [
    "packages.x86_64-linux.boomer",            # broken
    "packages.x86_64-linux.shed",              # broken
    "packages.x86_64-linux.koil",              # there's already a check that build this
    "packages.x86_64-linux.vintagestory-beta", # unfree
    "packages.x86_64-linux.tabby-terminal",    # idc enough about it being cached, and it's kinda sluggish to build
]
