#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i bash ../../../../integrations/nix-shell --arg f 'ps: [ ps.bash ps.gocryptfs ]'

pass_file=/run/gocryptfs/private.key
pass_str=$(cat "$pass_file")
rm "$pass_file"
echo "$pass_str" | exec gocryptfs -nosyslog -passfile /dev/fd/0 "$@"
