{ pkgs }:

let
  inherit (builtins) filter toFile;
  inherit (lib) hasInfix hasPrefix recursiveUpdate remove versionAtLeast warnIf;
  inherit (pkgs) callPackage fetchFromGitHub lib;

  isStable = hasPrefix "." lib.trivial.versionSuffix;
in
# Published as nur.repos.AndrewKvalheim (https://nur.nix-community.org/repos/andrewkvalheim/)
rec {
  hmModules = {
    xcompose = import ./library/xcompose.user.nix;
  };

  modules = {
    nixpkgs-issue-163080 = import ./library/nixpkgs-issue-163080.system.nix;
  };

  lib = {
    inherit (import ./library/utilities.lib.nix { inherit (pkgs) lib; })
      chebyshev
      chebyshevWithDomain
      contrastRatio
      linearRgbToRgb
      oklchToCss
      oklchToLinearRgb
      rgbToHex
      sgr
      uniqueBy;
  };

  "3mf-thumbnailer" = callPackage ./library/3mf-thumbnailer.pkg.nix { };
  ai-robots-txt = callPackage ./library/ai-robots-txt.pkg.nix { };
  apex = callPackage ./library/apex.pkg.nix { };
  blocky-ui = callPackage ./library/blocky-ui.pkg.nix { };
  buildJosmPlugin = callPackage ./library/buildJosmPlugin.fn.nix { };
  busyserve = (callPackage ./library/busyserve.pkg.nix { });
  caddy-with-cache-route53 = pkgs.caddy.withPlugins {
    plugins = [
      "github.com/caddy-dns/route53@v1.6.2"
      "github.com/caddyserver/cache-handler@v0.16.0"
    ];
    hash = {
      "2.11.4@1.26.4" = "sha256-JuJhKemHwx5geqA0Y0Vkaccmuf29ulUfWgXu2tOcsHk=";
      "2.11.4@1.26.5" = "sha256-SIZvtm7T4aM5gySIYTaVGnqqtK3/HvElyLjEAvNFTfI=";
    }."${pkgs.caddy.version}@${pkgs.caddy.go.version}";
  };
  cc-icons-unicode = callPackage ./library/cc-icons-unicode.pkg.nix { };
  ch57x-keyboard-tool = callPackage ./library/ch57x-keyboard-tool.pkg.nix { };
  chunker = callPackage ./library/chunker.pkg.nix { };
  co2monitor = callPackage ./library/co2monitor.pkg.nix { };
  decompiler-mc = callPackage ./library/decompiler-mc.pkg.nix { };
  dmarc-report-notifier = callPackage ./library/dmarc-report-notifier.pkg.nix { };
  easy-timeline = callPackage ./library/easy-timeline.pkg.nix { };
  fastnbt-tools = callPackage ./library/fastnbt-tools.pkg.nix { };
  fediblockhole = callPackage ./library/fediblockhole.pkg.nix { };
  git-diff-image = callPackage ./library/git-diff-image.pkg.nix { };
  gpx-reduce = callPackage ./library/gpx-reduce.pkg.nix { };
  incremental-compress = callPackage ./library/incremental-compress.pkg.nix { };
  iptables_exporter = callPackage ./library/iptables_exporter.pkg.nix { };
  josm-imagery-used = callPackage ./library/josm-imagery-used.pkg.nix { inherit buildJosmPlugin; };
  journal-brief = callPackage ./library/journal-brief.pkg.nix { };
  little-a-map = callPackage ./library/little-a-map.pkg.nix { };
  mark-applier = callPackage ./library/mark-applier.pkg.nix { };
  meshtastic-url = callPackage ./library/meshtastic-url.pkg.nix { };
  minemap = callPackage ./library/minemap.pkg.nix { };
  nbt-explorer = callPackage ./library/nbt-explorer.pkg.nix { };
  office-hours = (callPackage ./library/office-hours.pkg.nix {
    python3 = pkgs.python3.override {
      packageOverrides = _: pythonPackages: with pythonPackages; {
        # Pending NixOS/nixpkgs#493912
        icalendar =
          if (versionAtLeast icalendar.version "7") then
            warnIf isStable "Version override of icalendar is no longer necessary" icalendar
          else
            icalendar.overridePythonAttrs (icalendar: rec {
              version = "7.1.2";
              src = icalendar.src.override { tag = "v${version}"; hash = "sha256-y6t27/l2jnNr6/VlGuXlE2BcNDPOd0wscyCMpRY4+MM="; };
              patches = [ (toFile "no-dynamic-version.patch" "--- a/pyproject.toml\n+++ b/pyproject.toml\n@@ -38,4 +38 @@\n-# These attributes are dynamically generated by hatch-vcs\n-dynamic = [\n-    \"version\"\n-]\n+version = \"${version}\"\n") ];
              outputs = remove "doc" icalendar.outputs;
              nativeBuildInputs = filter (p: ! hasInfix "sphinx" p.pname) icalendar.nativeBuildInputs;
            });
        sunrisesunset =
          if (pythonPackages ? sunrisesunset) then
            warnIf isStable "Packaging of sunrisesunset is no longer necessary" sunrisesunset
          else
            buildPythonPackage rec {
              pname = "sunrisesunset";
              version = "1.0.2";
              src = fetchFromGitHub { owner = "cnobile2012"; repo = "sunrisesunset"; tag = "v${version}"; hash = "sha256-FvEhOClakdvPf5tNRHqvK/12TI6UN+d+NswW69JT1EA="; };
              format = "setuptools";
              pythonImportsCheck = [ "sunrisesunset" ];
            };
      };
    };
  }).overrideAttrs (o: recursiveUpdate o {
    meta.broken = pkgs.python3Packages.requests-ratelimiter.meta.broken; # NixOS/nixpkgs#497999
  });
  pdfalyzer = callPackage ./library/pdfalyzer.pkg.nix {
    python3Packages = (pkgs.python3.override {
      packageOverrides = _: pythonPackages: with pythonPackages; {
        pypdf = pypdf.overridePythonAttrs (pypdf: rec {
          version = "6.6.0";
          src = pypdf.src.override { tag = version; hash = "sha256-C1ZFqqLFtxWOuLUT7KFSfWIE6a9xDPCFtOakzYP4NMY="; };
        });
      };
    }).pkgs;
  };
  pngquant-interactive = callPackage ./library/pngquant-interactive.pkg.nix { };
  sort-domains = callPackage ./library/sort-domains.pkg.nix { };
  spf-check = callPackage ./library/spf-check.pkg.nix { };
  spf-tree = callPackage ./library/spf-tree.pkg.nix { };
  stretch-break = callPackage ./library/stretch-break.pkg.nix { };
  tile-stitch = callPackage ./library/tile-stitch.pkg.nix { };
  udon = callPackage ./library/udon.pkg.nix {
    python3 = pkgs.python3.override {
      packageOverrides = _: pythonPackages: with pythonPackages; {
        config = buildPythonPackage rec {
          pname = "config";
          version = "0.5.1";
          src = pkgs.fetchPypi { inherit pname version; extension = "zip"; hash = "sha256-LdSgOqOD0wcR1aMyWhhY3iJTKNYZUKhb5bdMEA9jAW0="; };
          format = "pyproject";
          nativeBuildInputs = [ setuptools ];
        };
      };
    };
  };
  wireguard-vanity-address = callPackage ./library/wireguard-vanity-address.pkg.nix { };
}
