# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  tree-sitter-hypr = {
    pname = "tree-sitter-hypr";
    version = "86025136c12cd1058985479a6b1935829077f1af";
    src = fetchFromGitHub {
      owner = "luckasRanarison";
      repo = "tree-sitter-hypr";
      rev = "86025136c12cd1058985479a6b1935829077f1af";
      fetchSubmodules = false;
      sha256 = "sha256-1HGA4VUWM/iR1XBNmrsdj1PRGo7qPYMw5vmcVQO1BH0=";
    };
    date = "2024-02-10";
  };
}
