# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  zen-browser = {
    pname = "zen-browser";
    version = "1.14.5b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.14.5b/zen.macos-universal.dmg";
      sha256 = "sha256-FAGfVV3CL5bFgGzDeSDIIunJ7NLtS0vbQ/dAJeHD3xs=";
    };
  };
  zen-browser-twilight = {
    pname = "zen-browser-twilight";
    version = "1.14.5b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/twilight/zen.macos-universal.dmg";
      sha256 = "sha256-Fk34ksJ/nvSZll9nyu19kZBwT+yndzn69Er1sDqDeL0=";
    };
  };
}
