# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  zen-browser = {
    pname = "zen-browser";
    version = "1.14.1b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.14.1b/zen.macos-universal.dmg";
      sha256 = "sha256-R1EqnnHDdRGs5ZNsvher7C2hA/w964B1iYJubNjR18A=";
    };
  };
  zen-browser-twilight = {
    pname = "zen-browser-twilight";
    version = "1.14.1b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/twilight/zen.macos-universal.dmg";
      sha256 = "sha256-sF7cXoCWr81/Tb0NMYz+1iyWCgAuY4X0Beyve7fajxo=";
    };
  };
}
