# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cardinal = {
    pname = "cardinal";
    version = "2488c341d5cfb939412872b6c2e2cfb76b01c47a";
    src = fetchFromGitHub {
      owner = "DISTRHO";
      repo = "Cardinal";
      rev = "2488c341d5cfb939412872b6c2e2cfb76b01c47a";
      fetchSubmodules = true;
      sha256 = "sha256-m0d90jwW8pEc7dxt0Ce6ceuF4CG1/NrCnmgbr9IBeTA=";
    };
    date = "2024-02-03";
  };
}
