# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cardinal = {
    pname = "cardinal";
    version = "6e024650b4529ab974b956e1ca8f4221caedaac3";
    src = fetchFromGitHub {
      owner = "DISTRHO";
      repo = "Cardinal";
      rev = "6e024650b4529ab974b956e1ca8f4221caedaac3";
      fetchSubmodules = true;
      sha256 = "sha256-5MdbVgz8hl5dK3kDdB2/e6k8KxJI5TzkDhN6ZR1ls68=";
    };
    date = "2024-09-22";
  };
}
