# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cardinal = {
    pname = "cardinal";
    version = "6505acaa75e8cd429be62fb7673517cee35c3373";
    src = fetchFromGitHub {
      owner = "DISTRHO";
      repo = "Cardinal";
      rev = "6505acaa75e8cd429be62fb7673517cee35c3373";
      fetchSubmodules = true;
      sha256 = "sha256-SV/CGJ0EqljVbJMytxGxhjZ/P0wZXwA4PWkmGFNer8M=";
    };
    date = "2024-01-06";
  };
}
