{ ... }:
{
  imports = [
    ./coturn.nix
    ./cryptocurrencies
    ./email
    ./ejabberd.nix
    ./freshrss.nix
    ./export
    ./gitea.nix
    ./goaccess.nix
    ./ipfs.nix
    ./jackett.nix
    ./jellyfin.nix
    ./kiwix-serve.nix
    ./komga.nix
    ./lemmy.nix
    ./matrix
    ./navidrome.nix
    ./nginx.nix
    ./nixos-prebuild.nix
    ./ntfy
    ./pict-rs.nix
    ./pleroma.nix
    ./postgres.nix
    ./prosody
    ./slskd.nix
    ./transmission
    ./trust-dns.nix
    ./wikipedia.nix
  ];
}
