{ ... }:
{
  imports = [
    ./bitmagnet.nix
    ./coturn.nix
    ./cryptocurrencies
    ./email
    ./ejabberd.nix
    ./freshrss.nix
    ./export
    ./hickory-dns.nix
    ./gerbera.nix
    ./gitea.nix
    ./goaccess.nix
    ./ipfs.nix
    ./jackett
    ./jellyfin
    ./kiwix-serve.nix
    ./komga.nix
    ./lemmy.nix
    ./matrix
    ./minidlna.nix
    ./mumble.nix
    ./navidrome.nix
    ./nginx
    ./nixos-prebuild.nix
    ./ntfy
    ./pict-rs.nix
    ./pleroma.nix
    ./postgresql
    ./prosody
    ./slskd.nix
    ./transmission
    ./wikipedia.nix
  ];
}
