" let the terminal handle mouse events, that way i get OS-level ctrl+shift+c/etc
" this used to be default, until <https://github.com/neovim/neovim/pull/19290>
set mouse=

" copy/paste to system clipboard
set clipboard=unnamedplus

" screw tabs; always expand them into spaces
set expandtab

" at least don't open files with sections folded by default
set nofoldenable

" allow text substitutions for certain glyphs.
" higher number = more aggressive substitution (0, 1, 2, 3)
" i only make use of this for tex, but it's unclear how to
" apply that *just* to tex and retain the SyntaxRange stuff.
set conceallevel=2

" horizontal rule under the active line
" set cursorline

" highlight trailing space & related syntax errors (doesn't seem to work??)
" let c_space_errors=1
" let python_space_errors=1

" enable highlighting of leading/trailing spaces,
" and especially tabs
" source: https://www.reddit.com/r/neovim/comments/chlmfk/highlight_trailing_whitespaces_in_neovim/
set list
set listchars=tab:▷\·,trail:·,extends:◣,precedes:◢,nbsp:○

" when using vim to view manpages
"   (`:Man topic` or `MANPAGER='nvim +Man!' man topic` or `vim man://topic`),
" instruct `man` to output unwrapped buffers, and let vim soft-wrap them.
" this allows one to resize the terminal and have the manpage be re-rendered.
" see: <https://github.com/neovim/neovim/issues/11436>
let g:man_hardwrap=0
