{ user }: {
  inherit (user) uid;
  inherit (user.group) gid;
  name = "csgo-data/csgo/cfg/gamemode_casual_server.cfg";
  # Below as per: https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers#Advanced_Configuration
  text = ''
    bot_autodifficulty_threshold_high					0.0
    bot_autodifficulty_threshold_low					-2.0
    bot_chatter											normal
    bot_defer_to_human_goals							0
    bot_defer_to_human_items							1
    bot_difficulty										1
    bot_quota											10
    bot_quota_mode										fill
    cash_player_bomb_defused							200
    cash_player_bomb_planted							200
    cash_player_damage_hostage							-30
    cash_player_interact_with_hostage					300
    cash_player_killed_enemy_default					200
    cash_player_killed_enemy_factor						0.5
    cash_player_killed_hostage							-1000
    cash_player_killed_teammate							-300
    cash_player_rescued_hostage							1000
    cash_team_elimination_bomb_map						2700
    cash_team_elimination_hostage_map_t					2000
    cash_team_elimination_hostage_map_ct				2300
    cash_team_hostage_alive								0
    cash_team_hostage_interaction						500
    cash_team_loser_bonus								2400
    cash_team_loser_bonus_consecutive_rounds			0
    cash_team_planted_bomb_but_defused					200
    cash_team_rescued_hostage							0
    cash_team_terrorist_win_bomb						2700
    cash_team_win_by_defusing_bomb						2700
    cash_team_win_by_hostage_rescue						3000
    cash_team_win_by_time_running_out_hostage			2000
    cash_team_win_by_time_running_out_bomb				2700
    ff_damage_reduction_bullets							0
    ff_damage_reduction_grenade							0
    ff_damage_reduction_grenade_self					0
    ff_damage_reduction_other							0
    mp_afterroundmoney									0
    mp_buytime											45
    mp_buy_anywhere										0
    mp_buy_during_immunity								0
    mp_death_drop_defuser								1	
    mp_death_drop_grenade								2	
    mp_death_drop_gun									1
    mp_defuser_allocation								2
    mp_force_pick_time									15
    mp_forcecamera										0
    mp_free_armor										1			
    mp_freezetime										5
    mp_friendlyfire										1
    mp_win_panel_display_time							3
    mp_ggprogressive_round_restart_delay				15
    mp_ggtr_bomb_defuse_bonus							1
    mp_ggtr_bomb_detonation_bonus						1
    mp_ggtr_bomb_pts_for_flash							4
    mp_ggtr_bomb_pts_for_he								3
    mp_ggtr_bomb_pts_for_molotov						5
    mp_ggtr_bomb_pts_for_upgrade						2
    mp_ggtr_bomb_respawn_delay							0
    mp_ggtr_end_round_kill_bonus						1
    mp_ggtr_halftime_delay								0.0
    mp_ggtr_last_weapon_kill_ends_half					0
    mp_respawn_immunitytime								0
    mp_halftime											0
    mp_match_can_clinch									1
    mp_maxmoney											10000
    mp_maxrounds										15
    mp_molotovusedelay									0
    mp_playercashawards									1
    mp_roundtime										3
    mp_roundtime_hostage								2
    mp_roundtime_defuse									2.25
    mp_solid_teammates									0
    mp_startmoney										1000
    mp_teamcashawards									1
    mp_timelimit										0
    mp_warmuptime										90		
    mp_weapons_allow_zeus								1
    mp_weapons_allow_typecount							2
    spec_freeze_panel_extended_time						0
    spec_freeze_time									5.0
    sv_allow_votes										1
    sv_alltalk											1
    sv_arms_race_vote_to_restart_disallowed_after		0
    sv_vote_to_changelevel_before_match_point			1		
    sv_deadtalk											0
    sv_ignoregrenaderadio								0
    tv_delay											30
    mp_warmup_pausetimer								0
    mp_halftime_pausetimer								0
    mp_randomspawn										0
    mp_randomspawn_los									0
    sv_infinite_ammo									0
    ammo_grenade_limit_flashbang						1
    ammo_grenade_limit_total							3
    mp_weapons_allow_map_placed							1
    mp_weapons_glow_on_ground							0
    mp_display_kill_assists								1
    mp_respawn_on_death_t								0
    mp_respawn_on_death_ct								0
    mp_ct_default_melee									weapon_knife
    mp_ct_default_secondary								weapon_hkp2000
    mp_ct_default_primary								""
    mp_t_default_melee									weapon_knife
    mp_t_default_secondary								weapon_glock
    mp_t_default_primary								""
    mp_default_team_winner_no_objective					-1
    sv_occlude_players								1
    occlusion_test_async								1
    spec_replay_enable								1
    mp_round_restart_delay								10
  '';
  mode = "0744";
}
