package androidx.compose.ui.res

import androidx.compose.runtime.Composable

object StringResources {
    val stringMap = mapOf<Int, String>(
        1 to "About",
        2 to "Automatic Updates Check",
        3 to "Check the selected channel automatically for new releases",
        4 to "Playing from %1\$s",
        5 to "-%1\$s",
        6 to "Android Auto",
        7 to "Driving playback, browsing and data",
        8 to "Team",
        9 to "Discord",
        10 to "Donate",
        11 to "GitHub",
        12 to "Telegram",
        13 to "Website",
        14 to "Contributor Translation",
        15 to "Contributors",
        16 to "Couldn\u2019t load translation credits.",
        17 to "There\u2019s nothing to show here yet.",
        18 to "Your shows",
        19 to "Search episodes",
        20 to "Couldn\u2019t sync your YouTube Music library",
        21 to "Couldn\u2019t load this page",
        22 to "Lead Developer",
        23 to "LICENSE",
        24 to "Unknown license",
        25 to "Developer | Team",
        26 to "Eh?",
        27 to "Base Framework | Metrolist",
        28 to "dummy reze | Admin",
        29 to "Creator of InnerTune \u00b7 Foundation for Metrolist, ArchiveTune, and other forks",
        30 to "Respecter",
        31 to "Account",
        32 to "Discord, Last.fm, Libre.fm, ListenBrainz",
        33 to "Backup",
        34 to "Download",
        35 to "Like",
        36 to "Log in",
        37 to "Log out",
        38 to "Remove like",
        39 to "Restore",
        40 to "Shuffle off",
        41 to "Shuffle on",
        42 to "Activity Status",
        43 to "Add",
        44 to "Add another account",
        45 to "Add anyway",
        46 to "Add current song",
        47 to "Add image",
        48 to "Add symbol",
        49 to "Add Tag",
        50 to "Add to library",
        51 to "Add to %1\$d",
        52 to "Add to playlist",
        53 to "Add to queue",
        54 to "Added %1\$d songs to %2\$d playlists",
        55 to "Added %1\$d songs to %2\$s",
        56 to "Added to %d playlists",
        57 to "Added to %s",
        58 to "Adjust corner radius",
        59 to "Login with token",
        60 to "API connected",
        61 to "API key",
        62 to "Configured",
        63 to "Required before AI features can run.",
        64 to "API failed. Test again after updating settings.",
        65 to "API ready",
        66 to "Not tested",
        67 to "API test failed",
        68 to "Testing connection\u2026",
        69 to "AI content filter",
        70 to "Hide AI-generated content",
        71 to "Filter songs, videos, albums, artists, and playlists from high-confidence AI channels in Home and Search",
        72 to "High confidence: %1\$d \u00b7 Moderate confidence: %2\$d",
        73 to "Include moderate-confidence channels",
        74 to "Also hide channels that are likely, but not confirmed, to use AI-generated content",
        75 to "About AiSList",
        76 to "Community-maintained channel data from AiSlopList.com",
        77 to "Update channel lists",
        78 to "Couldn\u2019t update AI channel lists. The previous lists will remain active.",
        79 to "AI channel lists updated",
        80 to "Custom endpoint",
        81 to "Custom translation prompt",
        82 to "Appended to the built-in lyrics translation instructions.",
        83 to "Fetch models",
        84 to "AI Integration",
        85 to "Configure AI translation and personalized user automates.",
        86 to "Model",
        87 to "API key required to load models",
        88 to "Failed to fetch available models",
        89 to "Tap refresh to load available models",
        90 to "Fetching available models\u2026",
        91 to "No models match your search",
        92 to "Not selected",
        93 to "Search models",
        94 to "AI provider",
        95 to "Choose the AI service.",
        96 to "Gemini",
        97 to "None (Disabled)",
        98 to "OpenAI",
        99 to "OpenRouter",
        100 to "Provider",
        101 to "Test API",
        102 to "AI Translation",
        103 to "Translation",
        104 to "Backdrop blur",
        105 to "Show artwork as blurred backdrop on the player",
        106 to "Album cover",
        107 to "Album name",
        108 to "Album not found",
        109 to "The requested album could not be loaded",
        110 to "Albums",
        111 to "All Artists",
        112 to "All Songs",
        113 to "All time",
        114 to "Allow",
        115 to "Note: This allows for syncing with YouTube Music. This is NOT changeable later.",
        116 to "Already in playlist:",
        117 to "Mixes and radios",
        118 to "%1\$s - %2\$s",
        119 to "Sort playlist",
        120 to "Suggested songs",
        121 to "Monochrome",
        122 to "Theme",
        123 to "Center",
        124 to "End",
        125 to "Start",
        126 to "Adaptive artwork",
        127 to "Adaptive frosted",
        128 to "Ambient glow",
        129 to "Frosted wallpaper",
        130 to "Pure black",
        131 to "Soft radial",
        132 to "Tonal edge",
        133 to "%d%%",
        134 to "Bold digital",
        135 to "Elegant thin",
        136 to "Minimal",
        137 to "Pixel stacked",
        138 to "Filled",
        139 to "Minimal",
        140 to "Tonal",
        141 to "Accent style",
        142 to "Ambient Brightness",
        143 to "Ambient intensity",
        144 to "Artwork glow",
        145 to "Auto-Dimming Low Power Mode",
        146 to "Lowers screen opacity after 10 seconds of inactivity",
        147 to "Auto-Lock on AOD Entry",
        148 to "Auto-Lock Delay",
        149 to "%ds",
        150 to "Automatically lock screen after a delay when entering AOD",
        151 to "Display AOD when screen turns off",
        152 to "Automatically show AOD ambient screen when screen turns off during playback",
        153 to "Background style",
        154 to "Clock Style",
        155 to "Content position",
        156 to "Control size",
        157 to "Control style",
        158 to "Controls",
        159 to "%1\$d\u00b0",
        160 to "%1\$d dp",
        161 to "Customize the always-on player screen",
        162 to "Gesture Controls",
        163 to "Double-tap to play/pause, swipe left/right to skip tracks",
        164 to "Horizontal padding",
        165 to "Layout",
        166 to "Marquee Song Titles",
        167 to "Scroll long song titles instead of truncating",
        168 to "Minimal Locked View",
        169 to "When locked, show only clock and song title \u2014 hides artwork and controls",
        170 to "Enable AOD mode",
        171 to "Allow ArchiveTune to show the always-on player screen",
        172 to "%1\$d%%",
        173 to "OLED Burn-in Protection",
        174 to "Periodically shifts display offset every 60 seconds",
        175 to "Live preview",
        176 to "Pocket & Face-Down Blackout",
        177 to "Turn off screen when proximity sensor detects pocket or face-down placement",
        178 to "Always On Sessions",
        179 to "moriee Ensemble",
        180 to "3:48",
        181 to "1:24",
        182 to "Midnight Archive",
        183 to "Scale and spacing",
        184 to "To activate AOD automatically while charging or docked, go to Android Settings > Display > Screen saver and select ArchiveTune.",
        185 to "System Screen Saver (Charging AOD)",
        186 to "Security & Power",
        187 to "Shake to Unlock",
        188 to "Shake your phone to exit touch-lock mode",
        189 to "Shape rotation",
        190 to "Show album",
        191 to "Show artist",
        192 to "Show Battery Status",
        193 to "Show Digital Clock",
        194 to "Show controls",
        195 to "Show exit button",
        196 to "Show lyric ticker",
        197 to "Show progress",
        198 to "Show thumbnail",
        199 to "Show time labels",
        200 to "Smart Lock & Display",
        201 to "Shape, layout, controls, and ambient styling",
        202 to "Text alignment",
        203 to "Thumbnail shape",
        204 to "Uses Shapes for the AOD artwork mask.",
        205 to "Thumbnail size",
        206 to "AOD customization",
        207 to "Title max lines",
        208 to "Touch Lock Enabled",
        209 to "Prevents accidental touches on AOD screen",
        210 to "True Ambient Always-On",
        211 to "Show minimal ambient artwork and clock when phone is untouched",
        212 to "Vertical spacing",
        213 to "Visibility",
        214 to "Hold for 1.5s to unlock",
        215 to "AOD Mode",
        216 to "Bottom",
        217 to "Center",
        218 to "Top",
        219 to "Arch",
        220 to "Circle",
        221 to "Clover",
        222 to "Cookie 6",
        223 to "Cookie 9",
        224 to "Diamond",
        225 to "Flower",
        226 to "Ghostish",
        227 to "Heart",
        228 to "Pentagon",
        229 to "Pill",
        230 to "Pixel circle",
        231 to "Rounded",
        232 to "Slanted",
        233 to "Soft burst",
        234 to "Square",
        235 to "Sunny",
        236 to "Triangle",
        237 to "Slide to Lock >>>",
        238 to "Slide to Unlock >>>",
        239 to "App icon",
        240 to "Available icons",
        241 to "Built in",
        242 to "Original ArchiveTune icon",
        243 to "Couldn't change the app icon",
        244 to "Community icon",
        245 to "Community icons are created by users and may change over time.",
        246 to "Current icon",
        247 to "Default",
        248 to "Choose the launcher icon",
        249 to "No app icons are available",
        250 to "ID %1\$s",
        251 to "Couldn't load app icons",
        252 to "Personalize your launcher",
        253 to "App language",
        254 to "ArchiveTune",
        255 to "Appearance",
        256 to "ArchiveTune Canvas",
        257 to "Animate album artwork while playing",
        258 to "Arrange library chips",
        259 to "Choose the order of tabs shown in your library",
        260 to "Arrange playlist tags",
        261 to "Choose the order of tag filters shown in your library",
        262 to "Artist name",
        263 to "Symbols to split artists",
        264 to "Artist",
        265 to "Artists",
        266 to "Assign Tags",
        267 to "Assign to playlists",
        268 to "Overlap the next song while the current song fades out.",
        269 to "Crossfade duration",
        270 to "%1\$s s",
        271 to "Crossfade",
        272 to "Audio normalization",
        273 to "Audio offload",
        274 to "Let supported devices play audio using low-power hardware decoding. Some audio processing features are disabled.",
        275 to "Audio quality",
        276 to "Auto",
        277 to "High",
        278 to "Low",
        279 to "Max (beta)",
        280 to "Auto download on like",
        281 to "Automatically download songs when you like them",
        282 to "Auto skip to next song when error occurs",
        283 to "Ensure your continuous playback experience",
        284 to "Auto-start on Bluetooth connect",
        285 to "Automatically resume playback when a Bluetooth audio device connects",
        286 to "Back",
        287 to "Backdrop blur amount",
        288 to "%1\$d%%",
        289 to "Account Details",
        290 to "YouTube, Spotify, Last.fm, Libre.fm, Discord & proxy credentials",
        291 to "Re-download offline songs",
        292 to "Will be downloaded again on restore",
        293 to "Library Data",
        294 to "Playlists, songs, history & artists",
        295 to "App Settings",
        296 to "Appearance, playback & preferences",
        297 to "Export library, settings, and account details.",
        298 to "Couldn't create backup",
        299 to "Backup created successfully",
        300 to "Backup in progress",
        301 to "What to back up?",
        302 to "Backup and restore",
        303 to "Preparing database",
        304 to "Copying %1\$s",
        305 to "Backing up settings",
        306 to "Bitrate",
        307 to "Bitrate",
        308 to "Block artist",
        309 to "Blur",
        310 to "Blur Gradient",
        311 to "Blur intensity",
        312 to "%1\$d dp",
        313 to "Brightness",
        314 to "Buffer Health",
        315 to "Cache",
        316 to "Cached",
        317 to "Cached",
        318 to "Cancel",
        319 to "Cancel",
        320 to "Apple Music",
        321 to "BetterLyrics",
        322 to "Canvas Cache",
        323 to "Videos play offline. Oldest videos are removed when the cache is full.",
        324 to "Use canvas",
        325 to "Available",
        326 to "Checking\u2026",
        327 to "Canvas is off",
        328 to "Paused by low data mode",
        329 to "Not checked",
        330 to "Not selected",
        331 to "Offline",
        332 to "Unavailable",
        333 to "Waiting for Wi-Fi",
        334 to "Provider health",
        335 to "Couldn't refresh animated canvas",
        336 to "Could not load canvas settings",
        337 to "Sources, mobile data and cache",
        338 to "Could not update canvas settings",
        339 to "Canvas source",
        340 to "All",
        341 to "Try BetterLyrics, Apple Music, TIDAL, then Spotify",
        342 to "Spotify",
        343 to "Uses your connected Spotify account",
        344 to "TIDAL",
        345 to "Use Wi-Fi only",
        346 to "Turn off to allow mobile data. Downloaded canvases remain available offline.",
        347 to "Change playlist cover",
        348 to "Change source",
        349 to "Replace this playlist entry from Local or YouTube Music.",
        350 to "Changelog",
        351 to "Artifact",
        352 to "Charts",
        353 to "Check for Update",
        354 to "Choose Color",
        355 to "Clear",
        356 to "Clear all downloads",
        357 to "Clear canvas cache",
        358 to "Are you sure you want to clear all cached canvas?",
        359 to "  Are you sure you want to clear all downloads?",
        360 to "Clear image cache",
        361 to "  Are you sure you want to clear all cached image?",
        362 to "Clear listen history",
        363 to "Are you sure you want to clear all listen history?",
        364 to "Clear lyrics cache",
        365 to "Are you sure you want to clear all lyrics cache?",
        366 to "Clear search history",
        367 to "Are you sure you want to clear all search history?",
        368 to "Clear selection",
        369 to "Clear song cache",
        370 to "  Are you sure you want to clear all cached songs?",
        371 to "Close",
        372 to "Close",
        373 to "Codec",
        374 to "Codecs",
        375 to "Color Palette",
        376 to "Coloring",
        377 to "Connecting",
        378 to "Content",
        379 to "Default content country",
        380 to "Default content language",
        381 to "Content Length",
        382 to "Contexts (comma-separated)",
        383 to "Continuous",
        384 to "Contrast",
        385 to "Copied to clipboard",
        386 to "Copied log to clipboard",
        387 to "Copy",
        388 to "Copy link",
        389 to "Copy log entry",
        390 to "Corner radius: %1\$d",
        391 to "Create playlist",
        392 to "Crop thumbnails to 1:1",
        393 to "Display YouTube thumbnails in square format instead of 16:9",
        394 to "Do not crossfade consecutive songs from the same album.",
        395 to "Skip gapless albums",
        396 to "Current Version",
        397 to "Custom",
        398 to "Adjustments",
        399 to "Adjust image in both previews.",
        400 to "%1\$d dp",
        401 to "The previous image access could not be released.",
        402 to "ArchiveTune could not keep access to this image.",
        403 to "Choose an image to see a live preview.",
        404 to "Lyrics",
        405 to "Player",
        406 to "Remove image",
        407 to "Replace image",
        408 to "%1\$d%%",
        409 to "Preview and adjust the player and lyrics background",
        410 to "Custom font",
        411 to "Pick a .ttf font",
        412 to "Pick a .ttf font file",
        413 to "Custom Large Text",
        414 to "Custom order",
        415 to "Customize thumbnail corner radius",
        416 to "Custom Theme",
        417 to "Custom value",
        418 to "Customize background",
        419 to "Customize colors",
        420 to "Choose your app theme colors",
        421 to "Customized background",
        422 to "Dark theme",
        423 to "Follow system",
        424 to "Off",
        425 to "On",
        426 to "Fri",
        427 to "Mon",
        428 to "Sat",
        429 to "Sun",
        430 to "Thu",
        431 to "Tue",
        432 to "Wed",
        433 to "Debug Logs",
        434 to "Change default library chip",
        435 to "Open supported links",
        436 to "Default open tab",
        437 to "Default",
        438 to "Delete",
        439 to "Do you really want to delete the playlist \"%s\"?",
        440 to "Description",
        441 to "Show current audio codec information on the player",
        442 to "Manually refresh Discord Rich Presence",
        443 to "Display real-time playback statistics (codec, bitrate, buffer)",
        444 to "Details",
        445 to "Increase volume from 0",
        446 to "Disabled",
        447 to "Playback paused because device volume is 0. Raise volume to resume.",
        448 to "Disable",
        449 to "Disable animations",
        450 to "Disable most app animations. Recommended for low-end devices",
        451 to "Disable blur effects",
        452 to "Disable blur effects throughout the app",
        453 to "Disable screenshot",
        454 to "When this option is on, screenshots and the app's view in Recents are disabled.",
        455 to "Discord",
        456 to "ArchiveTune is ready to publish Rich Presence for your listening session.",
        457 to "Button 1 label",
        458 to "Button 1 Custom URL",
        459 to "Button 2 label",
        460 to "Button 2 Custom URL",
        461 to "Button 1 URL Source",
        462 to "Button 2 URL Source",
        463 to "Activity Content",
        464 to "Activity details",
        465 to "Activity name",
        466 to "Activity state",
        467 to "Activity type",
        468 to "Competing",
        469 to "Listening",
        470 to "Playing",
        471 to "Streaming",
        472 to "Watching",
        473 to "Discord authorization failed",
        474 to "Discord account connected",
        475 to "Button Options",
        476 to "Connection",
        477 to "Album artwork",
        478 to "Artist artwork",
        479 to "Image Options",
        480 to "Discord Integration",
        481 to "Connect your Discord account with OAuth so ArchiveTune can publish Rich Presence.",
        482 to "Open Discord authorization",
        483 to "Paused",
        484 to "Do Not Disturb",
        485 to "Idle",
        486 to "Online",
        487 to "Streaming",
        488 to "Reauthorize",
        489 to "Rich Presence cannot be shown until you authorize Discord again.",
        490 to "Discord session expired",
        491 to "Discord presence refresh failed",
        492 to "Discord presence refreshed",
        493 to "Show RPC when paused",
        494 to "If enabled, Rich Presence will remain visible while paused with a pause icon. If disabled, RPC will disappear when paused.",
        495 to "Album URL",
        496 to "Artist URL",
        497 to "Custom URL",
        498 to "Song URL",
        499 to "Waiting for Discord authorization...",
        500 to "Dislike all",
        501 to "Dislikes",
        502 to "Dismiss",
        503 to "Display",
        504 to "Display Codec on Player",
        505 to "Custom DNS DoH URL",
        506 to "DNS over HTTPS",
        507 to "Use DNS over HTTPS (DoH) to resolve hostnames",
        508 to "DNS Provider",
        509 to "Dont Show",
        510 to "Download",
        511 to "Couldn\u2019t update the download",
        512 to "Download complete",
        513 to "Download failed",
        514 to "In progress",
        515 to "%1\$d%%",
        516 to "%1\$d%% \u00b7 %2\$s/s",
        517 to "%1\$s/s",
        518 to "Downloaded",
        519 to "Downloaded songs",
        520 to "Downloading",
        521 to "Downloads",
        522 to "Couldn\u2019t load downloads",
        523 to "Duplicates",
        524 to "%d songs are already in your playlist",
        525 to "The song is already in your playlist",
        526 to "%1\$ds",
        527 to "Duration",
        528 to "Edit",
        529 to "Edit ListenBrainz token",
        530 to "Edit playlist",
        531 to "Edit song",
        532 to "Edit Tag",
        533 to "Empty Album",
        534 to "This album doesn't contain any songs",
        535 to "Empty Playlist",
        536 to "This playlist doesn't contain any songs",
        537 to "Enable BetterLyrics",
        538 to "Enable BetterLyrics Portato",
        539 to "Enable debug settings lines",
        540 to "Enable Rich Presence",
        541 to "Enable dynamic theme",
        542 to "Enable KuGou lyrics provider",
        543 to "Enable LeakCanary",
        544 to "Detect memory leaks and show leak reports while the app is running.",
        545 to "Enable LrcLib lyrics provider",
        546 to "Enable Megalobiz lyrics",
        547 to "Enable Paxsenix lyrics",
        548 to "Enable proxy",
        549 to "Enable Scrobbling",
        550 to "Enable SimpMusic lyrics",
        551 to "Enable swipe to change song",
        552 to "Enable Translator",
        553 to "Translate selected fields before sending to Discord RPC",
        554 to "Enable Unison lyrics",
        555 to "Enable Update Notification",
        556 to "Get notified when a new release is available on the selected channel",
        557 to "Enable YouLyPlus lyrics",
        558 to "End of song",
        559 to "Enter symbol",
        560 to "EP",
        561 to "Episodes",
        562 to "Advanced",
        563 to "Precise bands, gain staging, effects, and profiles",
        564 to "Automatic headroom",
        565 to "Offsets the highest boost to reduce digital clipping",
        566 to "Bands",
        567 to "Tune every frequency band exposed by this device",
        568 to "Basic",
        569 to "Quick presets and broad tone shaping",
        570 to "Bass",
        571 to "Bass boost",
        572 to "Strengthen low-frequency impact",
        573 to "Close",
        574 to "Control mode",
        575 to "Custom profile",
        576 to "%1\$+.1f dB",
        577 to "Enhancements",
        578 to "Add low-frequency impact and spatial width",
        579 to "Applies these controls to ArchiveTune playback",
        580 to "Profile exported",
        581 to "Flat",
        582 to "%1\$d Hz",
        583 to "%1\$.1f kHz",
        584 to "Import",
        585 to "Invalid profile data",
        586 to "Imported %1\$d profiles",
        587 to "Imported",
        588 to "Manage",
        589 to "Midrange",
        590 to "Open system equalizer",
        591 to "Output gain",
        592 to "Trim or amplify the final equalizer output",
        593 to "%1\$d%%",
        594 to "Preset %1\$d",
        595 to "Presets",
        596 to "Start from a device-tuned sound",
        597 to "Profile name",
        598 to "Profile saved",
        599 to "Profiles",
        600 to "Keep, import, and share complete configurations",
        601 to "Save profile",
        602 to "Shape playback for your ears and equipment",
        603 to "Signal",
        604 to "Control output level and clipping protection",
        605 to "Sound shaping is off",
        606 to "Sound shaping is on",
        607 to "Tone",
        608 to "Balance the low, middle, and high frequencies",
        609 to "Treble",
        610 to "Virtualizer",
        611 to "Widen the perceived stereo field",
        612 to "Waiting for audio session",
        613 to "Equalizer",
        614 to "Error loading changelog",
        615 to "Source error",
        616 to "No network connection",
        617 to "No stream available",
        618 to "Timeout",
        619 to "Unknown error",
        620 to "Experimental Settings",
        621 to "Experimental Features",
        622 to "Explore",
        623 to "Export",
        624 to "Unable to export logs",
        625 to "Export playlist as CSV",
        626 to "Choose a playlist and save its songs as a CSV file",
        627 to "No non-empty playlists are available",
        628 to "Unable to export playlist",
        629 to "Unable to export playlist. Tap to try again",
        630 to "Exporting playlist",
        631 to "Unable to load playlists. Tap to retry",
        632 to "Loading playlists",
        633 to "Choose a playlist",
        634 to "Playlist exported as CSV",
        635 to "Writing CSV file",
        636 to "Export Theme",
        637 to "External Downloader",
        638 to "Download songs through an external app by package name",
        639 to "No external downloader configured. Set one in Settings \u00e2\u2020\u2019 Player.",
        640 to "External downloader app is not installed",
        641 to "Downloader App Package",
        642 to "Package name or app name of the external downloader (e.g. com.deniscerri.ytdl or YTDLnis)",
        643 to "External Service",
        644 to "FEATURED ALBUM",
        645 to "File size",
        646 to "Albums",
        647 to "All",
        648 to "All",
        649 to "Artists",
        650 to "Community playlists",
        651 to "Downloaded",
        652 to "Featured playlists",
        653 to "Library",
        654 to "Liked",
        655 to "Playlists",
        656 to "Songs",
        657 to "Videos",
        658 to "Follow theme",
        659 to "Font",
        660 to "Custom",
        661 to "Default",
        662 to "Choose the app font source",
        663 to "System",
        664 to "Force high refresh rate",
        665 to "Force Sync on Switch Account",
        666 to "Re-sync playlists, liked songs, artists, and albums from the selected account after switching",
        667 to "Forgotten favorites",
        668 to "Connection blocked by ArchiveTune Remote. This app could not be verified as an official ArchiveTune build. Install an official build from https://github.com/rukamori/ArchiveTune or https://t.me/ArchiveTuneGC.",
        669 to "General",
        670 to "Generating image",
        671 to "Glow",
        672 to "Got it",
        673 to "Gradient",
        674 to "Grid View",
        675 to "Vibration",
        676 to "Enable haptic feedback on interactive elements",
        677 to "Hidden playlists",
        678 to "Playlists hidden from library appear here",
        679 to "Hide explicit content",
        680 to "Hide Player Thumbnail",
        681 to "Replace album artwork with app logo in player",
        682 to "Hide playlist",
        683 to "Hide \\u0022%1\$s\\u0022 from library?",
        684 to "Hide music videos",
        685 to "History",
        686 to "History duration",
        687 to "Minimum playback time to count a song as listened",
        688 to "%1\$s s",
        689 to "Songs you play on this device will show up here.",
        690 to "No local history yet",
        691 to "Played on this device",
        692 to "Try a different song or artist name.",
        693 to "No matching songs",
        694 to "Your synced watch history will appear here after you listen on YouTube Music.",
        695 to "No remote history available",
        696 to "Try again in a moment.",
        697 to "Couldn\u2019t load remote history",
        698 to "Syncing remote history",
        699 to "Synced from YouTube Music",
        700 to "Home",
        701 to "Image Cache",
        702 to "Cancel edit",
        703 to "Confirm & Save (%1\$d/%2\$d)",
        704 to "Import a \"csv\" playlists",
        705 to "CSV playlist file",
        706 to "Edit match",
        707 to "Import failed",
        708 to "All",
        709 to "Matched",
        710 to "Unresolved",
        711 to "Include",
        712 to "M3U audio playlist",
        713 to "Matched to: %1\$s \u2014 %2\$s",
        714 to "Matching: %1\$d/%2\$d",
        715 to "No matching songs found.",
        716 to "Import a \"m3u\" playlists",
        717 to "Import playlist",
        718 to "Preparing import\u2026",
        719 to "Local First",
        720 to "Search the local library first, then YouTube Music when no match is found.",
        721 to "Choose where imported songs are matched.",
        722 to "Import Source Priority",
        723 to "YouTube Music Only",
        724 to "Skip local library matching and search YouTube Music directly.",
        725 to "%1\$d skipped",
        726 to "%1\$d local \u00b7 %2\$d YouTube Music \u00b7 %3\$d unresolved",
        727 to "Import Review",
        728 to "Saving import\u2026",
        729 to "Saving: %1\$d/%2\$d",
        730 to "Search Local",
        731 to "Search title and artist",
        732 to "Search YouTube",
        733 to "Skip",
        734 to "Local Library",
        735 to "Not Found",
        736 to "YouTube Music",
        737 to "Import Theme",
        738 to "Information",
        739 to "Instant playback",
        740 to "Integration",
        741 to "Internal Service",
        742 to "Internet",
        743 to "DNS over HTTPS only works if your country blocks YouTube. If YouTube actively blocks your region, consider using a Proxy or VPN.",
        744 to "Please only use Proxies that you are sure are safe. Free Proxies are convenient but not always safe, so be careful. You have been warned, and we are not responsible for your security.",
        745 to "Security & Usage Warning",
        746 to "Invalid code",
        747 to "Invalid link",
        748 to "Join",
        749 to "Join session",
        750 to "Joined",
        751 to "Jump to latest log",
        752 to "Keep listening",
        753 to "Language",
        754 to "Large Image",
        755 to "Large image custom URL",
        756 to "Large Text",
        757 to "Last End",
        758 to "Based on last song listened",
        759 to "Last Start",
        760 to "Last week",
        761 to "API credentials",
        762 to "Using custom credentials",
        763 to "Using default credentials",
        764 to "Leave credentials blank for compatible services that accept arbitrary API keys and shared secrets.",
        765 to "API key",
        766 to "Custom endpoint",
        767 to "Enter a valid HTTP or HTTPS endpoint.",
        768 to "Last.fm / Libre.fm Integration",
        769 to "API key suspended.",
        770 to "Authentication failed. Try again.",
        771 to "Login failed. Try again.",
        772 to "Invalid API key.",
        773 to "Invalid username or password.",
        774 to "Enter username and password.",
        775 to "Network error. Check your connection.",
        776 to "Update Now Playing",
        777 to "Custom",
        778 to "Last.fm",
        779 to "Libre.fm",
        780 to "Shared secret",
        781 to "Scrobbling service",
        782 to "Configure the scrobbling service before logging in.",
        783 to "Service provider",
        784 to "Later",
        785 to "Latest Release",
        786 to "Latest: %s",
        787 to "Least tracks",
        788 to "Leave",
        789 to "AI integration is required before ArchiveTune can build personal top mixes.",
        790 to "Configure AI to build mixes",
        791 to "Configure AI",
        792 to "Failed to build top mixes",
        793 to "Preparing your AI mixes\u2026",
        794 to "Listen to more songs, then refresh to build AI mixes from your recent history.",
        795 to "No recent listening mix yet",
        796 to "AI did not return any playable mixes from your recent history.",
        797 to "Refresh mixes",
        798 to "Like all",
        799 to "Liked",
        800 to "Liked songs",
        801 to "Likes",
        802 to "Link copied to clipboard",
        803 to "List View",
        804 to "Listen history",
        805 to "ListenBrainz scrobbling",
        806 to "Enable submitting now-playing and finished listens to ListenBrainz",
        807 to "Loading",
        808 to "Loading format",
        809 to "Local Files",
        810 to "Local",
        811 to "Open settings from the top bar and run a device scan to find offline audio on this device.",
        812 to "No local songs found",
        813 to "Latest scan",
        814 to "Try a different song, artist, or album name.",
        815 to "No matching local songs",
        816 to "Allow storage access to scan audio files stored on this device.",
        817 to "Play local songs on this device.",
        818 to "Skip songs shorter than the selected duration.",
        819 to "Exclude short songs",
        820 to "Couldn\u2019t finish scanning this device.",
        821 to "Changes apply the next time you scan this device.",
        822 to "Scan filters",
        823 to "Add folder",
        824 to "Skip songs stored in folders that match any of these paths.",
        825 to "No folders excluded yet.",
        826 to "Excluded folders",
        827 to "Include folder",
        828 to "Scan only songs stored in folders that match any of these paths.",
        829 to "All folders are included.",
        830 to "Included folders",
        831 to "Refresh songs stored on this device and update the local library metadata.",
        832 to "Last scan: %1\$d songs found, %2\$d removed",
        833 to "Scan local songs",
        834 to "Debug",
        835 to "Error",
        836 to "Info",
        837 to "Verbose",
        838 to "Warning",
        839 to "Logging in",
        840 to "Login",
        841 to "Logged in successfully",
        842 to "Are you sure you want to log out of Discord?.",
        843 to "Cancel",
        844 to "Confirm logout",
        845 to "Log out",
        846 to "Logs will appear here when available",
        847 to "Longest duration",
        848 to "Loudness",
        849 to "Reduces mobile data usage by using low-quality streams and disabling playback cache and canvas on metered networks",
        850 to "Low Data Mode",
        851 to "Lyrics",
        852 to "Lyrics animation style",
        853 to "Available only in V2 lyrics mode",
        854 to "Auto scroll lyrics",
        855 to "Default",
        856 to "Lyrics background style",
        857 to "Change lyrics on click",
        858 to "Blur lyrics lines",
        859 to "Lyrics line spacing",
        860 to "Lyrics mode",
        861 to "Enhanced",
        862 to "V2 Legacy",
        863 to "Lyrics not found",
        864 to "Romanize chinese lyrics",
        865 to "Romanize hindi lyrics",
        866 to "Romanize japanese lyrics",
        867 to "Romanize korean lyrics",
        868 to "Romanize other non-latin lyrics",
        869 to "Plain",
        870 to "%1\$d lines, %2\$d chars",
        871 to "%1\$d results",
        872 to "Still searching",
        873 to "Searching providers",
        874 to "Background blur",
        875 to "%1\$d px",
        876 to "Background dim",
        877 to "%1\$d%%",
        878 to "Failed to create image: %1\$s",
        879 to "Image sharing requires Android 6.0 or newer",
        880 to "Layout",
        881 to "Portrait",
        882 to "Square",
        883 to "Story",
        884 to "%1\$d x %2\$d",
        885 to "Show album cover",
        886 to "Include the artwork in the header of the exported image.",
        887 to "Album tint",
        888 to "Clear glass",
        889 to "Deep blur",
        890 to "Frosted dark",
        891 to "Frosted light",
        892 to "Vivid glow",
        893 to "Lyrics sync offset",
        894 to "Synced",
        895 to "Lyrics text size",
        896 to "Word Sync",
        897 to "Playlist Tags",
        898 to "Create and manage tags for organizing playlists",
        899 to "Manage Tags",
        900 to "Max cache size",
        901 to "Max image cache size",
        902 to "Max selection limit",
        903 to "Max song cache size",
        904 to "Max supported: %1\$d Hz",
        905 to "Maximum Volume",
        906 to "Media id",
        907 to "Media ID",
        908 to "No information available",
        909 to "Itag",
        910 to "Couldn\u2019t load this information",
        911 to "MIME type",
        912 to "Mini player background style",
        913 to "Minimum Volume",
        914 to "Misc",
        915 to "Monthly listeners",
        916 to "Months",
        917 to "Mood & Genres",
        918 to "more",
        919 to "More content",
        920 to "More",
        921 to "More options",
        922 to "More Playlists",
        923 to "MOST PLAYED",
        924 to "Most played songs",
        925 to "Most played",
        926 to "Most tracks",
        927 to "Music Player",
        928 to "Music Recognition",
        929 to "When enabled, the Quick Settings tile recognizes audio playing on this device without opening ArchiveTune.",
        930 to "Background recognition is unavailable in the FOSS variant. The Quick Settings tile opens the recognition screen instead.",
        931 to "Recognition in background",
        932 to "Something went wrong",
        933 to "Recognition history",
        934 to "Matched songs will appear here after recognition succeeds.",
        935 to "No recognized songs yet",
        936 to "Try another song, artist, album, or code.",
        937 to "No history matches",
        938 to "Recognized %1\$s",
        939 to "Search recognized songs",
        940 to "Listen again",
        941 to "Listening\u2026",
        942 to "Lyrics preview",
        943 to "No match found",
        944 to "Album: %1\$s",
        945 to "Artist: %1\$s",
        946 to "Music recognition progress and results",
        947 to "Music recognition",
        948 to "Genre: %1\$s",
        949 to "ISRC: %1\$s",
        950 to "Label: %1\$s",
        951 to "Capturing audio playing on this device",
        952 to "Listening for music",
        953 to "Keep the music playing clearly, then try recognition again.",
        954 to "No song found",
        955 to "Matching the captured audio fingerprint",
        956 to "Processing audio",
        957 to "The recognition service could not identify this audio. Try again shortly.",
        958 to "The playing app may block audio capture, or playback may have stopped.",
        959 to "Couldn\u2019t capture device audio",
        960 to "Released: %1\$s",
        961 to "The captured audio did not contain enough music to identify.",
        962 to "LISTENING",
        963 to "PROCESSING",
        964 to "RESULT",
        965 to "Open Shazam",
        966 to "Allow",
        967 to "Allow microphone access to recognize nearby music.",
        968 to "Microphone permission",
        969 to "Processing\u2026",
        970 to "Recognition failed",
        971 to "Music recognition settings",
        972 to "Couldn\u2019t generate a signature",
        973 to "Tap to listen",
        974 to "ArchiveTune Music Together",
        975 to "My top",
        976 to "Nerd Stats",
        977 to "Network unavailable",
        978 to "New release albums",
        979 to "New releases",
        980 to "New update available",
        981 to "New version available",
        982 to "Newest first",
        983 to "Newest year",
        984 to "News From Developers",
        985 to "%1\$s \u00b7 %2\$s",
        986 to "No announcements at the moment. Check back soon.",
        987 to "Nothing here yet",
        988 to "Check your internet connection and try again.",
        989 to "Couldn't load news",
        990 to "Important",
        991 to "Loading news\u2026",
        992 to "Try a different search term.",
        993 to "No matching articles",
        994 to "Retry",
        995 to "Search news\u2026",
        996 to "Search results",
        997 to "You have unread announcements from developers.",
        998 to "New Announcements",
        999 to "Next",
        1000 to "No Artist Yet",
        1001 to "No downloaded music yet",
        1002 to "No downloads in progress",
        1003 to "No hidden playlists",
        1004 to "No listening data for this year",
        1005 to "No Logs",
        1006 to "No matching downloads",
        1007 to "No matching playlists",
        1008 to "No playlists yet",
        1009 to "No releases found",
        1010 to "No releases found",
        1011 to "No results found",
        1012 to "No saved accounts yet",
        1013 to "No tags available. Create one first.",
        1014 to "No title",
        1015 to "No track playing",
        1016 to "Not allowed",
        1017 to "Not logged in",
        1018 to "Not logged in to YouTube",
        1019 to "Now Playing",
        1020 to "Numbers",
        1021 to "Downloaded",
        1022 to "Offline",
        1023 to "OK",
        1024 to "OK",
        1025 to "Oldest first",
        1026 to "Oldest year",
        1027 to "On device",
        1028 to "Join Discord",
        1029 to "Support ongoing development.",
        1030 to "Star the repository and follow releases.",
        1031 to "Follow development, report issues, or support ArchiveTune.",
        1032 to "Chat with the community and get updates.",
        1033 to "Join Telegram",
        1034 to "Stay connected",
        1035 to "Continue to ArchiveTune.",
        1036 to "Setup unavailable",
        1037 to "Couldn't load setup",
        1038 to "Start listening",
        1039 to "FOSS edition",
        1040 to "GMS edition",
        1041 to "Your account helps ArchiveTune",
        1042 to "Continue your listening journey across devices with synced history.",
        1043 to "Keep your history",
        1044 to "Keep your saved music and playlists available wherever you listen.",
        1045 to "Sync your library",
        1046 to "Optional. You can log in later from Settings.",
        1047 to "Use your account context for a more dependable playback experience.",
        1048 to "Better playback",
        1049 to "Skip for now",
        1050 to "Log in to sync your library and history across devices and get more reliable playback.",
        1051 to "Sync your listening",
        1052 to "Allowed by install",
        1053 to "Install downloaded APK updates from ArchiveTune.",
        1054 to "App installation",
        1055 to "Adjust playback audio behavior and provide light touch feedback.",
        1056 to "Audio settings and vibration",
        1057 to "Connect to nearby Bluetooth audio devices for playback.",
        1058 to "Bluetooth audio connection",
        1059 to "Discover Cast and nearby playback devices.",
        1060 to "Bluetooth scan",
        1061 to "Recognize music playing in other apps without using the microphone. Android asks for screen and audio capture approval each time, ArchiveTune processes audio only.",
        1062 to "On-device audio recognition",
        1063 to "Stream music, load artwork, and check online app content.",
        1064 to "Network access",
        1065 to "Show playback controls and music activity in the notification shade.",
        1066 to "Notifications",
        1067 to "Keep music playing reliably when ArchiveTune is in the background.",
        1068 to "Background playback",
        1069 to "Unavailable",
        1070 to "Grant only what you want now. You can continue and allow permissions later.",
        1071 to "Review permissions",
        1072 to "Version %1\$s",
        1073 to "Set up playback, local music, and update permissions before you start listening.",
        1074 to "Welcome to ArchiveTune",
        1075 to "Couldn't open app settings",
        1076 to "Open supported link by default",
        1077 to "Open with Downloader",
        1078 to "Options",
        1079 to "Options",
        1080 to "Other versions",
        1081 to "Amethyst",
        1082 to "Arctic",
        1083 to "Aurora",
        1084 to "Autumn",
        1085 to "Blush",
        1086 to "Bubblegum",
        1087 to "Candy",
        1088 to "Charcoal",
        1089 to "Sakura",
        1090 to "Clay",
        1091 to "Cobalt",
        1092 to "Coffee",
        1093 to "Coral",
        1094 to "Crimson",
        1095 to "Custom",
        1096 to "Cyberpunk",
        1097 to "Default",
        1098 to "Electric",
        1099 to "Emerald",
        1100 to "Deep Forest",
        1101 to "Forest",
        1102 to "Golden",
        1103 to "Grape",
        1104 to "Graphite",
        1105 to "Hot Pink",
        1106 to "Lavender",
        1107 to "Magenta",
        1108 to "Mango",
        1109 to "Midnight",
        1110 to "Mint",
        1111 to "Mocha",
        1112 to "Neon Blue",
        1113 to "Neon Green",
        1114 to "Neon Orange",
        1115 to "Neon Pink",
        1116 to "Ocean",
        1117 to "Ocean Blue",
        1118 to "Olive",
        1119 to "Pastel Blue",
        1120 to "Pastel Green",
        1121 to "Pastel Pink",
        1122 to "Pastel Purple",
        1123 to "Pastel Yellow",
        1124 to "Peach",
        1125 to "Rainbow",
        1126 to "Rose Quartz",
        1127 to "Royal Purple",
        1128 to "Ruby",
        1129 to "Sage",
        1130 to "Sand",
        1131 to "Scarlet",
        1132 to "Silver",
        1133 to "Sky Blue",
        1134 to "Slate",
        1135 to "Spotify",
        1136 to "Spring",
        1137 to "Summer",
        1138 to "Sunset",
        1139 to "Synthwave",
        1140 to "Tangerine",
        1141 to "Teal Wave",
        1142 to "Terracotta",
        1143 to "Twilight",
        1144 to "Ultra Violet",
        1145 to "Violet",
        1146 to "Amber",
        1147 to "Wine",
        1148 to "Winter",
        1149 to "YouTube",
        1150 to "Password",
        1151 to "Past 24 hours",
        1152 to "Past month",
        1153 to "Past week",
        1154 to "Past year",
        1155 to "Pause",
        1156 to "Pause listen history",
        1157 to "Pause when device volume is 0",
        1158 to "Pause at zero volume, explain play attempts, and resume when volume increases",
        1159 to "Pause search history",
        1160 to "Paxsenix API key",
        1161 to "Configured",
        1162 to "Required for authenticated Paxsenix requests",
        1163 to "Paxsenix: Apple Music",
        1164 to "Paxsenix: Musixmatch",
        1165 to "Paxsenix: Spotify",
        1166 to "Paxsenix API Stats",
        1167 to "Failed to load API stats",
        1168 to "Degraded",
        1169 to "Down",
        1170 to "Operational",
        1171 to "%1\$d%%",
        1172 to "%d%%",
        1173 to "Permanent shuffle mode",
        1174 to "Keep shuffle enabled when you start a new song",
        1175 to "Allowed",
        1176 to "Required to read your downloaded and local audio files for playback.",
        1177 to "Storage access",
        1178 to "We use a few permissions to play and manage your music reliably. You can change these anytime in system settings.",
        1179 to "Allow ArchiveTune to work best",
        1180 to "Persistent queue",
        1181 to "Restore your last queue when the app starts",
        1182 to "Personal",
        1183 to "Pin to speed dial",
        1184 to "Pitch",
        1185 to "x",
        1186 to "st",
        1187 to "Play",
        1188 to "Play all",
        1189 to "Play next",
        1190 to "Play time",
        1191 to "Playback confirmation required",
        1192 to "App version: %1\$s (%2\$d)",
        1193 to "Cause",
        1194 to "Code",
        1195 to "Details",
        1196 to "HTTP",
        1197 to "Message",
        1198 to "No network connection",
        1199 to "Before reporting this issue in the support server or group, update to the latest nightly or artifact build and try again.",
        1200 to "Unknown error",
        1201 to "Refresh YouTube Music login",
        1202 to "Confirm playback in YouTube Music, then return to ArchiveTune.",
        1203 to "Refresh your YouTube Music login, then return to ArchiveTune.",
        1204 to "Playback Speed",
        1205 to "BUFFERING",
        1206 to "ENDED",
        1207 to "IDLE",
        1208 to "READY",
        1209 to "UNKNOWN",
        1210 to "Player",
        1211 to "Player and audio",
        1212 to "Blur",
        1213 to "Player background style",
        1214 to "Unavailable with V8, V9, and V10 player styles",
        1215 to "Player button colors",
        1216 to "Player design style",
        1217 to "Classic",
        1218 to "Editorial",
        1219 to "Modern",
        1220 to "Minimal",
        1221 to "Cinematic",
        1222 to "Little",
        1223 to "Expressive",
        1224 to "Immersive",
        1225 to "Immersive Extended",
        1226 to "Material Extended",
        1227 to "Player slider style",
        1228 to "Available only with V7 and V8 player styles",
        1229 to "Playing",
        1230 to "Note: Adding local songs to synced/remote playlists is unsupported. Any other combination is valid",
        1231 to "Couldn\u2019t update playlist cover",
        1232 to "Playlist cover updated",
        1233 to "The playlist is empty",
        1234 to "Playlist name",
        1235 to "Playlist not found",
        1236 to "The requested playlist could not be loaded",
        1237 to "You don't have access to this playlist.",
        1238 to "This playlist was private",
        1239 to "Local",
        1240 to "Online",
        1241 to "Playlist title and content",
        1242 to "Playlist content",
        1243 to "Playlist title",
        1244 to "Playlist sync failed: %1\$s",
        1245 to "%1\$d/%2\$d Songs",
        1246 to "Playlist synced",
        1247 to "Playlists",
        1248 to "Please wait",
        1249 to "Podcast",
        1250 to "This podcast has no available episodes.",
        1251 to "Preload Mode",
        1252 to "Uses additional data, battery, and processing in the background.",
        1253 to "Presence manager: running",
        1254 to "Presence manager: stopped",
        1255 to "Preview",
        1256 to "Privacy",
        1257 to "Providers",
        1258 to "Proxy",
        1259 to "Proxy Authorization (optional)",
        1260 to "Proxy connection failed: %s",
        1261 to "Invalid proxy host or port",
        1262 to "Proxy connection successful!",
        1263 to "Proxy host (IP)",
        1264 to "Password",
        1265 to "Proxy port",
        1266 to "Proxy type",
        1267 to "Username",
        1268 to "Pure black",
        1269 to "Queue",
        1270 to "All songs",
        1271 to "Autoplaying similar music",
        1272 to "Continue Playing",
        1273 to "Searched songs",
        1274 to "Quick picks",
        1275 to "Quick Picks display mode",
        1276 to "Card",
        1277 to "List",
        1278 to "Random theme on startup",
        1279 to "Apply a random color palette every time the app starts",
        1280 to "Real-time playback statistics",
        1281 to "Recent Commits",
        1282 to "Recent Requests",
        1283 to "Recently added",
        1284 to "Recently Played",
        1285 to "Recently Played Artists",
        1286 to "Recently updated",
        1287 to "Refetch",
        1288 to "Refetch canvas",
        1289 to "Refresh",
        1290 to "Refresh suggestions",
        1291 to "%1\$s \u2022 %2\$d",
        1292 to "Release notes",
        1293 to "Release notes are unavailable",
        1294 to "Album",
        1295 to "Single",
        1296 to "Remote",
        1297 to "Remove account",
        1298 to "Remove download",
        1299 to "Are you sure you want to remove this downloaded item? This action cannot be undone.",
        1300 to "Do you really want to remove all \"%s\" playlist songs from the Downloaded Songs storage?",
        1301 to "Are you sure you want to remove all downloads in this section? This action cannot be undone.",
        1302 to "Remove from cache",
        1303 to "Remove from history",
        1304 to "Remove from library",
        1305 to "Remove \\u0022%1\$s\\u0022 from your library?",
        1306 to "Remove from playlist",
        1307 to "Remove from queue",
        1308 to "Remove from speed dial",
        1309 to "Remove custom cover",
        1310 to "Removed %d songs from queue",
        1311 to "Removed \"%s\" from queue",
        1312 to "Repeat queue",
        1313 to "Repeat mode off",
        1314 to "Repeat current song",
        1315 to "Replace song",
        1316 to "Reset",
        1317 to "Reset listening stats",
        1318 to "Reset all listening stats on this device? This deletes listening history, play counts, and listening time. Your library, playlists, and downloads will be kept. This cannot be undone.",
        1319 to "Could not reset listening stats. Try again.",
        1320 to "Resetting listening stats\u2026",
        1321 to "Listening stats reset",
        1322 to "The backup file appears to be corrupted and could not be read.",
        1323 to "Failed to restore backup",
        1324 to "Could not open the selected file.",
        1325 to "Restore in progress",
        1326 to "The selected file is not a valid backup archive.",
        1327 to "The backup archive does not contain any restorable data.",
        1328 to "What to restore?",
        1329 to "Select a backup file to restore.",
        1330 to "Restarting app",
        1331 to "Restoring %1\$s",
        1332 to "Restoring settings",
        1333 to "Stopping playback",
        1334 to "Verifying backup",
        1335 to "Backup restored successfully",
        1336 to "Resume Autoscroll",
        1337 to "Resume",
        1338 to "Resume logs",
        1339 to "Retry",
        1340 to "Retry",
        1341 to "Romanization",
        1342 to "Sample rate",
        1343 to "Sample Rate",
        1344 to "Save",
        1345 to "Save current account",
        1346 to "Saved accounts",
        1347 to "Scan device",
        1348 to "Scanning device\u2026",
        1349 to "Scheduled auto backup",
        1350 to "Custom",
        1351 to "Next backup: %1\$s",
        1352 to "Choose backup date",
        1353 to "Daily",
        1354 to "Backup directory",
        1355 to "Choose a folder to enable scheduled backups.",
        1356 to "Backup directory saved",
        1357 to "Automatic backups are paused.",
        1358 to "Enable scheduled backup",
        1359 to "Backups run automatically using the schedule below.",
        1360 to "Backup schedule",
        1361 to "Choose how often ArchiveTune creates a backup.",
        1362 to "Scheduled backup settings could not be loaded",
        1363 to "Monthly",
        1364 to "Overwrite existing backup",
        1365 to "Keep one current backup instead of creating a dated history.",
        1366 to "Scheduled backup settings could not be saved",
        1367 to "Weekly",
        1368 to "Scrobble Delay (Seconds)",
        1369 to "Scrobble Delay Percent",
        1370 to "Minimum Track Duration",
        1371 to "Scrobbling",
        1372 to "Scrobbling Configuration",
        1373 to "Search",
        1374 to "Search downloads",
        1375 to "Search history",
        1376 to "Search library",
        1377 to "Search lyrics",
        1378 to "Search online",
        1379 to "Search YouTube Music",
        1380 to "Secondary",
        1381 to "See all",
        1382 to "-%1\$d seconds backwards",
        1383 to "+%1\$d seconds forwards",
        1384 to "Progressive seek",
        1385 to "If enabled,  Adds up 5 extra seconds incrementally on each seek skip",
        1386 to "Select all",
        1387 to "%1\$d%%",
        1388 to "Session code",
        1389 to "Session link",
        1390 to "Preferred lyrics provider",
        1391 to "Set ListenBrainz token",
        1392 to "Set quick picks",
        1393 to "Settings",
        1394 to "App info, licenses, and contributors",
        1395 to "Sign in and manage account sync",
        1396 to "Themes, layout, and visual styles",
        1397 to "Export and recover your personal app data",
        1398 to "History, defaults, and privacy behavior",
        1399 to "Behavior",
        1400 to "Language, country, and recommendation defaults",
        1401 to "Experimental features and debugging",
        1402 to "Developer Options",
        1403 to "Discord, Last.fm, Libre.fm, and ListenBrainz",
        1404 to "Proxy, DNS, and network playback behavior",
        1405 to "Lyrics providers and translation",
        1406 to "Audio behavior, crossfade, and background playback",
        1407 to "Playback",
        1408 to "Player & Content",
        1409 to "Your top songs, artists, and playback history",
        1410 to "Listening Stats",
        1411 to "Cache, downloads, and offline storage",
        1412 to "Version, release notes, and update channel",
        1413 to "Share",
        1414 to "Share as image",
        1415 to "Share as text",
        1416 to "Share logs",
        1417 to "Share lyrics",
        1418 to "Share selected",
        1419 to "Share Summary",
        1420 to "Shortest duration",
        1421 to "Show button",
        1422 to "Toggle visibility of button 1 in Discord Rich Presence",
        1423 to "Toggle visibility of button 2 in Discord Rich Presence",
        1424 to "Show Debug UI",
        1425 to "Show home category chips",
        1426 to "Show category filter chips on the home screen",
        1427 to "Show player controls",
        1428 to "Show nerd stats",
        1429 to "Show volume bar",
        1430 to "Show tags in library",
        1431 to "Show tag filter chips in the library",
        1432 to "Shuffle",
        1433 to "Similar content",
        1434 to "Similar to",
        1435 to "Singles",
        1436 to "%s used",
        1437 to "Skip duplicates",
        1438 to "Skip silence",
        1439 to "Sleep timer",
        1440 to "Circular",
        1441 to "Simple",
        1442 to "Standard",
        1443 to "Thick",
        1444 to "Wavy",
        1445 to "Small Image",
        1446 to "Small image custom URL",
        1447 to "Smart Trimmer",
        1448 to "Smart trimmer dynamically manages the image cache and song cache, pruning old entries to save disk space.",
        1449 to "Song artists",
        1450 to "Song Cache",
        1451 to "Song",
        1452 to "Couldn\u2019t change the song source.",
        1453 to "Song source changed.",
        1454 to "Song title",
        1455 to "Songs",
        1456 to "A \\u2192 Z",
        1457 to "Artist",
        1458 to "Sort ascending",
        1459 to "Album",
        1460 to "Artist",
        1461 to "Date added",
        1462 to "Custom order",
        1463 to "Date updated",
        1464 to "Most played",
        1465 to "Name",
        1466 to "Play time",
        1467 to "Sort descending",
        1468 to "Ascending",
        1469 to "Descending",
        1470 to "Z \\u2192 A",
        1471 to "Source",
        1472 to "Speed dial",
        1473 to "SponsorBlock API URL",
        1474 to "SponsorBlock",
        1475 to "Select SponsorBlock filtering",
        1476 to "Fillers",
        1477 to "Sponsor Block",
        1478 to "Hook/Greetings",
        1479 to "Intro",
        1480 to "Non-music and off-topic portions",
        1481 to "Outro",
        1482 to "Previews",
        1483 to "Self promos",
        1484 to "Sponsors",
        1485 to "Subscription reminders",
        1486 to "Use SponsorBlock",
        1487 to "Spotify account",
        1488 to "%1\$d playlists available",
        1489 to "Connect Spotify",
        1490 to "Connected as %1\$s",
        1491 to "Loading Spotify library",
        1492 to "Spotify login",
        1493 to "No Spotify playlists found",
        1494 to "No Spotify tracks found.",
        1495 to "Spotify is not connected",
        1496 to "Spotify Playlist",
        1497 to "Reload Playlist",
        1498 to "Refresh Spotify playlists from your account.",
        1499 to "Show Playlist",
        1500 to "Show Spotify playlists in Library.",
        1501 to "Waiting for Spotify login",
        1502 to "Start mix",
        1503 to "Start radio",
        1504 to "Start session",
        1505 to "State",
        1506 to "Stats",
        1507 to "Artist breakdown",
        1508 to "Songs you play will appear here with listening trends and rankings.",
        1509 to "No listening stats yet",
        1510 to "Your Favourite Artist",
        1511 to "Your Favourite Song",
        1512 to "Listening by Day",
        1513 to "Listening by Hour",
        1514 to "Listening patterns",
        1515 to "Most active: %s",
        1516 to "Show all %1\$d songs",
        1517 to "Show top 5",
        1518 to "Time range",
        1519 to "Top songs",
        1520 to "Total Plays",
        1521 to "Total Time Listened",
        1522 to "Unique Artists",
        1523 to "Unique Songs",
        1524 to "ACTIVE",
        1525 to "INACTIVE",
        1526 to "Stop music on task clear",
        1527 to "Storage",
        1528 to "Cache could not be cleared. Check SD card access.",
        1529 to "Keep ArchiveTune open while cache files are being removed.",
        1530 to "Cache cleared.",
        1531 to "Clearing canvas cache...%1\$d%%",
        1532 to "Clearing downloads...%1\$d%%",
        1533 to "Clearing image cache...%1\$d%%",
        1534 to "Clearing song cache...%1\$d%%",
        1535 to "Storage folder",
        1536 to "Select a valid folder.",
        1537 to "ArchiveTune cannot write cache files in this folder.",
        1538 to "Choose folder",
        1539 to "Storage folder saved. App will restart in 3 seconds.",
        1540 to "This folder cannot be used by the file-backed media cache.",
        1541 to "Use this storage",
        1542 to "%s free",
        1543 to "Internal storage",
        1544 to "SD card",
        1545 to "SD card %s",
        1546 to "Storage location",
        1547 to "Moving Cache...%1\$d%%",
        1548 to "Moving Downloads...%1\$d%%",
        1549 to "Warning: Dont close the app or turn off your device during this process. Doing so may cause data loss.",
        1550 to "%1\$s / %2\$s",
        1551 to "Bypass proxy for streams",
        1552 to "Use your direct IP for stream playback to avoid IP mismatch",
        1553 to "Subscribe",
        1554 to "Subscribed",
        1555 to "Subscribed Only",
        1556 to "Subscribers",
        1557 to "Success Rate",
        1558 to "Suggestions",
        1559 to "Donate to support development",
        1560 to "Hey there! I'm rukamori, the developer of ArchiveTune. If ArchiveTune has earned a place in your daily listening, you can help keep it moving forward by donating or starring the project on GitHub. Thanks for supporting the work behind the app.",
        1561 to "Star on GitHub",
        1562 to "Support development",
        1563 to "Mini player swipe sensitivity",
        1564 to "Swipe song to the left to add it to the queue or to the right to play it next",
        1565 to "Sync disabled",
        1566 to "Sync playlist",
        1567 to "System default",
        1568 to "Tag Color",
        1569 to "Tag Name",
        1570 to "Tap to change color",
        1571 to "Target Language",
        1572 to "Tempo",
        1573 to "Tempo and Pitch",
        1574 to "Test proxy connection",
        1575 to "Testing proxy connection",
        1576 to "Theme",
        1577 to "Theme applied",
        1578 to "Apply Theme",
        1579 to "Theme Creator",
        1580 to "Hex",
        1581 to "Hex value (#RRGGBB or #AARRGGBB)",
        1582 to "%1\$s Color",
        1583 to "Export failed",
        1584 to "Theme exported",
        1585 to "Import failed",
        1586 to "Can't import theme",
        1587 to "Theme imported",
        1588 to "Theme Details",
        1589 to "Name (optional)",
        1590 to "Presets",
        1591 to "Seed Colors",
        1592 to "Neutral",
        1593 to "Primary",
        1594 to "Secondary",
        1595 to "Tertiary",
        1596 to "This week",
        1597 to "Today",
        1598 to "Error: %1\$s",
        1599 to "Host transferred to %1\$s",
        1600 to "%1\$s requested to join",
        1601 to "Joining session",
        1602 to "Activity log",
        1603 to "No activity yet",
        1604 to "Session events will appear here as they happen.",
        1605 to "Session and playback events",
        1606 to "%1\$s paused playback",
        1607 to "%1\$s resumed playback",
        1608 to "%1\$s changed playback state",
        1609 to "%1\$s changed the queue",
        1610 to "Session started",
        1611 to "%1\$s changed the song to %2\$s",
        1612 to "%1\$s skipped to %2\$s",
        1613 to "Guests can add songs",
        1614 to "Guests can control playback",
        1615 to "Approve",
        1616 to "Ban",
        1617 to "Ban %1\$s?",
        1618 to "Connected",
        1619 to "%1\$d connected",
        1620 to "Connection timed out",
        1621 to "Current playback",
        1622 to "Display name",
        1623 to "Your name",
        1624 to "Don't show this again",
        1625 to "Error",
        1626 to "Host Leaved Sessions",
        1627 to "Host",
        1628 to "Hosting session",
        1629 to "Not in a session",
        1630 to "Code",
        1631 to "Enter a session code",
        1632 to "Link",
        1633 to "Paste a join link or code",
        1634 to "Join",
        1635 to "Joining session",
        1636 to "Kick",
        1637 to "Kick %1\$s?",
        1638 to "LAN",
        1639 to "Online",
        1640 to "Online sessions aren't configured",
        1641 to "%1\$s joined the room",
        1642 to "%1\$s left the room",
        1643 to "Participants",
        1644 to "No participants yet",
        1645 to "People who join this session will appear here.",
        1646 to "Pending approval",
        1647 to "Nothing playing",
        1648 to "Paused",
        1649 to "Playing",
        1650 to "Session port",
        1651 to "%1\$d in queue",
        1652 to "%1\$d/%2\$d",
        1653 to "Reject",
        1654 to "Repeat %1\$d",
        1655 to "Requesting host to change the song\\u2026",
        1656 to "Require approval",
        1657 to "Guest",
        1658 to "Host",
        1659 to "Room closed because no one joined for 10 minutes",
        1660 to "Server error, please try again later",
        1661 to "Server unreachable",
        1662 to "Session not found",
        1663 to "Shuffle off",
        1664 to "Shuffle on",
        1665 to "Song change not applied. Please try again.",
        1666 to "Status",
        1667 to "Online sessions aren't available in this build",
        1668 to "Transfer host",
        1669 to "Transfer host ownership to %1\$s?",
        1670 to "Someone",
        1671 to "Waiting Approval",
        1672 to "Music Together lets multiple devices share a live session with a synced queue and playback.",
        1673 to "Tap Start session, then share the session link. Keep ArchiveTune open in the background while hosting.",
        1674 to "Host a session",
        1675 to "Open the shared link, or enter code and tap Join. Your queue and playback will follow the host.",
        1676 to "Join from another device",
        1677 to "Hosts can decide whether guests can add songs, control playback, or require approval to join.",
        1678 to "Permissions and safety",
        1679 to "Welcome to ArchiveTune Music Together",
        1680 to "This is an ADVANCED login method. As an alternative to the web portal, you may directly enter or update your login token here. For example, this can speed up logging in on multiple devices. Please note that any invalid token formats the app fails to parse will not be accepted",
        1681 to "Tap to show token",
        1682 to "Tap again to copy or edit",
        1683 to "Top Albums",
        1684 to "TOP ARTIST",
        1685 to "Top Artists",
        1686 to "My Top list length",
        1687 to "Top Mixes for You",
        1688 to "Top music videos",
        1689 to "Top Results",
        1690 to "Top Songs",
        1691 to "total",
        1692 to "Total Listening Time",
        1693 to "Total releases",
        1694 to "Total Requests",
        1695 to "Track",
        1696 to "Tracks count",
        1697 to "tracks",
        1698 to "Translate",
        1699 to "Translation failed",
        1700 to "Translation saved",
        1701 to "Translator Options",
        1702 to "Trending",
        1703 to "Unblock artist",
        1704 to "Undo",
        1705 to "Unhide",
        1706 to "Unhide playlist",
        1707 to "Unknown",
        1708 to "Unknown artist",
        1709 to "Unknown bitrate",
        1710 to "Unknown codec",
        1711 to "Unknown content length",
        1712 to "Unknown sample rate",
        1713 to "Unlimited",
        1714 to "Cancel login",
        1715 to "No thanks",
        1716 to "Yes, save current account",
        1717 to "Your current account has not been saved yet. Do you want to save it before adding another account?",
        1718 to "Account not saved",
        1719 to "Unsupported language: %1\$s",
        1720 to "Update",
        1721 to "Update Channel",
        1722 to "Choose between tested releases and development snapshots.",
        1723 to "Notifications for new app updates",
        1724 to "App Updates",
        1725 to "ArchiveTune %s is now available",
        1726 to "Update Available",
        1727 to "Update",
        1728 to "Updates",
        1729 to "Switch to the Artifact channel to receive development builds.\n\nArtifact builds are fetched directly from GitHub Actions workflow runs.\nNote: downloading directly from GitHub bypasses any additional screening performed by the store you might have originally installed the app from.",
        1730 to "Artifact builds are fetched directly from GitHub Actions workflow runs.",
        1731 to "Note: downloading directly from GitHub bypasses any additional screening performed by the store you might have originally installed the app from.\nBy continuing, you acknowledge that Artifact builds may be unstable and use them at your own risk.",
        1732 to "Artifact builds may include experimental features, unfinished changes, or temporary regressions.",
        1733 to "Artifact builds",
        1734 to "Artifact builds are provided for testing and early access only.\nStability, compatibility, and functionality are not guaranteed.",
        1735 to "ArchiveTune provides two download channels for builds:",
        1736 to "These versions are tested and recommended for most users.",
        1737 to "Distributed via official GitHub Releases.",
        1738 to "Stable builds",
        1739 to "Loading recent commits",
        1740 to "No recent commits found",
        1741 to "%1\$d recent commits",
        1742 to "Checking for the latest release",
        1743 to "You are on the latest available release",
        1744 to "Artifact builds from GitHub Actions workflow",
        1745 to "Uptime",
        1746 to "This can influence what content you see and for example shows premium-only albums if you are logged in with a Premium account",
        1747 to "Use system language",
        1748 to "Username",
        1749 to "View album",
        1750 to "View all",
        1751 to "View artist",
        1752 to "View Changelog",
        1753 to "View and filter application logs",
        1754 to "Views",
        1755 to "Visit Website",
        1756 to "Volume",
        1757 to "Keep CPU awake during playback",
        1758 to "Prevents the system from interrupting music by holding a CPU wake lock",
        1759 to "Wallpaper color permission",
        1760 to "Grant storage permission to extract colors from your wallpaper on older devices",
        1761 to "Weeks",
        1762 to "Listening Insights",
        1763 to "No listening time yet",
        1764 to "%1\$d h %2\$d min",
        1765 to "%1\$d min",
        1766 to "No genres yet",
        1767 to "No recent songs yet",
        1768 to "No recommendations yet",
        1769 to "Pause",
        1770 to "Previous",
        1771 to "Recommendations",
        1772 to "Tap to open ArchiveTune",
        1773 to "Top lately: %1\$s",
        1774 to "Year in Music",
        1775 to "Share card",
        1776 to "Play more music during %d and your recap will appear here.",
        1777 to "Nothing to recap yet",
        1778 to "Reveal your top songs, artists, albums, and listening time.",
        1779 to "It's here! Your year in music.",
        1780 to "Listening time",
        1781 to "minutes",
        1782 to "My musical passport",
        1783 to "Total plays",
        1784 to "Albums you returned to",
        1785 to "Artists on repeat",
        1786 to "Music Recap",
        1787 to "RECAP",
        1788 to "Swipe to begin",
        1789 to "Top pick",
        1790 to "Your top track",
        1791 to "You kept the music moving",
        1792 to "Year",
        1793 to "Years",
        1794 to "Yesterday",
        1795 to "You might like",
        1796 to "Playlist recommendation source",
        1797 to "Your Artists",
        1798 to "Your Collection",
        1799 to "Your Playlists",
        1800 to "Your YouTube playlists",
        1801 to "YouTube channels",
        1802 to "YouTube synced",
        1803 to "Auto sync with account",
    )
}

@Composable
fun stringResource(id: Int): String {
    return StringResources.stringMap[id] ?: "Stub String Resource ($id)"
}

@Composable
fun stringResource(id: Int, vararg formatArgs: Any): String {
    val str = StringResources.stringMap[id] ?: "Stub String Resource ($id)"
    return try { String.format(str, *formatArgs) } catch (e: Exception) { str }
}
