# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  geoip-dat = {
    pname = "geoip-dat";
    version = "202209262214";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202209262214/geoip.dat";
      sha256 = "sha256-DY+ynkNSSGIF2NrmCrRVs+adUJEd8ulKhUy/HXCSGBM=";
    };
  };
  geosite-dat = {
    pname = "geosite-dat";
    version = "202209262214";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202209262214/geosite.dat";
      sha256 = "sha256-DdgB9+at+hnD1DVS9vD35mtFk/QknMt7VVuPwfJw2Mk=";
    };
  };
  mosdns = {
    pname = "mosdns";
    version = "v4.2.0";
    src = fetchFromGitHub ({
      owner = "IrineSistiana";
      repo = "mosdns";
      rev = "v4.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-ifkvZt+d1YWfi0g8sof0gsN0W+98qEC2J/SfPGXtmZc=";
    });
  };
  v2ray = {
    pname = "v2ray";
    version = "v5.1.0";
    src = fetchFromGitHub ({
      owner = "v2fly";
      repo = "v2ray-core";
      rev = "v5.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-87BtyaJN6qbinZQ+6MAwaK62YzbVnncj4qnEErG5tfA=";
    });
  };
}
