# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  tonez = {
    pname = "tonez";
    version = "2.0.0";
    src = fetchurl {
      url = "https://www.retornz.com/ld/ToneZ_V2-x64-2.0.0_Linux.zip";
      sha256 = "sha256-rmz/fbmfMuvpi/juf3tx0+XK+NjpPioeQQDmiCQwEwE=";
    };
  };
}
