# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cloudreverb = {
    pname = "cloudreverb";
    version = "92804eda8439d058a018dad606ebd1c403c37b90";
    src = fetchFromGitHub {
      owner = "xunil-cloud";
      repo = "CloudReverb";
      rev = "92804eda8439d058a018dad606ebd1c403c37b90";
      fetchSubmodules = true;
      sha256 = "sha256-erpJlS9VYvYyqYyKjyDuob7Jup+zLuj93j+BRAjPtl4=";
    };
    date = "2026-04-13";
  };
}
