default_args := "--verbose --print-build-logs --log-format multiline-with-logs --show-trace"

@_default:
    just --list --unsorted

@_to-outputs +NAMES:
    echo {{ NAMES }} | sed -e 's:[^ ]*:".#&":g'

@_build-outputs:
    nix eval -f ./ci.nix buildOutputs --apply 'xs: builtins.concatStringsSep " " (map (x: x.drvPath + "^*") xs)' --raw

@_build-outputs-tests:
    nix eval -f ./ci.nix buildOutputs --apply 'xs: builtins.concatStringsSep " " (builtins.concatMap (x: map (t: t.drvPath + "^*") (builtins.attrValues (x.tests or {}))) xs)' --raw

@_cache-outputs:
    nix eval -f ./ci.nix cacheOutputs --apply 'xs: builtins.concatStringsSep " " (map (x: x.drvPath + "^*") xs)' --raw

@_cache-outputs-tests:
    nix eval -f ./ci.nix cacheOutputs --apply 'xs: builtins.concatStringsSep " " (builtins.concatMap (x: map (t: t.drvPath + "^*") (builtins.attrValues (x.tests or {}))) xs)' --raw

_nix-nixpkgs-unstable +ARGS:
    nix {{ ARGS }} {{ default_args }} --inputs-from . --override-input nixpkgs github:NixOS/nixpkgs/nixpkgs-unstable

_nix-nixos-unstable +ARGS:
    nix {{ ARGS }} {{ default_args }} --inputs-from . --override-input nixpkgs github:NixOS/nixpkgs/nixos-unstable

_nix-nixos-stable +ARGS:
    nix {{ ARGS }} {{ default_args }} --inputs-from . --override-input nixpkgs github:NixOS/nixpkgs/nixos-25.05

[group("build")]
build-nixpkgs-unstable +PACKAGES:
    just _nix-nixpkgs-unstable build $(just _to-outputs {{ PACKAGES }})

[group("build")]
build-nixos-unstable +PACKAGES:
    just _nix-nixos-unstable build $(just _to-outputs {{ PACKAGES }})

[group("build")]
build-nixos-stable +PACKAGES:
    just _nix-nixos-stable build $(just _to-outputs {{ PACKAGES }})

[group("build")]
build +PACKAGES: (build-nixpkgs-unstable PACKAGES) (build-nixos-unstable PACKAGES) (build-nixos-stable PACKAGES)

[group("build-all")]
build-all-nixpkgs-unstable:
    just _nix-nixpkgs-unstable build --no-link $(just _cache-outputs)

[group("build-all")]
build-all-nixos-unstable:
    just _nix-nixos-unstable build --no-link $(just _cache-outputs)

[group("build-all")]
build-all-nixos-stable:
    just _nix-nixos-stable build --no-link $(just _cache-outputs)

[group("build-all")]
build-all: build-all-nixpkgs-unstable build-all-nixos-unstable build-all-nixos-stable

[group("rebuild")]
rebuild-nixpkgs-unstable +PACKAGES: (build-nixpkgs-unstable PACKAGES)
    just _nix-nixpkgs-unstable build --rebuild $(just _to-outputs {{ PACKAGES }})

[group("rebuild")]
rebuild-nixos-unstable +PACKAGES: (build-nixos-unstable PACKAGES)
    just _nix-nixos-unstable build --rebuild $(just _to-outputs {{ PACKAGES }})

[group("rebuild")]
rebuild-nixos-stable +PACKAGES: (build-nixos-stable PACKAGES)
    just _nix-nixos-stable build --rebuild $(just _to-outputs {{ PACKAGES }})

[group("rebuild")]
rebuild +PACKAGES: (rebuild-nixpkgs-unstable PACKAGES) (rebuild-nixos-stable PACKAGES)

[group("rebuild-all")]
rebuild-all-nixpkgs-unstable:
    just _nix-nixpkgs-unstable build --no-link --rebuild $(just _cache-outputs)

[group("rebuild-all")]
rebuild-all-nixos-unstable:
    just _nix-nixos-unstable build --no-link --rebuild $(just _cache-outputs)

[group("rebuild-all")]
rebuild-all-nixos-stable:
    just _nix-nixos-stable build --no-link --rebuild $(just _cache-outputs)

[group("rebuild-all")]
rebuild-all: rebuild-all-nixpkgs-unstable rebuild-all-nixos-stable

[group("test-all")]
test-all-nixpkgs-unstable:
    just _nix-nixpkgs-unstable build --no-link $(just _cache-outputs-tests)

[group("test-all")]
test-all-nixos-unstable:
    just _nix-nixos-unstable build --no-link $(just _cache-outputs-tests)

[group("test-all")]
test-all-nixos-stable:
    just _nix-nixos-stable build --no-link $(just _cache-outputs-tests)

[group("test-all")]
test-all: test-all-nixpkgs-unstable test-all-nixos-stable

[group("run")]
run-nixpkgs-unstable PACKAGE: (build-nixpkgs-unstable PACKAGE)
    just _nix-nixpkgs-unstable run ".#{{ PACKAGE }}"

[group("run")]
run-nixos-unstable PACKAGE: (build-nixos-stable PACKAGE)
    just _nix-nixos-unstable run ".#{{ PACKAGE }}"

[group("run")]
run-nixos-stable PACKAGE: (build-nixos-stable PACKAGE)
    just _nix-nixos-stable run ".#{{ PACKAGE }}"

[group("path-info")]
path-info-nixpkgs-unstable PACKAGE: (build-nixpkgs-unstable PACKAGE)
    just _nix-nixpkgs-unstable path-info ".#{{ PACKAGE }}"

[group("path-info")]
path-info-nixos-unstable PACKAGE: (build-nixos-stable PACKAGE)
    just _nix-nixos-unstable path-info ".#{{ PACKAGE }}"

[group("path-info")]
path-info-nixos-stable PACKAGE: (build-nixos-stable PACKAGE)
    just _nix-nixos-stable path-info ".#{{ PACKAGE }}"

[group("update")]
update +PACKAGES:
    just _nix-nixpkgs-unstable run ".#update" {{ PACKAGES }}

[group("update-all")]
update-all:
    just _nix-nixpkgs-unstable run ".#update-all"

tree PACKAGE: (build-nixpkgs-unstable PACKAGE)
    #!/usr/bin/env nix-shell
    #!nix-shell -i bash -p nix-tree
    set -euxo pipefail
    nix-tree ".#{{ PACKAGE }}"

inspect:
    #!/usr/bin/env nix-shell
    #!nix-shell -i bash -p nix-inspect
    set -euxo pipefail
    nix-inspect --path .

lint:
    #!/usr/bin/env nix-shell
    #!nix-shell -i bash -p statix deadnix
    set -euxo pipefail
    statix check
    deadnix

generate-readme:
    just _nix-nixpkgs-unstable run ".#generate-readme"
