#!/bin/bash
### original script by Adrien Linuxtricks (credit: https://github.com/aaaaadrien)

ARGS=$1

#echo "$ARGS"

# CHECK if only IP/HOSTNAME or user@IP/user@HOSTAME
if [[ "$ARGS" =~ \@ ]]
then
	# KEEP only things after @ (The IP or HOSTNAME)
	SRV=$(echo $ARGS | cut -d '@' -f2)
else
	SRV="$ARGS"
fi

# REMOVE in known_hosts
ssh-keygen -R $SRV

# ASK to reconnect
read -p "Reconnect ? IT WILL RUN \"ssh $SRV\" ? (y/N) " RECO

# CHECK ANSWSER
if [[ "$RECO" == "y" ]]
then
	ssh "$ARGS"
fi
