# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  balenaEtcher = {
    pname = "balenaEtcher";
    version = "2.1.2";
    src = fetchurl {
      url = "https://github.com/balena-io/etcher/releases/download/v2.1.2/balenaEtcher-2.1.2-arm64.dmg";
      sha256 = "sha256-sqXbFtmCU+H9dGekzUZwA8Umop4tSYKCx0dm8FHBlgY=";
    };
  };
  bartender5 = {
    pname = "bartender5";
    version = "5-3-6";
    src = fetchurl {
      url = "https://www.macbartender.com/B2/updates/5-3-6/Bartender%205.dmg";
      name = "Bartender5.dmg";
      sha256 = "sha256-ojdOO1coUs41Hwz10mX7L0pV0MJLMTe8i6a79kod8p8=";
    };
  };
  chatterino = {
    pname = "chatterino";
    version = "2.5.3";
    src = fetchurl {
      url = "https://chatterino.fra1.digitaloceanspaces.com/bin/2.5.3/Chatterino.dmg";
      sha256 = "sha256-pTAw2Ko1fcYxWhQK9j0odQPn28I1Lw2CHLs21KCbo7g=";
    };
  };
  cryptomator = {
    pname = "cryptomator";
    version = "1.16.2";
    src = fetchurl {
      url = "https://github.com/cryptomator/cryptomator/releases/download/1.16.2/Cryptomator-1.16.2-arm64.dmg";
      sha256 = "sha256-ENYGW4eX2jtrokjy2FT/TJ+Iu7H/0a74O6d0QIz5FkE=";
    };
  };
  garmin-basecamp = {
    pname = "garmin-basecamp";
    version = "4813";
    src = fetchurl {
      url = "https://download.garmin.com/software/BaseCampforMac_4813.dmg";
      sha256 = "sha256-5M209u+JpwnRl+AnOgb5lbtLNUJTjw8+R0O/yFznTgs=";
    };
  };
  gitkraken-cli-darwin-arm64 = {
    pname = "gitkraken-cli-darwin-arm64";
    version = "3.0.7";
    src = fetchurl {
      url = "https://github.com/gitkraken/gk-cli/releases/download/v3.0.7/gk_3.0.7_darwin_arm64.zip";
      sha256 = "sha256-ZC+RLoWQ1YfHlf8o7/35Gm8WwD6H9Y14x+wT+b75S58=";
    };
  };
  gitkraken-cli-darwin-x86 = {
    pname = "gitkraken-cli-darwin-x86";
    version = "3.0.7";
    src = fetchurl {
      url = "https://github.com/gitkraken/gk-cli/releases/download/v3.0.7/gk_3.0.7_darwin_amd64.zip";
      sha256 = "sha256-+uO3HGjFa98Mp9YFvy8JQ8naAbDdXyDRWXv2++lpc+c=";
    };
  };
  handbrake = {
    pname = "handbrake";
    version = "1.9.2";
    src = fetchurl {
      url = "https://github.com/HandBrake/HandBrake/releases/download/1.9.2/HandBrake-1.9.2.dmg";
      sha256 = "sha256-YaV8UzEaDKI+WDZ/USE0r5lCjBSsOmJmXyRfxeRsN5E=";
    };
  };
  komiser-darwin-arm64 = {
    pname = "komiser-darwin-arm64";
    version = "v3.1.22";
    src = fetchurl {
      url = "https://github.com/tailwarden/komiser/releases/download/v3.1.22/komiser_Darwin_arm64";
      sha256 = "sha256-HuRn7jf2OQ7c017gWkNiPnQpIEDViAIpDSKCJXRlEZ4=";
    };
  };
  komiser-darwin-x86 = {
    pname = "komiser-darwin-x86";
    version = "v3.1.22";
    src = fetchurl {
      url = "https://github.com/tailwarden/komiser/releases/download/v3.1.22/komiser_Darwin_x86_64";
      sha256 = "sha256-fYzK7EEAUkaJYjnIn3Fid5Go6tdp7YRahLscebQ7iaE=";
    };
  };
  komiser-linux-x86 = {
    pname = "komiser-linux-x86";
    version = "v3.1.22";
    src = fetchurl {
      url = "https://github.com/tailwarden/komiser/releases/download/v3.1.22/komiser_Linux_x86_64";
      sha256 = "sha256-1E5Soxjx7ei3RivaFe213cbzPClekpF+TcZhDoPJ6AE=";
    };
  };
  openaudible = {
    pname = "openaudible";
    version = "4.5.3";
    src = fetchurl {
      url = "https://github.com/openaudible/openaudible/releases/download/v4.5.3/OpenAudible_4.5.3.dmg";
      sha256 = "sha256-AHr7uOwyPhWX8Qm0X1n/eGbP5MYcCe4+wSFQyPkR9w8=";
    };
  };
  ps-remote-play = {
    pname = "ps-remote-play";
    version = "8.0.0";
    src = fetchurl {
      url = "https://remoteplay.dl.playstation.net/remoteplay/module/mac/RemotePlayInstaller.pkg";
      sha256 = "sha256-+iyK9RcaFLqVlRZaHMGxxlMpxkGgCuP+zzW12xOjms4=";
    };
  };
  signal-desktop = {
    pname = "signal-desktop";
    version = "7.56.0";
    src = fetchurl {
      url = "https://updates.signal.org/desktop/signal-desktop-mac-universal-7.56.0.dmg";
      sha256 = "sha256-uwzj5P/bZLcjrXBmtPtSBf/+CdN9e6mry2rWhuQxKks=";
    };
  };
}
