name: Update Sources

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 5 * * *"
      timezone: "Asia/Shanghai"

concurrency:
  group: update-sources
  cancel-in-progress: true

jobs:
  update-sources:
    runs-on: ubuntu-latest
    name: Update Sources
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v35
        with:
          nix_conf: |
            accept-flake-config = true

      - name: Update sources
        run: |
          nix flake update
          NIXPKGS_PATH=$(nix eval --raw .#nixpkgs)
          export NIX_PATH="nixpkgs=$NIXPKGS_PATH"
          nix run .#nvfetcher-bin
          git add .
          cp "$NIXPKGS_PATH/pkgs/by-name/mo/motrix-next/package.nix" ./pkgs/motrix-next
          pkgs/daed/update.sh
          pkgs/dav2d/update.sh
          pkgs/kanzi-cpp/update.sh
          pkgs/kikoflu/update.sh
          pkgs/loveiwara/update.sh
          pkgs/enimul/update.sh
          # pkgs/motrix-next/update.sh
          pkgs/motrix-next/update-beta.sh
          pkgs/nix-auth/update.sh
          pkgs/piliplus/update.sh
          pkgs/pixes/update.sh
          pkgs/pixes/update-git.sh
          pkgs/splayer-git/update.sh
          pkgs/splayer-next-dev/update.sh
          pkgs/wild-reader/update.sh

      - name: Create Pull Request
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          commit-message: Update sources
          branch: ci/update-sources
          delete-branch: true
          title: Update sources
          labels: dependencies
