# Do not manually edit this file, it is managed by Gleam.
#
# This file locks the dependency versions used, to make your build
# deterministic and to prevent unexpected versions from being included
# in your application.
#
# You should check this file into your source control repository.

packages = [
  { name = "barrel_mcp", version = "4.3.0", build_tools = [
    "rebar3",
  ], requirements = [
    "erlang_h1",
    "h2",
    "hackney",
  ], otp_app = "barrel_mcp", source = "hex", outer_checksum = "6A6CAB96F8CEBF84643FDE8BEDCC5F4F661AC9E0BFECEAA29758C9B115EF9557" },
  { name = "certifi", version = "2.17.0", build_tools = [
    "rebar3",
  ], requirements = [
  ], otp_app = "certifi", source = "hex", outer_checksum = "8122798A17F0293C80DAADA25D0F81C7F4D708C73FEF782C7C9B1950E26E4D21" },
  { name = "erlang_h1", version = "0.9.1", build_tools = [
    "rebar3",
  ], requirements = [
  ], otp_app = "h1", source = "hex", outer_checksum = "F6C7D1C0947CBE56AB7494E5E131CADAC626E7D5FA42396314B6CCE1380B0C73" },
  { name = "esqlite", version = "0.9.0", build_tools = [
    "rebar3",
  ], requirements = [
  ], otp_app = "esqlite", source = "hex", outer_checksum = "CCF72258A4EE152EC7AD92AA9A03552EB6CA1B06B65C93AD5B6E55C302E05855" },
  { name = "exception", version = "2.1.1", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_stdlib",
  ], otp_app = "exception", source = "hex", outer_checksum = "6BDEA95248093599391C3B5DF1835C5C6A86C353C2F99CE539B450E3432FE117" },
  { name = "gleam_crypto", version = "1.6.0", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_stdlib",
  ], otp_app = "gleam_crypto", source = "hex", outer_checksum = "2DE9E4EF53CF6FEE049D4F765731F7178F7A11AEFAE00EEE63BF7536B354AD3F" },
  { name = "gleam_erlang", version = "1.3.0", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_stdlib",
  ], otp_app = "gleam_erlang", source = "hex", outer_checksum = "1124AD3AA21143E5AF0FC5CF3D9529F6DB8CA03E43A55711B60B6B7B3874375C" },
  { name = "gleam_http", version = "4.4.0", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_stdlib",
  ], otp_app = "gleam_http", source = "hex", outer_checksum = "F065CE9941A7756ABBAEAE7F9F32A96CAD29DA3311A381DB2D926EA8E8C156DC" },
  { name = "gleam_json", version = "3.1.0", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_stdlib",
  ], otp_app = "gleam_json", source = "hex", outer_checksum = "44FDAA8847BE8FC48CA7A1C089706BD54BADCC4C45B237A992EDDF9F2CDB2836" },
  { name = "gleam_otp", version = "1.3.0", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_erlang",
    "gleam_stdlib",
  ], otp_app = "gleam_otp", source = "hex", outer_checksum = "DE4CA6850842F0266EE95317A25DD6A0A0F20CDFAB7C0ADC2E63251D7C3C72EC" },
  { name = "gleam_stdlib", version = "1.0.5", build_tools = [
    "gleam",
  ], requirements = [
  ], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "CEE5B6C076A85B45F60C585F4316C63EC8B7127C119D5738C3958A9C4D50404E" },
  { name = "gleeunit", version = "1.11.0", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_stdlib",
  ], otp_app = "gleeunit", source = "hex", outer_checksum = "EC31ABA74256AEA531EDF8169931D775BBB384FED0A8A1BDC4DD9354E3E21826" },
  { name = "glisten", version = "9.0.1", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_erlang",
    "gleam_otp",
    "gleam_stdlib",
    "logging",
  ], otp_app = "glisten", source = "hex", outer_checksum = "7795AA50830656F3A0316A6B26595F893C83272DA901B3405E31339CAA31A10B" },
  { name = "gramps", version = "6.0.1", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_crypto",
    "gleam_erlang",
    "gleam_http",
    "gleam_stdlib",
  ], otp_app = "gramps", source = "hex", outer_checksum = "D55636072DEE173F6586A5679D3C02EC7A0DE3F8646B78C351B72908FF223DF7" },
  { name = "h2", version = "0.12.4", build_tools = [
    "rebar3",
  ], requirements = [
  ], otp_app = "h2", source = "hex", outer_checksum = "238553579D2599E823F1F7B1CACB763362EE6E2DF8E8F3B0C8FC67DA982C0675" },
  { name = "hackney", version = "4.8.5", build_tools = [
    "rebar3",
  ], requirements = [
    "certifi",
    "h2",
    "idna",
    "mimerl",
    "parse_trans",
    "quic",
    "ssl_verify_fun",
    "webtransport",
  ], otp_app = "hackney", source = "hex", outer_checksum = "D1C18324CE5EAA5E45A245F31E68D212C4F3F24EE0A27E4EAC09C5959831C138" },
  { name = "hpack_erl", version = "0.3.0", build_tools = [
    "rebar3",
  ], requirements = [
  ], otp_app = "hpack", source = "hex", outer_checksum = "D6137D7079169D8C485C6962DFE261AF5B9EF60FBC557344511C1E65E3D95FB0" },
  { name = "idna", version = "7.1.0", build_tools = [
    "rebar3",
  ], requirements = [
  ], otp_app = "idna", source = "hex", outer_checksum = "6AE959A025BF36DF61A8CAB8508D9654891B5426A84C44D82DEAFFD6DDF8C71F" },
  { name = "logging", version = "1.5.0", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_stdlib",
  ], otp_app = "logging", source = "hex", outer_checksum = "BC5F18CE5DD9686100229FE5409BDC3DD5C46D5A7DF2F804AD2D8F0DD6C5060E" },
  { name = "mimerl", version = "1.5.0", build_tools = [
    "rebar3",
  ], requirements = [
  ], otp_app = "mimerl", source = "hex", outer_checksum = "DB648CE065BAE14EA84CA8B5DD123F42F49417CEF693541110BF6F9E9BE9ECC4" },
  { name = "mist", version = "6.0.3", build_tools = [
    "gleam",
  ], requirements = [
    "exception",
    "gleam_erlang",
    "gleam_http",
    "gleam_otp",
    "gleam_stdlib",
    "glisten",
    "gramps",
    "hpack_erl",
    "logging",
  ], otp_app = "mist", source = "hex", outer_checksum = "1B07F321D5FA0CB162D81496F2DE96AEB6EF8980F4F38230A4CC3F849497E020" },
  { name = "parse_trans", version = "3.4.2", build_tools = [
    "rebar3",
  ], requirements = [
  ], otp_app = "parse_trans", source = "hex", outer_checksum = "4C25347DE3B7C35732D32E69AB43D1CEEE0BEAE3F3B3ADE1B59CBD3DD224D9CA" },
  { name = "quic", version = "2.1.1", build_tools = [
    "rebar3",
  ], requirements = [
  ], otp_app = "quic", source = "hex", outer_checksum = "305D78A857298D940F6621A9ACD7391C02980555D5E7FFFEF364ECCD330FD64D" },
  { name = "sqlight", version = "1.2.0", build_tools = [
    "gleam",
  ], requirements = [
    "esqlite",
    "gleam_stdlib",
  ], otp_app = "sqlight", source = "hex", outer_checksum = "841768D0A81107EE2DB46B949354F284A68B2E8098315C28A1FE3C07D206C17A" },
  { name = "ssl_verify_fun", version = "1.1.7", build_tools = [
    "mix",
    "rebar3",
    "make",
  ], requirements = [
  ], otp_app = "ssl_verify_fun", source = "hex", outer_checksum = "FE4C190E8F37401D30167C8C405EDA19469F34577987C76DDE613E838BBC67F8" },
  { name = "webtransport", version = "0.4.8", build_tools = [
    "rebar3",
  ], requirements = [
    "h2",
    "quic",
  ], otp_app = "webtransport", source = "hex", outer_checksum = "08477A2195CCBF944DA0B78F85DC4E6EE4498790E3DD7FE84EE7A245938E1B26" },
  { name = "yamerl", version = "0.10.0", build_tools = [
    "rebar3",
  ], requirements = [
  ], otp_app = "yamerl", source = "hex", outer_checksum = "346ADB2963F1051DC837A2364E4ACF6EB7D80097C0F53CBDC3046EC8EC4B4E6E" },
]

[requirements]
barrel_mcp = { version = ">= 4.0.0 and < 5.0.0" }
gleam_crypto = { version = ">= 1.0.0 and < 2.0.0" }
gleam_erlang = { version = ">= 1.3.0 and < 2.0.0" }
gleam_http = { version = ">= 4.4.0 and < 5.0.0" }
gleam_json = { version = ">= 3.1.0 and < 4.0.0" }
gleam_otp = { version = ">= 1.3.0 and < 2.0.0" }
gleam_stdlib = { version = ">= 1.0.0 and < 2.0.0" }
gleeunit = { version = ">= 1.0.0 and < 2.0.0" }
mist = { version = ">= 6.0.3 and < 7.0.0" }
sqlight = { version = ">= 1.2.0 and < 2.0.0" }
yamerl = { version = ">= 0.10.0 and < 1.0.0" }
