# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "0i6544qpnchr68bgwv8bckaga6ki0cgldnw0wl0vh6yy64r1ikwg";
    x86_64-linux = "0jllcy5khh1b7b3l476105hzxjvbwz21nzis9qhbzgfbgn85j1sg";
    armv7l-linux = "0c90qbwyqj8mfpdp0x6kfhbl0w6k5qlz1ibj0bqj44c4w9m9f31v";
    aarch64-linux = "0182gfrzqxa49b14dyyb86iym2c6ylk31qgc1654gs5qn9iad1wi";
    x86_64-darwin = "0f84bn36hjcfird8d5zng8k03l5sp6wa117aqcjddv6gpx4b755s";
    aarch64-darwin = "037a2ymmxklavzwv0078w4cj8h88x41vxwznzlar1m58rw6wxnm5";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/soft-serve/releases/download/v0.12.2/soft-serve_0.12.2_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/soft-serve/releases/download/v0.12.2/soft-serve_0.12.2_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/soft-serve/releases/download/v0.12.2/soft-serve_0.12.2_Linux_arm.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/soft-serve/releases/download/v0.12.2/soft-serve_0.12.2_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/soft-serve/releases/download/v0.12.2/soft-serve_0.12.2_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/soft-serve/releases/download/v0.12.2/soft-serve_0.12.2_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "soft-serve_0.12.2_Linux_i386";
    x86_64-linux = "soft-serve_0.12.2_Linux_x86_64";
    armv7l-linux = "soft-serve_0.12.2_Linux_arm";
    aarch64-linux = "soft-serve_0.12.2_Linux_arm64";
    x86_64-darwin = "soft-serve_0.12.2_Darwin_x86_64";
    aarch64-darwin = "soft-serve_0.12.2_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "soft-serve";
  version = "0.12.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./soft $out/bin/soft
    installManPage ./manpages/soft-serve.1.gz
    installShellCompletion ./completions/*
  '';

  meta = {
    description = "A tasty, self-hostable Git server for the command line🍦";
    homepage = "https://charm.land/";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
