# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  dimmer = {
    pname = "dimmer";
    version = "1.0.2_20Sep2024";
    src = fetchurl {
      url = "https://www.vennaudio.com/downloads/Dimmer/Dimmer_Linux_1.0.2_20Sep2024_Release.zip";
      sha256 = "sha256-SqLn1/UgzaMVkxdiRzGJkHilw70b8/Yuhv1IVxpEbhE=";
    };
  };
  free-suite = {
    pname = "free-suite";
    version = "1.0.2_11Dec2023_2246";
    src = fetchurl {
      url = "https://www.vennaudio.com/downloads/Free%20Suite/Free%20Suite_Linux_1.0.2_11Dec2023_2246.zip";
      name = "Free_Suite_Linux_1.0.2_11Dec2023_2246.zip";
      sha256 = "sha256-ER65y/l7vyzu3aHrirKV7OatvneLSWPVP993QigoX3c=";
    };
  };
  viper = {
    pname = "viper";
    version = "1.6.1_15Nov2024";
    src = fetchurl {
      url = "https://www.vennaudio.com/downloads/Viper/Viper_Linux_1.6.1_15Nov2024_Release.zip";
      sha256 = "sha256-enFKPgn4jYci/JuqvEIMAnT/r7Aef9j1hpb1efRqIdI=";
    };
  };
}
