# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "01hjx2ga41sa0i0bq53rvrbinkaanmmfimzyn32z665wxagx7l5m";
    x86_64-linux = "05qxb96zwg8n2vv1wprqd1zyn8g6jcp3qhn4accjh2p7i52h3d0z";
    armv7l-linux = "07d8knab7haqsz4q9llcqb2i1qvdz6n939mip6sv9vi41cg3whbp";
    aarch64-linux = "0b2sa05i486liz9l52jx9l2khzjx3pas1clc6ijvjfwq6vvl8sji";
    x86_64-darwin = "1flwliwqpmqrl1dlsyymy9s5n068fg7d974mxcwmhmfrkskmkayx";
    aarch64-darwin = "1ryyzaff6kh9wqp0z8n5f0qmjlf4gvhc5vwdpgmv61c300pkyc11";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/skate/releases/download/v1.0.0/skate_1.0.0_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/skate/releases/download/v1.0.0/skate_1.0.0_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/skate/releases/download/v1.0.0/skate_1.0.0_Linux_arm.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/skate/releases/download/v1.0.0/skate_1.0.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/skate/releases/download/v1.0.0/skate_1.0.0_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/skate/releases/download/v1.0.0/skate_1.0.0_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "skate_1.0.0_Linux_i386";
    x86_64-linux = "skate_1.0.0_Linux_x86_64";
    armv7l-linux = "skate_1.0.0_Linux_arm";
    aarch64-linux = "skate_1.0.0_Linux_arm64";
    x86_64-darwin = "skate_1.0.0_Darwin_x86_64";
    aarch64-darwin = "skate_1.0.0_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "skate";
  version = "1.0.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./skate $out/bin/skate
  '';

  system = system;

  meta = {
    description = "A personal key value store 🛼";
    homepage = "https://charm.sh/";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
