#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i bash ../../../integrations/nix-shell --arg f 'ps: [ ps.bash ps.coreutils ]'

set -xeu

case "${1-}" in
  (-h|--help)
    echo "usage: UPDATE_NIX_OLD_VERSION=VERSION update-guard DAYS" >&2
    echo "  where UPDATE_NIX_OLD_VERSION contains a YYYY-MM-DD date, e.g. 0-unstable-2026-02-03" >&2
    exit 0
    ;;
  ('')
    echo "usage: UPDATE_NIX_OLD_VERSION=VERSION update-guard DAYS" >&2
    exit 2
    ;;
esac

cadence=$1
old_version=$UPDATE_NIX_OLD_VERSION

if [[ ! $old_version =~ ([0-9]{4}-[0-9]{2}-[0-9]{2}) ]]; then
  echo "couldn't extract date from UPDATE_NIX_OLD_VERSION=$old_version" >&2
  echo "not blocking update" >&2
  exit 0
fi

old_date=${BASH_REMATCH[1]}
old_seconds=$(date --date="$old_date" '+%s')
cadence_seconds=$((cadence * 24 * 60 * 60))

now_seconds=$(date '+%s')
next_update_seconds=$((old_seconds + cadence_seconds))

(( now_seconds > next_update_seconds ))
