(library (hangamod catalog)
  (export catalog-parse catalog-name catalog-index)
  (import (scheme base) (scheme char))

  (define (trim s)
    (let* ((n (string-length s))
           (a (let loop ((i 0))
                (if (and (< i n) (char-whitespace? (string-ref s i)))
                    (loop (+ i 1))
                    i)))
           (b (let loop ((i n))
                (if (and (> i a) (char-whitespace? (string-ref s (- i 1))))
                    (loop (- i 1))
                    i))))
      (substring s a b)))

  (define (catalog-parse csv)
    (let ((n (string-length csv)))
      (let loop ((i 0) (out '()))
        (if (>= i n)
            (reverse out)
            (let ((j (let scan ((k i))
                       (if (or (>= k n) (char=? (string-ref csv k) #\,))
                           k
                           (scan (+ k 1))))))
              (let ((name (trim (substring csv i j)))
                    (next (if (< j n) (+ j 1) n)))
                (if (string=? name "")
                    (loop next out)
                    (loop next (cons name out)))))))))

  (define (catalog-name entries index)
    (let loop ((xs entries) (i 0))
      (cond
       ((null? xs) "air")
       ((= i index) (car xs))
       (else (loop (cdr xs) (+ i 1))))))

  (define (catalog-index entries name)
    (let loop ((xs entries) (i 0))
      (cond
       ((null? xs) 0)
       ((string=? (car xs) name) i)
       (else (loop (cdr xs) (+ i 1)))))))
