(import (scheme base)
        (scheme write)
        (hangamod kit)
        (hangamod catalog)
        (hangamod wire))

(define (fail msg)
  (display "fail: ")
  (display msg)
  (newline)
  (error msg))

(define fields (kit-fields "a=1;mystery=nope\nb=2"))
(unless (= (length fields) 3) (fail "fields length"))
(unless (string=? (car (list-ref fields 0)) "a") (fail "fields a"))
(unless (string=? (cdr (list-ref fields 2)) "2") (fail "fields b"))
(unless (kit-flag "1") (fail "flag 1"))
(when (kit-flag "0") (fail "flag 0"))
(unless (string=? (kit-get "kind=none;jump=5" "kind") "none") (fail "get"))
(unless (= (kit-f32 "walk=10" "walk" 0.0) 10.0) (fail "f32"))
(define catalog (catalog-parse "air, tile ,lamp"))
(unless (= (length catalog) 3) (fail "catalog length"))
(unless (string=? (catalog-name catalog 1) "tile") (fail "catalog name"))
(unless (= (catalog-index catalog "lamp") 2) (fail "catalog index"))
(unless (= (checker-floor 0 -1 0) 2) (fail "floor below"))
(unless (= (checker-floor 0 0 0) 1) (fail "floor even"))
(unless (= (checker-floor 1 0 0) 2) (fail "floor odd"))
(unless (= (checker-floor 0 1 0) 0) (fail "floor air"))
(define probe (wire-voxel-probe "glass" #t))
(unless (string=? (wire-bag-text probe "name") "glass") (fail "wire text"))
(unless (wire-bag-flag probe "edit") (fail "wire flag"))
(let ((err (wire-fail "busy")))
  (unless (and (pair? err) (eq? (car err) 'fail) (string=? (cadr err) "busy"))
    (fail "wire fail")))
(display "hangamod kit ok")
(newline)
#t
