# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agent-run = {
    pname = "agent-run";
    version = "cc3ff756b421e185a564ecdcfadb03dbb58edc53";
    src = fetchgit {
      url = "https://git.jeffthecoder.xyz/public/agent-run.git";
      rev = "cc3ff756b421e185a564ecdcfadb03dbb58edc53";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-k4OVlH1au3b3X8ApIDPVhQLjGnmB81wACzbXo6Ni3UY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-k4OVlH1au3b3X8ApIDPVhQLjGnmB81wACzbXo6Ni3UY=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-07-13";
  };
  claude-code-bin-amd64-darwin = {
    pname = "claude-code-bin-amd64-darwin";
    version = "2.1.220";
    src = fetchurl {
      url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/2.1.220/darwin-x64/claude";
      sha256 = "sha256-3Ke+CqfT2SSDbUQODG2OPUfvPI5h+lgJtUuQFxcM4vM=";
    };
  };
  claude-code-bin-amd64-linux = {
    pname = "claude-code-bin-amd64-linux";
    version = "2.1.220";
    src = fetchurl {
      url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/2.1.220/linux-x64/claude";
      sha256 = "sha256-Z09h8g/zBvMQDPkgDkw2xLcCeLW+8ohFSYGblCqJyGM=";
    };
  };
  claude-code-bin-arm64-darwin = {
    pname = "claude-code-bin-arm64-darwin";
    version = "2.1.220";
    src = fetchurl {
      url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/2.1.220/darwin-arm64/claude";
      sha256 = "sha256-it3IV/P+ZNWgNor57lAyG1CvtKaRi6PvAYq4T1274IE=";
    };
  };
  claude-code-bin-arm64-linux = {
    pname = "claude-code-bin-arm64-linux";
    version = "2.1.220";
    src = fetchurl {
      url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/2.1.220/linux-arm64/claude";
      sha256 = "sha256-FZ5KUdeW878UZ3V3EA9++4RWEbHOrwwwy9jUZQ2UIYU=";
    };
  };
  codex = {
    pname = "codex";
    version = "rust-v0.146.0";
    src = fetchFromGitHub {
      owner = "openai";
      repo = "codex";
      rev = "rust-v0.146.0";
      fetchSubmodules = false;
      sha256 = "sha256-/kTIOX/klxm1nq2bJsBqS8f1jZZp2ilaTeULQFPJgDk=";
    };
    cargoLock."codex-rs/Cargo.lock" = {
      lockFile = ./. + "/sha256-_kTIOX_klxm1nq2bJsBqS8f1jZZp2ilaTeULQFPJgDk=/codex-rs/Cargo.lock";
      outputHashes = {
        "nucleo-0.5.0" = "sha256-Hm4SxtTSBrcWpXrtSqeO0TACbUxq3gizg1zD/6Yw/sI=";
        "runfiles-0.1.0" = "sha256-uJpVLcQh8wWZA3GPv9D8Nt43EOirajfDJ7eq/FB+tek=";
        "ratatui-0.29.0" = "sha256-HBvT5c8GsiCxMffNjJGLmHnvG77A6cqEL+1ARurBXho=";
        "crossterm-0.28.1" = "sha256-6qCtfSMuXACKFb9ATID39XyFDIEMFDmbx6SSmNe+728=";
        "tungstenite-0.27.0" = "sha256-VVHhk7l9J/sEmG3q/UuV/sQ3f+fGsmq5vumSy8vbMvw=";
        "tokio-tungstenite-0.28.0" = "sha256-V1xmnrfRWOcZZogelZEA4vvyMj2awCfHVA5/glQ6KAI=";
      };
    };
  };
  codex-bin-amd64-darwin = {
    pname = "codex-bin-amd64-darwin";
    version = "0.146.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.146.0/codex-x86_64-apple-darwin.zst";
      sha256 = "sha256-3C7UGBufh4+n7X0mjYb889/hGbasJwMf0R2H9ED6TX8=";
    };
  };
  codex-bin-amd64-linux = {
    pname = "codex-bin-amd64-linux";
    version = "0.146.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.146.0/codex-x86_64-unknown-linux-musl.zst";
      sha256 = "sha256-CtaXkiCN1GqEhqbuw1QpPvVHFZRuOmBmgwjqj5r8bA4=";
    };
  };
  codex-bin-arm64-darwin = {
    pname = "codex-bin-arm64-darwin";
    version = "0.146.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.146.0/codex-aarch64-apple-darwin.zst";
      sha256 = "sha256-u5nthJSsu6qtj/XdkyW/C820NwNxjMBALdne/qFAFOw=";
    };
  };
  codex-bin-arm64-linux = {
    pname = "codex-bin-arm64-linux";
    version = "0.146.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.146.0/codex-aarch64-unknown-linux-musl.zst";
      sha256 = "sha256-KEU9lfjTWRPjeJ0Q2qK1vLuCqmzMXwe7Zr12TuGHAgE=";
    };
  };
  create-tauri-app = {
    pname = "create-tauri-app";
    version = "create-tauri-app-v4.7.3";
    src = fetchFromGitHub {
      owner = "tauri-apps";
      repo = "create-tauri-app";
      rev = "create-tauri-app-v4.7.3";
      fetchSubmodules = false;
      sha256 = "sha256-/hegf8HHQQ0bFiA5cIFOS7XjJiNS2Fl5s12dok7KKK4=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-_hegf8HHQQ0bFiA5cIFOS7XjJiNS2Fl5s12dok7KKK4=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  cursor-cli-bin-amd64-darwin = {
    pname = "cursor-cli-bin-amd64-darwin";
    version = "2026.07.01-41b2de7";
    src = fetchurl {
      url = "https://downloads.cursor.com/lab/2026.07.01-41b2de7/darwin/x64/agent-cli-package.tar.gz";
      sha256 = "sha256-T3fzfWMLYsxzi9B1qAjYoHoAPcYYal330uqexz96cCc=";
    };
  };
  cursor-cli-bin-amd64-linux = {
    pname = "cursor-cli-bin-amd64-linux";
    version = "2026.07.01-41b2de7";
    src = fetchurl {
      url = "https://downloads.cursor.com/lab/2026.07.01-41b2de7/linux/x64/agent-cli-package.tar.gz";
      sha256 = "sha256-ww358eUYvWJuxYqXUo5ZeLzqbiNyGTqH2w04uFfcwZM=";
    };
  };
  cursor-cli-bin-arm64-darwin = {
    pname = "cursor-cli-bin-arm64-darwin";
    version = "2026.07.01-41b2de7";
    src = fetchurl {
      url = "https://downloads.cursor.com/lab/2026.07.01-41b2de7/darwin/arm64/agent-cli-package.tar.gz";
      sha256 = "sha256-SMvykcLijYG3n6DcvxirUL9Kx3ctDpqwlI7L1fWikVg=";
    };
  };
  cursor-cli-bin-arm64-linux = {
    pname = "cursor-cli-bin-arm64-linux";
    version = "2026.07.01-41b2de7";
    src = fetchurl {
      url = "https://downloads.cursor.com/lab/2026.07.01-41b2de7/linux/arm64/agent-cli-package.tar.gz";
      sha256 = "sha256-VVZqv+h6nSg0bVDH3HHPzw3GE132GYtGYeTV3Wh5bRE=";
    };
  };
  dingtalk-bin-amd64 = {
    pname = "dingtalk-bin-amd64";
    version = "8.1.0.6021101";
    src = fetchurl {
      url = "https://dtapp-pub.dingtalk.com/dingtalk-desktop/xc_dingtalk_update/linux_deb/Release/com.alibabainc.dingtalk_8.1.0.6021101_amd64.deb";
      sha256 = "sha256-7EkvEv6r7ONHAupH48/BoWSuLo2r3umwXnSjpeTeIdU=";
    };
  };
  dingtalk-bin-arm64 = {
    pname = "dingtalk-bin-arm64";
    version = "8.1.0.6021101";
    src = fetchurl {
      url = "https://dtapp-pub.dingtalk.com/dingtalk-desktop/xc_dingtalk_update/linux_deb/Release/com.alibabainc.dingtalk_8.1.0.6021101_arm64.deb";
      sha256 = "sha256-SEKPcpWGmBWQDDQYZ7u9J5sOsXI2QofdeLshzt+0me8=";
    };
  };
  kagent-bin-amd64-darwin = {
    pname = "kagent-bin-amd64-darwin";
    version = "v0.9.12";
    src = fetchurl {
      url = "https://github.com/kagent-dev/kagent/releases/download/v0.9.12/kagent-darwin-amd64";
      sha256 = "sha256-a6dtIrizOYV0UaKnK0Gr7WJr9MoHe6rhu+QuQEwRv1w=";
    };
  };
  kagent-bin-amd64-linux = {
    pname = "kagent-bin-amd64-linux";
    version = "v0.9.12";
    src = fetchurl {
      url = "https://github.com/kagent-dev/kagent/releases/download/v0.9.12/kagent-linux-amd64";
      sha256 = "sha256-r8Op8r3tQHU4TNbVnE1yfCLuSrkh15zlLrzgBO4WsaE=";
    };
  };
  kagent-bin-arm64-darwin = {
    pname = "kagent-bin-arm64-darwin";
    version = "v0.9.12";
    src = fetchurl {
      url = "https://github.com/kagent-dev/kagent/releases/download/v0.9.12/kagent-darwin-arm64";
      sha256 = "sha256-A5TqTcpQGXFMudJHNeyOsJC1OYY+Jky8eA4KE4mEdiw=";
    };
  };
  kagent-bin-arm64-linux = {
    pname = "kagent-bin-arm64-linux";
    version = "v0.9.12";
    src = fetchurl {
      url = "https://github.com/kagent-dev/kagent/releases/download/v0.9.12/kagent-linux-arm64";
      sha256 = "sha256-d7E4424zda3HK99jDfOiMR1q2ZBo0S9PcMB9WkS7a4Q=";
    };
  };
  kimi-code = {
    pname = "kimi-code";
    version = "0.31.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/@moonshot-ai/kimi-code/-/kimi-code-0.31.1.tgz";
      sha256 = "sha256-itcBS209TEdnuGy3e16ZkCzqM3p8FRHXT0er2CR6dLQ=";
    };
  };
  kwok = {
    pname = "kwok";
    version = "v0.8.0";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "kwok";
      rev = "v0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-SXiZiDor/+58JcKSBPHOWijvuCqdFmP2vRKJzLTriw8=";
    };
  };
  oh-my-pi-bin-amd64-darwin = {
    pname = "oh-my-pi-bin-amd64-darwin";
    version = "v17.2.2";
    src = fetchurl {
      url = "https://github.com/can1357/oh-my-pi/releases/download/v17.2.2/omp-darwin-x64";
      sha256 = "sha256-0Jm/sqGCcQ+uA/xeqnTn6XTmXzi4B5sbeYuXbRuVRKk=";
    };
  };
  oh-my-pi-bin-amd64-linux = {
    pname = "oh-my-pi-bin-amd64-linux";
    version = "v17.2.2";
    src = fetchurl {
      url = "https://github.com/can1357/oh-my-pi/releases/download/v17.2.2/omp-linux-x64";
      sha256 = "sha256-MG9VVjfWPc7YDP+y/pCNp+BUOJ+FjAcfMEvBfj7WIt4=";
    };
  };
  oh-my-pi-bin-arm64-darwin = {
    pname = "oh-my-pi-bin-arm64-darwin";
    version = "v17.2.2";
    src = fetchurl {
      url = "https://github.com/can1357/oh-my-pi/releases/download/v17.2.2/omp-darwin-arm64";
      sha256 = "sha256-M/WYC5YBfsIN0AL6xsiljW9kHtAY8gVO+4s8Fso0OAQ=";
    };
  };
  oh-my-pi-bin-arm64-linux = {
    pname = "oh-my-pi-bin-arm64-linux";
    version = "v17.2.2";
    src = fetchurl {
      url = "https://github.com/can1357/oh-my-pi/releases/download/v17.2.2/omp-linux-arm64";
      sha256 = "sha256-BE5AXcNA0YYroaY00g7FxgCkDg7yQiG72z2zc7H+OtU=";
    };
  };
  pi-agent = {
    pname = "pi-agent";
    version = "0.83.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@earendil-works/pi-coding-agent/-/pi-coding-agent-0.83.0.tgz";
      sha256 = "sha256-cJf+Szh2Ldp+x4AB57kEMMhJ+69xcyW/6BCXROMiVeY=";
    };
  };
  pi-agent-bin-amd64-darwin = {
    pname = "pi-agent-bin-amd64-darwin";
    version = "v0.83.0";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.83.0/pi-darwin-x64.tar.gz";
      sha256 = "sha256-mrEuQG5UW+Ex0SeamiwNXA1KPG6dhqUnAKehNaRFBBs=";
    };
  };
  pi-agent-bin-amd64-linux = {
    pname = "pi-agent-bin-amd64-linux";
    version = "v0.83.0";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.83.0/pi-linux-x64.tar.gz";
      sha256 = "sha256-sGJetiMZewr+IMhw0h7y80SB8VBOV3ffP2mKZsdjb18=";
    };
  };
  pi-agent-bin-arm64-darwin = {
    pname = "pi-agent-bin-arm64-darwin";
    version = "v0.83.0";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.83.0/pi-darwin-arm64.tar.gz";
      sha256 = "sha256-FH/DxFHsVDoVECryUc4xYHnI/K3+iuTT/+4gI0bpvtk=";
    };
  };
  pi-agent-bin-arm64-linux = {
    pname = "pi-agent-bin-arm64-linux";
    version = "v0.83.0";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.83.0/pi-linux-arm64.tar.gz";
      sha256 = "sha256-uE+QFmEMc43ZRA32L2SYgNvplR25enrpNsvykoUOmAI=";
    };
  };
  vagrant-vmware-utility = {
    pname = "vagrant-vmware-utility";
    version = "utility-v1.0.24";
    src = fetchFromGitHub {
      owner = "hashicorp";
      repo = "vagrant-vmware-desktop";
      rev = "utility-v1.0.24";
      fetchSubmodules = false;
      sha256 = "sha256-CdeJEVdQH3m/D8GsnkXGqaKcrWhqWM6vwcvs3VDA4Lc=";
    };
  };
}
