on:
  schedule:
    - cron: "5 4 * * 1"
      timezone: Europe/Amsterdam
  workflow_dispatch: {}

jobs:
  update:
    uses: https://git.toostveen.nl/tom/puntbestanden/.forgejo/workflows/update.yml@hoofdlijn
    secrets:
      GPG_PRIVKEY: ${{ secrets.GPG_PRIVKEY }}
