cmd_help() {
  echo -e ""
  echo -e "${BOLD}${SCRIPT_NAME}${RESET} — KVM VM import/export for virt-manager"
  echo -e ""
  echo -e "${BOLD}USAGE${RESET}"
  echo -e "  ${SCRIPT_NAME} <command> [options]"
  echo -e ""
  echo -e "${BOLD}COMMANDS${RESET}"
  echo -e "  ${GREEN}list${RESET}"
  echo -e "      List all defined VMs (running or not)."
  echo -e ""
  echo -e "  ${GREEN}export${RESET} <vm_name> [destination_dir] [--format gz|xz|zst] [--level 1-9]"
  echo -e "      Export a VM (XML + disks) to a compressed archive."
  echo -e "      • Gracefully stops the VM if running, restarts it after."
  echo -e "      • ZFS zvol disks are backed up via zfs snapshot + send (efficient)."
  echo -e "      • Falls back to qemu-img convert if 'zfs' command is unavailable."
  echo -e "      • Default destination: ${DEFAULT_EXPORT_DIR}"
  echo -e "      • Default format: gz (level 6) — xz for best ratio, zst for best speed."
  echo -e ""
  echo -e "  ${GREEN}import${RESET} <archive.tar.gz|xz|zst> [--pool <pool_name>] [--name <new_name>] [--zfs-pool <pool>]"
  echo -e "      Import a VM from an archive created by this script."
  echo -e "      • Disks are restored into the target libvirt pool."
  echo -e "      • Default pool: ${DEFAULT_POOL}"
  echo -e "      • Use --name <new_name> to rename the VM on import."
  echo -e "      • Use --zfs-pool <pool> to restore zvols into a different ZFS pool."
  echo -e ""
  echo -e "  ${GREEN}help${RESET}"
  echo -e "      Show this help."
  echo -e ""
  echo -e "${BOLD}EXAMPLES${RESET}"
  echo -e "  ${SCRIPT_NAME} list"
  echo -e "  sudo ${SCRIPT_NAME} export myVM ~/archives/"
  echo -e "  sudo ${SCRIPT_NAME} export myVM ~/archives/ --format xz --level 9"
  echo -e "  sudo ${SCRIPT_NAME} export myVM ~/archives/ --format zst --level 3"
  echo -e "  sudo ${SCRIPT_NAME} import ~/archives/myVM_20260101_120000.tar.gz"
  echo -e "  sudo ${SCRIPT_NAME} import ~/archives/myVM_20260101_120000.tar.gz --pool ssd-pool"
  echo -e "  sudo ${SCRIPT_NAME} import ~/archives/myVM_20260101_120000.tar.gz --name myVM-clone"
  echo -e "  sudo ${SCRIPT_NAME} import ~/archives/myVM_20260101_120000.tar.gz --zfs-pool ssd"
  echo -e "  sudo ${SCRIPT_NAME} import ~/archives/myVM_20260101_120000.tar.gz --zfs-pool ssd --name myVM-clone"
  echo -e ""
  echo -e "${BOLD}DEPENDENCIES${RESET}"
  echo -e "  Required : virsh, qemu-img, tar, gzip, pv, xz, zstd"
  echo -e "  Required for zvols : zfs"
  echo -e "  On NixOS : nix-shell -p libvirt qemu pv xz zstd"
  echo -e ""
}
