#!/bin/sh

set -eu

die() {
  echo "$1"
  return 1
}

test_01_trivial() {
  bunpen --bunpen-path / /usr/bin/env true
}

test_02_invoke_by_path() {
  bunpen --bunpen-path / true
}

test_03_errors_on_invalid_file() {
  bunpen --bunpen-path / this_file_does_not_exist && return 1 || true
}

test_04_disable_by_env_var() {
  BUNPEN_DISABLE=1 bunpen /usr/bin/env true
}

test_05_propagates_rc_when_disabled() {
  BUNPEN_DISABLE=1 bunpen /usr/bin/env false && return 1 || true
}

test_06_propagates_rc() {
  bunpen --bunpen-path / /usr/bin/env false && return 1 || true
}

test_07_propagates_rc() {
  bunpen --bunpen-path / false && return 1 || true
}

test_08_forwards_stdout_when_disabled() {
  local stdout=$(BUNPEN_DISABLE=1 bunpen --bunpen-path / echo "hello")
  test "$stdout" = "hello"
}

test_09_forwards_stdout() {
  local stdout=$(bunpen --bunpen-path / echo "hello")
  test "$stdout" = "hello"
}

rc=0
for f in $(declare -F); do
  if [[ "$f" =~ test_* ]]; then
    echo -n "$f: ..."
    if "$f"; then
      echo " SUCCESS"
    else
      rc=1
      echo " FAIL"
    fi
  fi
done

exit "$rc"
