name: Nix

on:
  push:
  workflow_dispatch:

env:
  NIX_ABORT_ON_WARN: "1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - aarch64-darwin
          - aarch64-linux
          - x86_64-linux

    runs-on: [self-hosted, "${{ matrix.system }}"]

    steps:
      - name: Check flake
        run: |
          nix flake check --keep-going --print-build-logs github:${{ github.repository }}/${{ github.sha }}
