name: Update

on:
  schedule:
    - cron: "0 19 * * *" # 11am PST
  workflow_dispatch:

permissions:
  contents: write

env:
  NIXPKGS_ALLOW_UNFREE: "1"

jobs:
  update:
    strategy:
      fail-fast: false
      matrix:
        system:
          - aarch64-darwin
          # - aarch64-linux
          - x86_64-linux

    runs-on: [self-hosted, "${{ matrix.system }}"]

    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" | tee -a "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Configure git commit author
        run: |
          git config --local user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --local user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - id: attrs
        name: Get package attributes to update
        run: |
          set -o pipefail
          nix eval --raw --impure --file ./internal/update-script-attrs.nix | tee "$GITHUB_OUTPUT"
        env:
          FLAKE_URI: ${{ github.workspace }}

      - name: Run update-script
        run: |
          set -o pipefail
          exit_code=0
          while read -r attr; do
            printf "\n\n==== Updating %s ====\n" "$attr" >&2
            if ! UPDATE_NIX_ATTR_PATH="$attr" nix run --file ./internal/update-script.nix; then
              echo "::error::Update failed for $attr" >&2
              exit_code=1
            fi
          done <<<"$(jq --raw-output '.[]' <<<"$UPDATE_NIX_ATTRS")"
          exit $exit_code
        env:
          FLAKE_URI: ${{ github.workspace }}
          UPDATE_NIX_ATTRS: ${{ steps.attrs.outputs.attrs }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
