[
  [ "aasgBrotlifyHook" ]
  [ "dma" ]
  [ "drep" ]
  [ "dyndnsc" ]
  [ "esbuild" ]
  [ "guile-commonmark" ]
  [ "guile-json" ]
  [ "haunt" ]
  [ "iwgtk" ]
  [ "linuxPackages" "rtl8723bu" ]
  [ "linuxPackages_latest" "rtl8723bu" ]
  [ "makeJobScript" ]
  [ "matrix-appservice-irc" ]
  [ "prometheus-bird-exporter" ]
  [ "python3Packages" "daemonocle" ]
  [ "python3Packages" "json-logging" ]
  [ "shellharden" ]
  [ "trust-dns" ]
]
