#!/bin/sh

set -e

cur="$(grep -E '^  version = ' pkgs/firefox-darwin/default.nix|cut -d'"' -f2 | head -n1)"
version="$(curl -s https://www.mozilla.org/en-US/firefox/releases/ | pup 'ol.c-release-list a text{}' | sort -nr | head -n1)"

if [ "$cur" = "$version" ]; then
  echo "Already up to date ($version)"
  exit 0
fi

ffhash="$(nix-prefetch-url "https://download-installer.cdn.mozilla.net/pub/firefox/releases/${version}/mac/en-GB/Firefox%20${version}.dmg" --name firefox-$version | head -n1)"
sed -ibk "s|^  version =.*|  version = \"$version\";|" pkgs/firefox-darwin/default.nix
sed -ibk "s|^    sha256 = .*|    sha256 = \"$ffhash\";|" pkgs/firefox-darwin/default.nix

nix-build -A firefox-darwin

rm pkgs/firefox-darwin/default.nixbk

git add pkgs/firefox-darwin/default.nix
git commit -m "firefox-darwin: $cur -> $version"