#!/usr/bin/env nix-shell
#! nix-shell -i bash -p curl jq nix

set -euo pipefail

VERSION=$(curl -s https://api.mefrp.com/api/auth/products | jq -r '.data[] | select(.productId == "MEFrp-Core") | .version')
echo "VERSION: $VERSION"

ALIST_API="https://drive.mcsl.com.cn/api/fs/list"
SOURCE="Lanzou"
LIST_JSON=$(curl -s -G "$ALIST_API" --data-urlencode "path=/ME-Frp/$SOURCE/MEFrp-Core/$VERSION")

declare -A ARCH_MAP=(
    ["x86_64-linux"]="amd64"
    ["aarch64-linux"]="arm64"
    ["i686-linux"]="386"
    ["riscv64-linux"]="riscv64"
    ["armv7l-linux"]="arm_hf"
    ["loongarch64-linux"]="loong64"
    ["mips64-linux"]="mips64"
    ["mips64el-linux"]="mips64le"
    ["mips-linux"]="mips"
    ["mipsel-linux"]="mipsle"
    ["s390x-linux"]="s390x"
    ["arm-linux"]="arm"
)

download_and_hash() {
    local url="$1"
    local temp_file=$(mktemp)
    trap "rm -f $temp_file" RETURN
    
    curl -sL "$url" -o "$temp_file"
    nix hash file --sri --type sha256 "$temp_file"
}

cat <<EOF > sources.nix
# This file is generated by update.sh. Do not edit!
{
  version = "$VERSION";
  platforms = {
EOF

for nix_arch in "${!ARCH_MAP[@]}"; do
    core_arch=${ARCH_MAP[$nix_arch]}
    
    TARGET_NAME="mefrpc_linux_${core_arch}_${VERSION}.tar"
    FILE_INFO=$(echo "$LIST_JSON" | jq -r ".data.content[] | select(.name == \"$TARGET_NAME\")")
    
    if [ -n "$FILE_INFO" ]; then
        DOWNLOAD_URL="https://drive.mcsl.com.cn/d/ME-Frp/$SOURCE/MEFrp-Core/$VERSION/$TARGET_NAME"
        
        echo "Downloading $nix_arch ($core_arch)..."
        HASH=$(download_and_hash "$DOWNLOAD_URL")
        echo "Found $nix_arch ($core_arch): $HASH"
        
        cat <<EOF >> sources.nix
    "$nix_arch" = {
      arch = "$core_arch";
      hash = "$HASH";
    };
EOF
    else
        echo "Warning: No file found for $nix_arch"
    fi
done

cat <<EOF >> sources.nix
  };
}
EOF
