name: "Build and populate cache"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        include:
          - nixpkgs: unstable
            system: x86_64-linux
            runner: ubuntu-24.04
          - nixpkgs: unstable
            system: aarch64-linux
            runner: ubuntu-24.04-arm
          - nixpkgs: unstable
            system: aarch64-darwin
            runner: macos-15

    name: ${{ matrix.system }} / ${{ matrix.nixpkgs }}
    runs-on: ${{ matrix.runner }}
    env:
      nurRepo: duncannah
      cachixName: duncannah-nur

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-${{ matrix.nixpkgs }}.tar.gz"
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org https://duncannah-nur.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= duncannah-nur.cachix.org-1:miatqAoEE+7++VDIf6BxFOFe2Or4JJj7ixeKrd9TXdc=

      - name: Show nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

      - name: Setup cachix
        uses: cachix/cachix-action@v17
        with:
          name: ${{ env.cachixName }}
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Check evaluation
        run: |
          nix-env -f . -qa \* --meta --xml \
            --allowed-uris https://static.rust-lang.org \
            --option restrict-eval true \
            --option allow-import-from-derivation true \
            --drv-path --show-trace \
            -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
            -I $PWD
      - name: Build nix packages
        run: nix shell -f '<nixpkgs>' nix-build-uncached -c nix-build-uncached ci.nix -A cacheOutputs

      - name: Trigger NUR update
        run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ env.nurRepo }}"
