# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bash-prompt = {
    pname = "bash-prompt";
    version = "0.0.1";
    src = fetchFromGitHub {
      owner = "Freed-Wu";
      repo = "bash-prompt";
      rev = "0.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-64KFbS63jyPhl4z0tsS+7vg6b2XrL2uIzhzWtOepu5k=";
    };
  };
  lsp-tree-sitter = {
    pname = "lsp-tree-sitter";
    version = "0.2.9";
    src = fetchurl {
      url = "https://pypi.org/packages/source/l/lsp_tree_sitter/lsp_tree_sitter-0.2.9.tar.gz";
      sha256 = "sha256-a9N8+LZ1MujL1+7IZkj5PwVJxaPXGsH+9SsVwn5nZxo=";
    };
  };
  manpager = {
    pname = "manpager";
    version = "0.0.3";
    src = fetchFromGitHub {
      owner = "Freed-Wu";
      repo = "manpager";
      rev = "0.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-oqAgY/9qZ2d8p74qqFEM2VxT9ohV3CR8bcBCbyHlcOo=";
    };
  };
  mulimgviewer = {
    pname = "mulimgviewer";
    version = "3.9.10";
    src = fetchurl {
      url = "https://pypi.org/packages/source/m/mulimgviewer/mulimgviewer-3.9.10.tar.gz";
      sha256 = "sha256-srBgon7/yrbvV6m0Em67iiA1KLo6b2QTJjN786bZIck=";
    };
  };
  mutt-language-server = {
    pname = "mutt-language-server";
    version = "0.1.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/m/mutt_language_server/mutt_language_server-0.1.1.tar.gz";
      sha256 = "sha256-nhbnXu4250jHz5nENsH1RE6GGyTddHY6TH5VFIT9jbI=";
    };
  };
  pyrime = {
    pname = "pyrime";
    version = "0.2.3";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pyrime/pyrime-0.2.3.tar.gz";
      sha256 = "sha256-M5BEMvaWmTCh+DE2LrW5WqiOCXqMy2MlvAdCmK+GJ+w=";
    };
  };
  requirements-language-server = {
    pname = "requirements-language-server";
    version = "0.1.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/r/requirements_language_server/requirements_language_server-0.1.2.tar.gz";
      sha256 = "sha256-cFRPXqq7+hmR+EJgU2uUZ2pO6s2ZHHTHmr1B4Tkuuso=";
    };
  };
  sublime-syntax-language-server = {
    pname = "sublime-syntax-language-server";
    version = "0.0.4";
    src = fetchurl {
      url = "https://pypi.org/packages/source/s/sublime-syntax-language-server/sublime-syntax-language-server-0.0.4.tar.gz";
      sha256 = "sha256-bC3gVsjJMccA5vxdwV6/DNTn81+RCAprjLgBMQAjyzs=";
    };
  };
  termux-language-server = {
    pname = "termux-language-server";
    version = "0.1.3";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/termux_language_server/termux_language_server-0.1.3.tar.gz";
      sha256 = "sha256-oY8iBtVmxfLaLjkfpdNu29BGcKJD9ayeEPaxiTbuWBo=";
    };
  };
  tmux-language-server = {
    pname = "tmux-language-server";
    version = "0.1.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tmux_language_server/tmux_language_server-0.1.1.tar.gz";
      sha256 = "sha256-I93A8M4bOBenz4uiiomMdp5ba/np0EDemC4poI1q0ts=";
    };
  };
  translate-shell = {
    pname = "translate-shell";
    version = "0.0.59";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/translate_shell/translate_shell-0.0.59.tar.gz";
      sha256 = "sha256-3hRSLKA5aI7bgtCAafxwj7WeQO8GmIwTEeJoSp3CvHs=";
    };
  };
  tree-sitter-muttrc = {
    pname = "tree-sitter-muttrc";
    version = "0.1.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tree_sitter_muttrc/tree_sitter_muttrc-0.1.1.tar.gz";
      sha256 = "sha256-gb7kIpnHVpuF2tHjbPLDtqeYUlXRhgk2+bOnhZ9F6jg=";
    };
  };
  tree-sitter-requirements = {
    pname = "tree-sitter-requirements";
    version = "v0.6.1";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-requirements";
      rev = "v0.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-jLG+DcdVfC2Rj8SYL3WTBWreOLJWwtxpPxzyvJl77d4=";
    };
  };
  tree-sitter-tmux = {
    pname = "tree-sitter-tmux";
    version = "0.1.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tree_sitter_tmux/tree_sitter_tmux-0.1.1.tar.gz";
      sha256 = "sha256-N/BB6HC9fRdtUbY2Z2g0xOYiG0buJzF/lbEbDP2hs8I=";
    };
  };
  tree-sitter-zathurarc = {
    pname = "tree-sitter-zathurarc";
    version = "0.1.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tree_sitter_zathurarc/tree_sitter_zathurarc-0.1.2.tar.gz";
      sha256 = "sha256-jGLqa41i4RWci2qONoGksZCCzbWvbKN7PBfG9OQPL6g=";
    };
  };
  undollar = {
    pname = "undollar";
    version = "0.0.5";
    src = fetchFromGitHub {
      owner = "Freed-Wu";
      repo = "undollar";
      rev = "0.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-HyWZz7wYnKDID8zs/a96YByjoPO7vKRAPZg6rL17sQ4=";
    };
  };
  windows10-themes = {
    pname = "windows10-themes";
    version = "3.2.1";
    src = fetchFromGitHub {
      owner = "B00merang-Project";
      repo = "Windows-10";
      rev = "3.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-O8sKYHyr1gX1pQRTTSw/kHREJ5MujbVjmLHJHbrUcRM=";
    };
  };
  xilinx-language-server = {
    pname = "xilinx-language-server";
    version = "0.0.6";
    src = fetchurl {
      url = "https://pypi.org/packages/source/x/xilinx_language_server/xilinx_language_server-0.0.6.tar.gz";
      sha256 = "sha256-LG70XPEf7dwuIogr6+ucQcAjJT2wxIqCKQpeXkYPWEI=";
    };
  };
  zathura-language-server = {
    pname = "zathura-language-server";
    version = "0.1.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/z/zathura_language_server/zathura_language_server-0.1.2.tar.gz";
      sha256 = "sha256-zT/uE16LcVLbXt1dpvtjRAMwXjXBhnDsc5f0XmlOiHE=";
    };
  };
}
