# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bash-prompt = {
    pname = "bash-prompt";
    version = "0.0.1";
    src = fetchFromGitHub {
      owner = "Freed-Wu";
      repo = "bash-prompt";
      rev = "0.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-64KFbS63jyPhl4z0tsS+7vg6b2XrL2uIzhzWtOepu5k=";
    };
  };
  expect-language-server = {
    pname = "expect-language-server";
    version = "0.0.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/e/expect-language-server/expect-language-server-0.0.1.tar.gz";
      sha256 = "sha256-7L2h91ZpB+VhUlP5kOa4lpKzr8LnkjXcP8I45M9Lrgk=";
    };
  };
  manpager = {
    pname = "manpager";
    version = "0.0.3";
    src = fetchFromGitHub {
      owner = "Freed-Wu";
      repo = "manpager";
      rev = "0.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-oqAgY/9qZ2d8p74qqFEM2VxT9ohV3CR8bcBCbyHlcOo=";
    };
  };
  mulimgviewer = {
    pname = "mulimgviewer";
    version = "3.9.10";
    src = fetchurl {
      url = "https://pypi.org/packages/source/m/mulimgviewer/mulimgviewer-3.9.10.tar.gz";
      sha256 = "sha256-srBgon7/yrbvV6m0Em67iiA1KLo6b2QTJjN786bZIck=";
    };
  };
  mutt-language-server = {
    pname = "mutt-language-server";
    version = "0.0.17";
    src = fetchurl {
      url = "https://pypi.org/packages/source/m/mutt_language_server/mutt_language_server-0.0.17.tar.gz";
      sha256 = "sha256-2NL+XfSAe3MjdFUyeZyv6CmLBsYxJHb6ky2CKmWsGe0=";
    };
  };
  pyrime = {
    pname = "pyrime";
    version = "0.1.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pyrime/pyrime-0.1.2.tar.gz";
      sha256 = "sha256-nPnYIEAhf8O7rHp/NcsoEbaKFLg2eWZFypjmlM/y+Qc=";
    };
  };
  requirements-language-server = {
    pname = "requirements-language-server";
    version = "0.0.22";
    src = fetchurl {
      url = "https://pypi.org/packages/source/r/requirements_language_server/requirements_language_server-0.0.22.tar.gz";
      sha256 = "sha256-R/dvvv0KIpZQNOQMXlqLW2TfcKSb5h2qHNPkQfQeC/4=";
    };
  };
  sublime-syntax-language-server = {
    pname = "sublime-syntax-language-server";
    version = "0.0.4";
    src = fetchurl {
      url = "https://pypi.org/packages/source/s/sublime-syntax-language-server/sublime-syntax-language-server-0.0.4.tar.gz";
      sha256 = "sha256-bC3gVsjJMccA5vxdwV6/DNTn81+RCAprjLgBMQAjyzs=";
    };
  };
  termux-language-server = {
    pname = "termux-language-server";
    version = "0.0.31";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/termux_language_server/termux_language_server-0.0.31.tar.gz";
      sha256 = "sha256-PtUWZvulzXgn9sqfedSlX4aS+Gdq44XTE9VyQi0+XgM=";
    };
  };
  tmux-language-server = {
    pname = "tmux-language-server";
    version = "0.0.17";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tmux_language_server/tmux_language_server-0.0.17.tar.gz";
      sha256 = "sha256-PUmfq4CJ0V9BhBwYCX5AfaZYy7lvNo2/zF11h64ZM4c=";
    };
  };
  translate-shell = {
    pname = "translate-shell";
    version = "0.0.59";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/translate_shell/translate_shell-0.0.59.tar.gz";
      sha256 = "sha256-3hRSLKA5aI7bgtCAafxwj7WeQO8GmIwTEeJoSp3CvHs=";
    };
  };
  tree-sitter-bash = {
    pname = "tree-sitter-bash";
    version = "v0.25.0";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-bash";
      rev = "v0.25.0";
      fetchSubmodules = false;
      sha256 = "sha256-vRaN/mNfpR+hdv2HVS1bzaW0o+HGjizRFsk3iinICJE=";
    };
  };
  tree-sitter-muttrc = {
    pname = "tree-sitter-muttrc";
    version = "0.0.6";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tree_sitter_muttrc/tree_sitter_muttrc-0.0.6.tar.gz";
      sha256 = "sha256-BnxsTaOSSDImVs2BT3FmT/M6Gjzga4/MH24yFPt0pu0=";
    };
  };
  tree-sitter-requirements = {
    pname = "tree-sitter-requirements";
    version = "v0.5.0";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-requirements";
      rev = "v0.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-YszXgZZSMiWBf2vIij8+5GA1FY3Ipeoow8dkrzkLl78=";
    };
  };
  tree-sitter-tmux = {
    pname = "tree-sitter-tmux";
    version = "0.0.4";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tree_sitter_tmux/tree_sitter_tmux-0.0.4.tar.gz";
      sha256 = "sha256-yGEMIItsfAV4bVLsa18GkS2lMxHmqxVbE3oimC8NfFE=";
    };
  };
  tree-sitter-zathurarc = {
    pname = "tree-sitter-zathurarc";
    version = "0.0.9";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tree_sitter_zathurarc/tree_sitter_zathurarc-0.0.9.tar.gz";
      sha256 = "sha256-a9UfhfiCqe6/kSVodetNhcgZKAtofRDRGvdQQ3aA/lI=";
    };
  };
  undollar = {
    pname = "undollar";
    version = "0.0.5";
    src = fetchFromGitHub {
      owner = "Freed-Wu";
      repo = "undollar";
      rev = "0.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-HyWZz7wYnKDID8zs/a96YByjoPO7vKRAPZg6rL17sQ4=";
    };
  };
  windows10-themes = {
    pname = "windows10-themes";
    version = "3.2.1";
    src = fetchFromGitHub {
      owner = "B00merang-Project";
      repo = "Windows-10";
      rev = "3.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-O8sKYHyr1gX1pQRTTSw/kHREJ5MujbVjmLHJHbrUcRM=";
    };
  };
  xilinx-language-server = {
    pname = "xilinx-language-server";
    version = "0.0.4";
    src = fetchurl {
      url = "https://pypi.org/packages/source/x/xilinx-language-server/xilinx-language-server-0.0.4.tar.gz";
      sha256 = "sha256-Qs2/RO4i0WHm4dmZh6iHmCLGkgTPLIBErc1n8YRvuk8=";
    };
  };
  zathura-language-server = {
    pname = "zathura-language-server";
    version = "0.0.14";
    src = fetchurl {
      url = "https://pypi.org/packages/source/z/zathura_language_server/zathura_language_server-0.0.14.tar.gz";
      sha256 = "sha256-ndrKPy1mrF/UJ4mSz05n8F3gQn4zMd+XnmGpS1PBfRw=";
    };
  };
}
