## Tab bar
tab_bar_edge top
tab_bar_margin_width 4
tab_bar_margin_height 8 0
tab_bar_style custom
tab_separator ""
tab_title_template "{fmt.fg._38296e}{fmt.bg.default}{fmt.fg.white}{fmt.bg._38296e}{(f'{index} {title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 13 else f'{index} {title}')}{fmt.fg._38296e}{fmt.bg.default}{fmt.fg.default}{fmt.bg.default}{fmt.fg.default}{fmt.bg.default} {fmt.fg.white}{fmt.bg.default}"
active_tab_title_template "{fmt.fg._f4d03e}{fmt.bg.default}{fmt.fg._38296e}{fmt.bg._f4d03e}{(f'{index} {title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 13 else f'{index} {title}')}{fmt.fg._f4d03e}{fmt.bg.default}{fmt.fg.default}{fmt.bg.default}{fmt.fg.default}{fmt.bg.default} {fmt.fg._38296e}{fmt.bg.default}"

### Controls
map ctrl+t launch --cwd=last_reported --type=tab
map ctrl+w close_tab

map ctrl+r set_tab_title

map alt+left previous_tab
map alt+right next_tab

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 10
