# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "0vn4kwy3h44w7d6izrixxiki28sqwh74arigbkz9w5cbgj7rnikj";
    x86_64-linux = "0jw4j80zj820vzliszqg0c933vb5281pmqjjgzs9vrrzpxbazhia";
    aarch64-linux = "1wpx3s3wgmij35xlr9aiy9l9dfz09jff6fw3jk3qwq4xyn79lfgb";
    x86_64-darwin = "111l047s1pq02zm8xxvq9rhmlzy69x1ni37kbnkssyngmnvsb332";
    aarch64-darwin = "14mza8vzgq86lq3qr9yy1v9x2zryw6jz0jkwa2qrx1g7005w5g9m";
  };

  urlMap = {
    i686-linux = "https://download.runway.horse/runway/1.39.0/runway_Linux_i386.tar.gz";
    x86_64-linux = "https://download.runway.horse/runway/1.39.0/runway_Linux_x86_64.tar.gz";
    aarch64-linux = "https://download.runway.horse/runway/1.39.0/runway_Linux_arm64.tar.gz";
    x86_64-darwin = "https://download.runway.horse/runway/1.39.0/runway_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://download.runway.horse/runway/1.39.0/runway_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "runway_Linux_i386";
    x86_64-linux = "runway_Linux_x86_64";
    aarch64-linux = "runway_Linux_arm64";
    x86_64-darwin = "runway_Darwin_x86_64";
    aarch64-darwin = "runway_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "runway";
  version = "1.39.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./runway $out/bin/runway
  '';

  meta = {
    description = "The Runway CLI.";
    homepage = "https://www.runway.horse/";
    license = lib.licenses.unfree;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
