---
name: Updaters
'on':
  schedule:
    - cron: '13 1 * * *'  # 01:13 UTC every day
  workflow_dispatch:

jobs:
  updater:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    strategy:
      max-parallel: 1
      matrix:
        include:
          - package: llr
          - package: mkvcleaner
          - package: goprocmgr
          # - package: g90updatefw
          - package: dmsShellPlugins.emojiLauncher
            extraArgs: '--version=branch=main'
          - package: dmsShellPlugins.nixPackageRunner
            extraArgs: '--version=branch=main'
          - package: dmsShellPlugins.quickCapture

    steps:
      - uses: actions/checkout@v7
        with:
          ref: main
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v17
        with:
          name: etu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: 'Update ${{ matrix.package }}'
        run: 'nix shell nixpkgs#nix-update -c nix-update ${{ matrix.package }} ${{ matrix.extraArgs }}'

      - name: 'Build ${{ matrix.package }}'
        run: 'nix build .#${{ matrix.package }}'

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "cron(${{ matrix.package }}): Update ${{ matrix.package }} package"
