diff --git a/Makefile b/Makefile
index 27b0e9a..eb95272 100644
--- a/Makefile
+++ b/Makefile

 ############## Main objects and libraries #######

@@ -62,12 +62,12 @@ DUMMYOBS=read_dalton_dummy.o read_molcas_dummy.o

 ############## Dalton and SEWARD ################
 # no Dalton and SEWARD support
-#LIBS = $(LALIB)
-#OPTOBS = $(DUMMYOBS)
+LIBS = $(LALIB)
+OPTOBS = $(DUMMYOBS)

 # activate direct reading of Dalton and Seward files
 #LIBS = $(COLUMBUS)/libmolcas_col.a $(COLUMBUS)/colib.a $(COLUMBUS)/blaswrapper.a  $(LALIB)
-OPTOBS = read_dalton.o read_molcas.o
+#OPTOBS = read_dalton.o read_molcas.o

 ############## Compilation routines #############

@@ -80,13 +80,10 @@ OPTOBS = read_dalton.o read_molcas.o

 wfoverlap.x : main.f90 $(MAINOBS) $(OPTOBS) iomod.o
 	$(FC) $(FCFLAGS) $(LINKFLAGS) $(PROFILE) $^ -o $@ $(LIBS)
-	cp $@ ../../bin

 # executable that is linked to dummy I/O interfaces and that reads only ASCII files
 wfoverlap_ascii.x : main.f90 $(MAINOBS) $(DUMMYOBS) iomod.o
 	$(FC) $(FCFLAGS) $(LINKFLAGS) $(PROFILE) $^ -o $@ $(LALIB)
-	cp $@ ../../bin
-	ln -fs $@ ../../bin/wfoverlap.x

 alloc:
 	./write_allocmod.pl > my_alloc.f90
