name: "Build and Populate Cache"
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '10 4 * * *'
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-15
        nurRepo:
          - anntnzrb
        cachixName:
          - anntnzrb
        nixPath:
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: "${{ matrix.nixPath }}"
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Show nixpkgs Version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

    - name: Setup cachix
      uses: cachix/cachix-action@v17
      with:
        name: ${{ matrix.cachixName }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Check Nix Evaluation
      run: |
        nix-env -f . -qa \* --meta --xml \
          --allowed-uris https://static.rust-lang.org \
          --option restrict-eval true \
          --option allow-import-from-derivation true \
          --drv-path --show-trace \
          -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
          -I $PWD

    - name: Build Nix Packages
      run: nix shell -f '<nixpkgs>' nix-build-uncached -c nix-build-uncached ci.nix -A cacheOutputs

    - name: Trigger NUR update
      if: matrix.os == 'ubuntu-latest'
      run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"
