#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i bash ../../../../integrations/nix-shell --arg f 'ps: [ ps.bash ps.curl ps.gnused ps.jq ps.nix-prefetch-git ps.nix-prefetch-github ]'

set -eu

usage() {
  echo "USAGE: nixpkgs-bootstrap-updater BRANCH"
}

branch=
parseArgs() {
  while [ "$#" -ne 0 ]; do
    local arg=$1
    shift
    case $arg in
      (--help)
        usage
        exit 0
        ;;
      (*)
        if [ -z "$branch" ]; then
          branch=$arg
        else
          usage
          exit 1
        fi
        ;;
    esac
  done
  if [ -z "$branch" ]; then
    usage
    exit 1
  fi
}

jsonGetField() {
  local json=$1
  local field=$2
  echo "$json" | jq --exit-status --raw-output ".$field"
}

main() {
  local branch=$1
  local attrPos=$(nix-instantiate --raw --eval -A "$UPDATE_NIX_ATTR_PATH.meta.position")
  local nixFile=${attrPos%:[0-9]*}

  local oldVersion=$UPDATE_NIX_OLD_VERSION
  if [[ -z "$oldVersion" ]]; then
    oldVersion=$(nix-instantiate --raw --eval -A "$UPDATE_NIX_ATTR_PATH.version")
  fi
  local oldRev=$(nix-instantiate --raw --eval -A "$UPDATE_NIX_ATTR_PATH.src.rev")
  local oldHash=$(nix-instantiate --raw --eval -A "$UPDATE_NIX_ATTR_PATH.src.hash")

  test -n "$oldVersion" -a -n "$oldRev" -a -n "$oldHash"

  local prefetchData=$(nix-prefetch-github --json --meta --rev "$branch" NixOS nixpkgs)

  local rev=$(jsonGetField "$prefetchData" src.rev)
  local nixHash=$(jsonGetField "$prefetchData" src.hash)
  local commitDate=$(jsonGetField "$prefetchData" meta.commitDate)

  test -n "$rev" -a -n "$nixHash" -a -n "$commitDate"
  sed \
    -e "s|\"$oldHash\"|\"$nixHash\"|" \
    -e "s|\"$oldVersion\"|\"unstable-$commitDate\"|" \
    -e "s|\"$oldRev\"|\"$rev\"|" \
    -i "$nixFile"
}

args=("$@")
parseArgs "${args[@]}"
echo "nixpkgs-bootstrap-updater" "${args[@]}"
set -x
main "$branch"
