name: checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-26
      fail-fast: false
    runs-on: ${{ matrix.image }}
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@48b6d3dd393260451050b0e6b78bc51fc483d500 # v1.58.0

      - name: Check flake
        run: nix flake check --max-jobs 1

      - name: Check evaluation
        run: |
          nix-env -f . -qa \* --meta --json \
            --allowed-uris https://static.rust-lang.org \
            --option restrict-eval true \
            --option allow-import-from-derivation true \
            --drv-path --show-trace \
            -I "$PWD"

  build:
    needs: check
    strategy:
      matrix:
        nix:
          - nixpkgs-unstable.tar.gz
          - nixos-unstable.tar.gz
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-26
      fail-fast: false
    runs-on: ${{ matrix.image }}
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@48b6d3dd393260451050b0e6b78bc51fc483d500 # v1.58.0
        with:
          shell: check

      - name: Build packages
        run: |
          nix-fast-build \
            --skip-cached \
            --no-nom \
            --override-input nixpkgs "https://github.com/NixOS/nixpkgs/archive/refs/heads/${{ matrix.nix }}" \
            --flake ".#packages.$(nix eval --raw --impure --expr builtins.currentSystem)"

  fix:
    needs: check
    if: >-
      always() &&
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      (needs.check.result == 'failure' || needs.check.result == 'cancelled')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@48b6d3dd393260451050b0e6b78bc51fc483d500 # v1.58.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch_depth: 0

      - name: Run codex
        uses: spotdemo4/codex-action@fd133063dc6ebe79decdd4f62058321c7c9d1bb9 # v0.3.2
        with:
          auth: ${{ secrets.CODEX_ACTION_AUTH }}
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          prompt: .github/prompts/fix.md

  trigger:
    needs: [check, build]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger NUR update
        run: curl -XPOST "https://nur-update.nix-community.org/update?repo=trev"
