name: update

on:
  schedule:
    - cron: "0 9 * * *" # every day at 09:00 UTC
  workflow_dispatch:

concurrency:
  group: update

permissions:
  contents: read
  id-token: write

jobs:
  pkgs:
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-26
    runs-on: ${{ matrix.image }}
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@fc128008797d8467f50a419abe60e75c9004d021 # v1.36.1
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          shell: update

      - name: Update packages
        run: ./utils/update/update.sh

  pkgs-pr:
    needs: pkgs
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: spotdemo4/better-checkout@9772c97e43eba14b9cbf29c6e9f8c8121bad5b53 # v0.7.0
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          fetch-depth: 0

      - name: Merge packages
        run: ./utils/update/merge.sh
        env:
          GH_TOKEN: ${{ steps.checkout.outputs.token }}

  renovate:
    runs-on: ubuntu-latest
    steps:
      - id: init
        name: Initialize
        uses: spotdemo4/nix-init@fc128008797d8467f50a419abe60e75c9004d021 # v1.36.1
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          shell: update

      - name: Renovate
        run: renovate
        env:
          RENOVATE_CONFIG_FILE: .github/renovate.json
          RENOVATE_TOKEN: ${{ steps.init.outputs.token }}
          LOG_LEVEL: ${{ runner.debug == '1' && 'debug' || 'info' }}
