name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every Sunday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: spotdemo4/nix-init@b0b33f024c18fa92f42f732e2e2001de507210cd # v1.45.0
        with:
          shell: vulnerable

      - name: Run flake-checker
        run: flake-checker -f

  actions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: spotdemo4/nix-init@b0b33f024c18fa92f42f732e2e2001de507210cd # v1.45.0
        with:
          shell: vulnerable

      - name: Run zizmor
        run: zizmor .github
