name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every Sunday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: spotdemo4/nix-init@2fc360eefced0d01fc56eaf691ab9393a94a1c60 # v1.60.0
        with:
          shell: vulnerable

      - name: Run flake-checker
        run: flake-checker -f

  actions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: spotdemo4/nix-init@2fc360eefced0d01fc56eaf691ab9393a94a1c60 # v1.60.0
        with:
          shell: vulnerable

      - name: Run zizmor
        run: zizmor .github
