name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every Sunday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: spotdemo4/nix-init@91bbca32bfa8d48baf47c8b2c0a15ce89c5ff0aa # v1.42.0
        with:
          shell: vulnerable

      - name: Run flake-checker
        run: flake-checker -f

  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: spotdemo4/nix-init@91bbca32bfa8d48baf47c8b2c0a15ce89c5ff0aa # v1.42.0
        with:
          shell: vulnerable

      - name: Run octoscan
        run: octoscan scan .github
