# See https://sw.kovidgoyal.net/kitty/conf.html
font_family Maple Mono NF CN
font_size 13.500000


# Shell integration is sourced and configured manually
shell_integration no-rc

background_opacity 0.8
background_blur 1
confirm_os_window_close 0
dynamic_background_opacity yes





shell /run/current-system/sw/bin/herdr
disable_ligatures never
cursor_blink_interval 0.3

# protocol file
# ext js,jsx,ts,tsx,rs,c,cpp,cc,json,toml,kt,yaml,yml,sh,fish,nu,nix,lock
# action launch --type=overlay $EDITOR $FILE_PATH

# protocol file
# mime text/plain
# action launch --type=overlay $EDITOR $FILE_PATH

# # Open directories
# protocol file
# mime inode/directory
# action launch --cwd $FILE_PATH

# # Open executable file
# protocol file
# mime inode/executable,application/vnd.microsoft.portable-executable
# action launch --hold --type=overlay $FILE_PATH

# # Open text files without fragments in the editor
# protocol file
# mime text/*
# action launch --type=overlay $EDITOR $FILE_PATH

# # Open image files with icat
# protocol file
# mime image/*
# action launch --type=overlay kitty +kitten icat --hold $FILE_PATH

# # Open video files with vlc
# protocol file
# mime video/*
# action launch --type=os-window vlc $FILE_PATH

# # Open ssh URLs with ssh command
# protocol ssh
# action launch --type=overlay ssh $URL




# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME
