# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  carla-git = {
    pname = "carla-git";
    version = "f3d8dce5861fcd6024c524c7966d5226aa07e328";
    src = fetchFromGitHub {
      owner = "falkTX";
      repo = "Carla";
      rev = "f3d8dce5861fcd6024c524c7966d5226aa07e328";
      fetchSubmodules = false;
      sha256 = "sha256-jedRiiEYnh/lRKcqbprSSga93RWLC5NbVSoHwvKs79k=";
    };
    date = "2023-11-26";
  };
  gtk-4_13_0 = {
    pname = "gtk-4_13_0";
    version = "4.13.0";
    src = fetchFromGitHub {
      owner = "GNOME";
      repo = "gtk";
      rev = "4.13.0";
      fetchSubmodules = false;
      sha256 = "sha256-SiL+/wfpeIUF2sQpGN1nWVn/mna+m3UxfORAFq/8fl0=";
    };
  };
  libadwaita-1_4 = {
    pname = "libadwaita-1_4";
    version = "1.4.rc";
    src = fetchFromGitHub {
      owner = "GNOME";
      repo = "libadwaita";
      rev = "1.4.rc";
      fetchSubmodules = false;
      sha256 = "sha256-VJV5kLoDXTPXb3gXz0iANmrfo+wiR4a59Z2tcjL5+/8=";
    };
  };
  zix-git = {
    pname = "zix-git";
    version = "60236967632849b4d8b0b925758e91cfdff23d38";
    src = fetchFromGitHub {
      owner = "drobilla";
      repo = "zix";
      rev = "60236967632849b4d8b0b925758e91cfdff23d38";
      fetchSubmodules = false;
      sha256 = "sha256-pi/ndtkF0fDJx/xTafBQK/F+hmHRO33AUM3j24vcazI=";
    };
    date = "2023-11-30";
  };
  zrythm = {
    pname = "zrythm";
    version = "228c7ad526b354c9ba01bed71028b9cb422f73f0";
    src = fetchgit {
      url = "https://git.sr.ht/~alextee/zrythm";
      rev = "228c7ad526b354c9ba01bed71028b9cb422f73f0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-G7U9GI5B3o2MuS6saZk+yeu1YBdY2iY1QGbksoDpY58=";
    };
    date = "2023-09-02";
  };
}
