# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "0sa0lc8a6jfksg2axlghra2hbkl780cm7zslrl37bd7rzf6vxnxg";
    x86_64-linux = "0rm5zhh5a3ifwg0qq6fngcbdf9i7nb0pb3d3yqhdv8sc0f83hhij";
    armv6l-linux = "19y4lqs44gphw3hs24m9zfwpyzn1v2f33w8xw9jchr2mjrwczw8p";
    aarch64-linux = "1d11rbi2rysm0rv4ys5jvzwj04kfw3rj06rnniv2xzyj2a6dpq7v";
    x86_64-darwin = "1d1l0plh4x5n7c9gb2hmqi4ghrng2p3n0q7ikii2bk5gmjnms303";
    aarch64-darwin = "1acgnnkcclzwma3ynprp80spc3x9k1vlhgnf6h20d1ar3w965pcy";
  };

  urlMap = {
    i686-linux = "https://github.com/goreleaser/goreleaser-pro/releases/download/v2.17.0/goreleaser-pro_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/goreleaser/goreleaser-pro/releases/download/v2.17.0/goreleaser-pro_Linux_x86_64.tar.gz";
    armv6l-linux = "https://github.com/goreleaser/goreleaser-pro/releases/download/v2.17.0/goreleaser-pro_Linux_armv6.tar.gz";
    aarch64-linux = "https://github.com/goreleaser/goreleaser-pro/releases/download/v2.17.0/goreleaser-pro_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/goreleaser/goreleaser-pro/releases/download/v2.17.0/goreleaser-pro_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/goreleaser/goreleaser-pro/releases/download/v2.17.0/goreleaser-pro_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "goreleaser-pro";
  version = "2.17.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./goreleaser $out/bin/goreleaser
    installManPage ./manpages/goreleaser.1.gz
    installShellCompletion ./completions/*
  '';

  meta = {
    description = "Release engineering, simplified.";
    homepage = "https://goreleaser.com";
    license = lib.licenses.unfree;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
