{
  config,
  lib,
  pkgs,
  vacuModuleType,
  ...
}:
lib.optionalAttrs (vacuModuleType == "nixos") (
  lib.mkIf config.vacu.isGui {
    # result of `nix-locate --at-root --minimal /share/fonts | sed -e 's/\.out//'`
    # and then filtered manually
    fonts.packages = with pkgs; [
      # keep-sorted start
      _0xpropo
      _0xproto
      _3270font
      adwaita-fonts
      agave
      aileron
      alegreya
      alegreya-sans
      aleo-fonts
      alice
      alice.woff2
      alkalami
      amiri
      anakron
      andika
      ankacoder
      ankacoder-condensed
      annapurna-sil
      anonymousPro
      apl386
      aporetic
      aporetic-bin
      arcticons-sans
      ark-pixel-font
      arkpandora_ttf
      arphic-ukai
      arphic-uming
      atkinson-hyperlegible
      atkinson-hyperlegible-mono
      atkinson-hyperlegible-next
      atkinson-monolegible
      aurulent-sans
      azeret-mono
      b612
      babelstone-han
      baekmuk-ttf
      bakoma_ttf
      barlow
      beedii
      behdad-fonts
      beon
      blackout
      borg-sans-mono
      bqn386
      bront_fonts
      brygada-1918
      cabin
      caladea
      cantarell-fonts
      cardo
      carlito
      cascadia-code
      catamaran
      ccsymbols
      charis-sil
      cherry
      chonburi-font
      chunk
      cinzel
      cinzel.variable
      clarity-city
      clearlyU
      cm_unicode
      cns11643-kai
      cnstrokeorder
      comfortaa
      comic-mono
      comic-neue
      comic-relief
      commit-mono
      constructium
      cooper-hewitt
      courier-prime
      cozette
      creep
      crimson
      crimson-pro
      culmus
      curie
      d2coding
      dancing-script
      dejavu_fonts
      denemo
      departure-mono
      dina-font
      dinish
      dm-mono
      dm-sans
      dosemu_fonts
      dosis
      dotcolon-fonts
      doulos-sil
      eb-garamond
      edwin
      efont-unicode
      emacs-all-the-icons-fonts
      encode-sans
      envypn-font
      etBook
      eunomia
      eurofurence
      excalifont
      ezra-sil
      f1_8
      f5_6
      fa_1
      fairfax
      fairfax-hd
      fantasque-sans-mono
      fanwood
      ferrum
      fg-virgil
      finalcut
      fira
      fira-code
      fira-code-symbols
      fira-go
      fira-math
      fira-mono
      fira-sans
      fixedsys-excelsior
      font-alias
      font-awesome
      font-awesome_4
      font-awesome_5
      font-util
      fragment-mono
      fraunces
      freefont_ttf
      freenukum
      galatia-sil
      gandom-fonts
      garamond-libre
      gargoyle
      geist-font
      gelasio
      gentium
      gentium-book-basic
      ghostscript.fonts
      glasstty-ttf
      go-font
      gohufont
      goudy-bookletter-1911
      gradia
      gubbi-font
      guitarix
      gyre-fonts
      hachimarupop
      hack-font
      hackgen-font
      hackgen-nf-font
      hanazono
      hanken-grotesk
      hasklig
      hermit
      hubot-sans
      hyperscrypt-font
      i-dot-ming
      ia-writer-duospace
      ia-writer-quattro
      ibm-plex
      icomoon-feather
      inconsolata
      inconsolata-lgc
      inriafonts
      intel-one-mono
      inter
      inter-alia
      inter-alia.variable
      inter-alia.variableweb
      inter-alia.web
      inter-nerdfont
      iosevka
      iosevka-bin
      iosevka-comfy.comfy
      iosevka-comfy.comfy-duo
      iosevka-comfy.comfy-fixed
      iosevka-comfy.comfy-motion
      iosevka-comfy.comfy-motion-duo
      iosevka-comfy.comfy-motion-fixed
      iosevka-comfy.comfy-wide
      iosevka-comfy.comfy-wide-duo
      iosevka-comfy.comfy-wide-fixed
      iosevka-comfy.comfy-wide-motion
      iosevka-comfy.comfy-wide-motion-duo
      iosevka-comfy.comfy-wide-motion-fixed
      ipaexfont
      ipafont
      iwona
      jetbrains-mono
      jigmo
      jost
      julia-mono
      junction-font
      junicode
      kacst
      kanit-font
      kanji-stroke-order-font
      karla
      kawkab-mono-font
      kdePackages.kiten
      khmeros
      knewave
      kochi-substitute
      kode-mono
      koruri
      kreative-square
      lalezar-fonts
      lao
      last-resort
      lato
      league-gothic
      league-of-moveable-type
      league-script-number-one
      league-spartan
      lexend
      liberastika
      liberation-sans-narrow
      liberation_ttf
      liberation_ttf_v1
      libertine
      libertine-g
      libertinus
      libre-baskerville
      libre-bodoni
      libre-caslon
      libre-franklin
      lilex
      linden-hill
      line-awesome
      linearicons-free
      linja-sike
      lklug-sinhala
      lmmath
      lmodern
      lohit-fonts.assamese
      lohit-fonts.bengali
      lohit-fonts.devanagari
      lohit-fonts.gujarati
      lohit-fonts.gurmukhi
      lohit-fonts.kannada
      lohit-fonts.kashmiri
      lohit-fonts.konkani
      lohit-fonts.maithili
      lohit-fonts.malayalam
      lohit-fonts.marathi
      lohit-fonts.nepali
      lohit-fonts.odia
      lohit-fonts.sindhi
      lohit-fonts.tamil
      lohit-fonts.tamil-classical
      lohit-fonts.telugu
      lora
      lorem
      luculent
      ludusavi
      lxgw-fusionkai
      lxgw-neoxihei
      lxgw-wenkai
      lxgw-wenkai-screen
      lxgw-wenkai-tc
      major-mono-display
      maple-mono.CN
      maple-mono.CN-unhinted
      maple-mono.NF
      maple-mono.NF-CN
      maple-mono.NF-CN-unhinted
      maple-mono.NF-unhinted
      maple-mono.NL-CN
      maple-mono.NL-CN-unhinted
      maple-mono.NL-NF
      maple-mono.NL-NF-CN
      maple-mono.NL-NF-CN-unhinted
      maple-mono.NL-NF-unhinted
      maple-mono.NL-OTF
      maple-mono.NL-TTF
      maple-mono.NL-TTF-AutoHint
      maple-mono.NL-Variable
      maple-mono.NL-Woff2
      maple-mono.Normal-CN
      maple-mono.Normal-CN-unhinted
      maple-mono.Normal-NF
      maple-mono.Normal-NF-CN
      maple-mono.Normal-NF-CN-unhinted
      maple-mono.Normal-NF-unhinted
      maple-mono.Normal-OTF
      maple-mono.Normal-TTF
      maple-mono.Normal-TTF-AutoHint
      maple-mono.Normal-Variable
      maple-mono.Normal-Woff2
      maple-mono.NormalNL-CN
      maple-mono.NormalNL-CN-unhinted
      maple-mono.NormalNL-NF
      maple-mono.NormalNL-NF-CN
      maple-mono.NormalNL-NF-CN-unhinted
      maple-mono.NormalNL-NF-unhinted
      maple-mono.NormalNL-OTF
      maple-mono.NormalNL-TTF
      maple-mono.NormalNL-TTF-AutoHint
      maple-mono.NormalNL-Variable
      maple-mono.NormalNL-Woff2
      maple-mono.opentype
      maple-mono.truetype
      maple-mono.truetype-autohint
      maple-mono.variable
      maple-mono.woff2
      marathi-cursive
      martian-mono
      material-design-icons
      material-icons
      material-symbols
      medio
      melete
      merriweather
      merriweather-sans
      meslo-lg
      meslo-lgs-nf
      migmix
      migu
      minecraftia
      miracode
      mitimasu
      mno16
      mona-sans
      monaspace
      monocraft
      monoid
      mononoki
      montserrat
      moralerspace
      moralerspace-hw
      moralerspace-hwjpdoc
      moralerspace-jpdoc
      mph_2b_damase
      mplus-outline-fonts.githubRelease
      mplus-outline-fonts.osdnRelease
      mro-unicode
      myrica
      nacelle
      nafees
      nagios
      nahid-fonts
      nanum
      nanum-gothic-coding
      nasin-nanpa
      national-park-typeface
      navilu-font
      newcomputermodern
      nika-fonts
      nomnatong
      norwester-font
      noto-fonts
      noto-fonts-cjk-sans
      noto-fonts-cjk-serif
      noto-fonts-color-emoji
      noto-fonts-emoji-blob-bin
      noto-fonts-lgc-plus
      noto-fonts-lgc-plus.megamerge
      noto-fonts-monochrome-emoji
      noto-fonts.megamerge
      notonoto
      notonoto-35
      notonoto-console
      notonoto-hs
      notonoto-hs-35
      notonoto-hs-console
      ocr-a
      office-code-pro
      oldsindhi
      oldstandard
      open-dyslexic
      open-fonts
      open-sans
      openmoji-black
      openmoji-color
      openttd-ttf
      orbitron
      ostrich-sans
      oswald
      overpass
      oxygenfonts
      parastoo-fonts
      paratype-pt-mono
      paratype-pt-sans
      paratype-pt-serif
      pecita
      penna
      pixel-code
      plemoljp
      plemoljp-hs
      plemoljp-nf
      poly
      poppins
      powerline
      powerline-fonts
      powerline-symbols
      pretendard
      pretendard-gov
      pretendard-jp
      pretendard-std
      prociono
      profont
      proggyfonts
      public-sans
      quattrocento
      quattrocento-sans
      quicksand
      quinze
      quivira
      raleway
      recursive
      redhat-official-fonts
      rhodium-libre
      rictydiminished-with-firacode
      rnote
      roboto
      roboto-flex
      roboto-mono
      roboto-serif
      roboto-slab
      rounded-mgenplus
      route159
      rt
      rubik
      ruwudu
      sahel-fonts
      samim-fonts
      sampradaya
      sarabun-font
      sarasa-gothic
      scheherazade
      scheherazade-new
      scid-vs-pc
      scientifica
      seshat
      shabnam-fonts
      shanggu-fonts
      shrikhand
      signwriting
      siji
      sil-abyssinica
      sil-padauk
      sitelen-seli-kiwen
      sketchybar-app-font
      smc-chilanka
      smc-manjari
      smiley-sans
      sn-pro
      sniglet
      sorts-mill-goudy
      source-code-pro
      source-han-code-jp
      source-han-mono
      source-han-sans
      source-han-sans-vf-otf
      source-han-sans-vf-ttf
      source-han-serif
      source-han-serif-vf-otf
      source-han-serif-vf-ttf
      source-sans
      source-sans-pro
      source-serif
      source-serif-pro
      spleen
      stix-otf
      stix-two
      sudo-font
      tai-ahom
      takao
      tamsyn
      tamzen
      tempora_lgc
      tenderness
      terminus_font
      terminus_font_ttf
      termsyn
      the-neue-black
      theano
      tibetan-machine
      times-newer-roman
      tlwg
      tt2020
      ttf-indic
      ttf_bitstream_vera
      twemoji-color-font
      twitter-color-emoji
      typodermic-public-domain
      ubuntu-classic
      ubuntu-sans
      ubuntu-sans-mono
      ucs-fonts
      udev-gothic
      udev-gothic-nf
      uiua386
      ultimate-oldschool-pc-font-pack
      undefined-medium
      unfonts-core
      uni-vga
      unifont
      unifont-csur
      unifont_upper
      unscii
      unscii.extra
      uw-ttyp0
      vazir-code-font
      vazir-fonts
      vdrsymbols
      vegur
      victor-mono
      vollkorn
      vt323
      weather-icons
      winePackages.fonts
      work-sans
      wqy_microhei
      wqy_zenhei
      xits-math
      xorg.encodings
      xscreensaver
      yanone-kaffeesatz
      yasashisa-gothic
      zilla-slab
      zrythm
      # keep-sorted end
    ];
  }
)
