{
  config,
  lib,
  pkgs,
  vacuModuleType,
  ...
}:
lib.optionalAttrs (vacuModuleType == "nixos") (
  lib.mkIf config.vacu.isGui {
    # result of `nix-locate --at-root --minimal /share/fonts | sed -e 's/\.out//'`
    fonts.packages = with pkgs; [
      zrythm
      zilla-slab
      yasashisa-gothic
      yanone-kaffeesatz
      xscreensaver
      xits-math
      work-sans
      wqy_zenhei
      wqy_microhei
      winePackages.fonts
      weather-icons
      vt323
      vollkorn
      victor-mono
      vegur
      vdrsymbols
      vazir-code-font
      vazir-fonts
      uw-ttyp0
      unscii
      unscii.extra
      unifont
      unifont-csur
      unifont_upper
      unfonts-core
      uni-vga
      ultimate-oldschool-pc-font-pack
      undefined-medium
      ucs-fonts
      ubuntu-classic
      udev-gothic
      udev-gothic-nf
      uiua386
      ubuntu-sans
      ubuntu-sans-mono
      typodermic-public-domain
      twitter-color-emoji
      twemoji-color-font
      tt2020
      ttf_bitstream_vera
      ttf-indic
      tlwg
      times-newer-roman
      tibetan-machine
      theano
      the-neue-black
      terminus_font_ttf
      terminus_font
      termsyn
      tempora_lgc
      lohit-fonts.telugu
      tenderness
      tai-ahom
      takao
      tamzen
      lohit-fonts.tamil
      lohit-fonts.tamil-classical
      tamsyn
      sudo-font
      stix-otf
      stix-two
      spleen
      source-han-serif-vf-otf
      source-han-serif-vf-ttf
      source-serif-pro
      source-code-pro
      sorts-mill-goudy
      source-han-sans
      source-han-mono
      source-han-code-jp
      source-han-sans-vf-ttf
      source-han-sans-vf-otf
      source-han-serif
      source-sans
      source-sans-pro
      source-serif
      sniglet
      smiley-sans
      sn-pro
      smc-manjari
      sketchybar-app-font
      sitelen-seli-kiwen
      lohit-fonts.sindhi
      signwriting
      sil-padauk
      sil-abyssinica
      siji
      shrikhand
      shanggu-fonts
      seshat
      shabnam-fonts
      scid-vs-pc
      scientifica
      scheherazade-new
      scheherazade
      samim-fonts
      sampradaya
      sarasa-gothic
      sarabun-font
      sahel-fonts
      ruwudu
      rubik
      rt
      route159
      rounded-mgenplus
      roboto-slab
      roboto-mono
      roboto
      rnote
      roboto-flex
      roboto-serif
      rhodium-libre
      rictydiminished-with-firacode
      recursive
      redhat-official-fonts
      raleway
      quivira
      quinze
      quicksand
      quattrocento
      quattrocento-sans
      ark-pixel-font
      public-sans
      prociono
      profont
      proggyfonts
      pretendard
      pretendard-gov
      pretendard-jp
      pretendard-std
      powerline-symbols
      powerline-fonts
      powerline
      poppins
      poly
      plemoljp-hs
      plemoljp
      plemoljp-nf
      pixel-code
      penna
      pecita
      parastoo-fonts
      paratype-pt-serif
      paratype-pt-mono
      paratype-pt-sans
      overpass
      oxygenfonts
      oswald
      ostrich-sans
      orbitron
      openttd-ttf
      openmoji-black
      openmoji-color
      open-dyslexic
      constructium
      fairfax
      fairfax-hd
      kreative-square
      open-sans
      open-fonts
      oldstandard
      oldsindhi
      office-code-pro
      lohit-fonts.odia
      ocr-a
      noto-fonts-cjk-sans
      noto-fonts-color-emoji
      noto-fonts-lgc-plus.megamerge
      noto-fonts.megamerge
      noto-fonts-cjk-serif
      noto-fonts-emoji-blob-bin
      noto-fonts-lgc-plus
      noto-fonts-monochrome-emoji
      notonoto
      notonoto-hs
      notonoto-35
      notonoto-hs-console
      notonoto-console
      notonoto-hs-35
      noto-fonts
      norwester-font
      nomnatong
      nika-fonts
      newcomputermodern
      lohit-fonts.nepali
      nagios
      nahid-fonts
      nafees
      nanum
      nanum-gothic-coding
      national-park-typeface
      nasin-nanpa
      navilu-font
      myrica
      nacelle
      mro-unicode
      mplus-outline-fonts.osdnRelease
      mplus-outline-fonts.githubRelease
      mph_2b_damase
      moralerspace-jpdoc
      moralerspace-hwjpdoc
      montserrat
      moralerspace
      moralerspace-hw
      monocraft
      monoid
      mononoki
      mona-sans
      monaspace
      mno16
      mitimasu
      miracode
      minecraftia
      migmix
      migu
      meslo-lg
      meslo-lgs-nf
      merriweather
      merriweather-sans
      melete
      medio
      material-design-icons
      material-icons
      material-symbols
      martian-mono
      manrope
      maple-mono.NL-CN-unhinted
      maple-mono.Normal-CN
      maple-mono.NL-TTF
      maple-mono.opentype
      maple-mono.CN
      maple-mono.truetype
      maple-mono.CN-unhinted
      maple-mono.NF-CN-unhinted
      maple-mono.NF-CN
      maple-mono.NF
      maple-mono.truetype-autohint
      maple-mono.NF-unhinted
      maple-mono.variable
      maple-mono.NL-CN
      maple-mono.NL-NF-unhinted
      maple-mono.woff2
      maple-mono.NL-OTF
      maple-mono.NL-Woff2
      maple-mono.NL-NF
      maple-mono.NL-NF-CN-unhinted
      maple-mono.NL-TTF-AutoHint
      maple-mono.NL-Variable
      maple-mono.Normal-Woff2
      maple-mono.Normal-TTF-AutoHint
      maple-mono.Normal-CN-unhinted
      maple-mono.Normal-Variable
      maple-mono.Normal-NF
      maple-mono.Normal-NF-CN
      maple-mono.Normal-NF-CN-unhinted
      maple-mono.NormalNL-CN
      maple-mono.Normal-TTF
      maple-mono.Normal-OTF
      maple-mono.NormalNL-NF-CN
      maple-mono.NormalNL-NF-unhinted
      maple-mono.NormalNL-NF
      maple-mono.NormalNL-NF-CN-unhinted
      maple-mono.NormalNL-CN-unhinted
      maple-mono.NormalNL-OTF
      maple-mono.NormalNL-TTF-AutoHint
      maple-mono.NormalNL-TTF
      maple-mono.NormalNL-Variable
      maple-mono.NormalNL-Woff2
      lohit-fonts.marathi
      marathi-cursive
      maple-mono.Normal-NF-unhinted
      maple-mono.NL-NF-CN
      lohit-fonts.malayalam
      lohit-fonts.maithili
      major-mono-display
      ludusavi
      luculent
      lxgw-wenkai-tc
      lxgw-wenkai
      lxgw-fusionkai
      lxgw-neoxihei
      lxgw-wenkai-screen
      lora
      lorem
      lmmath
      lmodern
      lklug-sinhala
      libertine-g
      libertine
      linja-sike
      linden-hill
      line-awesome
      linearicons-free
      lilex
      libre-caslon
      libre-bodoni
      libre-baskerville
      libre-franklin
      liberastika
      liberation_ttf_v1
      liberation-sans-narrow
      libertinus
      liberation_ttf
      lexend
      league-of-moveable-type
      league-gothic
      league-script-number-one
      league-spartan
      lato
      lao
      last-resort
      lalezar-fonts
      koruri
      kochi-substitute
      lohit-fonts.konkani
      kode-mono
      knewave
      kdePackages.kiten
      khmeros
      lohit-fonts.kashmiri
      kawkab-mono-font
      kanit-font
      kanji-stroke-order-font
      lohit-fonts.kannada
      karla
      kacst
      junction-font
      junicode
      julia-mono
      jost
      jetbrains-mono
      jigmo
      iwona
      ipaexfont
      ipafont
      iosevka-bin
      iosevka
      iosevka-comfy.comfy
      iosevka-comfy.comfy-fixed
      iosevka-comfy.comfy-wide-duo
      iosevka-comfy.comfy-wide
      iosevka-comfy.comfy-motion
      iosevka-comfy.comfy-duo
      iosevka-comfy.comfy-motion-fixed
      iosevka-comfy.comfy-motion-duo
      iosevka-comfy.comfy-wide-motion
      iosevka-comfy.comfy-wide-fixed
      iosevka-comfy.comfy-wide-motion-duo
      iosevka-comfy.comfy-wide-motion-fixed
      inriafonts
      intel-one-mono
      inter-alia.variable
      inter-alia
      inter
      inter-nerdfont
      inter-alia.variableweb
      inter-alia.web
      inconsolata
      inconsolata-lgc
      icomoon-feather
      i-dot-ming
      ia-writer-duospace
      ia-writer-quattro
      ibm-plex
      hyperscrypt-font
      hubot-sans
      hermit
      hasklig
      hanazono
      hanken-grotesk
      hackgen-nf-font
      hackgen-font
      gyre-fonts
      hachimarupop
      hack-font
      guitarix
      lohit-fonts.gujarati
      lohit-fonts.gurmukhi
      gubbi-font
      gradia
      goudy-bookletter-1911
      gohufont
      go-font
      glasstty-ttf
      ghostscript.fonts
      gentium
      gentium-book-basic
      gelasio
      geist-font
      garamond-libre
      gargoyle
      gandom-fonts
      galatia-sil
      freefont_ttf
      freenukum
      fraunces
      fragment-mono
      font-alias
      font-util
      font-awesome
      font-awesome_4
      font-awesome_5
      fixedsys-excelsior
      fira-code
      fira
      fira-code-symbols
      fira-go
      fira-mono
      finalcut
      fira-sans
      fira-math
      fg-virgil
      ferrum
      fa_1
      fantasque-sans-mono
      fanwood
      f5_6
      ezra-sil
      f1_8
      excalifont
      eunomia
      eurofurence
      etBook
      envypn-font
      xorg.encodings
      encode-sans
      emacs-all-the-icons-fonts
      edwin
      efont-unicode
      eb-garamond
      doulos-sil
      dosemu_fonts
      dotcolon-fonts
      dosis
      dm-mono
      dm-sans
      dinish
      dina-font
      lohit-fonts.devanagari
      dejavu_fonts
      denemo
      departure-mono
      d2coding
      dancing-script
      culmus
      curie
      creep
      crimson
      crimson-pro
      courier-prime
      cozette
      cooper-hewitt
      comic-neue
      commit-mono
      comic-mono
      comfortaa
      comic-relief
      cns11643-kai
      cnstrokeorder
      cm_unicode
      clearlyU
      clarity-city
      chonburi-font
      chunk
      cinzel
      cinzel.variable
      cherry
      smc-chilanka
      charis-sil
      ccsymbols
      cardo
      cantarell-fonts
      carlito
      cascadia-code
      catamaran
      cabin
      caladea
      brygada-1918
      bront_fonts
      bqn386
      borg-sans-mono
      blackout
      beon
      lohit-fonts.bengali
      behdad-fonts
      beedii
      barlow
      babelstone-han
      baekmuk-ttf
      bakoma_ttf
      b612
      azeret-mono
      aurulent-sans
      atkinson-hyperlegible
      atkinson-hyperlegible-next
      atkinson-hyperlegible-mono
      atkinson-monolegible
      lohit-fonts.assamese
      arkpandora_ttf
      arphic-ukai
      arphic-uming
      arcticons-sans
      apl386
      aporetic
      aporetic-bin
      ankacoder
      annapurna-sil
      anonymousPro
      anakron
      andika
      ankacoder-condensed
      amiri
      alkalami
      alice.woff2
      alice
      alegreya
      alegreya-sans
      aleo-fonts
      aileron
      agave
      adwaita-fonts
      _0xproto
      _0xpropo
      _3270font
    ];
  }
)
