#!/usr/bin/env bash
NIXPKGS_PATH=$(nix-instantiate --eval '<nixpkgs>' -A path)
"$NIXPKGS_PATH/maintainers/scripts/update-luarocks-packages" --input-names ./luarocks-packages.csv --out ./generated-packages.nix --debug DEBUG --proc 8 --no-commit

# vim: set ft=sh :
