# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  aws-sigv4-proxy = {
    pname = "aws-sigv4-proxy";
    version = "v1.10";
    src = fetchFromGitHub {
      owner = "awslabs";
      repo = "aws-sigv4-proxy";
      rev = "v1.10";
      fetchSubmodules = false;
      sha256 = "sha256-DC9JJeMdwxKeALQYA53BmMdAxQlUfPowAEul7+dTh4s=";
    };
  };
  baibot = {
    pname = "baibot";
    version = "v1.8.1";
    src = fetchFromGitHub {
      owner = "etkecc";
      repo = "baibot";
      rev = "v1.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-qWJ4Z/ixqUq4rN06vq6JM+lJSovoh9DP1wB37C08Vt0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-qWJ4Z_ixqUq4rN06vq6JM+lJSovoh9DP1wB37C08Vt0=/Cargo.lock";
      outputHashes = {
        "async-openai-0.28.1" = "sha256-5xrO2k5jA94cf3Ub0DGuAvKqDDXVk1Ro/naC5FG1AAw=";
        "anthropic-0.0.8" = "sha256-q21o2GB8nN0jGcRPgW/cujC+3gdgQg5mFJUJy2tipCA=";
      };
    };
  };
  cowrie = {
    pname = "cowrie";
    version = "v2.8.1";
    src = fetchFromGitHub {
      owner = "cowrie";
      repo = "cowrie";
      rev = "v2.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-/8yJaBAlHZMu7YUgtu2GCkMplF8Ln/hZGVqCiCfT4CY=";
    };
  };
  dot-tar = {
    pname = "dot-tar";
    version = "b5f1f3f37abd9f65dd75cc5e74d32e6356090534";
    src = fetchgit {
      url = "https://github.com/linyinfeng/dot-tar.git";
      rev = "b5f1f3f37abd9f65dd75cc5e74d32e6356090534";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-M5Qw/aUX7zwq15bpe+Ix1t7kfkFF/JIC1ngOwAtx7Tg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-M5Qw_aUX7zwq15bpe+Ix1t7kfkFF_JIC1ngOwAtx7Tg=/Cargo.lock";
      outputHashes = {

      };
    };
    date = "2024-08-18";
  };
  dpt-rp1-py = {
    pname = "dpt-rp1-py";
    version = "v0.1.18";
    src = fetchFromGitHub {
      owner = "janten";
      repo = "dpt-rp1-py";
      rev = "v0.1.18";
      fetchSubmodules = false;
      sha256 = "sha256-5Ny62Kp1GHH9vmPSZ6smNqyEt9PZYPHAiungHZQMB/A=";
    };
  };
  gnome-shell-mobile-shell = {
    pname = "gnome-shell-mobile-shell";
    version = "9b7df11f136da27633c8d30cd419dcc7906c8b4d";
    src = fetchgit {
      url = "https://gitlab.gnome.org/verdre/gnome-shell.git";
      rev = "9b7df11f136da27633c8d30cd419dcc7906c8b4d";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+onnwvFsogGlNBrhvc2F2DRrEw+e6VCWqQA0npO0bMo=";
    };
    date = "2023-06-05";
  };
  icalingua-plus-plus = {
    pname = "icalingua-plus-plus";
    version = "v2.12.28";
    src = fetchurl {
      url = "https://github.com/icalingua-plus-plus/icalingua-plus-plus/releases/download/v2.12.28/app-x86_64.asar";
      sha256 = "sha256-lNlzQPDXXVNuacic1BYjWA5sGLRLlcGVRaqHPmZ3ZYs=";
    };
  };
  libva-v4l2 = {
    pname = "libva-v4l2";
    version = "4bcd48cdeae182c7af5d23526068b51338c01b05";
    src = fetchgit {
      url = "https://github.com/mxsrc/libva-v4l2.git";
      rev = "4bcd48cdeae182c7af5d23526068b51338c01b05";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-40wAxU7xj9VF4Dk+zrQWn9iiGAzWlhEdN9dQa5ftLLE=";
    };
    date = "2024-10-21";
  };
  linux-intel-lts = {
    pname = "linux-intel-lts";
    version = "lts-v6.12.55-linux-251024T074402Z";
    src = fetchFromGitHub {
      owner = "intel";
      repo = "linux-intel-lts";
      rev = "lts-v6.12.55-linux-251024T074402Z";
      fetchSubmodules = false;
      sha256 = "sha256-GSnK/uzQSOQo64episCJNJcPRm0UAhLX4QldRJFYqPg=";
    };
  };
  linux-intel-mainline-tracking = {
    pname = "linux-intel-mainline-tracking";
    version = "mainline-tracking-v6.11.10-linux-241202T040109Z";
    src = fetchFromGitHub {
      owner = "intel";
      repo = "mainline-tracking";
      rev = "mainline-tracking-v6.11.10-linux-241202T040109Z";
      fetchSubmodules = false;
      sha256 = "sha256-TlqDEFCu4IPmAm0NYHD5fyQy38Ce6BZbGEDu1FpJXd8=";
    };
  };
  lpac = {
    pname = "lpac";
    version = "v2.3.0";
    src = fetchFromGitHub {
      owner = "estkme-group";
      repo = "lpac";
      rev = "v2.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-ALne5sHB6ff7cHAWe0rFwpP/Yz4EhZBiOrgdM2B8+OE=";
    };
  };
  ly2video = {
    pname = "ly2video";
    version = "v0.5.0";
    src = fetchFromGitHub {
      owner = "aspiers";
      repo = "ly2video";
      rev = "v0.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-4ARRCmz7uDKWVuY1LG98oAGV/S0BFo4DYyoWw9TlZoo=";
    };
  };
  mediawiki-auth-manager-oauth = {
    pname = "mediawiki-auth-manager-oauth";
    version = "v0.3.3";
    src = fetchurl {
      url = "https://github.com/mohe2015/AuthManagerOAuth/releases/download/v0.3.3/AuthManagerOAuth.zip";
      sha256 = "sha256-smLFY4EQrjbKBNiy2hpY6oB2bdOPwlmhMuHUuXqS2sE=";
    };
  };
  moe-koe-music = {
    pname = "moe-koe-music";
    version = "v1.5.2";
    src = fetchurl {
      url = "https://github.com/iAJue/MoeKoeMusic/releases/download/v1.5.2/MoeKoe_Music_v1.5.2.AppImage";
      sha256 = "sha256-eM6wqJ6X3ImxCJ00fyO7OxHkj2PHq2DfYVKc/9gu5w4=";
    };
  };
  mstickereditor = {
    pname = "mstickereditor";
    version = "v0.3.7";
    src = fetchFromGitHub {
      owner = "LuckyTurtleDev";
      repo = "mstickereditor";
      rev = "v0.3.7";
      fetchSubmodules = false;
      sha256 = "sha256-yLelr190my12Ff5JbJXV5fh7VgeqGu0VYe/Mw0mLoNo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-yLelr190my12Ff5JbJXV5fh7VgeqGu0VYe_Mw0mLoNo=/Cargo.lock";
      outputHashes = {

      };
    };
  };
  mutter-mobile-shell = {
    pname = "mutter-mobile-shell";
    version = "5e72de83dbf48991d8d60913c8396a0d7f86990c";
    src = fetchgit {
      url = "https://gitlab.gnome.org/verdre/mutter.git";
      rev = "5e72de83dbf48991d8d60913c8396a0d7f86990c";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-93CmMhowMEnl4jVtoNZXgCIOUgmfeIyD2QWT11wGcIw=";
    };
    date = "2023-06-04";
  };
  niri-taskbar = {
    pname = "niri-taskbar";
    version = "v0.3.0+niri.25.08";
    src = fetchFromGitHub {
      owner = "LawnGnome";
      repo = "niri-taskbar";
      rev = "v0.3.0+niri.25.08";
      fetchSubmodules = false;
      sha256 = "sha256-Gbzh4OTkvtP9F/bfDUyA14NH2DMDdr3i6oFoFwinEAg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-Gbzh4OTkvtP9F_bfDUyA14NH2DMDdr3i6oFoFwinEAg=/Cargo.lock";
      outputHashes = {

      };
    };
  };
  plugin-bang-bang = {
    pname = "plugin-bang-bang";
    version = "ec991b80ba7d4dda7a962167b036efc5c2d79419";
    src = fetchgit {
      url = "https://github.com/oh-my-fish/plugin-bang-bang";
      rev = "ec991b80ba7d4dda7a962167b036efc5c2d79419";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oPPCtFN2DPuM//c48SXb4TrFRjJtccg0YPXcAo0Lxq0=";
    };
    date = "2023-07-23";
  };
  plugin-git = {
    pname = "plugin-git";
    version = "d6950214b6b2392d3dbb2cb670f2a5f240090038";
    src = fetchgit {
      url = "https://github.com/jhillyerd/plugin-git";
      rev = "d6950214b6b2392d3dbb2cb670f2a5f240090038";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0uEKw+7EXkf5u3p3hfthSfQO/2rr3wl35ela7P2vB0Q=";
    };
    date = "2025-03-28";
  };
  pyim-greatdict = {
    pname = "pyim-greatdict";
    version = "87594b2a4d6391cf69475257b286d3b844791571";
    src = fetchgit {
      url = "https://github.com/tumashu/pyim-greatdict.git";
      rev = "87594b2a4d6391cf69475257b286d3b844791571";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-IvSAFs3TZ84q2FflPyrDbvwkPVVlyvRQTzpCx+JvKGA=";
    };
    date = "2019-07-19";
  };
  replay-fish = {
    pname = "replay-fish";
    version = "1.2.1";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "replay.fish";
      rev = "1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-bM6+oAd/HXaVgpJMut8bwqO54Le33hwO9qet9paK1kY=";
    };
  };
  rime-bopomofo = {
    pname = "rime-bopomofo";
    version = "1859af68a927ba3cd5afb8c47feedcecf874dab2";
    src = fetchgit {
      url = "https://github.com/rime/rime-bopomofo.git";
      rev = "1859af68a927ba3cd5afb8c47feedcecf874dab2";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-gHir+jt36CgHkAweaWBOiAsk4ixyDbdu8rEGftU/3vQ=";
    };
    date = "2025-07-29";
  };
  rime-cangjie = {
    pname = "rime-cangjie";
    version = "0ac8452eeb4abbcd8dd1f9e7314012310743285f";
    src = fetchgit {
      url = "https://github.com/rime/rime-cangjie.git";
      rev = "0ac8452eeb4abbcd8dd1f9e7314012310743285f";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v8n3+73l9YbTexpA9C2356quioRwFRVcBY0IncolVoY=";
    };
    date = "2024-03-25";
  };
  rime-cantonese = {
    pname = "rime-cantonese";
    version = "41816434b0b2457c772eae5e7dfd85054e8f5e24";
    src = fetchgit {
      url = "https://github.com/rime/rime-cantonese.git";
      rev = "41816434b0b2457c772eae5e7dfd85054e8f5e24";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oe35CuCGQekCAkpGaCLzXRDcAVuwlmxkQZswFJwPf1Y=";
    };
    date = "2025-09-24";
  };
  rime-double-pinyin = {
    pname = "rime-double-pinyin";
    version = "01a13287cbd27819be1c34fa1ddc1b3643d5001b";
    src = fetchgit {
      url = "https://github.com/rime/rime-double-pinyin.git";
      rev = "01a13287cbd27819be1c34fa1ddc1b3643d5001b";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-iHaGHKwmhyciU6zKJRLyRETRR15QSHZ7ML1l4iAV6eM=";
    };
    date = "2025-09-24";
  };
  rime-emoji = {
    pname = "rime-emoji";
    version = "3dd83a264b4686b56abddedecbde75360cbbbfab";
    src = fetchgit {
      url = "https://github.com/rime/rime-emoji.git";
      rev = "3dd83a264b4686b56abddedecbde75360cbbbfab";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TQYNzrX57gyJG4M7EklE21fs/WoaZTsd5IafMRG4Ob8=";
    };
    date = "2025-03-31";
  };
  rime-essay = {
    pname = "rime-essay";
    version = "943c7bff037c163a80c452bd7ac80cd2b01975e6";
    src = fetchgit {
      url = "https://github.com/rime/rime-essay.git";
      rev = "943c7bff037c163a80c452bd7ac80cd2b01975e6";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xn5xh6Txfz73tM9HJMS7kuKw0iTqeHeajWEsuggeZok=";
    };
    date = "2025-10-24";
  };
  rime-ice = {
    pname = "rime-ice";
    version = "49e5ed738f849279c7033221b6227c295f0e05f5";
    src = fetchgit {
      url = "https://github.com/iDvel/rime-ice.git";
      rev = "49e5ed738f849279c7033221b6227c295f0e05f5";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NuqUBZJiPAidwBEIq36H8YstutCOUJdxvJGdFAVJ2YU=";
    };
    date = "2025-10-23";
  };
  rime-loengfan = {
    pname = "rime-loengfan";
    version = "987ac95b02f957e8764a2f45222a4006c188ed50";
    src = fetchgit {
      url = "https://github.com/CanCLID/rime-loengfan.git";
      rev = "987ac95b02f957e8764a2f45222a4006c188ed50";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vOqVSwKZ+p5Wc03pRUWxCdWBdxuTe8n4xu2BTbj9/b4=";
    };
    date = "2022-03-03";
  };
  rime-luna-pinyin = {
    pname = "rime-luna-pinyin";
    version = "46acf03142c12b5aeed7002675046bf7255eed35";
    src = fetchgit {
      url = "https://github.com/rime/rime-luna-pinyin.git";
      rev = "46acf03142c12b5aeed7002675046bf7255eed35";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-gwqThVCjEZnIWI+WVgRPxVBUN0bp52QoL9LHONSlDw4=";
    };
    date = "2025-08-05";
  };
  rime-pinyin-simp = {
    pname = "rime-pinyin-simp";
    version = "0c6861ef7420ee780270ca6d993d18d4101049d0";
    src = fetchgit {
      url = "https://github.com/rime/rime-pinyin-simp.git";
      rev = "0c6861ef7420ee780270ca6d993d18d4101049d0";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-eVd7dbiMH1sb/ZhZFwYxbhS4cQ2Wt2K3ZMfeTUozl9E=";
    };
    date = "2024-12-29";
  };
  rime-prelude = {
    pname = "rime-prelude";
    version = "3c602fdb0dcca7825103e281efc50ef7580f99ec";
    src = fetchgit {
      url = "https://github.com/rime/rime-prelude.git";
      rev = "3c602fdb0dcca7825103e281efc50ef7580f99ec";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-R9sxeCe1e2A3pn//iGwRr3eTTpgxprjEEjlo15/O19c=";
    };
    date = "2025-04-20";
  };
  rime-quick = {
    pname = "rime-quick";
    version = "3fe5911ba608cb2df1b6301b76ad1573bd482a76";
    src = fetchgit {
      url = "https://github.com/rime/rime-quick.git";
      rev = "3fe5911ba608cb2df1b6301b76ad1573bd482a76";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-yctopPkng3QQLhDRuHP5gpEmTx0UCO5pKXzjUv1BcCE=";
    };
    date = "2019-01-20";
  };
  rime-stroke = {
    pname = "rime-stroke";
    version = "3a4b0f4013e2b4c14b1e80c92b1d4723eb65f39c";
    src = fetchgit {
      url = "https://github.com/rime/rime-stroke.git";
      rev = "3a4b0f4013e2b4c14b1e80c92b1d4723eb65f39c";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-l2YRET+aywThX+iBTYKqtBESs6ozJn5Du5IewwMhhmM=";
    };
    date = "2025-09-23";
  };
  rime-terra-pinyin = {
    pname = "rime-terra-pinyin";
    version = "11878613ea12c2199b3aa71e320491f468e1fc7d";
    src = fetchgit {
      url = "https://github.com/rime/rime-terra-pinyin.git";
      rev = "11878613ea12c2199b3aa71e320491f468e1fc7d";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Tluiw/VEnPmjZ3OaqvZqeG+TwLr5txN0iuoOBoFzTj0=";
    };
    date = "2025-10-09";
  };
  rime-wubi = {
    pname = "rime-wubi";
    version = "152a0d3f3efe40cae216d1e3b338242446848d07";
    src = fetchgit {
      url = "https://github.com/rime/rime-wubi.git";
      rev = "152a0d3f3efe40cae216d1e3b338242446848d07";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-IetRNGZkyAzZ8tqqpa45oit0nQw1qx5BdwRhQDibUdw=";
    };
    date = "2023-10-25";
  };
  rime-wugniu = {
    pname = "rime-wugniu";
    version = "abd1ee98efbf170258fcf43875c21a4259e00b61";
    src = fetchgit {
      url = "https://github.com/rime/rime-wugniu.git";
      rev = "abd1ee98efbf170258fcf43875c21a4259e00b61";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mNqUJ9iXSDCHqvnBoJ0TxXJjS0aAtx4NCN5SxkYjxWI=";
    };
    date = "2019-01-20";
  };
  rlt = {
    pname = "rlt";
    version = "v0.1.6";
    src = fetchFromGitHub {
      owner = "kaichaosun";
      repo = "rlt";
      rev = "v0.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-Ibzax4AZCMEj10rJ8A47qek2Kd8U+idwTDvbHB8A1xo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-Ibzax4AZCMEj10rJ8A47qek2Kd8U+idwTDvbHB8A1xo=/Cargo.lock";
      outputHashes = {

      };
    };
  };
  secureboot_objects = {
    pname = "secureboot_objects";
    version = "v1.6.1-signed";
    src = fetchFromGitHub {
      owner = "microsoft";
      repo = "secureboot_objects";
      rev = "v1.6.1-signed";
      fetchSubmodules = false;
      sha256 = "sha256-EFy4XsUi7f1BZHT95HPX2wp+B2q6WqlVmT6pME72kfA=";
    };
  };
  telegram-send = {
    pname = "telegram-send";
    version = "38cd39fb0eac6c58e886c11706ae39f58991af55";
    src = fetchgit {
      url = "https://github.com/rahiel/telegram-send.git";
      rev = "38cd39fb0eac6c58e886c11706ae39f58991af55";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DeEz1cVor2GBoQrDIHNWr5IYnPgBsTWr5xMuSM38MBw=";
    };
    date = "2023-10-07";
  };
  tg-send = {
    pname = "tg-send";
    version = "d3aea3f2dc37c39521ce59c5fb156427764ad68f";
    src = fetchgit {
      url = "https://github.com/linyinfeng/tg-send.git";
      rev = "d3aea3f2dc37c39521ce59c5fb156427764ad68f";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-I1saekIoRV/as3sVMUlfCpqLA6xHX5YdtRgIjuof1AU=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-I1saekIoRV_as3sVMUlfCpqLA6xHX5YdtRgIjuof1AU=/Cargo.lock";
      outputHashes = {

      };
    };
    date = "2023-03-25";
  };
  trojan = {
    pname = "trojan";
    version = "v1.16.0";
    src = fetchFromGitHub {
      owner = "trojan-gfw";
      repo = "trojan";
      rev = "v1.16.0";
      fetchSubmodules = false;
      sha256 = "sha256-fCoZEXQ6SL++QXP6GlNYIyFaVhQ8EWelJ33VbYiHRGw=";
    };
  };
  vlmcsd = {
    pname = "vlmcsd";
    version = "svn1113";
    src = fetchFromGitHub {
      owner = "Wind4";
      repo = "vlmcsd";
      rev = "svn1113";
      fetchSubmodules = false;
      sha256 = "sha256-OKysOm44T9wrAaopp9HfLlox5InlpV33AHGXRSjhDqc=";
    };
  };
  yacd = {
    pname = "yacd";
    version = "v0.3.8";
    src = fetchurl {
      url = "https://github.com/haishanh/yacd/releases/download/v0.3.8/yacd.tar.xz";
      sha256 = "sha256-1dfs3pGnCKeThhFnU+MqWfMsjLjuyA3tVsOrlOURulA=";
    };
  };
  zeronsd = {
    pname = "zeronsd";
    version = "v0.5.2";
    src = fetchFromGitHub {
      owner = "zerotier";
      repo = "zeronsd";
      rev = "v0.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-TL0bgzQgge6j1SpZCdxv/s4pBMSg4/3U5QisjkVE6BE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-TL0bgzQgge6j1SpZCdxv_s4pBMSg4_3U5QisjkVE6BE=/Cargo.lock";
      outputHashes = {

      };
    };
  };
}
