# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  copyq-darwin = {
    pname = "copyq-darwin";
    version = "10.0.0";
    src = fetchurl {
      url = "https://github.com/hluk/CopyQ/releases/download/v10.0.0/CopyQ-macos-12-m1.dmg.zip";
      sha256 = "sha256-9TXMRaHfd3ZD/kcgDCBrOp1GG3tYhpsXg6t94clezNw=";
    };
  };
  emacs-plus = {
    pname = "emacs-plus";
    version = "3e95d573d5f13aba7808193b66312b38a7c66851";
    src = fetchFromGitHub {
      owner = "d12frosted";
      repo = "homebrew-emacs-plus";
      rev = "3e95d573d5f13aba7808193b66312b38a7c66851";
      fetchSubmodules = false;
      sha256 = "sha256-Eepinxv05Yl79AoPVJveGDZPKHhlAes7XtUvrssflrU=";
    };
    date = "2025-03-31";
  };
  hammerspoon = {
    pname = "hammerspoon";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/Hammerspoon/hammerspoon/releases/download/1.0.0/Hammerspoon-1.0.0.zip";
      sha256 = "sha256-XbcCtV2kfcMG6PWUjZHvhb69MV3fopQoMioK9+1+an4=";
    };
  };
  nixpkgs-review = {
    pname = "nixpkgs-review";
    version = "b4d0a817180b1a079d00d41c0a41308cb11407f7";
    src = fetchFromGitHub {
      owner = "natsukium";
      repo = "nixpkgs-review";
      rev = "b4d0a817180b1a079d00d41c0a41308cb11407f7";
      fetchSubmodules = false;
      sha256 = "sha256-fZkXkhwsNoxcQcC4fqwnkfGherazl/YZBkuVWGmnWPY=";
    };
    date = "2025-01-10";
  };
  paperwm-spoon = {
    pname = "paperwm-spoon";
    version = "e47ca19eddb1cb6000415a6a61db7255162f4cdb";
    src = fetchFromGitHub {
      owner = "mogenson";
      repo = "PaperWM.spoon";
      rev = "e47ca19eddb1cb6000415a6a61db7255162f4cdb";
      fetchSubmodules = false;
      sha256 = "sha256-QHEhH+Gya8KzLKH17DMDqwXu7rnUzQ5JYTF8q2RzyYE=";
    };
    date = "2025-05-18";
  };
  qmk-toolbox = {
    pname = "qmk-toolbox";
    version = "0.3.3";
    src = fetchurl {
      url = "https://github.com/qmk/qmk_toolbox/releases/download/0.3.3/QMK.Toolbox.app.zip";
      sha256 = "sha256-WPre2csGAQzavtksLbj3L/MrWUT6d2gTJVq7eAmpcLk=";
    };
  };
  qutebrowser-darwin = {
    pname = "qutebrowser-darwin";
    version = "3.5.0";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.5.0/qutebrowser-3.5.0-arm64.dmg";
      sha256 = "sha256-ib7eF7smzQ5yzU8tilW0IQkTPIrTWKNY6L0YFkifBc0=";
    };
  };
  sbarlua = {
    pname = "sbarlua";
    version = "437bd2031da38ccda75827cb7548e7baa4aa9978";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "SbarLua";
      rev = "437bd2031da38ccda75827cb7548e7baa4aa9978";
      fetchSubmodules = false;
      sha256 = "sha256-F0UfNxHM389GhiPQ6/GFbeKQq5EvpiqQdvyf7ygzkPg=";
    };
    date = "2024-08-12";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "3e019b331fbf9bd1d4539e7bd650a1c543125cee";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "3e019b331fbf9bd1d4539e7bd650a1c543125cee";
      fetchSubmodules = false;
      sha256 = "sha256-VDu8WypgpzY+Dd8KIPJXsvtBEwt5YiuGXn6HAUKCbIQ=";
    };
    date = "2025-05-05";
  };
  vivaldi-darwin = {
    pname = "vivaldi-darwin";
    version = "7.4.3684.43";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.7.4.3684.43.universal.dmg";
      sha256 = "sha256-xggzqGKZFIZTAobSChVHYaXNifP3GaBSR8wqmGUSIPA=";
    };
  };
  zen-browser = {
    pname = "zen-browser";
    version = "1.12.10b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.12.10b/zen.macos-universal.dmg";
      sha256 = "sha256-dcJ+J4hwpIdJE07fyEcG8E7CcsDNEcS6q30yC6F9uMo=";
    };
  };
}
