# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  copyq-darwin = {
    pname = "copyq-darwin";
    version = "7.1.0";
    src = fetchurl {
      url = "https://github.com/hluk/CopyQ/releases/download/v7.1.0/CopyQ.dmg.zip";
      sha256 = "sha256-8dYfEZSSI5NHGXXA+KzPg61Y7Z6nezo0Knced3j3TRU=";
    };
  };
  nixfmt = {
    pname = "nixfmt";
    version = "ca1fe3572ea6134551ee6af40ae735a1a1ed0d35";
    src = fetchFromGitHub {
      owner = "piegamesde";
      repo = "nixfmt";
      rev = "ca1fe3572ea6134551ee6af40ae735a1a1ed0d35";
      fetchSubmodules = false;
      sha256 = "sha256-d7a6xfqhbyLikHultxjHO33SqUcif/8eGyxhRZ9PvZk=";
    };
    date = "2024-02-08";
  };
  nixpkgs-review = {
    pname = "nixpkgs-review";
    version = "236d75ca105090170934f6f33abbd04d0fdb30fd";
    src = fetchFromGitHub {
      owner = "natsukium";
      repo = "nixpkgs-review";
      rev = "236d75ca105090170934f6f33abbd04d0fdb30fd";
      fetchSubmodules = false;
      sha256 = "sha256-+DWTeOnglwqLZ9Hke1Y2oCW1pYXPIrutnOXnBLply08=";
    };
    date = "2024-01-03";
  };
  nowplaying-cli = {
    pname = "nowplaying-cli";
    version = "1.2.1";
    src = fetchurl {
      url = "https://github.com/kirtan-shah/nowplaying-cli/archive/v1.2.1.tar.gz";
      sha256 = "sha256-u0kSPGYoK2SVwkVYkxOvyUh1p7DoLJrp951vJedQPbQ=";
    };
  };
  qmk-toolbox = {
    pname = "qmk-toolbox";
    version = "0.2.2";
    src = fetchurl {
      url = "https://github.com/qmk/qmk_toolbox/releases/download/0.2.2/QMK.Toolbox.app.zip";
      sha256 = "sha256-dfQ5qdkWMNIxCWhWa7cDMGzrpHl/m1RZsSaVFL56Ytg=";
    };
  };
  qutebrowser-darwin = {
    pname = "qutebrowser-darwin";
    version = "3.1.0";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.1.0/qutebrowser-3.1.0.dmg";
      sha256 = "sha256-AvuuwUnxMcr2ekZ/O1FL/4IizV1aTMhXNrbf1SwNY7U=";
    };
  };
  sbarlua = {
    pname = "sbarlua";
    version = "2220739be594965a1ddab6167dbdab77f617749e";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "SbarLua";
      rev = "2220739be594965a1ddab6167dbdab77f617749e";
      fetchSubmodules = false;
      sha256 = "sha256-VsPdorwYo/W5xWUQyC9nJ4E3Q1vCwo8CNXFyhIsxD2o=";
    };
    date = "2024-01-30";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "b9fe24dce395cb7b7696fa23f0546d3d870365a3";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "b9fe24dce395cb7b7696fa23f0546d3d870365a3";
      fetchSubmodules = false;
      sha256 = "sha256-H7L8FOSVQn4PkUmwJ6s7WoWqHGcyT73bwU0oyXRQnZI=";
    };
    date = "2024-02-09";
  };
  vivaldi-darwin = {
    pname = "vivaldi-darwin";
    version = "6.5.3206.61";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.6.5.3206.61.universal.dmg";
      sha256 = "sha256-B81vJye1rh6VjDP/eYeVEdbJVQljNqywxNMVHppMYrs=";
    };
  };
}
