# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  claudecode-nvim = {
    pname = "claudecode-nvim";
    version = "1552086ebcce9f4a2ea3b9793018a884d6b60169";
    src = fetchFromGitHub {
      owner = "coder";
      repo = "claudecode.nvim";
      rev = "1552086ebcce9f4a2ea3b9793018a884d6b60169";
      fetchSubmodules = false;
      sha256 = "sha256-XYmf1RQ2bVK6spINZW4rg6OQQ5CWWcR0Tw4QX8ZDjgs=";
    };
    date = "2025-10-19";
  };
  copyq-darwin = {
    pname = "copyq-darwin";
    version = "13.0.0";
    src = fetchurl {
      url = "https://github.com/hluk/CopyQ/releases/download/v13.0.0/CopyQ-macos-12-m1.dmg.zip";
      sha256 = "sha256-LrdDzFepf95scdbsBYdAiuK+tBk5aZEX0yt05oiC534=";
    };
  };
  emacs-plus = {
    pname = "emacs-plus";
    version = "89952793a1226de8b47dd6269806693713178b84";
    src = fetchFromGitHub {
      owner = "d12frosted";
      repo = "homebrew-emacs-plus";
      rev = "89952793a1226de8b47dd6269806693713178b84";
      fetchSubmodules = false;
      sha256 = "sha256-M24JpkYH7xdrm7Uine17wrmnpszfhCn9dBhw13Yt69Q=";
    };
    date = "2025-11-01";
  };
  hammerspoon = {
    pname = "hammerspoon";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/Hammerspoon/hammerspoon/releases/download/1.0.0/Hammerspoon-1.0.0.zip";
      sha256 = "sha256-XbcCtV2kfcMG6PWUjZHvhb69MV3fopQoMioK9+1+an4=";
    };
  };
  nixpkgs-review = {
    pname = "nixpkgs-review";
    version = "b4d0a817180b1a079d00d41c0a41308cb11407f7";
    src = fetchFromGitHub {
      owner = "natsukium";
      repo = "nixpkgs-review";
      rev = "b4d0a817180b1a079d00d41c0a41308cb11407f7";
      fetchSubmodules = false;
      sha256 = "sha256-fZkXkhwsNoxcQcC4fqwnkfGherazl/YZBkuVWGmnWPY=";
    };
    date = "2025-01-10";
  };
  paperwm-spoon = {
    pname = "paperwm-spoon";
    version = "254bf9244e316e231cd9d37e9a03ad147314bbee";
    src = fetchFromGitHub {
      owner = "mogenson";
      repo = "PaperWM.spoon";
      rev = "254bf9244e316e231cd9d37e9a03ad147314bbee";
      fetchSubmodules = false;
      sha256 = "sha256-BxlVwNeSMviWhi+DcSO50Exv9nmhGuVABnbmyiJ29/w=";
    };
    date = "2025-11-16";
  };
  qmk-toolbox = {
    pname = "qmk-toolbox";
    version = "0.3.3";
    src = fetchurl {
      url = "https://github.com/qmk/qmk_toolbox/releases/download/0.3.3/QMK.Toolbox.app.zip";
      sha256 = "sha256-WPre2csGAQzavtksLbj3L/MrWUT6d2gTJVq7eAmpcLk=";
    };
  };
  qutebrowser-darwin = {
    pname = "qutebrowser-darwin";
    version = "3.6.1";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.6.1/qutebrowser-3.6.1-arm64.dmg";
      sha256 = "sha256-2jk1nSq2O7z6tsVX7/ypvu2ipQh1mb8/Dz/n9KnqvAM=";
    };
  };
  sbarlua = {
    pname = "sbarlua";
    version = "437bd2031da38ccda75827cb7548e7baa4aa9978";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "SbarLua";
      rev = "437bd2031da38ccda75827cb7548e7baa4aa9978";
      fetchSubmodules = false;
      sha256 = "sha256-F0UfNxHM389GhiPQ6/GFbeKQq5EvpiqQdvyf7ygzkPg=";
    };
    date = "2024-08-12";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "71178b6debd9f1b3bb00abfd865ca642e82e24c7";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "71178b6debd9f1b3bb00abfd865ca642e82e24c7";
      fetchSubmodules = false;
      sha256 = "sha256-833WpBi0X6MhblLda1cp6dFU2zu+TYBgimlsBX+3rQo=";
    };
    date = "2025-10-27";
  };
  vivaldi-darwin = {
    pname = "vivaldi-darwin";
    version = "7.7.3851.48";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.7.7.3851.48.universal.dmg";
      sha256 = "sha256-7F5/Wx1JY2QOT27NY0jWM68z7nYGCwgBiUc06ezF2D0=";
    };
  };
  zen-browser = {
    pname = "zen-browser";
    version = "1.17.7b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.17.7b/zen.macos-universal.dmg";
      sha256 = "sha256-wvyiYg3kqvGOfIEYLy9/LyMoMkA7am0VxXffgE/JeRQ=";
    };
  };
}
