#!/usr/bin/env bash
set -euo pipefail

export TERM=xterm-256color
export NIXPKGS_ALLOW_UNFREE=1

channel='https://github.com/NixOS/nixpkgs/archive/ea8a8b9c52c7828d190beaf96f8cf1f7eb1adb18.tar.gz'  # 2021-10-23
nix run -f $channel talon -c talon
