#!/usr/bin/env bash
set -euo pipefail

export TERM=xterm-256color
export NIXPKGS_ALLOW_UNFREE=1

channel='https://github.com/NixOS/nixpkgs/archive/89882817b71fe0bce05146aa5c1ad9563c928f8d.tar.gz'  # 2021-09-18
nix run -f $channel talon -c talon
