#!/usr/bin/env zsh
set -euo pipefail

# WARNING: This will break some talon features. Use at your own risk!

echo "Killing..."
systemctl --user stop talon || true

# Workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1255432
systemctl --user reset-failed talon || true

echo "Starting..."

# TODO: Need to fix the xcb wrapper before this works.
# -p ProtectHome=tmpfs \

systemd-run --user \
    --send-sighup \
    --no-block \
    --unit talon \
    -E DISPLAY="$DISPLAY" \
    -E HOME="$HOME" \
    -p BindPaths=$HOME/.config/Talon \
    -p BindPaths=$HOME/.nix-profile \
    -p BindPaths=$HOME/.talon \
    -p BindPaths=/nix/store \
    -p BindPaths=/run/user/1000 \
    -p PrivateNetwork=true \
    -p PrivateUsers=yes \
    -p ProtectHostname=yes \
    -p ProtectSystem=strict \
    $(realpath $(which talon))

systemctl --user status talon
sleep 5
journalctl --user -u talon -ef
