# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  satty = {
    pname = "satty";
    version = "2283b1246fe0b44aa656902da5226bfef0d6d20b";
    src = fetchFromGitHub {
      owner = "gabm";
      repo = "Satty";
      rev = "2283b1246fe0b44aa656902da5226bfef0d6d20b";
      fetchSubmodules = false;
      sha256 = "sha256-VWcyzkZ/Juj/GAlNSspfGpowwkOtCw7d5Fate4WaYu4=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./satty-2283b1246fe0b44aa656902da5226bfef0d6d20b/Cargo.lock;
      outputHashes = {
      };
    };
    date = "2024-02-23";
  };
}
