#!/usr/bin/env -S NIX_BUILD_SHELL=/bin/sh nix-shell
#!nix-shell -i bash ../../../../integrations/nix-shell --arg f 'ps: [ ps.bash ps.xdg-open ]'

allow_empty=
uris=()
for u in "$@"; do
  if [ "$u" == xdg-open:null ]; then
    echo "xdg-open-scheme-handler: ignoring xdg-open:null"
    allow_empty=1
  else
    uris+=("${u/xdg-open:/}")
  fi
done

if [ "${#uris[@]}" -eq 0 ] && [ -n "$allow_empty" ]; then
  echo "xdg-open-scheme-handler: no URIs -> not forwarding to xdg-open"
else
  xdg-open "${uris[@]}"
fi
