# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  distrho-ports = {
    pname = "distrho-ports";
    version = "b3596e6a690eb0556e69e8b6d943fee2dfbb04fb";
    src = fetchFromGitHub {
      owner = "DISTRHO";
      repo = "DISTRHO-Ports";
      rev = "b3596e6a690eb0556e69e8b6d943fee2dfbb04fb";
      fetchSubmodules = true;
      sha256 = "sha256-/fOroqWUdxW8DfeUt0c98zOFYFHic0sn8AKMOpC7bGE=";
    };
    date = "2024-05-01";
  };
}
