name: Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    name: ${{ matrix.name }}
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.nix-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - name: Setup cachix
        uses: cachix/cachix-action@v17
        with:
          name: linyinfeng
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: Build flake check
        run: nix build --print-build-logs '.#${{ matrix.attr }}'
