apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.35.3
controlPlaneEndpoint: "[fdcc::100]:6443"
apiServer:
  certSANs:
    - "fdcc::100"
    - "fdcc:3::3"
    - "fdcc:1::2"
    - "fdcc::e"
    - "localhost"
    - "127.0.0.1"
networking:
  serviceSubnet: "10.96.0.0/12,fd00:10:96::/108"
  podSubnet: "10.244.0.0/16,fd00:10:244::/64"
  dnsDomain: cluster.local
