[ace-ctx]
fetch.github = "CodingOX/ace-ctx"
src.github_tag = "CodingOX/ace-ctx"
src.include_regex = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"

[autocli]
fetch.github = "nashsu/AutoCLI"
src.github_tag = "nashsu/AutoCLI"
src.include_regex = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"

[cliproxyapiplus]
fetch.github = "kaitranntt/CLIProxyAPIPlus"
src.github_tag = "kaitranntt/CLIProxyAPIPlus"
src.include_regex = "^v[0-9]+\\.[0-9]+\\.[0-9]+-[0-9]+$"

[gryph]
fetch.github = "safedep/gryph"
src.github_tag = "safedep/gryph"
src.include_regex = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"

[pumpkin]
src.git = "https://github.com/Pumpkin-MC/Pumpkin"
src.branch = "master"
fetch.github = "Pumpkin-MC/Pumpkin"
git.fetchSubmodules = true

[sing-box-alpha]
fetch.github = "SagerNet/sing-box"
src.github_tag = "SagerNet/sing-box"
src.include_regex = "^v[0-9]+\\.[0-9]+\\.[0-9]+(-(alpha|beta)\\.[0-9]+)?$"
src.sort_version_key = "parse_version"

[sing-box-beta]
fetch.github = "SagerNet/sing-box"
src.github_tag = "SagerNet/sing-box"
src.include_regex = "^v[0-9]+\\.[0-9]+\\.[0-9]+(-beta\\.[0-9]+)?$"
src.sort_version_key = "parse_version"

[tree-sitter-nix]
src.git = "https://github.com/nix-community/tree-sitter-nix"
src.branch = "main"
fetch.github = "nix-community/tree-sitter-nix"

[typenix]
src.git = "https://github.com/ryanrasti/typenix"
src.branch = "main"
fetch.github = "ryanrasti/typenix"
