version = 1

[*]
flash-attn = on

[Qwen 3.8 27B]
hf-repo = DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF
hf-file = Qwen3.8-27B-TurboFCFusion-735-882-Here-Uncen-NEO-CODER-MAX-MTP-Q4_K_M.gguf
alias = qwen3.8-27b
ctx-size = 48000
temp = 0.6
top-p = 0.95
top-k = 20
presence-penalty = 0
min-p = 0
spec-type = draft-mtp
spec-draft-n-max = 3

# [Qwen 3.6 35B A3B]
# hf-repo = llmfan46/Qwen3.6-35B-A3B-uncensored-heretic-Native-MTP-Preserved-GGUF:Q4_K_M
# alias = qwen3.6-35b-a3b
# reasoning = off
# ctx-size = 48000
# temp = 0.7
# top-p = 0.8
# top-k = 20
# presence-penalty = 1.5
# min-p = 0
# spec-type = draft-mtp
# spec-draft-n-max = 4
