# Free Mode: All new windows will float.
windowrule {
    name = float-all
    match:class = ^(.*)$
    float = true
}

# Initial Windows size Fix
windowrulev2 = size 1280 720, class:^(app.zen_browser.zen)$
windowrulev2 = size 1280 720, class:^(eu.betterbird.Betterbird)$
# windowrulev2 = size 1280 720, class:^(Godot)$
windowrulev2 = size 1280 720, class:^(dev.zed.Zed-Preview)$
windowrulev2 = size 1280 720, class:^(codium)$
windowrulev2 = size 1280 720, class:^(org.kde.okular)$, title:negative:Print.*
windowrulev2 = center, class:^(org.kde.okular)$

# --- Okular Print Preview Dialog ---
windowrulev2 = float, class:^(org.kde.okular)$, title:^(Print Preview — Okular)$
windowrulev2 = size 720 1280, class:^(org.kde.okular)$, title:^(Print Preview — Okular)$
windowrulev2 = center, class:^(org.kde.okular)$, title:^(Print Preview — Okular)$
