# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "11qk322nivvcp8l2n47gj7llpll0vxsx6v7kf5k3ds2gnrvr7fn8";
    aarch64-linux = "08szs2qa37wqly38jyapfrw5sgl5gsw7dfp1d1xg0mxbnqicxs09";
    x86_64-darwin = "192fqqlsiz2hwndnh824y7mhhgvxi3wnj4s0n4hm2zipic0nbssa";
    aarch64-darwin = "1z7bscsak7g688b9dm25f4z4kpk5azv0i6h4arr6brfi1qwc8bgi";
  };

  urlMap = {
    x86_64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v2.0.1/javascript-package-delegator_2.0.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v2.0.1/javascript-package-delegator_2.0.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v2.0.1/javascript-package-delegator_2.0.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v2.0.1/javascript-package-delegator_2.0.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "javascript-package-delegator";
  version = "2.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./jpd $out/bin/jpd
  '';

  system = system;

  meta = {
    description = "A CLI for executing JavaScript package manager commands based on lock files. Supports npm, yarn, pnpm, bun, and deno.";
    homepage = "https://github.com/louiss0/javascript-package-delegator";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
