# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
  args = {
    name = "typescript";
    packageName = "typescript";
    version = "4.1.3";
    src = fetchurl { url = "https://registry.npmjs.org/typescript/-/typescript-4.1.3.tgz"; sha1 = "519d582bd94cba0cf8934c7d8e8467e473f53bb7"; };
    buildInputs = globalBuildInputs;
    meta = {
      description = "TypeScript is a language for application scale JavaScript development";
      homepage = https://www.typescriptlang.org/;
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}