# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@types/estree-0.0.40" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "0.0.40";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-0.0.40.tgz";
        sha512 = "p3KZgMto/JyxosKGmnLDJ/dG5wf+qTRMUjHJcspC2oQKa4jP7mz+tv0ND56lLBu3ojHlhzY33Ol+khLyNmilkA==";
      };
    };
    "@types/node-12.12.21" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "12.12.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-12.12.21.tgz";
        sha512 = "8sRGhbpU+ck1n0PGAUgVrWrWdjSW2aqNeyC15W88GRsMpSwzv6RJGlLhE7s2RhVSOdyDmxbqlWSeThq4/7xqlA==";
      };
    };
    "acorn-7.1.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.1.0.tgz";
        sha512 = "kL5CuoXA/dgxlBbVrflsflzQ3PAas7RYZB52NOm/6839iVYJgKMJ3cQJD+t2i5+qFa8h3MDpEOJiS64E8JLnSQ==";
      };
    };
  };
  args = {
    name = "rollup";
    packageName = "rollup";
    version = "1.27.13";
    src = fetchurl { url = "https://registry.npmjs.org/rollup/-/rollup-1.27.13.tgz"; sha512 = "hDi7M07MpmNSDE8YVwGVFA8L7n8jTLJ4lG65nMAijAyqBe//rtu4JdxjUBE7JqXfdpqxqDTbCDys9WcqdpsQvw=="; };
    dependencies = [
      sources."@types/estree-0.0.40"
      sources."@types/node-12.12.21"
      sources."acorn-7.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Next-generation ES module bundler";
      homepage = https://github.com/rollup/rollup;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}