name: Nix Flake Check
on: push

permissions:
  contents: read

jobs:
  nix-flake-check:
    uses: pedorich-n/github-workflows/.github/workflows/flake-check.yaml@8dae1302115fad2af5d92f4e0368f727b17cd8ce # main
