name: Nix Flake Check
on: push

permissions:
  contents: read

jobs:
  nix-flake-check:
    uses: pedorich-n/github-workflows/.github/workflows/flake-check.yaml@37c055d3c6b1062846d5f9a45cf845f202e63b22 # main
