name: Update Packages' Sources

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1 * *"

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github App info
        id: app_auth
        uses: pedorich-n/github-workflows/.github/actions/app-token@37c055d3c6b1062846d5f9a45cf845f202e63b22 # main
        with:
          client_id: ${{ vars.APP_CLIENT_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@37c055d3c6b1062846d5f9a45cf845f202e63b22 # main
        with:
          git_https_token: ${{ steps.app_auth.outputs.token }}

      - name: Set NIX_PATH to this flake's nixpkgs input
        shell: bash
        run: |
          nixpkgs_path="$(nix flake archive --json . | jq -r '.inputs.nixpkgs.path')"
          echo "NIX_PATH=nixpkgs=$nixpkgs_path" >> "$GITHUB_ENV"

      - name: Get packages list
        id: get_packages
        run: |
          {
            echo 'packages<<EOF'
            nix eval --json .#nixUpdatePackages | jq -r '.[]'
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Run nix-update
        id: nix_update
        uses: pedorich-n/github-workflows/.github/actions/nix-update@8dae1302115fad2af5d92f4e0368f727b17cd8ce # main
        with:
          args: "--use-update-script --flake"
          packages: ${{ steps.get_packages.outputs.packages }}

      - name: Update README.md
        run: nix run .#nur-readme-update

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected"
            echo "changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes detected"
            echo "changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and open PR
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ steps.app_auth.outputs.token }}
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "Updated ${{ steps.nix_update.outputs.packages }} package(s)"
          branch: "nix-update/${{ github.run_id }}"
          title: "Update package(s) using nix-update"
          body: ${{ steps.nix_update.outputs.summary }}
