#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source $DIR/nix_env
version=$(nix eval --raw nixpkgs.lib.version)
mainversion=$(echo $version | cut -d"." -f -2)

echo "https://releases.nixos.org/nixos/$mainversion/nixos-$version/nixexprs.tar.xz"
nix eval --raw nixpkgs.bc.meta.position | cut -d"/" -f-4
