name: "Build and populate cache"
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**/*.nix'
      - tree-eval.nu
      - sign-upload-build.nu
  schedule:
    - cron:  '25 4 * * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        nurRepo:
          - komo
        nixPath:
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-unstable.tar.gz
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-26.05.tar.gz
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Setup Lix
      run: |
        curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix | sh -s -- install linux --no-confirm --init none
        . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
        mkdir -p ~/.config/nix
        true > ~/.config/nix/nix.conf
        echo "nix-path = ${{ matrix.nixPath }}" >> ~/.config/nix/nix.conf
        echo "extra-substituters = https://den.krome-fin.deno.net" >> ~/.config/nix/nix.conf
        echo "extra-trusted-public-keys = kromfin-nixcache:eb0zARxpXg9NaiR2g5TQFnj4z3DucJyj9PVMSZB02xA=" >> ~/.config/nix/nix.conf
        # store a signing key into file
        echo "$SIGNING_KEY" > ./signing-key.pem
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    - name: Fetch required tools
      run: |
        nix profile install \
          nixpkgs/nixos-unstable#{nix-fast-build,nushell,attic-client,as-tree}
    - name: Check evaluation
      run: |
        nu ./tree-eval.nu
    - name: Build nix packages
      run: |
        nix-fast-build --skip-cached --file ./default.nix --result-file result.json
    - name: Sign & Upload builds to binary cache
      run: |
        attic login --set-default default https://den.wuff.foo.ng "$ATTIC_TOKEN"
        nu ./sign-upload-build.nu --binary-cache default
      env:
        ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  update:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger NUR update
      run: |
        curl -XPOST "https://nur-update.nix-community.org/update?repo=komo"
