# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  exloli-next = {
    pname = "exloli-next";
    version = "41d7a6e52a1625d6febb47160a4b143ca47c16d5";
    src = fetchFromGitHub {
      owner = "lolishinshi";
      repo = "exloli-next";
      rev = "41d7a6e52a1625d6febb47160a4b143ca47c16d5";
      fetchSubmodules = false;
      sha256 = "sha256-S3hjuRSDtPkK9XF2USXfyOawWoD/fu9qYDJbUPI3Op0=";
    };
    date = "2024-11-23";
  };
  pam-watchid = {
    pname = "pam-watchid";
    version = "f33d4a81b51e477f32bd87df817eabaa28e175e7";
    src = fetchFromGitHub {
      owner = "Logicer16";
      repo = "pam-watchid";
      rev = "f33d4a81b51e477f32bd87df817eabaa28e175e7";
      fetchSubmodules = false;
      sha256 = "sha256-P18Ek1EsiNbVMKDQm1b8hDsOtXwRQMYa7g1dDdzfMe8=";
    };
    date = "2025-01-29";
  };
  v2ray-rules-dat-geoip = {
    pname = "v2ray-rules-dat-geoip";
    version = "202501302211";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202501302211/geoip.dat";
      sha256 = "sha256-VgT6+9ubT67Z+ItsejGPFMldjheam/Fc1HBCB3ml9HY=";
    };
  };
  v2ray-rules-dat-geosite = {
    pname = "v2ray-rules-dat-geosite";
    version = "202501302211";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202501302211/geosite.dat";
      sha256 = "sha256-UxiOrowDx2WQ0EeYLNkaQIDBxtm3aAYvLEQxHDIzUxQ=";
    };
  };
}
