# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  aliyundrive-webdav = {
    pname = "aliyundrive-webdav";
    version = "6e8eba62b4e50acf89681e3a67a3a693186dcd05";
    src = fetchFromGitHub {
      owner = "messense";
      repo = "aliyundrive-webdav";
      rev = "6e8eba62b4e50acf89681e3a67a3a693186dcd05";
      fetchSubmodules = false;
      sha256 = "sha256-jyAq4B7SNbw++eoUFoI/Rc9GucU/1NMrC1/Rjysr5wg=";
    };
    date = "2025-06-10";
  };
  aliyundrive-webdav-stable = {
    pname = "aliyundrive-webdav-stable";
    version = "v2.3.3";
    src = fetchFromGitHub {
      owner = "messense";
      repo = "aliyundrive-webdav";
      rev = "v2.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-LN2HdmhcPk6RCrRZdV3A8InoYgqJSHC2XjjuKZLfVaI=";
    };
  };
  bark-server = {
    pname = "bark-server";
    version = "1e2ecf2137e1e31edcc75b1c8438e816473c41f6";
    src = fetchFromGitHub {
      owner = "Finb";
      repo = "bark-server";
      rev = "1e2ecf2137e1e31edcc75b1c8438e816473c41f6";
      fetchSubmodules = false;
      sha256 = "sha256-6B+maZVHlh95+b2yR98cdc9CL4UnOQ0bKSgnPccqP9w=";
    };
    date = "2025-12-30";
  };
  bark-server-stable = {
    pname = "bark-server-stable";
    version = "v2.3.3";
    src = fetchFromGitHub {
      owner = "Finb";
      repo = "bark-server";
      rev = "v2.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-Pnj4ZRzW0ZW1mgtl+wT7JE/ccJ9kivGBe6tgbBiBMLs=";
    };
  };
  boringssl-oqs = {
    pname = "boringssl-oqs";
    version = "OQS-BoringSSL-snapshot-2025-01";
    src = fetchFromGitHub {
      owner = "open-quantum-safe";
      repo = "boringssl";
      rev = "OQS-BoringSSL-snapshot-2025-01";
      fetchSubmodules = false;
      sha256 = "sha256-zVZgAvq6V85hxO79Ct8s+VVyf9yPa/YbRL4D5z31qEs=";
    };
  };
  english_words = {
    pname = "english_words";
    version = "20f5cc9b3f0ccc8ce45d814c532b7c2031bba31c";
    src = fetchFromGitHub {
      owner = "dwyl";
      repo = "english-words";
      rev = "20f5cc9b3f0ccc8ce45d814c532b7c2031bba31c";
      fetchSubmodules = false;
      sha256 = "sha256-PfBQ9iavOLx7M8+j0TXASUxVamPiQn2YXsiuUmz4XCg=";
    };
    date = "2025-01-06";
  };
  exloli-next = {
    pname = "exloli-next";
    version = "41d7a6e52a1625d6febb47160a4b143ca47c16d5";
    src = fetchFromGitHub {
      owner = "lolishinshi";
      repo = "exloli-next";
      rev = "41d7a6e52a1625d6febb47160a4b143ca47c16d5";
      fetchSubmodules = false;
      sha256 = "sha256-S3hjuRSDtPkK9XF2USXfyOawWoD/fu9qYDJbUPI3Op0=";
    };
    date = "2024-11-23";
  };
  fcitx5-themes-candlelight = {
    pname = "fcitx5-themes-candlelight";
    version = "653677b0454569f41c815b3d262a57e42c90ee05";
    src = fetchFromGitHub {
      owner = "thep0y";
      repo = "fcitx5-themes-candlelight";
      rev = "653677b0454569f41c815b3d262a57e42c90ee05";
      fetchSubmodules = false;
      sha256 = "sha256-dN77aUt1qkN177BZOfrT6O72Qp0J2jlM2mGNxI0cBnA=";
    };
    date = "2025-11-07";
  };
  flapalerted = {
    pname = "flapalerted";
    version = "174fb3be025c180150fd4b3e0dd5615b832fa0fb";
    src = fetchFromGitHub {
      owner = "Kioubit";
      repo = "FlapAlerted";
      rev = "174fb3be025c180150fd4b3e0dd5615b832fa0fb";
      fetchSubmodules = false;
      sha256 = "sha256-+AQ5+voOgKRcknOpPQH7IPdWCKSaODd8u1MTvq6H/cU=";
    };
    date = "2026-01-19";
  };
  flapalerted-stable = {
    pname = "flapalerted-stable";
    version = "v4.3.0";
    src = fetchFromGitHub {
      owner = "Kioubit";
      repo = "FlapAlerted";
      rev = "v4.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-xoskkM5xdU3+T5AtgGv0uPZEUOLtMGl7RPv8gKBJBho=";
    };
  };
  geolite2-asn = {
    pname = "geolite2-asn";
    version = "2026.01.22";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.01.22/GeoLite2-ASN.mmdb";
      sha256 = "sha256-SIzcw1MnhWmZMx3vTWOGcq9w1NRzfCDk6J0EkDkYJ+c=";
    };
  };
  geolite2-city = {
    pname = "geolite2-city";
    version = "2026.01.22";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.01.22/GeoLite2-City.mmdb";
      sha256 = "sha256-kt37x/2pCf3GT8z/ykukaJuJm6L7TAtu/Ck4Tk/THAc=";
    };
  };
  geolite2-country = {
    pname = "geolite2-country";
    version = "2026.01.22";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.01.22/GeoLite2-Country.mmdb";
      sha256 = "sha256-aPPDxH23HEcFlbFZlHUQ+o1uaUtypvBOmom0g8HvL9o=";
    };
  };
  git-mcp-server = {
    pname = "git-mcp-server";
    version = "v2.4.9";
    src = fetchFromGitHub {
      owner = "cyanheads";
      repo = "git-mcp-server";
      rev = "v2.4.9";
      fetchSubmodules = false;
      sha256 = "sha256-oS1zQWbD3pGHytrAKaufyeCeVg0nnktuzLDJQVXoa4E=";
    };
  };
  libinput-three-finger-drag = {
    pname = "libinput-three-finger-drag";
    version = "6acd3f84b551b855b5f21b08db55e95dae3305c5";
    src = fetchFromGitHub {
      owner = "marsqing";
      repo = "libinput-three-finger-drag";
      rev = "6acd3f84b551b855b5f21b08db55e95dae3305c5";
      fetchSubmodules = false;
      sha256 = "sha256-xmcTb+23d6mMzIfMVjzN6bwV0fWH4p6YhXXqrFmt4TM=";
    };
    date = "2024-06-17";
  };
  mautrix-telegramgo = {
    pname = "mautrix-telegramgo";
    version = "c7a7f6ec200f5a783daf0500bbe37a9c77f97289";
    src = fetchFromGitHub {
      owner = "mautrix";
      repo = "telegramgo";
      rev = "c7a7f6ec200f5a783daf0500bbe37a9c77f97289";
      fetchSubmodules = false;
      sha256 = "sha256-GrLRxVlTXjepBqIV7wlB27q6QhVX3v5UeTKjwixSHjM=";
    };
    date = "2026-01-20";
  };
  mm-geofeed-verifier = {
    pname = "mm-geofeed-verifier";
    version = "v3.1.0";
    src = fetchFromGitHub {
      owner = "maxmind";
      repo = "mm-geofeed-verifier";
      rev = "v3.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-14TztORKynlHS277k+W7FN1kgQD0FFu5W07wxgCDFS0=";
    };
  };
  mpv-danmaku = {
    pname = "mpv-danmaku";
    version = "08acd6c6a73e6743af7a522a5d9a899dea608df2";
    src = fetchFromGitHub {
      owner = "moraxyc";
      repo = "mpv-danmaku";
      rev = "08acd6c6a73e6743af7a522a5d9a899dea608df2";
      fetchSubmodules = false;
      sha256 = "sha256-JfitGKDwdq5jU0H1PzpCv2+TaKLPFzGITkTJRyUR8sg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-JfitGKDwdq5jU0H1PzpCv2+TaKLPFzGITkTJRyUR8sg=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-01-19";
  };
  mpv-danmaku-stable = {
    pname = "mpv-danmaku-stable";
    version = "v1.9.0";
    src = fetchFromGitHub {
      owner = "moraxyc";
      repo = "mpv-danmaku";
      rev = "v1.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-N+Vi+mbKGogO6PgONqiegbrHGh+5BePePkU9+Irate0=";
    };
  };
  new-api = {
    pname = "new-api";
    version = "v0.10.6-alpha.4";
    src = fetchFromGitHub {
      owner = "QuantumNous";
      repo = "new-api";
      rev = "v0.10.6-alpha.4";
      fetchSubmodules = false;
      sha256 = "sha256-vCPZShMd0zFKkFKPk0g3QLFoNDRQa8DwS26ewaHgVc8=";
    };
  };
  opencode = {
    pname = "opencode";
    version = "v1.1.31";
    src = fetchFromGitHub {
      owner = "anomalyco";
      repo = "opencode";
      rev = "v1.1.31";
      fetchSubmodules = false;
      sha256 = "sha256-csDcgd0V4QEG+jYIycCElTc0UbXh8FwZ5D34a7eg9wY=";
    };
  };
  pixy2 = {
    pname = "pixy2";
    version = "d7c38d49ae8071b58e46f5b35eda927dd2b7c621";
    src = fetchFromGitHub {
      owner = "charmedlabs";
      repo = "pixy2";
      rev = "d7c38d49ae8071b58e46f5b35eda927dd2b7c621";
      fetchSubmodules = false;
      sha256 = "sha256-w0t7KqV8OS3PJBdZtLn86zknQYo70rBv7fuK/UFx9zQ=";
    };
    date = "2024-07-17";
  };
  v2ray-rules-dat-geoip = {
    pname = "v2ray-rules-dat-geoip";
    version = "202601212218";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202601212218/geoip.dat";
      sha256 = "sha256-GyBfdD4EKx4L03sAELIySFQwFBXbzlmCVr8wczjmjDo=";
    };
  };
  v2ray-rules-dat-geosite = {
    pname = "v2ray-rules-dat-geosite";
    version = "202601212218";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202601212218/geosite.dat";
      sha256 = "sha256-xio8BPpZhNMjROU1HMGvJTuy/MK8GqBJA+H/gg/IZRU=";
    };
  };
  watt-toolkit-aarch64-linux = {
    pname = "watt-toolkit-aarch64-linux";
    version = "3.0.0-rc.16";
    src = fetchurl {
      url = "https://github.com/BeyondDimension/SteamTools/releases/download/3.0.0-rc.16/Steam++_v3.0.0-rc.16_linux_arm64.tgz";
      sha256 = "sha256-xfzxxxMKsoMww9PzB/nvRcxqOqyn65escvxkzK9csCo=";
    };
  };
  watt-toolkit-x86_64-linux = {
    pname = "watt-toolkit-x86_64-linux";
    version = "3.0.0-rc.16";
    src = fetchurl {
      url = "https://github.com/BeyondDimension/SteamTools/releases/download/3.0.0-rc.16/Steam++_v3.0.0-rc.16_linux_x64.tgz";
      sha256 = "sha256-mUk/gh8GPYwhs5OZzKorkNIMMKl+amFrwbTtH0AnHTI=";
    };
  };
}
