#!/usr/bin/env bash

xrdb $(dotfiles)/Xresources
system launch &
system reload &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width               2
bspc config window_gap                 8

bspc config split_ratio                0.52
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_follows_pointer      true
bspc config pointer_follows_focus      true
bspc config pointer_follows_monitor    true

bspc rule -a "Zathura" state=tiled

xsetroot -cursor_name left_ptr
