files = ["default.nix", "spotx.nix"]
tests = [
  ["nix", "build", "-f", "tests/pkgs/spotify-spotx.nix", "--no-link"],
]

[snapshot]
name = "SpotX"
repository = "SpotX-Official/SpotX-Bash"
branch = "main"
attribute = "spotify-spotx.spotx"
command = ["just", "update-spotx"]
files = ["spotx.nix"]
