name: "Update flake inputs"
on:
  workflow_dispatch:
  schedule:
    # bump weekly at 6:50
    - cron:  '50 6 * * 1'
jobs:
  update-flake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: https://github.com/actions/checkout@v6
      - uses: https://github.com/actions/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.INPUT_GITHUB_ACCESS_TOKEN }}
      - name: "flake: update inputs"
        uses: https://github.com/actions/update-flake-lock@v28
        with:
          pr-title: "flake: update inputs"
          pr-labels: dependencies
          commit-msg: "flake: update inputs"
