name: CI
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  Atelier:
    uses: stepbrobd/atelier/.github/workflows/discover.yaml@8644a5e5563f7270a0f9b6a52325cba176f0bda0
    with:
      install-command: curl -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
      extra-conf: |
        extra-experimental-features = nix-command flakes pipe-operator
    secrets:
      ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
