# Virtual monophone microphone
#
# the main purpose is to provide a node to which audio can be injected and the
# system interprets that as if the injected audio came from an actual microphone.
# based on:
# - <https://sorrel.sh/blog/pipewire-how-to-static-loopbacks/>
# - <repo:pipewire/pipewire:src/daemon/filter-chain/source-duplicate-FL.conf>
# - <https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Virtual-devices>
# filter-chain docs:
# - <https://docs.pipewire.org/page_module_filter_chain.html>
#
# send audio to this sink like:
# - `mpv --audio-output=pipewire/effect_input.augmented_mic path/to/file.flac`

context.modules = [
  { name = libpipewire-module-filter-chain
    flags = [ nofail ]
    args = {
      node.description = "Augmented Mic (default mic + soundboard)"
      media.name       = "Augmented Mic"
      filter.graph = {
        nodes = [
          {
            name   = copyC
            type   = builtin
            label  = copy
          }
        ]
        links = [
        ]
        inputs  = [ "copyC:In" ]
        outputs = [ "copyC:Out" ]
      }
      capture.props = {
        node.name         = "effect_input.augmented_mic"
        media.class       = Audio/Sink
        audio.channels    = 1
        audio.position    = [ FC ]
      }
      playback.props = {
        node.name         = "effect_output.augmented_mic"
        media.class       = Audio/Source
        audio.channels    = 1
        audio.position    = [ FC ]
      }
    }
  }
]

