# based on <https://docs.pipewire.org/page_module_loopback.html>
#
# this creates a no-op output device, `mic_effects`, which respects volume controls.
# - route audio into it like: `mpv --audio-device=pipewire/mic_effects.sink MY_MEDIA_FILE`.
# - direct its output into the mic input of something like `audacity` by using `coppwr` GUI (link `mic_effects.source` -- NOT monitor).
#   - audacity (alsa) can have multiple input streams, which pipewire seems to sum together, implicitly.
#   - "Mic Effects" shows up as two wholly distinct nodes:
#     - the sink, which has "playback" (input) and "monitor" (output)
#     - the source, which has "output" (output).
#       the source is linked _automatically_ to the system-default source, such that you hear the virtual effects
#       hence, effect volume is controlled in the "outputs" section of Pavucontrol
#
# in the future, i hope to create a wireplumber rule to automate linking `mic_effects.source` to every thing that's linked to the system-default mic.
# TODO: combine with wireplumber smart-filter rule: <https://pipewire.pages.freedesktop.org/wireplumber/policies/smart_filters.html>
context.modules = [
  { name = libpipewire-module-loopback
    args = {
      node.description = "Mic Effects"
      capture.props = {
        node.name = "mic_effects.sink"
        media.class = "Audio/Sink"
        audio.position = [ MONO ]
        # audio.position = [ FL FR ]
      }
      playback.props = {
        node.name = "mic_effects.source"
        audio.position = [ MONO ]
        # audio.position = [ FL FR ]
        # media.class = "Audio/Source"  #< uncomment to have the device show up as an "input" in pavucontrol.
        # node.dont-reconnect = true
        # dont-remix means the node only gets the ports as defined here, rather than pipewire implicitly expanding them.
        stream.dont-remix = true
        # node.passive = true
      }
    }
  }
]
