# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  keepmenu = {
    pname = "keepmenu";
    version = "78fe4760e7fe8f95feff7ddcb47aeeac63b67b42";
    src = fetchFromGitHub {
      owner = "firecat53";
      repo = "keepmenu";
      rev = "78fe4760e7fe8f95feff7ddcb47aeeac63b67b42";
      fetchSubmodules = false;
      sha256 = "sha256-vmautVUniAtN/gxsqEeVQ5yPhhnSaCqQUr+8i+m20Mw=";
    };
    date = "2024-01-24";
  };
}
