name: "Nix Flake Check"

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Nix Flake
        run: nix flake check
