#:schema https://www.schemastore.org/treefmt.json

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.oxfmt]
command = "oxfmt"
options = ["--write"]
includes = ["*.json", "*.yaml", "*.toml", "*.md"]
