#:schema https://www.schemastore.org/treefmt.json

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.toml]
command = "tombi"
options = ["format"]
includes = ["*.toml"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.yaml", "*.json", "*.md"]
