#!/bin/sh
NIX_FILES_TOP=/home/colin/nixos
cd $NIX_FILES_TOP/integrations/nur
# TODO: should include `-I nixpkgs=</path/to/an/unpatched/nixpkgs>`
NIX_PATH= NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix-env -f . -qa \* --meta --xml \
  --allowed-uris https://static.rust-lang.org \
  --option restrict-eval true \
  --option allow-import-from-derivation true \
  --drv-path --show-trace \
  -I ../../ \
  "$@" \
  | tee  # tee to prevent interactive mode

