# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  ep_copy_paste_select_all = nodeEnv.buildNodePackage {
    name = "ep_copy_paste_select_all";
    packageName = "ep_copy_paste_select_all";
    version = "0.0.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/ep_copy_paste_select_all/-/ep_copy_paste_select_all-0.0.4.tgz";
      sha1 = "41b89ece9da8e549a7ca4b11cdfa0a27344f21c8";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Add support to do Copy, Paste, Select All and Find and Replace, this plugin requires the file menu";
      homepage = https://github.com/ether/ep_copy_paste_select_all;
    };
    production = true;
    bypassCache = false;
  };
}